src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountVisibility__c</fullName>
        <description>Used for sharing, depends on visibility state
100 = visible (not invalid, not deleted)
50 = invalid (not deleted)
0 = deleted</description>
        <inlineHelpText>Used for sharing, depends on visibility state
100 = visible (not invalid, not deleted)
50 = invalid (not deleted)
0 = deleted</inlineHelpText>
        <label>Account Visibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomTv_CleanUp_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account-Bereinigung 04/2015: soll gelöscht werden (Vorschlag)</description>
        <inlineHelpText>Account-Bereinigung 04/2015: soll gelöscht werden (Vorschlag)</inlineHelpText>
        <label>soll gelöscht werden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ungueltiger_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Dieser Account darf für Angebote und Aufträge nicht mehr verwendet werden - es handelt sich um eine Dublette/Fehleingabe oder die Firma gibt es so nicht.</description>
        <inlineHelpText>This account shall not longer be used  if it is a duplicate, contains incorrect data or the company does not longer exits. To enable or disable, please follow the required approval process</inlineHelpText>
        <label>ungültiger Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountVisibility__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for sharing, depends on visibility state 0 = visible (not invalid, not deleted) 50 = invalid (not deleted) 100 = deleted</description>
        <inlineHelpText>Used for sharing, depends on visibility state 0 = visible (not invalid, not deleted) 50 = invalid (not deleted) 100 = deleted</inlineHelpText>
        <label>Account Visibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/P7S1_Account_Visibility.cls
public class P7S1_Account_Visibility{

    // This Method sets the P7S1_AccountVisibility__c for Account & Contact
    public static void updateVisibility(Map <Id, Account> mapAccount, List<Account> listAccount, Boolean bIsInsert, Boolean bIsUpdate){

        Map<ID, Integer> mapChangedAccounts = new Map<ID, Integer>();
        for (Account o : listAccount) {
            if (o.SomTv_CleanUp_Delete__c)
                o.P7S1_AccountVisibility__c = 0;
            else if(o.ungueltiger_Account__c)
                o.P7S1_AccountVisibility__c = 50;
            else
                o.P7S1_AccountVisibility__c = 100;


            // Check if it changed, to update the contacts
            if (bIsUpdate)
                if (mapAccount.get(o.ID).P7S1_AccountVisibility__c != o.P7S1_AccountVisibility__c)
                    mapChangedAccounts.put(o.ID, (Integer)o.P7S1_AccountVisibility__c);
        }


        if (bIsUpdate && !mapChangedAccounts.isEmpty()){
            // Update Contacts
            List<Contact> listContacts = new List<Contact>([SELECT AccountID FROM Contact WHERE AccountID IN :mapChangedAccounts.keySet()]);
            for (Contact c : listContacts)
                c.P7S1_AccountVisibility__c = mapChangedAccounts.get(c.AccountID);


            if (!listContacts.isEmpty())
                update listContacts;
        }
    }
}