src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ProRex_Rolle__c</fullName>
        <description>ehemals ProRex Rolle</description>
        <inlineHelpText>Dieses Feld bildet die historischen Rollen aus dem Altsystem ProRex ab.</inlineHelpText>
        <label>Rolle</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kunde</fullName>
                </value>
                <value>
                    <fullName>Konzern</fullName>
                </value>
                <value>
                    <fullName>Agentur</fullName>
                </value>
                <value>
                    <fullName>Agenturverbund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomTv_HilfsfeldProRexRolle__c</fullName>
        <description>wird per Trigger befüllt. Dient zur Aufnahme der ProRex Rollenwerte. Filter in AnsprechpartnerZustaendigkeit__r.Agentur__c und AnsprechpartnerZustaendigkeit__r.Kunde__c referenzieren auf dieses Hilfsfeld (Begründung: LookUp Filter können nicht auf MultiPicklist referenzieren)</description>
        <inlineHelpText>wird per Trigger befüllt. Dient zur Aufnahme der ProRex Rollenwerte. Filter in AnsprechpartnerZustaendigkeit__r.Agentur__c und AnsprechpartnerZustaendigkeit__r.Kunde__c referenzieren auf dieses Hilfsfeld</inlineHelpText>
        <label>HilfsfeldProRexRolle</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Som_Rechtsform__c</fullName>
        <description>Rechtsformen des Unternehmens. HINWEIS: sollte eine Rechtsform fehlen, bitte bei den Admins vom Team Sales Solutions melden, der Eintrag wird dann umgehend angelegt.</description>
        <inlineHelpText>Rechtsformen des Unternehmens. HINWEIS: sollte eine Rechtsform fehlen, bitte bei den Admins vom Team Sales Solutions melden, der Eintrag wird dann umgehend angelegt.</inlineHelpText>
        <label>Rechtsform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>A/S</fullName>
                </value>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AG &amp; Co. KG</fullName>
                </value>
                <value>
                    <fullName>AG &amp; Co. KGaA</fullName>
                </value>
                <value>
                    <fullName>AG &amp; Co. OHG</fullName>
                </value>
                <value>
                    <fullName>Anstalt des öffentlichen Rechts</fullName>
                </value>
                <value>
                    <fullName>ApS</fullName>
                </value>
                <value>
                    <fullName>ApS &amp; Co. KG</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>B.V.</fullName>
                </value>
                <value>
                    <fullName>Corp.</fullName>
                </value>
                <value>
                    <fullName>d.o.o.</fullName>
                </value>
                <value>
                    <fullName>e. K.</fullName>
                </value>
                <value>
                    <fullName>e. Kffr.</fullName>
                </value>
                <value>
                    <fullName>e. Kfm.</fullName>
                </value>
                <value>
                    <fullName>e.U.</fullName>
                </value>
                <value>
                    <fullName>e.V.</fullName>
                </value>
                <value>
                    <fullName>eG</fullName>
                </value>
                <value>
                    <fullName>ehf</fullName>
                </value>
                <value>
                    <fullName>einfache Gesellschaft</fullName>
                </value>
                <value>
                    <fullName>Einzelunternehmen</fullName>
                </value>
                <value>
                    <fullName>EURL</fullName>
                </value>
                <value>
                    <fullName>EWIV</fullName>
                </value>
                <value>
                    <fullName>gAG</fullName>
                </value>
                <value>
                    <fullName>GbR</fullName>
                </value>
                <value>
                    <fullName>Gemeinnützige Stiftung</fullName>
                </value>
                <value>
                    <fullName>Genossenschaft</fullName>
                </value>
                <value>
                    <fullName>GesbR</fullName>
                </value>
                <value>
                    <fullName>GesmbH</fullName>
                </value>
                <value>
                    <fullName>GmbH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Agentur</fullName>
        <active>true</active>
        <description>Ein Unternehmen, welches im Auftrag von Werbungtreibende Marketing- und Werbekampagnen plant, Werbung entwirft und produziert und diese auch in den Medien platziert</description>
        <label>Agentur</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SomTv_KundeAgenturBeziehung__c.object
<CustomObject>
    <fields>
        <fullName>GueltigBis__c</fullName>
        <description>Bis wann ist diese Kd.-Agentur-Beziehung gültig?</description>
        <inlineHelpText>Bis wann ist diese Kd.-Agentur-Beziehung gültig?</inlineHelpText>
        <label>gültig bis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GueltigVon__c</fullName>
        <description>Ab wann ist diese Kd.-Agentur-Beziehung gültig?</description>
        <inlineHelpText>Ab wann ist diese Kd.-Agentur-Beziehung gültig?</inlineHelpText>
        <label>gültig von</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kunde__c</fullName>
        <label>Kunde</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Beziehungen (Kunde)</relationshipLabel>
        <relationshipName>AnsprechpartnerZustaendigkeiten</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Beziehung</label>
    <nameField>
        <label>BeziehungsId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SomTv_KundeAgenturBez_ValidateData_Test.cls
@isTest
public class SomTv_KundeAgenturBez_ValidateData_Test{

  private static final string VALIDATION_DUPLICATE_KABEZ_IN_LIST  = 'Kunde-Agentur-Beziehung gibt es bereits';
  private static final string VALIDATION_DUPLICATE_KABEZ_IN_SF  = 'Kunde-Agentur-Beziehung gibt es bereits';

  public static testMethod void testValidation() {
    Account acc  = new Account(Name='Testaccount GmbH', ProRex_Rolle__c='Kunde', SomTv_HilfsfeldProRexRolle__c='Kunde', Som_Rechtsform__c='GmbH');
    insert acc;
    
    SomTV_KundeAgenturBeziehung__c kaBez1  = new SomTV_KundeAgenturBeziehung__c(Kunde__c=acc.Id, GueltigVon__c=system.today(), Gueltigbis__c=system.today()+2);
    SomTV_KundeAgenturBeziehung__c kaBez2  = new SomTV_KundeAgenturBeziehung__c(Kunde__c=acc.Id, GueltigVon__c=system.today());
    SomTV_KundeAgenturBeziehung__c kaBez3  = new SomTV_KundeAgenturBeziehung__c(Kunde__c=acc.Id, GueltigVon__c=system.today()-2, Gueltigbis__c=system.today()-1);
    
    try {
      insert new List<SomTV_KundeAgenturBeziehung__c>{kaBez1,kaBez2,kaBez3};
    }
    catch (Exception e) {
      system.assert(e.getMessage().contains(VALIDATION_DUPLICATE_KABEZ_IN_LIST));
    }
    
    insert kaBez1;
    try {
      insert(kaBez2);
    }
    catch (Exception e) {
      system.assert(e.getMessage().contains(VALIDATION_DUPLICATE_KABEZ_IN_SF));
    }
    
    update kaBez1;
    
    delete kaBez1;
    
    undelete kaBez1;
    
  }
}