src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SomDig_DebitorennrBarter__c</fullName>
        <label>SomDig DebitorennrBarter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Debitorennr__c</fullName>
        <description>Hidden Field, Storing external id for the media campaign</description>
        <label>SomDig Debitorennr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_ExternalId__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_Account__c</fullName>
        <description>Nimmt die ID aus Prosa, SAP oder anderen Anwendungen auf für diesen Account</description>
        <inlineHelpText>Nimmt die ID aus Prosa, SAP oder anderen Anwendungen auf für diesen Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Externe IDs</relationshipLabel>
        <relationshipName>P7S1_ExternalId</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>P7S1_Source__c</fullName>
        <description>In welchem System kennzeichnet diese ID diesen Account eineindeutig?</description>
        <inlineHelpText>In welchem System kennzeichnet diese ID diesen Account eineindeutig?
Wichtig ist das bei Konzerninternen Accounts immer eine separate Sachkontonummer erfasst wird.</inlineHelpText>
        <label>Quelle/System</label>
        <picklist>
            <picklistValues>
                <fullName>Debitorennr BK 29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debitorennr BK 29 - Barter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debitorennr TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nielsen-ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProSa/ProSedi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sachkonto konzernintern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vermarkter-Id (ProSa)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Externe ID</label>
    <nameField>
        <label>Externe ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Externe IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/P7S1_ExternalID_DebNrSync.cls
public class P7S1_ExternalID_DebNrSync{
    /**
    * Sync the debitornumber from the P7S1_ExternalId__c to the account
    * 
    * @param trigger.new (List<P7S1_ExternalId__c>)
    **/
    public static void getDebitor(List<P7S1_ExternalId__c> lstExtId, Map<Id, P7S1_ExternalId__c> mapOldItems, Boolean isInsert, Boolean isUpdate) {
        Set<Id> accountIDs = new Set<Id>(); 

        P7S1_ExternalId__c oldObjExtId;
        
        for(P7S1_ExternalId__c objExtId : lstExtID){
            
            oldObjExtId = isUpdate ? mapOldItems.get(objExtId.Id) : null;
                
            if(isInsert && isValidSource(objExtId)) {
                accountIDs.add(objExtId.P7S1_Account__c);
            } else if(isUpdate && isSourceChanged(objExtId, oldObjExtId) && isValidSource(objExtId)) {
                accountIDs.add(objExtId.P7S1_Account__c);
            } else if(isUpdate && isNameChanged(objExtId, oldObjExtId))
                accountIDs.add(objExtId.P7S1_Account__c);

        }
        
        if(accountIDs.isEmpty()) return;
        
        Map<Id, Account> mapAccounts = new Map<Id, Account>([SELECT Id, SomDig_Debitorennr__c, SomDig_DebitorennrBarter__c FROM Account WHERE ID in :accountIDs]);
        for(P7S1_ExternalId__c objExtId: lstExtID){
            if(objExtId.P7S1_Source__c == 'Debitorennr BK 29') mapAccounts.get(objExtId.P7S1_Account__c).SomDig_Debitorennr__c = objExtId.Name;
            else if(objExtId.P7S1_Source__c == 'Debitorennr BK 29 - Barter') mapAccounts.get(objExtId.P7S1_Account__c).SomDig_DebitorennrBarter__c = objExtId.Name;
        }

        update mapAccounts.values();

    }
    
    private static Boolean isValidSource(P7S1_ExternalId__c objExtId) {
        return (objExtId.P7S1_Source__c == 'Debitorennr BK 29' || objExtId.P7S1_Source__c == 'Debitorennr BK 29 - Barter');
    }

    private static Boolean isSourceChanged(P7S1_ExternalId__c objExtId, P7S1_ExternalId__c oldObjExtId) {
        return objExtId.P7S1_Source__c != oldObjExtId.P7S1_Source__c;
    }

    private static Boolean isNameChanged(P7S1_ExternalId__c objExtId, P7S1_ExternalId__c oldObjExtId) {
        return objExtId.Name != oldObjExtId.Name;
    }


    public static void removeDebitor(List<P7S1_ExternalId__c> lstExtId){
        Set<Id> setId = new Set<Id>();
        
        for(P7S1_ExternalId__c objExtId: lstExtID){
            if(!(objExtId.P7S1_Source__c == 'Debitorennr BK 29' || objExtId.P7S1_Source__c == 'Debitorennr BK 29 - Barter')) continue;
            setId.add(objExtId.P7S1_Account__c);
        }
        
        if(setId.isEmpty()) return;
        
        Map<Id, Account> mapAccounts = new Map<Id, Account>([SELECT Id, SomDig_Debitorennr__c, SomDig_DebitorennrBarter__c FROM Account WHERE ID in :setId]);
 
        
        for(P7S1_ExternalId__c objExtId: lstExtID){
            if(objExtId.P7S1_Source__c == 'Debitorennr BK 29'){
                mapAccounts.get(objExtId.P7S1_Account__c).SomDig_Debitorennr__c = '';
            }
            else if(objExtId.P7S1_Source__c == 'Debitorennr BK 29 - Barter'){
                mapAccounts.get(objExtId.P7S1_Account__c).SomDig_DebitorennrBarter__c = '';
            }
        }
        
        update mapAccounts.values();
    }
}