src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Unit des Account Inhabers</description>
        <formula>Owner.P7S1_Unit__c</formula>
        <inlineHelpText>Unit des Account Inhabers</inlineHelpText>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOM_TVKundenverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Kundenverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Accounts (TV Kundenverkäufer)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_AccountAccess__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Freigaben</relationshipLabel>
        <relationshipName>Account_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Som_TVKundenverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Kundenverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Freigaben2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Freigabe</label>
    <nameField>
        <label>Account Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Freigaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountOwner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>Opportunity_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_TVKundenverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Kundenverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Opportunity Freigaben (TV Kundenverkäufer)</relationshipLabel>
        <relationshipName>Opportunity_Freigaben4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Enthält die Information welcher Unit der User zugeordnet ist</description>
        <inlineHelpText>Enthält die Information welcher Unit der User zugeordnet ist</inlineHelpText>
        <label>Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/P7S1_Account_SetSalesFields_Test.cls
/**
* ===================================================================
* (c) factory42 GmbH 2015, Germany, All rights reserved
* P7S1_Account_SetSalesFields_Test
* @author:		BS factory42
* @email:		bschneider@factory42.com
* @version:		V0.1
* @date:		Nov 25, 2015
* @last change:	
* @description:	
* @objects:		
* =================================================================
*/
@isTest
private class P7S1_Account_SetSalesFields_Test {
	
	private static User insertUser;
	private static String currentUserId = UserInfo.getUserId();
	private static Integer cnt = 30;

	/***********************
    * Test Account update
    ***/
    static testMethod void testAccountUpdate() {
    	
    	//Testdata
    	createTestData();
    	
    	Test.startTest();
    	//*********************************
		
		P7S1_Account_SetSalesFields.runTwice = false;
    	update [SELECT Id FROM Account];
    	
    	for(Account acc : [SELECT SOM_TVKundenverkaeufer__c FROM Account]){
    		system.assertEquals(currentUserId,acc.SOM_TVKundenverkaeufer__c);
    	}
    	
    	//*********************************
    	Test.stopTest();
		
    }
    
    /***********************
    * Test AccountAccess update
    ***/
    static testMethod void testAccountAccessUpdate() {
		
		//Testdata
    	createTestData();
    	
    	Test.startTest();
    	//*********************************
    	
    	P7S1_Account_SetSalesFields.runTwice = false;
    	update [SELECT Id FROM P7S1_AccountAccess__c];
    	
    	for(Account acc : [SELECT SOM_TVKundenverkaeufer__c FROM Account]){
    		system.assertEquals(currentUserId,acc.SOM_TVKundenverkaeufer__c);
    	}
    	
    	//*********************************
    	Test.stopTest();
        
    }
    
    /***********************
    * Test Opportunity Approval update
    ***/
    static testMethod void testOpportunityApprovalUpdate() {
		
		//Testdata
    	createTestData();
    	
    	Test.startTest();
    	//*********************************
    	
    	P7S1_Account_SetSalesFields.runTwice = false;
    	update [SELECT Id FROM P7S1_OpportunityApproval__c];
    	
    	for(Account acc : [SELECT SOM_TVKundenverkaeufer__c FROM Account]){
    		system.assertEquals(currentUserId,acc.SOM_TVKundenverkaeufer__c);
    	}
    	
    	//*********************************
    	Test.stopTest();
        
    }
    
    /***********************
    * Test data
    ***/
    private static void createTestData(){
    	
    	insertUser = createTestUser(999, null, null, '71M', true);
    	
    	system.runAs(insertUser){
    		//Account
    		list<Account> lstAcc = new list<Account>();
    		for(Integer i=0; i<cnt; i++){
	    		lstAcc.add(cls_P7S1_TestData.createTestAccount(false));
    		}
    		insert lstAcc;
	    	
	    	//AccountTeamMember, AccountAccess, OpportunityApproval
	    	list<AccountTeamMember> lstAtm = new list<AccountTeamMember>();
	    	list<P7S1_AccountAccess__c> lstAccAccess = new list<P7S1_AccountAccess__c>();
	    	list<Opportunity> lstOpp = new list<Opportunity>();
	    	for(Integer i=0; i<cnt; i++){
	    		lstAtm.add(new AccountTeamMember(AccountId = lstAcc[i].Id, TeamMemberRole = 'TV_Kundenverkäufer', UserId = currentUserId));
                lstAccAccess.add(new P7S1_AccountAccess__c(P7S1_Account__c = lstAcc[i].Id,OwnerId = currentUserId));
                lstOpp.add(cls_P7S1_TestData.createTestOpportunity(false, lstAcc[i]));
	    	}
	    	insert lstAtm;
	    	insert lstAccAccess;
	    	insert lstOpp;
	    	
	    	list<P7S1_OpportunityApproval__c> lstOppApproval = new list<P7S1_OpportunityApproval__c>();
	    	for(Integer i=0; i<cnt; i++){
	    		lstOppApproval.add(new P7S1_OpportunityApproval__c(P7S1_Opportunity__c = lstOpp[i].Id, P7S1_AccountOwner__c = insertUser.Id));
	    	}
	    	insert lstOppApproval;
    	}
    
    }
    
    //User
    public static User createTestUser(Integer i, Id idProfile, String idRole, String unit, Boolean insertObject){
        User obj = new User();
        if(idProfile == NULL) idProfile = [Select Id from Profile where Name = 'System Administrator' or Name='Systemadministrator' limit 1].id;
        obj.ProfileId = idProfile;
        obj.FirstName = 'First' + i;
        obj.LastName = 'Last' + i;
        obj.Username = 'test@email' + i + '.de';
        obj.Email = 'test@email' + i + '.de';
        obj.Alias = 'fila' + i;
        obj.CommunityNickname = 'test@email' + i + '.de';
        obj.TimeZoneSidKey = 'America/Los_Angeles';
        obj.LocaleSidKey = 'en_US';
        obj.EmailEncodingKey = 'ISO-8859-1';
        obj.LanguageLocaleKey = 'en_US';
        obj.IsActive = true;
        obj.UserRoleId = idRole;
        obj.P7S1_Unit__c = unit;
        
        if(insertObject)           insert obj;
        return obj;
    }
    
}