src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Agentur</fullName>
        <active>true</active>
        <description>Ein Unternehmen, welches im Auftrag von Werbungtreibende Marketing- und Werbekampagnen plant, Werbung entwirft und produziert und diese auch in den Medien platziert</description>
        <label>Agentur</label>
    </recordTypes>
    <recordTypes>
        <fullName>Werbetreibender</fullName>
        <active>true</active>
        <label>Werbetreibender</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SomDig_Mediagattung__c.object
<CustomObject>
    <description>Die erste Klassifizierung/Zuordnung des Werbeträgers zu einer Mediagattung (TV/Digital/Text)</description>
    <label>Mediagattung</label>
    <nameField>
        <label>Mediagattung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Prognose__c.object
<CustomObject>
    <description>Fasst alle Prognosen auf Basis der Werbetreibenden und Agenturen auch wenn es eine 1:n Beziehung ist</description>
    <fields>
        <fullName>SomDig_Jahr__c</fullName>
        <description>Für welches Geschäftsjahr gilt diese Prognose?</description>
        <inlineHelpText>Für welches Geschäftsjahr gilt diese Prognose?</inlineHelpText>
        <label>gültig für Geschäftsjahr</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_MedDiffInStream__c</fullName>
        <description>Prognose/Forecast-Wert für diesen Account im Bereich InStream des aktuellen Kalender-/ Geschäftsjahr (MN2).</description>
        <inlineHelpText>Prognose/Forecast-Wert für diesen Account im Bereich InStream des aktuellen Kalender-/ Geschäftsjahr (MN2).</inlineHelpText>
        <label>Prognose InStream</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_PrognoseQ1__c</fullName>
        <description>Prognose/Forecast-Wert für diesen Account  im Quartal 1 des aktuellen Kalender-/ Geschäftsjahr (MN2).</description>
        <inlineHelpText>Prognose/Forecast-Wert für diesen Account  im Quartal 1 des aktuellen Kalender-/ Geschäftsjahr (MN2).</inlineHelpText>
        <label>Prognose Q1</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_PrognoseQ2__c</fullName>
        <description>Prognose/Forecast-Wert für diesen Account  im Quartal 2 des aktuellen Kalender-/ Geschäftsjahr (MN2).</description>
        <inlineHelpText>Prognose/Forecast-Wert für diesen Account  im Quartal 2 des aktuellen Kalender-/ Geschäftsjahr (MN2).</inlineHelpText>
        <label>Prognose Q2</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_PrognoseQ3__c</fullName>
        <description>Prognose/Forecast-Wert für diesen Account  im Quartal 3 des aktuellen Kalender-/ Geschäftsjahr (MN2).</description>
        <inlineHelpText>Prognose/Forecast-Wert für diesen Account  im Quartal 3 des aktuellen Kalender-/ Geschäftsjahr (MN2).</inlineHelpText>
        <label>Prognose Q3</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_PrognoseQ4__c</fullName>
        <description>Prognose/Forecast-Wert für diesen Account  im Quartal 4 des aktuellen Kalender-/ Geschäftsjahr (MN2).</description>
        <inlineHelpText>Prognose/Forecast-Wert für diesen Account  im Quartal 4 des aktuellen Kalender-/ Geschäftsjahr (MN2).</inlineHelpText>
        <label>Prognose Q4</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_RelativesJahr__c</fullName>
        <description>Wobei handelt es sich hierbei um das in der Prognose ausgewählt Geschäftsjahr: ist es zum Zeitpunkt der Betrachtung das aktuelle Jahr (AJ), vorherige Jahr (VJ), nächste Jahr (NJ) oder außerhalb des Betrachtungszeitraums (out of scope). Dynamisches Infofeld zum Jahreswechsel. Dient dazu, in Formeln/RollUps nicht immer die Jahre wechseln zu müssen. Wird per Workflow/Feldaktualisierung befüllt, Basis ist Feld &quot;SomDig_RelativesJahrHelp&quot;</description>
        <inlineHelpText>Wobei handelt sich hierbei um das in der Prognose ausgewählt Geschäftsjahr: zum Zeitpunkt der Betrachtung das aktuelle Jahr (AJ), vorherige Jahr (VJ), nächste Jahr (NJ) oder außerhalb des Betrachtungszeitraums (out of scope). Wird automatisch befüllt.</inlineHelpText>
        <label>relatives Jahr</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_WtAgBeziehung__c</fullName>
        <description>Prognosen werden an &apos;WT AG Beziehungen&apos; verknüpft stat an einzelne Accounts. Sollte keine gewünschte Beziehung existieren, muss diese vorher noch im Objekt &apos;WT AG Beziehung&apos; angelegt werden</description>
        <inlineHelpText>Prognosen werden an &apos;WT AG Beziehungen&apos; verknüpft stat an einzelne Accounts. Sollte keine gewünschte Beziehung existieren, muss diese vorher noch im Objekt &apos;WT AG Beziehung&apos; angelegt werden</inlineHelpText>
        <label>WT AG Beziehung</label>
        <referenceTo>SomDig_WtAgBeziehung__c</referenceTo>
        <relationshipLabel>Prognosen Digital</relationshipLabel>
        <relationshipName>Prognosen_Digital</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Prognose Digital</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Prognose-Digital</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prognosen Digital</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SomDig_Umsatz__c.object
<CustomObject>
    <description>aggregierte Umsätze aus ProDia. Werden täglich automatisiert befüllt.</description>
    <fields>
        <fullName>SomDig_Jahr__c</fullName>
        <description>In welchem Geschäftsjahr ist der Umsatz aufgelaufen? Wird automatisch per SST befüllt</description>
        <inlineHelpText>In welchem Geschäftsjahr ist der Umsatz aufgelaufen?</inlineHelpText>
        <label>Jahr</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Mediagattung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Zuordnung des Umsatz-Datensatzes zur Mediagattung (Digital, TV, Text)</description>
        <inlineHelpText>Zuordnung des Umsatz-Datensatzes zur Mediagattung (Digital, TV, Text)</inlineHelpText>
        <label>Mediagattung</label>
        <referenceTo>SomDig_Mediagattung__c</referenceTo>
        <relationshipLabel>Umsätze Digital</relationshipLabel>
        <relationshipName>Umsaetze_Digital</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Mn2__c</fullName>
        <description>Monetärer Wert, MN2 bedeutet nach Abzug aller Rabatte (vor Skonto)</description>
        <inlineHelpText>Monetärer Wert, MN2 bedeutet nach Abzug aller Rabatte (vor Skonto)</inlineHelpText>
        <label>MN2</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_Quartal__c</fullName>
        <description>In welchem Quartal des jeweiligen Geschäftsjahres ist der Umsatz entstanden (Q1 bis Q4). Wird automatisch via SST befüllt</description>
        <inlineHelpText>In welchem Quartal des jeweiligen Geschäftsjahres ist der Umsatz entstanden (Q1 bis Q4)</inlineHelpText>
        <label>Quartal</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_RelativesJahr__c</fullName>
        <description>Wobei handelt es sich hierbei um das im Umsatz ausgewählt (Geschäfts-)Jahr: ist es zum Zeitpunkt der Betrachtung das aktuelle Jahr (AJ), vorherige Jahr (VJ), nächste Jahr (NJ) oder außerhalb des Betrachtungszeitraums (out of scope). Dynamisches Infofeld zum Jahreswechsel. Dient dazu, in Formeln/RollUps nicht immer die Jahre wechseln zu müssen. Wird per Workflow/Feldaktualisierung befüllt, Basis ist Feld &quot;SomDig_RelativesJahrHelp&quot;</description>
        <inlineHelpText>Wobei handelt sich hierbei um das im Umsatz ausgewählt (Geschäfts-)Jahr: zum Zeitpunkt der Betrachtung das aktuelle Jahr (AJ), vorherige Jahr (VJ), nächste Jahr (NJ) oder außerhalb des Betrachtungszeitraums (out of scope). Wird automatisch befüllt.</inlineHelpText>
        <label>relatives Jahr</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_WtAgBeziehung__c</fullName>
        <description>Verknüpfung der Umsatz-Datensätze an das JunctionObject &quot;WT AG Beziehungen&quot; statt an Accounts direkt. Für jede WT AG Beziehung muss ein Datensatz exisitieren</description>
        <inlineHelpText>Verknüpfung der Umsatz-Datensätze an das JunctionObject &quot;WT AG Beziehungen&quot; statt an Accounts direkt. Für jede WT AG Beziehung muss ein Datensatz exisitieren</inlineHelpText>
        <label>WT AG Beziehung</label>
        <referenceTo>SomDig_WtAgBeziehung__c</referenceTo>
        <relationshipLabel>Umsätze Digital</relationshipLabel>
        <relationshipName>Umsaetze_Digital</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Umsatz Digital</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Umsatz Digital</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Umsätze Digital</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SomDig_WtAgBeziehung__c.object
<CustomObject>
    <description>Junction-Objekt um Account-Beziehungen darstellen zu können, an denen Datensätze verknüpft werden wie Prognosen, Umsätze etc. (siehe auch Kundenvorgang 995 für eine detaillierte Beschreibung bzw. Anforderung).</description>
    <fields>
        <fullName>SomDig_BeziehungInhaber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>In der Regel der Inhaber/Betreuer des Werbetreibenders, ist aber manuell Auswählbar und kann daher individuell eingestellt werden</description>
        <inlineHelpText>In der Regel der Inhaber/Betreuer des Werbetreibenders, ist aber manuell Auswählbar und kann daher individuell eingestellt werden</inlineHelpText>
        <label>Beziehung Inhaber</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Id</field>
                <operation>equals</operation>
                <value>00e20000001QBtU</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>WT_AG_Beziehungen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WT AG Beziehung</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WT AG Beziehungsname</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WT AG Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/P7S1_TestdatageneratorAtmWtAg.cls
public with sharing class P7S1_TestdatageneratorAtmWtAg {
	static Final string WTNAME = 'Werbetreibender';
	static Final string AGNAME = 'Agentur';

	public static Account generateTestData(){
		Account wt = new Account();
        List<Account> accList = new List<Account>();
        List<SomDig_WtAgBeziehung__c> wtagList = new List<SomDig_WtAgBeziehung__c>();
        List<SomDig_Prognose__c> progList = new List<SomDig_Prognose__c>();
        List<SomDig_Umsatz__c> umsList = new List<SomDig_Umsatz__c>();

        //Create MediaGattung for Umsatz
		SomDig_Mediagattung__c m = new SomDig_Mediagattung__c();
		m.Name = 'Digital';
		insert m;

        // Agentur Accounts
        Account a_Agentur = cls_P7S1_TestData.createTestAccount(false);
        a_Agentur.name = AGNAME+'1';
        accList.add(a_Agentur);
        Account a_Agentur2 = cls_P7S1_TestData.createTestAccount(false);
        a_Agentur2.name = AGNAME+'2';
        accList.add(a_Agentur2);
        Account a_Agentur3 = cls_P7S1_TestData.createTestAccount(false);
        a_Agentur3.name = AGNAME+'3';
        accList.add(a_Agentur3);
        Account a_Agentur4 = cls_P7S1_TestData.createTestAccount(false);
        a_Agentur4.name = AGNAME+'4';
        accList.add(a_Agentur4);

        // Werbetreibende Accounts
        Account a_Werbetreibender = cls_P7S1_TestData.createTestAccount(false);
        a_Werbetreibender.name = WTNAME;
        accList.add(a_Werbetreibender);
        Account a_Werbetreibender2 = cls_P7S1_TestData.createTestAccount(false);
        a_Werbetreibender2.name = WTNAME+'2';
        accList.add(a_Werbetreibender2);
        Account a_WerbetreibenderDel = cls_P7S1_TestData.createTestAccount(false);
        a_WerbetreibenderDel.name = WTNAME+'Del';
        accList.add(a_WerbetreibenderDel);
        insert acclist;

        //Set WT Account for asserts
        wt = a_Werbetreibender;

        //WtAg Beziehungen
        SomDig_WtAgBeziehung__c wtag = cls_P7S1_TestData.createTestWTAG(false, a_Werbetreibender, a_Agentur);
        wtag.SomDig_BeziehungInhaber__c = Userinfo.getUserID();
        SomDig_WtAgBeziehung__c wtag2 = cls_P7S1_TestData.createTestWTAG(false, a_Werbetreibender, a_Agentur2);
        wtag2.SomDig_BeziehungInhaber__c = Userinfo.getUserID();
        SomDig_WtAgBeziehung__c wtag3 = cls_P7S1_TestData.createTestWTAG(false, a_Werbetreibender, a_Agentur3);
        wtag3.SomDig_BeziehungInhaber__c = Userinfo.getUserID();
        SomDig_WtAgBeziehung__c wtag4 = cls_P7S1_TestData.createTestWTAG(false, a_Werbetreibender, a_Agentur4);
        wtag4.SomDig_BeziehungInhaber__c = Userinfo.getUserID();
        SomDig_WtAgBeziehung__c wtag5 = cls_P7S1_TestData.createTestWTAG(false, a_Werbetreibender2, a_Agentur4);
        wtag4.SomDig_BeziehungInhaber__c = Userinfo.getUserID();
        wtagList.add(wtag);
        wtagList.add(wtag2);
        wtagList.add(wtag3);
        wtagList.add(wtag4);
        wtagList.add(wtag5);
        insert wtagList;

        //Prognose
		progList.add(populatePrognose(wtag.id,10));
		progList.add(populatePrognose(wtag2.id,5));
        progList.add(populatePrognose(wtag3.id,25));
        progList.add(populatePrognose(wtag4.id,20));
        progList.add(populatePrognose(wtag5.id,30));
        insert progList;

        //Umsatz
        for(integer i=1; i<5;i++){
			umsList.add(populateUmsatz(wtag.id,10,''+i,m.id));
			umsList.add(populateUmsatz(wtag2.id,5,''+i,m.id));
	        umsList.add(populateUmsatz(wtag3.id,25,''+i,m.id));
	        umsList.add(populateUmsatz(wtag4.id,20,''+i,m.id));
	        umsList.add(populateUmsatz(wtag4.id,20,''+i,m.id));
        }

        insert umsList;

        //update to start trigger for aggregate Results again
        update  wtagList;

		AccountTeamMember atm = new AccountTeamMember();
		atm.AccountId = wt.id;
		atm.UserId = Userinfo.getUserID();
		atm.TeamMemberRole = 'Digital_Sales';
		insert atm;
		update wt;

        delete a_WerbetreibenderDel;
        return wt;
	}

	static SomDig_Prognose__c populatePrognose(ID wtagID, integer proValue){
		SomDig_Prognose__c pro = new SomDig_Prognose__c();
		pro.SomDig_Jahr__c = ''+System.today().year();
        pro.SomDig_PrognoseQ1__c = proValue;
        pro.SomDig_PrognoseQ2__c = proValue;
        pro.SomDig_PrognoseQ3__c = proValue;
        pro.SomDig_PrognoseQ4__c = proValue;
        pro.SomDig_MedDiffInStream__c = 4*proValue;
        pro.SomDig_WtAgBeziehung__c = wtagID;
        return pro;
	}

	static SomDig_Umsatz__c populateUmsatz(ID wtagID, integer umsValue,string quartal, ID mediaGattung){
		SomDig_Umsatz__c ums = new SomDig_Umsatz__c();
		ums.SomDig_Jahr__c = ''+System.today().year();
        ums.SomDig_Mn2__c = umsValue;
        ums.SomDig_Mediagattung__c = mediaGattung;
        ums.SomDig_RelativesJahr__c = 'AJ';
        ums.SomDig_Quartal__c = quartal;
        ums.SomDig_WtAgBeziehung__c = wtagID;
        return ums;
	}
}