src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SomTv_ForecastPro7MAXXMN3__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Forecast Pro7 MAXX MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ADvendio__RTBAccount__c.object
<CustomObject>
    <description>PA web service writes data to this object.</description>
    <fields>
        <fullName>ADvendio__AdServerLogin__c</fullName>
        <description>PA web service writes to this field.</description>
        <inlineHelpText>RTB web service writes to this field.</inlineHelpText>
        <label>AdServer Login (deprecated)</label>
        <referenceTo>ADvendio__AdServer_Logins__c</referenceTo>
        <relationshipLabel>PA Accounts (deprecated)</relationshipLabel>
        <relationshipName>RTBAccounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PA Account (deprecated)</label>
    <nameField>
        <label>PAAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PA Accounts (deprecated)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SomTv_Agentur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agentur</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomTv_MN3__c</fullName>
        <description>MN3 als für gesamt P7S1 abgestimmter Standard Wert
[ Nettoinvestment der Opportunity bzw. MN3= MN2-Skonto% ]</description>
        <inlineHelpText>MN3 als für gesamt P7S1 abgestimmter Standard Wert
[ Nettoinvestment der Opportunity bzw. MN3= MN2-Skonto% ]</inlineHelpText>
        <label>MN3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_Rollup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChildCalculationField__c</fullName>
        <label>Child Calculation Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChildObject__c</fullName>
        <label>ChildObject</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObject__c</fullName>
        <label>Parent Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentResultField__c</fullName>
        <label>Parent Result Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipField__c</fullName>
        <description>Field on the child object which is referencing to the parent</description>
        <label>Relationship Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Count</fullName>
                </value>
                <value>
                    <fullName>Sum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WhereCondition__c</fullName>
        <label>WHERE-Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rollup</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Rollup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rollup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SomDig_Commitment__c.object
<CustomObject>
    <description>fasst die heutigen Commitments der Division Digital (aufgebaut im Bezug auf WT-AG Beziehung)</description>
    <fields>
        <fullName>SomDig_WtAgBeziehung__c</fullName>
        <description>Zugehörige Werbetreibende-Agentur Beziehung</description>
        <inlineHelpText>Zugehörige Werbetreibende-Agentur Beziehung</inlineHelpText>
        <label>WT-AG Beziehung</label>
        <referenceTo>SomDig_WtAgBeziehung__c</referenceTo>
        <relationshipName>Commitments_Digital</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Commitment Digital</label>
    <nameField>
        <displayFormat>Commitment-Digital-{000}</displayFormat>
        <label>Commitment Digital Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commitments Digital</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SomDig_RtbDataAggr__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_NetRevenue__c</fullName>
        <label>Nettoumsatz</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>RTB Data Aggr</label>
    <nameField>
        <displayFormat>RTBDA-{00000}</displayFormat>
        <label>RTB Data Aggr-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTB Data Aggr</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_WtAgBeziehung__c.object
<CustomObject>
    <description>Junction-Objekt um Account-Beziehungen darstellen zu können, an denen Datensätze verknüpft werden wie Prognosen, Umsätze etc. (siehe auch Kundenvorgang 995 für eine detaillierte Beschreibung bzw. Anforderung).</description>
    <label>WT AG Beziehung</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WT AG Beziehungsname</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WT AG Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SomTv_Agentursplit__c.object
<CustomObject>
    <fields>
        <fullName>SomTv_Agentur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Für Agentursplit verantwortliche Agentur.</inlineHelpText>
        <label>Agentur</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agentursplit</relationshipLabel>
        <relationshipName>Agentursplit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomTv_MN3__c</fullName>
        <inlineHelpText>Bitte geben Sie den MedioNetto 3 NUR mit dieser Agentur (Agentursplit) ein.</inlineHelpText>
        <label>MN3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Der Agentursplit bezieht sich auf folgende Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Agentursplit</relationshipLabel>
        <relationshipName>Agentursplit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomTv_Prozent_Anteil__c</fullName>
        <description>Definiert den Anteil einer Agentur an Gesamt MN3</description>
        <inlineHelpText>Definiert den Anteil einer Agentur an Gesamt MN3</inlineHelpText>
        <label>%-Anteil</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Agentursplit</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Agentursplit-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agentursplit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomTv_ForecastTV__c.object
<CustomObject>
    <description>Ganzjährige Eingabe des Forecasts  für TV</description>
    <fields>
        <fullName>SomTV_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forecasts TV</relationshipLabel>
        <relationshipName>Forecasts_TV</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomTv_Agentur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zugehörige Agentur für die dieser Forecast erstellt wird</description>
        <inlineHelpText>Zugehörige Agentur für die dieser Forecast erstellt wird</inlineHelpText>
        <label>Agentur</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forecast TV (Agentur)</relationshipLabel>
        <relationshipName>Forecast_TV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastPro7MAXXMN3__c</fullName>
        <label>Forecast Pro7 MAXX MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Forecast TV</label>
    <nameField>
        <label>Forecast TV</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast TV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_Rollup_Test.cls
@isTest
public class P7S1_Rollup_Test{


    public static testMethod void testSomDig_Commitment()
    {
        Account l_oAccWt = cls_P7S1_TestData.createTestAccount(true);
        Account l_oAccAg = cls_P7S1_TestData.createTestAccount(true);
        SomDig_WtAgBeziehung__c l_oWtAg = cls_P7S1_TestData.createTestWTAG(true,l_oAccWt,l_oAccAg);
        SomDig_Commitment__c l_oComm = cls_P7S1_TestData.createSomDigCommitment(true,l_oWtAg );
    }

    public static testMethod void testSomDigRtbDataAggr() {
        createTestRtbDataAggr(true);
    }

    public static testMethod void testAdvRtbAccount() {
        createTestAdvRtbAccount(true);
    }

    @isTest
	public static void testAccountForecast()
    {
		
        Account acc = cls_P7S1_TestData.createTestAccount(true);
        
        SomTv_ForecastTV__c fc1 = new SomTv_ForecastTV__c ();
        fc1.SomTv_ForecastPro7MAXXMN3__c = 5.74;
        fc1.SomTV_Account__c =  acc.id;

        insert new List<SomTv_ForecastTV__c>{fc1};
    }    
    
    public static testmethod void testRollup(){

        // Sum Rollup
        createRollup(true, 'Opportunity', 'SomTv_Agentursplit__c', 'SomTv_Opportunity__c', 'SomTv_MN3__c', 'SomTv_MN3__c', 'SomTv_MN3__c > 0', 'Sum');

        // Count Rollup
        createRollup(true, 'Opportunity', 'SomTv_Agentursplit__c', 'SomTv_Opportunity__c', null, 'TotalOpportunityQuantity', null, 'Count');

        Account objAcc = cls_P7S1_TestData.createTestAccount(true);
        Opportunity objOpp = cls_P7S1_TestData.createTestOpportunity(true, objAcc, null);


        // TESTINSERT: Create Agentursplits and add them together
        List<SomTv_Agentursplit__c> listAS = new List<SomTv_Agentursplit__c>();


        SomTv_Agentursplit__c objAS1 = createTestAgenturSplit(false, objOpp, objAcc, 10);
        objAS1.SomTv_MN3__c = 10;
        listAS.add(objAS1);


        SomTv_Agentursplit__c objAS2 = createTestAgenturSplit(false, objOpp, objAcc, 30);
        objAS2.SomTv_MN3__c = 20;
        listAS.add(objAS2);


        SomTv_Agentursplit__c objAS3 = createTestAgenturSplit(false, objOpp, objAcc, 60);
        objAS3.SomTv_MN3__c = 30;
        listAS.add(objAS3);

        insert listAS;


        // Prepare newMap for insert
        Map<ID, sObject> newMap = new Map<ID, sObject>();
        for(SomTv_Agentursplit__c o : listAS)
            newMap.put(o.ID, o);


        // Test insert
        P7S1_Rollup.startRollup('SomTv_Agentursplit__c', null, listAS,  null, newMap,  true, false, false, false, true);


        // Check sum on Opp
        objOpp = [SELECT SomTv_MN3__c, TotalOpportunityQuantity FROM Opportunity WHERE ID = :objOpp.ID];
        Double dSum = objAS1.SomTv_MN3__c + objAS2.SomTv_MN3__c + objAS3.SomTv_MN3__c;

        System.assert(dSum == objOpp.SomTv_MN3__c);
        System.assert(listAS.size() == objOpp.TotalOpportunityQuantity);



        // TESTUPDATE
        // Prepare listOld
        List<SomTv_Agentursplit__c> listASOld = new List<SomTv_Agentursplit__c>();
        for(SomTv_Agentursplit__c o : listAS)
            listASOld.add(o);



        // Prepare oldmap
        Map<ID, sObject> oldMapUpdate = new Map<ID, sObject>();
        for(SomTv_Agentursplit__c o : listASOld)
            oldMapUpdate.put(o.ID, o);


        // Do an update
        objAS3.SomTv_MN3__c = 20;
        update objAS3;

        SomTv_Agentursplit__c objAS3AfterUpdate = objAS3.clone(true);


        // Prepare listNew
        List<SomTv_Agentursplit__c> listASNew = new List<SomTv_Agentursplit__c>();
        listASNew.add(objAS1);
        listASNew.add(objAS2);
        listASNew.add(objAS3AfterUpdate);


        // Prepare newMap
        Map<ID, sObject> newMapUpdate = new Map<ID, sObject>();
        for(SomTv_Agentursplit__c o : listASNew)
            newMapUpdate.put(o.ID, o);


        P7S1_Rollup.startRollup('SomTv_Agentursplit__c', listASOld, listASNew,  oldMapUpdate, newMapUpdate,  false, true, false, false, true);

        Opportunity objNewOpp = [SELECT SomTv_MN3__c FROM Opportunity WHERE ID = :objOpp.ID];
        dSum = objAS1.SomTv_MN3__c + objAS2.SomTv_MN3__c + objAS3.SomTv_MN3__c;
    }






    public static testmethod void testRollupBatch(){

        Account objAcc = cls_P7S1_TestData.createTestAccount(true);
        Opportunity objOpp = cls_P7S1_TestData.createTestOpportunity(true, objAcc, null);


        // TESTINSERT: Create Agentursplits and add them together
        List<SomTv_Agentursplit__c> listAS = new List<SomTv_Agentursplit__c>();


        SomTv_Agentursplit__c objAS1 = createTestAgenturSplit(false, objOpp, objAcc, 10);
        objAS1.SomTv_MN3__c = 10;
        listAS.add(objAS1);


        SomTv_Agentursplit__c objAS2 = createTestAgenturSplit(false, objOpp, objAcc, 30);
        objAS2.SomTv_MN3__c = 20;
        listAS.add(objAS2);


        SomTv_Agentursplit__c objAS3 = createTestAgenturSplit(false, objOpp, objAcc, 60);
        objAS3.SomTv_MN3__c = 30;
        listAS.add(objAS3);

        insert listAS;


        // Count Rollup
        P7S1_Rollup__c objRollup = createRollup(true, 'Opportunity', 'SomTv_Agentursplit__c', 'SomTv_Opportunity__c', null, 'TotalOpportunityQuantity', null, 'Count');



        // Create Class and StandardController
        PageReference pageRef = Page.P7S1_RollupBatch;
        Test.setCurrentPage(pageRef);
        System.currentPageReference().getParameters().put('id', objRollup.Id);


        Test.startTest();

        P7S1_Rollup con = new P7S1_Rollup();
        con.recalculate();


        Test.stopTest();
    }


    public static P7S1_Rollup__c createRollup(Boolean insertObject, String sParentObject, String sChildObject, String sRelationfield, String sChildCalculationField, String sParentResultField, String sWhereCondition, String sType) {
        P7S1_Rollup__c rollup   = new P7S1_Rollup__c();
        rollup.Active__c        = true;
        rollup.ChildCalculationField__c  = sChildCalculationField;
        rollup.ChildObject__c            = sChildObject;
        rollup.ParentObject__c           = sParentObject;
        rollup.ParentResultField__c      = sParentResultField;
        rollup.RelationshipField__c      = sRelationfield;
        rollup.Type__c                   = sType;
        rollup.WhereCondition__c         = sWhereCondition;

        if (insertObject) insert rollup;
        return rollup;
    }


    // TODO : Auslagern
    public static SomTv_Agentursplit__c createTestAgenturSplit(Boolean insertObject, Opportunity opportunity,Account account, Integer anteil) {
        SomTv_Agentursplit__c AgenturSplit_TestData = new SomTv_Agentursplit__c();
        AgenturSplit_TestData.SomTv_Prozent_Anteil__c = anteil;
        AgenturSplit_TestData.SomTv_Opportunity__c = opportunity.ID;
        AgenturSplit_TestData.SomTv_Agentur__c = account.ID;

        if (insertObject) insert AgenturSplit_TestData;
        return AgenturSplit_TestData;
    }

    public static SomDig_RtbDataAggr__c createTestRtbDataAggr(Boolean insertObject) {
        SomDig_RtbDataAggr__c RtbDataAggr_TestData = new SomDig_RtbDataAggr__c();
        RtbDataAggr_TestData.SomDig_NetRevenue__c = 123;
        if (insertObject) insert RtbDataAggr_TestData;
        return RtbDataAggr_TestData;
    }

    public static ADvendio__RTBAccount__c createTestAdvRtbAccount(Boolean insertObject) {
        ADvendio__RTBAccount__c RtbAccount_TestData = new ADvendio__RTBAccount__c();
        RtbAccount_TestData.Name = 'abc-test';
        RtbAccount_TestData.ADvendio__AdServerLogin__c = cls_P7S1_TestData.createTestAdServerLogin(true).Id;
        if (insertObject) insert RtbAccount_TestData;
        return RtbAccount_TestData;
    }

}