src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ven_Business_Model__c</fullName>
        <description>Dieses Feld kann gelöscht werden.</description>
        <inlineHelpText>Dieses Feld wird nicht länger benötigt und kann gelöscht werden.</inlineHelpText>
        <label>Business Model LOESCHEN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ven_USP__c</fullName>
        <description>Diese Information wird auf den Investment Summary übertragen.</description>
        <inlineHelpText>Diese Information wird auf den Investment Summary übertragen.</inlineHelpText>
        <label>USP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ven_Year_of_Founding__c</fullName>
        <description>Diese Information wird auf den Investment Summary übertragen.</description>
        <inlineHelpText>Diese Information wird auf den Investment Summary übertragen.</inlineHelpText>
        <label>Year of Founding</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Kontakt_f_r_das_Investment_Summary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Diese Checkbox ist für Seven Ventures angelegt und markiert Kontakte die im Investement Summary angezeigt werden sollen.</description>
        <inlineHelpText>Mit dieser Checkbox wird gesteuert ob der Kontakt im Investment Summary angezeigt werden soll oder nicht.</inlineHelpText>
        <label>Kontakt für das Investment Summary</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ven_Competitors__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Account_Key_Player_Competition__c</fullName>
        <description>Der Account zu dem der Competitor eingetragen werden soll wird hier erfasst.</description>
        <inlineHelpText>Der Account zu dem der Competitor eingetragen werden soll wird hier erfasst.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Key Players &amp; Competitions</relationshipLabel>
        <relationshipName>Key_Players_Competitions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Competitor__c</fullName>
        <description>Hier wird der Competitor zur Account erfasst. Der Competitor muss nicht als Account in Salesforce erfasst werden.</description>
        <inlineHelpText>Hier wird der Competitor zur Account erfasst. Der Competitor muss nicht als Account in Salesforce erfasst werden.</inlineHelpText>
        <label>Competitor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ven_Informationen_zum_competitor__c</fullName>
        <description>Hier werden Informationen zum Competitor der verlinkten Accounts angetragen.
Für Seven Ventures.</description>
        <inlineHelpText>Hier bitte Informationen zum Competitor zur verknüpften Account eintragen.</inlineHelpText>
        <label>Informationen zum Competitor</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Key Players &amp; Competition</label>
    <nameField>
        <displayFormat>KPC-{00000000}</displayFormat>
        <label>Key Players &amp; Competition-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Players &amp; Competitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Contract_Terms__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Vertrag_SevenVentures__c</fullName>
        <description>Hier wird die Verbindung eines Contract Terms zum Vertrag eingetragen.</description>
        <inlineHelpText>Hier wird die Verbindung eines Contract Terms zum Vertrag eingetragen.</inlineHelpText>
        <label>Vertrag (SevenVentures)</label>
        <referenceTo>Ven_Vertrag_SevenVentures__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Terms</label>
    <nameField>
        <displayFormat>VenCT-{0000000}</displayFormat>
        <label>Contract Term-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Round__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Account__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Hier handelt es sich um die Firma (Account) an der die Investoren beteiligt sind.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rounds</relationshipLabel>
        <relationshipName>Rounds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Category__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Hier wird die Category der Firma (Accounts) eingetragen an der die Investoren beteiligt sind.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ven_Founders_Equity_Share__c</fullName>
        <label>dontUse</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ven_Round_Number__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Hier wird die Beteiligungsrunde erfasst.</inlineHelpText>
        <label>Round Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ven_SV_Equity_Share__c</fullName>
        <label>dontUse</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ven_SV_Share__c</fullName>
        <description>Formelfeld was die Beteiligung von SV in % ausgibt.</description>
        <formula>0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hier werden die Anteile von Seven Ventures an den Account in % angezeigt.</inlineHelpText>
        <label>dontUse</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_all_Shares__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Hier wird die Summe alles Shares die im Umlauf sind automatisch addiert.</inlineHelpText>
        <label>#Shares</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Round</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Round-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Share__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Account__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Hier handelt es sich um die Firma (Account) an der die Investoren beteiligt sind.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shares (Account)</relationshipLabel>
        <relationshipName>Cap_Table_s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Round_Number__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt. Die Formel kopiert den Wert aus dem gleichnamigen Feld aus dem Objekt Round.</description>
        <formula>Ven_Round__r.Ven_Round_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hier wird die Beteiligungsrunde erfasst per Formel.</inlineHelpText>
        <label>Round Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ven_Round__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Die Round zu der dieser Share gehört.</inlineHelpText>
        <label>Round</label>
        <referenceTo>Ven_Round__c</referenceTo>
        <relationshipLabel>Shares</relationshipLabel>
        <relationshipName>Ven_Shares</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Share__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <formula>Ven_Shares__c / Ven_Round__r.Ven_all_Shares__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hier werden automatisch die % der Beteiligungen errechnet.</inlineHelpText>
        <label>Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Shareholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Bitte den Shareholder (Account) eingetragen für den verknüpften Account.</inlineHelpText>
        <label>Shareholder</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Shareholder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ven_Shares__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Bitte die Beteiligung des Investors an der Firma (Account) eintragen in einer bestimmten Beteiligungsrunde.</inlineHelpText>
        <label>Shares</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Share</label>
    <nameField>
        <displayFormat>CT-{0000000}</displayFormat>
        <label>Share-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Vertrag_SevenVentures__c.object
<CustomObject>
    <description>Vertragsobjekt für SevenVentures Verträge</description>
    <fields>
        <fullName>Ven_Contract_Status__c</fullName>
        <description>Der Vertragsstatus wird hiermit erfasst.</description>
        <inlineHelpText>Der Vertragsstatus wird hiermit erfasst.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ven_Opportunity__c</fullName>
        <description>Verknüpfung des Vertrages mit einer Opportunity.</description>
        <inlineHelpText>Mit diesem Feld wird die Verknüpfung der Vertrages mit eine Opportunity hergestellt.</inlineHelpText>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Verträge</relationshipLabel>
        <relationshipName>Vertr_ge_Sevenventures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vertrag (Sevenventures)</label>
    <nameField>
        <displayFormat>VenV-{00000000}</displayFormat>
        <label>Vertrag (SevenVentures)-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verträge (Sevenventures)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvestmentSummaryController.cls
/**
 * @author: ADvendio.com (helge.kosuch@advendio.com)
 */

public with sharing class InvestmentSummaryController {
    
	public class InvestmentSummaryControllerException extends Exception{ 
	}	    
    
    final static Id medialeistungsVertragsRecordTypeId; 
    static { 
    	final String failMsg = 'Could not find Contract RecordType Medialeistungsvertrag';
    	
        try {
       		medialeistungsVertragsRecordTypeId = ClsHelper.queryMedialeistungsVertragsRecordTypeId();
        } catch (Exception e) {
            throw new InvestmentSummaryControllerException(failMsg, e);
        }

   		if (medialeistungsVertragsRecordTypeId == null) {
            throw new InvestmentSummaryControllerException(failMsg);
   		}        
    }
    
    

	public Ven_Round__c currentRound {get; private set;}
    
    public PdfGenerator pdfGeneratorInstance {get; private set;}
    {
        pdfGeneratorInstance = new PdfGenerator();
    }
    
    static final Boolean DEBUG = ClsHelper.isSandboxOrgFlag;
    
    public String getStyleEverywhere() {
        return pdfGeneratorInstance.renderAsPdf?'':'width: 900px;'; 
    }

    public PageReference pdfNewPageReference() { 
        return pdfGeneratorInstance.pdfNewPageReference(opp.id);
    }   

    // Do not try to include this in a test method. It will fail with "getContent not allowed in test methods"
    public PageReference pdfSaveAsAttachment() { 
        return pdfGeneratorInstance.pdfSaveAsAttachment(opp.id, 'Investment_Summary',  false);
    }
    
    public ContractTerms termsInstance {get; private set;}

    public List<Ven_Share__c> shares {get; private set;} 

    private Opportunity oppPrivate;
    public Opportunity opp {get {return oppPrivate;}}
    public String capTable {get; private set;} 
    
    public Competitors competitorsInstance {get; private set;}    

    public class Competitors {
        private List<Ven_Competitors__c> competitors {get; private set;}
        public String listOfNames {get; private set;} 
        public String description {get; private set;} 
        
        public Competitors(Opportunity opp) {
            competitors = [SELECT id,Ven_Competitor__c, Ven_Informationen_zum_competitor__c 
                    FROM Ven_Competitors__c WHERE Ven_Account_Key_Player_Competition__c=:opp.accountId
            ];
            
            listOfNames = ClsHelper.newStringWithSeparators(competitors,'Ven_Competitor__c', ' / ');
            description = ClsHelper.newStringWithSeparators(competitors,'Ven_Informationen_zum_competitor__c', ' / ');
        }
    }
    
    public TeamMembers teamMembersInstance {get; private set;}
    
    // This is called from other test methods.
    public static void testTeamMembers(Opportunity opp) {
	    TeamMembers members = new TeamMembers(opp);
        
        members.getDealTeam();

		OpportunityTeamMember  otMember = new OpportunityTeamMember();
        
        members.setNames(otMember,'Industry Expert');
        members.setNames(otMember,'Account Manager');
        members.setNames(otMember,'Deal Analyst');
        members.setNames(otMember,'Media Expert');
        members.setNames(otMember,'Source');
    } 
    
    public class TeamMembers {
        String expertName = '-';
        String ownerName = '-';
        String analystName = '-';

        public String mediaExpert {get; private set;}
        {
            mediaExpert = '-';
        }
        public String sourcePerson {get; private set;}
        {
            sourcePerson = '-';
        }
        
        // This is just not private for the test method
        void setNames(OpportunityTeamMember otMember, String str) {
            if (str=='Industry Expert') {
                expertName = otMember.user.lastname;
            } else if (str=='Account Manager') {
                ownerName = otMember.user.lastname;
            } else if (str=='Deal Analyst') {
                analystName = otMember.user.lastname;
            } else if (str=='Media Expert') {
                mediaExpert = otMember.user.lastname;
            } else if (str=='Source') {
                sourcePerson = otMember.user.lastname;        
            }
        }   
        
        TeamMembers(Opportunity opp) {
            for (OpportunityTeamMember member: opp.OpportunityTeamMembers) {
                setNames(member, member.TeamMemberRole);
            }        
        } // end method
        
        public String getDealTeam() { 
            return expertName 
            + ' / ' + ownerName 
            + ' / ' + analystName;
        }
    }
    
    public String getManagementTeam() {
        return getManagementTeam(opp.OpportunityContactRoles);
    }
    
    private static String getManagementTeam(List<OpportunityContactRole> opportunityContactRoles) {
        String str = '';
        
        for (OpportunityContactRole contactRole : opportunityContactRoles) {
            str += contactRole.contact.name + ' (' + contactRole.role + ')<br/>';
        }
        return str;     
    }

    public InvestmentSummaryController() { //constructor
        this(ApexPages.currentPage().getParameters().get('id'));
    }
    
    public InvestmentSummaryController(ApexPages.StandardController stdController) { //constructor
        this(((Opportunity)stdController.getRecord()).id);
    }
    
    public InvestmentSummaryController(Id oppId) { //constructor
        
        oppPrivate = [SELECT
            id
            ,(SELECT id
                ,User.lastname 
                ,TeamMemberRole // a picklist
                FROM OpportunityTeamMembers
            )
            ,(SELECT id
                          ,role // a picklist
              ,Contact.Name
              FROM OpportunityContactRoles WHERE Contact.Kontakt_f_r_das_Investment_Summary__c	= true
            )
            ,(SELECT id
              FROM Vertr_ge_Sevenventures__r // Ven_Vertrag_SevenVentures__c
              WHERE RecordTypeId=:medialeistungsVertragsRecordTypeId AND Ven_Contract_Status__c='Signed'
            )
            ,Account.id
            ,Account.name
            ,Account.Ven_Business_Model__c
            ,Account.Ven_USP__c
            ,Account.Ven_Year_of_Founding__c
            FROM Opportunity WHERE id=:oppId
        ];
        
        /*
        Ven_Contract_Terms__c contractTerms = [ SELECT
        FROM Ven_Contract_Terms__c WHERE Ven_Vertrag_SevenVentures_del__c=:opp.account.];
                */
        
        teamMembersInstance = new TeamMembers(opp);

        shares = new List<Ven_Share__c>(); 
        currentRound = capTablesAdd(shares, opp.accountId);        
        
        termsInstance = new ContractTerms(opp.Vertr_ge_Sevenventures__r);
        
        competitorsInstance = new Competitors(opp);
    }
    
        
    private static Ven_Round__c capTablesAdd(List<Ven_Share__c> shares, Id accountId) {
 
        Ven_Round__c mostRecentRound = new Ven_Round__c(
                Ven_all_Shares__c = 0.0
                ,Ven_Round_Number__c = 0.0
                ,Ven_Founders_Equity_Share__c = 0.0
                ,Ven_Category__c =''
            ); 
        
        { // init 
            List<Ven_Round__c> rounds = [SELECT id
    		,Ven_Round_Number__c
            ,Ven_Founders_Equity_Share__c
            ,Ven_all_Shares__c
            ,Ven_SV_Equity_Share__c
            ,Ven_SV_Share__c                             
            ,Ven_Category__c                          
            FROM Ven_Round__c WHERE Ven_Account__c=:accountId];                            
            
            // Find the most recent round, which is the one with highest round number:
            for (Ven_Round__c round : rounds) {
                if (round.Ven_Round_Number__c>mostRecentRound.Ven_Round_Number__c) {
                    mostRecentRound = round;
                }
            }
        }
        
        shares.addAll([SELECT id
                    ,Ven_Shareholder__r.name
                    ,Ven_Shares__c
                    ,Ven_Share__c
                  FROM Ven_Share__c WHERE Ven_Round__c=:mostRecentRound.id]);

        return mostRecentRound;
    }
    
    public static void deleteRounds(Id accId) {
        for (List<Ven_Round__c> o : [SELECT id FROM Ven_Round__c WHERE Ven_account__c=:accId] ) {
            delete o;
        }
    }    
    
    @isTest 
    static void testInvestmentSummaryController() {
        Account acc = ClsHelper.newTestAccount(
            System.UserInfo.getUserId()
            , 'Test account 1'
        );
        System.debug('UserId=='+System.UserInfo.getUserId());
        insert acc;
        Opportunity opp = cls_P7S1_Temp_TestData.createTestOpportunity(false, acc, NULL);
        opp.StageName = cls_P7S1_Temp_TestData.nameOfAWonStage;

  //      ClsHelper.insertTestOpp(acc.id); 
        insert opp;

        
        Ven_Vertrag_SevenVentures__c vertrag = ClsHelper.insertVertrag(opp.id, medialeistungsVertragsRecordTypeId);
        insert new Ven_Standart_Terms__c(Ven_Abschnitt__c = 'Example Abschnittsname');
        ClsHelper.insertTerms(vertrag.id); 
        ClsHelper.insertRounds1And2AndShares(acc.id);
        
        InvestmentSummaryController controller = new InvestmentSummaryController(opp.id);
        
        controller.getStyleEverywhere();
		controller.pdfNewPageReference();        
        controller.getManagementTeam();
      
        InvestmentSummaryController.testTeamMembers(opp); 
    }     
}