src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accountname_Kurzform__c</fullName>
        <description>Kurzform des Accountnamen zur einfachen Suche Beispiel
SevenOne Media GmbH - &gt; 71M SOM</description>
        <inlineHelpText>Kurzform des Accountnamen zur einfachen Suche Beispiel
SevenOne Media GmbH - &gt; 71M SOM</inlineHelpText>
        <label>Accountname Kurzform</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_ExternalId__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_Account__c</fullName>
        <description>Nimmt die ID aus Prosa, SAP oder anderen Anwendungen auf für diesen Account</description>
        <inlineHelpText>Nimmt die ID aus Prosa, SAP oder anderen Anwendungen auf für diesen Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Externe IDs</relationshipLabel>
        <relationshipName>P7S1_ExternalId</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>P7S1_Source__c</fullName>
        <description>In welchem System kennzeichnet diese ID diesen Account eineindeutig?</description>
        <inlineHelpText>In welchem System kennzeichnet diese ID diesen Account eineindeutig?
Wichtig ist das bei Konzerninternen Accounts immer eine separate Sachkontonummer erfasst wird.</inlineHelpText>
        <label>Quelle/System</label>
        <picklist>
            <picklistValues>
                <fullName>Debitorennr BK 29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debitorennr BK 29 - Barter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debitorennr TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nielsen-ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProSa/ProSedi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sachkonto konzernintern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vermarkter-Id (ProSa)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Externe ID</label>
    <nameField>
        <label>Externe ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Externe IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GetCompanyByName.cls
/**
*
* This function should return a list of Accounts with their assigned P7S1_ExternalIds as response.
*
*/

@RestResource(urlMapping='/GetCompanyByName/*')
global with sharing class GetCompanyByName {

	@HttpGet
	global static void doGet() {

		RestRequest req = RestContext.request;
		RestResponse res = RestContext.response;
		res.addHeader('Content-Type', 'application/json');

		// read param in
		String companyName = RestContext.request.params.get('Name');

		System.debug('>>>> GetCompanyByName param in ' + companyName);

		// response
		ResponseWrapper response = new ResponseWrapper();
		response.request.put('Name', companyName);

		// pre condition
		// param in must not be null

		if (String.isEmpty(companyName)) {
			response.status.put('success', 'false');
			response.status.put('error', 'param Name is missing');

			res.statusCode = 400;
			res.responseBody = blob.valueOf(JSON.serialize(response));

			return;
		}

		try {
			// Wild card
			if (companyName.indexOf('*') > -1) {
				companyName = '%' + companyName.replaceAll('\\*', '') + '%';
			}

			// all pre condition ok
			List < Account > accounts = [SELECT AccountNumber, Name, RecordType.Name, Accountname_Kurzform__c,Parent.AccountNumber, (SELECT Name FROM P7S1_ExternalId__r WHERE P7S1_Source__c = 'ProSa/ProSedi') FROM Account WHERE Name LIKE :companyName];

			response.results = new Map<String,Object>();
			List<Map<String,Object>> records = new List<Map<String,Object>>();

			for (Account acc : accounts) {

				Map<String,Object> rec = new Map<String,Object>();
				rec.put('Name', acc.Name);
				rec.put('ProRexId__c', acc.AccountNumber);
				rec.put('RecordType.Name', acc.RecordType.Name);
				rec.put('Accountname_Kurzform__c', acc.Accountname_Kurzform__c);
				rec.put('Parent.ProRexId__c', acc.Parent.AccountNumber);
				rec.put('Industry', '');

				// handle the nested query
				List<Map<String,String>> p7s1records = new List<Map<String,String>>();
				for (P7S1_ExternalId__c p7s1 : acc.P7S1_ExternalId__r) {

					Map<String,String> p7s1rec = new Map<String,String>();
					p7s1rec.put('Name', p7s1.Name);

					p7s1records.add(p7s1rec);
				}


				rec.put('P7S1_ExternalId__c', p7s1records);
				records.add(rec);

			}

			response.results.put('Account', records);

			res.statusCode = 200;
			res.responseBody = blob.valueOf(JSON.serialize(response));

			System.debug('>>>> GetCompanyByName' + JSON.serializePretty(response));


		} catch(Exception ex) {

			response.status.put('success', 'false');
			response.status.put('error', ex.getMessage());

			res.statusCode = 400;

			res.responseBody = blob.valueOf(JSON.serialize(response));

		}
	}
}