src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SomDig_DebitorennrBarter__c</fullName>
        <label>SomDig DebitorennrBarter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Debitorennr__c</fullName>
        <description>Hidden Field, Storing external id for the media campaign</description>
        <label>SomDig Debitorennr</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_ExternalId__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_Source__c</fullName>
        <description>In welchem System kennzeichnet diese ID diesen Account eineindeutig?</description>
        <inlineHelpText>In welchem System kennzeichnet diese ID diesen Account eineindeutig?
Wichtig ist das bei Konzerninternen Accounts immer eine separate Sachkontonummer erfasst wird.</inlineHelpText>
        <label>Quelle/System</label>
        <picklist>
            <picklistValues>
                <fullName>Debitorennr BK 29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debitorennr BK 29 - Barter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debitorennr TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nielsen-ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProSa/ProSedi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sachkonto konzernintern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vermarkter-Id (ProSa)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Externe ID</label>
    <nameField>
        <label>Externe ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Externe IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/P7S1_ExternalID_DebNrSync_Test.cls
@isTest
public class P7S1_ExternalID_DebNrSync_Test {
    
    @TestSetup
    public static void testSetup(){
        cls_P7S1_TestData.createTestAccount(true);
    }

    @isTest
    public static void test_syncDebNrOnInsert(){
        Account oneAcc = [SELECT ID, SomDig_DebitorennrBarter__c, SomDig_Debitorennr__c FROM Account LIMIT 1];
        P7S1_ExternalId__c oneExtId = cls_P7S1_TestData.createTestExternalId(false, oneAcc);
        oneExtId.P7S1_Source__c = 'Debitorennr BK 29 - Barter';      
        
        Test.startTest();
        insert oneExtId;
        Test.stopTest();
        
        Account uptAcc = [SELECT ID, SomDig_DebitorennrBarter__c, SomDig_Debitorennr__c FROM Account LIMIT 1];
        System.assert(uptAcc.SomDig_DebitorennrBarter__c.contains(oneExtId.Name), 'Expected Value: '+oneExtId.Name+' , Existing Value: '+uptAcc.SomDig_DebitorennrBarter__c);
    }
    
    @isTest
    public static void test_syncDebNrOnInsert_negative(){
        delete [SELECT Id, Name, P7S1_Source__c FROM P7S1_ExternalId__c];
        
        Account oneAcc = [SELECT ID, SomDig_DebitorennrBarter__c, SomDig_Debitorennr__c FROM Account LIMIT 1];
        P7S1_ExternalId__c oneExtId = cls_P7S1_TestData.createTestExternalId(false, oneAcc);
        oneExtId.P7S1_Source__c = 'Nielsen-ID';      
        
        Test.startTest();
        insert oneExtId;
        Test.stopTest();
        
        Account uptAcc = [SELECT ID, SomDig_DebitorennrBarter__c, SomDig_Debitorennr__c FROM Account LIMIT 1];
        System.assert(uptAcc.SomDig_DebitorennrBarter__c == Null, 'Expected Value: '+null+' , Existing Value: '+uptAcc.SomDig_DebitorennrBarter__c);
        System.assert(uptAcc.SomDig_Debitorennr__c == Null, 'Expected Value: '+null+' , Existing Value: '+uptAcc.SomDig_Debitorennr__c);
    }
    
    @isTest
    public static void test_syncDebNrOnUpdate(){
        P7S1_ExternalId__c oneExtId = [SELECT Id, Name, P7S1_Source__c FROM P7S1_ExternalId__c LIMIT 1];
        oneExtId.P7S1_Source__c = 'Debitorennr BK 29 - Barter';
        
        Test.startTest();
        update oneExtId;
        Test.stopTest();
        
        Account uptAcc = [SELECT ID, SomDig_DebitorennrBarter__c, SomDig_Debitorennr__c FROM Account LIMIT 1];
        System.assert(uptAcc.SomDig_DebitorennrBarter__c.contains(oneExtId.Name), 'Expected Value: '+oneExtId.Name+' , Existing Value: '+uptAcc.SomDig_DebitorennrBarter__c);
        System.assert(uptAcc.SomDig_Debitorennr__c.contains(oneExtId.Name), 'Expected Value: '+oneExtId.Name+' , Existing Value: '+uptAcc.SomDig_Debitorennr__c);
    }
    
    @isTest
    public static void test_syncDebNrOnDelete(){
        P7S1_ExternalId__c oneExtId = [SELECT Id, Name, P7S1_Source__c FROM P7S1_ExternalId__c LIMIT 1];
        
        Test.startTest();
        delete oneExtId;
        Test.stopTest();
        
        System.assert([SELECT Id FROM P7S1_ExternalId__c].size() == 0);
        System.assert([SELECT ID, SomDig_DebitorennrBarter__c, SomDig_Debitorennr__c FROM Account LIMIT 1].SomDig_Debitorennr__c == null);
    }
    
    @isTest
    public static void test_syncDebNrOnDeleteBarter(){
        P7S1_ExternalId__c oneExtId = [SELECT Id, Name, P7S1_Source__c FROM P7S1_ExternalId__c LIMIT 1];
        oneExtId.P7S1_Source__c = 'Debitorennr BK 29 - Barter';
        update oneExtId;
        
        Test.startTest();
        delete oneExtId;
        Test.stopTest();
        
        System.assert([SELECT Id FROM P7S1_ExternalId__c].size() == 0);
        System.assert([SELECT ID, SomDig_DebitorennrBarter__c, SomDig_Debitorennr__c FROM Account LIMIT 1].SomDig_DebitorennrBarter__c == null);
    }
    
}