src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Unit des Account Inhabers</description>
        <formula>Owner.P7S1_Unit__c</formula>
        <inlineHelpText>Unit des Account Inhabers</inlineHelpText>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_ForecastValue__c.object
<CustomObject>
    <fields>
        <fullName>MT_April__c</fullName>
        <label>April</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_MediaCampaignType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media Campaign Type</label>
        <referenceTo>MT_MediaCampaignType__c</referenceTo>
        <relationshipLabel>Media Forecast Values</relationshipLabel>
        <relationshipName>Media_Forecast_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Media Forecast Value</label>
    <nameField>
        <displayFormat>MFV-{000000}</displayFormat>
        <label>Forecast Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Forecast Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>MT_BmvTv__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Working value for the BMV (TV). Copied from the Opp Approval until approval is done, afterwards source of truth.</description>
        <label>BMV gesamt (TV)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_HasMediaTV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVStart__c</fullName>
        <label>Start Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <formula>MT_MediaCampaignType_ref__r.Name</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaignType__c.object
<CustomObject>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <label>Asset</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Media Campaign Types</relationshipLabel>
        <relationshipName>Media_Campaign_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign Type</label>
    <nameField>
        <label>Media Campaign Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaign Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlightMotiveAllocation__c.object
<CustomObject>
    <fields>
        <fullName>MT_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main</fullName>
                    <default>true</default>
                    <label>Main</label>
                </value>
                <value>
                    <fullName>Reminder</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Flight Motive Allocation</label>
    <nameField>
        <displayFormat>MFMA-{00000}</displayFormat>
        <label>Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Flight Motive Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaMotive__c.object
<CustomObject>
    <fields>
        <fullName>MT_AgencyProductNumber__c</fullName>
        <label>Agency Product Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Main</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminder</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Media Motive</label>
    <nameField>
        <label>Media Motive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Motives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>P7S1_HasMediaTV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TV</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>SomDig_Default</businessProcess>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_Asset__c.object
<CustomObject>
    <description>Wird benutzt, um die Marken (Assets) der Units zu pflegen.</description>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Die Unit, zu dem das Asset gehört.</description>
        <label>Unit</label>
        <referenceTo>P7S1_Unit__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>MT_Asset_ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interner Partner (Asset)</label>
        <referenceTo>P7S1_Asset__c</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>MT_OpportunityApprovals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVEnd__c</fullName>
        <label>Ende Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MT_RunTimeTVStart__c</fullName>
        <label>Start Laufzeit (TV)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P7S1_BmvTvCustomerIntegration__c</fullName>
        <description>Brutto Media Volumen des Kunden TV Werbeanteils</description>
        <inlineHelpText>Brutto Media Volumen des Kunden TV Werbeanteils</inlineHelpText>
        <label>BMV TV Kundenintegration</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>P7S1_BmvTv__c</fullName>
        <inlineHelpText>Brutto Media Volumen TV Gesamt</inlineHelpText>
        <label>BMV gesamt (TV)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>P7S1_HasMediaTV__c</fullName>
        <formula>P7S1_Opportunity__r.P7S1_HasMediaTV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_Mn3TvCustomerIntegration__c</fullName>
        <inlineHelpText>Media Netto 3 des Kunden TV Werbeanteils</inlineHelpText>
        <label>MN3 TV Kundenintegration</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>P7S1_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>Opportunity_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_TvSpotLengthCustomer__c</fullName>
        <inlineHelpText>Länge des Kundenanteils des TV Spots in Sekunden</inlineHelpText>
        <label>Kundenanteil Spotlänge (in Sekunden)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P7S1_TvSpotLength__c</fullName>
        <inlineHelpText>Länge des Gesamt TV Spots in Sekunden</inlineHelpText>
        <label>Gesamtspotlänge (in Sekunden)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_Test.cls
/**
 * Test utility for Media Transparency to
 * handle basic test stuff like creating
 * test data.
 *
 */
@isTest
public class MT_Test {
  @IsTest
  private static void selfTest() {
    Test.startTest();
    Init();
    Test.stopTest();

    // just validate that all DB operation went fine without any exception
  }

  public static void Init() {
    List<P7S1_OpportunityApproval__c> oppApps = initMediaCampaignPreparationTestData();

    P7S1_OpportunityApproval__c oppApp = oppApps.get(0);

    MT_MediaCampaignType__c mct = [SELECT Id
                                     FROM MT_MediaCampaignType__c
                                    WHERE MT_Type__c = :MT_Constants.getInstance().MediaCampaignType_External
                                      AND MT_IsActive__c = true
                                      AND MT_Asset_ref__c = :oppApp.MT_Asset_ref__c
                                    LIMIT 1];

    MT_MediaCampaign__c mc = MT_MediaCampaigns.create(oppApp.P7S1_Opportunity__r, oppApp, mct);
    mc.RecordTypeId = MT_MediaCampaigns.getRecordTypeIdForExternalCampaign();
    mc.MT_RunTimeTVStart__c = oppApp.MT_RunTimeTVStart__c;
    mc.MT_RunTimeTVEnd__c = oppApp.MT_RunTimeTVEnd__c;
    mc.MT_BmvTv__c = oppApp.P7S1_BmvTv__c; // WE NEED TO DEFINE THAT SPECIFICALLY AND MANUALLY IN TEST. Usually this value is prepopulated in standard UI. The trigger only handles null values but not zero values. For purpose of this test, it must be assigned manually
    mc.MT_HasMediaTV__c = true;
    insert mc;

    MT_ProSaOrder__c pso = MT_ProSaOrders.create(mc, '123334');
    insert pso;

    MT_ForecastVersion__c fver = MT_MediaForecastVersions.create('Test Version');
    insert fver;

    MT_ForecastValue__c fv = MT_MediaForecastValues.create(mct, fver);
    fv.MT_April__c = 1000;
    insert fv;

    MT_MediaFlight__c mf = MT_MediaFlights.create(
      Date.today().addMonths(-5),
      Date.today().addMonths(7),
    [SELECT Id FROM MT_MediaCampaignMonthlyPlan__c LIMIT 1]
    );
    insert mf;

    MT_AdvertisedMediaProduct__c amp = MT_AdvertisedMediaProducts.create(oppApp.P7S1_Opportunity__r.Account, 'Test Product', '12345');
    insert amp;

    MT_MediaMotive__c mm = MT_MediaMotives.create(amp, 'Test Motive');
    mm.MT_AgencyProductNumber__c = '12345';
    insert mm;

    MT_MediaFlightMotiveAllocation__c mfma = MT_MediaFlightMotiveAllocations.create(
      mf,
      mm,
      amp);
    insert mfma;

  }

  /**
   * Prepares all test data structures that are required to create Media Campaigns.
   *
   * @return created and inserted test data with references filled
   */
  public static List<P7S1_OpportunityApproval__c> initMediaCampaignPreparationTestData() {
    List<P7S1_OpportunityApproval__c> oppApprovals = initOpportunityApprovalTestData();

    MT_MediaCampaignType__c mct = MT_MediaCampaignTypes.create('Test', true, oppApprovals.get(0).MT_Asset_ref__r);
    mct.MT_Type__c = MT_Constants.getInstance().MediaCampaignType_External;
    insert mct;

    return oppApprovals;
  }

  /**
   * Initializes all the required test data structure for campaign imports.
   *
   * @return created campaign import data with all references filled
   */
  public static List<MT_CampaignImportData__c> initCampaignImportTestData() {
    List<P7S1_OpportunityApproval__c> oppApprovals = initMediaCampaignPreparationTestData();

    List<MT_CampaignImportData__c> testData = createCampaignImportTestData(oppApprovals);
    insert testData;
    return testData;
  }

  /**
   * Creates campaign import records referencing the provided opportunity
   * approvals <code>oppApprovals</code>. The records are not inserted into
   * the database.
   *
   * @param oppApprovals list of opportunity approvals
   * @return list of created but not inserted campaign import data
   */
  public static List<MT_CampaignImportData__c> createCampaignImportTestData(List<P7S1_OpportunityApproval__c> oppApprovals) {
    List<MT_CampaignImportData__c> testData = new List<MT_CampaignImportData__c>();

    // FIXME increase to 30 once 1:n relationship between oppty approval and campaign is established with MT-413
    final Integer importDataCount = 2; // = 30;
    for (Integer i = 0; i < importDataCount; i++) {
      Integer oppAppIndex = Math.mod(i, oppApprovals.size());
      MT_CampaignImportData__c rec = MT_CampaignImportData.create(i, oppApprovals.get(oppAppIndex).P7S1_Opportunity__c);
      rec.MT_CampaignName__c = 'KRS test import campaign #' + i;
      testData.add(rec);
    }

    return testData;
  }

  /**
   * Initializes all the required test data structure down to Opportunity Approvals.
   *
   * @return created and inserted test data with references filled
   */
  public static List<P7S1_OpportunityApproval__c> initOpportunityApprovalTestData() {
    Account acc = new Account(
      Name = 'Test'
    );
    insert acc;

    List<Schema.PicklistEntry> oppStagePicklistEntries = Opportunity.StageName.getDescribe().getPicklistValues();

    Opportunity opp = new Opportunity(
      Name = 'TestOpp1',
      AccountId = acc.Id,
      Account = acc,
      StageName = oppStagePicklistEntries.get(0).getValue(),
      CloseDate = Date.today().addMonths(15),
      P7S1_HasMediaTV__c = true
    );
    Opportunity opp2 = new Opportunity(
      Name = 'TestOpp2',
      AccountId = acc.Id,
      Account = acc,
      StageName = oppStagePicklistEntries.get(0).getValue(),
      CloseDate = Date.today().addMonths(15),
      P7S1_HasMediaTV__c = true
    );

    insert new List<Opportunity> { opp, opp2 };

    P7S1_Unit__c un = MT_Units.create('D&A', 'Test Unit');
    insert un;

    P7S1_Asset__c ass = MT_Assets.create(un, 'New Asset');
    insert ass;

    P7S1_OpportunityApproval__c oppApp = new P7S1_OpportunityApproval__c(
      P7S1_Opportunity__c = opp.Id,
      P7S1_Opportunity__r = opp,
      Name = 'TestOppApp',
      P7S1_BmvTv__c = 100000,
      P7S1_BmvTvCustomerIntegration__c = 30,
      P7S1_Mn3TvCustomerIntegration__c = 20,
      P7S1_TvSpotLengthCustomer__c = 10,
      P7S1_TvSpotLength__c = 30,
      MT_RunTimeTVEnd__c = Date.today().addMonths(2),
      MT_RunTimeTVStart__c = Date.today().addMonths(-2),
      P7S1_internerPartner__c = ass.Name,
      MT_Asset_ref__c = ass.Id,
      MT_Asset_ref__r = ass
    );
    P7S1_OpportunityApproval__c oppApp2 = new P7S1_OpportunityApproval__c(
      P7S1_Opportunity__c = opp2.Id,
      P7S1_Opportunity__r = opp2,
      Name = 'TestOppApp2',
      P7S1_BmvTv__c = 100000,
      P7S1_BmvTvCustomerIntegration__c = 30,
      P7S1_Mn3TvCustomerIntegration__c = 20,
      P7S1_TvSpotLengthCustomer__c = 10,
      P7S1_TvSpotLength__c = 30,
      MT_RunTimeTVEnd__c = Date.today().addMonths(2),
      MT_RunTimeTVStart__c = Date.today().addMonths(-2),
      P7S1_internerPartner__c = ass.Name,
      MT_Asset_ref__c = ass.Id,
      MT_Asset_ref__r = ass
    );

    List<P7S1_OpportunityApproval__c> oppApps = new List<P7S1_OpportunityApproval__c> { oppApp, oppApp2 };
    insert oppApps;
    return oppApps;
  }
}