src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ProRex_Rolle__c</fullName>
        <description>ehemals ProRex Rolle</description>
        <inlineHelpText>Dieses Feld bildet die historischen Rollen aus dem Altsystem ProRex ab.</inlineHelpText>
        <label>Rolle</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kunde</fullName>
                </value>
                <value>
                    <fullName>Konzern</fullName>
                </value>
                <value>
                    <fullName>Agentur</fullName>
                </value>
                <value>
                    <fullName>Agenturverbund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomTv_HilfsfeldProRexRolle__c</fullName>
        <description>wird per Trigger befüllt. Dient zur Aufnahme der ProRex Rollenwerte. Filter in AnsprechpartnerZustaendigkeit__r.Agentur__c und AnsprechpartnerZustaendigkeit__r.Kunde__c referenzieren auf dieses Hilfsfeld (Begründung: LookUp Filter können nicht auf MultiPicklist referenzieren)</description>
        <inlineHelpText>wird per Trigger befüllt. Dient zur Aufnahme der ProRex Rollenwerte. Filter in AnsprechpartnerZustaendigkeit__r.Agentur__c und AnsprechpartnerZustaendigkeit__r.Kunde__c referenzieren auf dieses Hilfsfeld</inlineHelpText>
        <label>HilfsfeldProRexRolle</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SomTv_AdfactoryAnteilAbsolut__c</fullName>
        <label>Adfactory Anteil (absolut)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_MutterOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mutter Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.SomTv_Jahr__c</field>
                <operation>equals</operation>
                <valueField>Opportunity.SomTv_Jahr__c</valueField>
            </filterItems>
            <infoMessage>Es werden nur Opportunities aus dem selben Jahr angezeigt.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Tochter Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>SomTv_AdFactory</fullName>
        <active>true</active>
        <businessProcess>SomTv_Default</businessProcess>
        <description>Opportunities für AdFactory mit Produkten</description>
        <label>AdFactory</label>
    </recordTypes>
    <recordTypes>
        <fullName>SomTv_Paket</fullName>
        <active>true</active>
        <businessProcess>SomTv_Default</businessProcess>
        <label>Paket (TV)</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SomTv_Opportunity_ValidateData_Test.cls
/**
 * Test class for SomTv_Opportunity_ValidateData.
 */
@IsTest
private class SomTv_Opportunity_ValidateData_Test {

  @isTest
    public static void testSomTv_Opportunity_ValidateData_Test() {
        
        
        Id childRecordTypeId = null;
        Id parentRecordTypeId = null;
        
        for (RecordType r : [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'Opportunity' AND (DeveloperName = 'SomTv_AdFactory' OR DeveloperName = 'SomTv_Paket')]) {
            if ('SomTv_AdFactory'.equals(r.DeveloperName)) {
                childRecordTypeId = r.Id;
            } else if ('SomTv_Paket'.equals(r.DeveloperName)) {
                parentRecordTypeId = r.Id;
            }
        }
        System.assert(childRecordTypeId!=null, 'No RecordType \'SomTv_AdFactory\' for Opportunity found!');
        System.assert(parentRecordTypeId!=null, 'No RecordType \'SomTv_Paket\' for Opportunity found!');
        
        Account acc = new Account(Name='Test Account', ProRex_Rolle__c='Kunde', SomTv_HilfsfeldProRexRolle__c='Kunde');
        insert acc;
        
        //Opportunity childopp = new Opportunity(Name='Test Child Opportunity', AccountId=acc.Id, RecordTypeId=childRecordTypeId, StageName='Angebot abgegeben', CloseDate=System.today(), Amount = 1000);
        //insert childopp;
        Opportunity childopp = cls_P7S1_Temp_TestData.createTestOpportunity(false, acc, new RecordType(Id=childRecordTypeId));
        childopp.Name = 'Test Child Opportunity';
        childopp.StageName = 'Angebot abgegeben';
        insert childopp;

Test.startTest();
        //childopp = [SELECT Id, Amount FROM Opportunity WHERE Id = :childopp.Id];

        //Opportunity parentopp = new Opportunity(Name='Test Parent Opportunity', AccountId=acc.Id, RecordTypeId=parentRecordTypeId, StageName='Angebot abgegeben', CloseDate=System.today(), Amount = 1000);
        Opportunity parentopp = cls_P7S1_Temp_TestData.createTestOpportunity(false, acc, new RecordType(Id=parentRecordTypeId));
        parentopp.Name = 'Test Parent Opportunity';
        parentopp.StageName = 'Angebot abgegeben';
        insert parentopp;
        
        parentopp = [SELECT Id, SomTv_AdfactoryAnteilAbsolut__c FROM Opportunity WHERE Id = :parentopp.Id];
        System.assertEquals(null, parentopp.SomTv_AdfactoryAnteilAbsolut__c);
        
        childopp.SomTv_MutterOpportunity__c = parentopp.Id;
        update childopp;
        
        childopp = [SELECT Id, Amount FROM Opportunity WHERE Id = :childopp.Id];

        parentopp = [SELECT Id, SomTv_AdfactoryAnteilAbsolut__c FROM Opportunity WHERE Id = :parentopp.Id];
        System.assertEquals(childopp.Amount, parentopp.SomTv_AdfactoryAnteilAbsolut__c);

        delete childopp;
        
        parentopp = [SELECT Id, SomTv_AdfactoryAnteilAbsolut__c FROM Opportunity WHERE Id = :parentopp.Id];
        System.assertEquals(0.0, parentopp.SomTv_AdfactoryAnteilAbsolut__c);
        
        undelete childopp;
        
        childopp = [SELECT Id, Amount FROM Opportunity WHERE Id = :childopp.Id];

        parentopp = [SELECT Id, SomTv_AdfactoryAnteilAbsolut__c FROM Opportunity WHERE Id = :parentopp.Id];
        System.assertEquals(childopp.Amount, parentopp.SomTv_AdfactoryAnteilAbsolut__c);
        
        childopp.StageName = 'Geschlossene und gewonnene';
        update childopp;
        
        Test.stopTest();
    }
}