src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <description>Zuordnung zur jeweiligen Sphere</description>
        <formula>Text ( Owner.P7S1_Sphere__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Zuordnung zur jeweiligen Sphere</inlineHelpText>
        <label>P7S1_Sphere</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>P7S1_Emp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mitarbeiter im P7S1-Konzern</description>
        <inlineHelpText>Mitarbeiter im P7S1-Konzern</inlineHelpText>
        <label>Mitarbeiter</label>
        <referenceTo>P7S1_Emp__c</referenceTo>
        <relationshipLabel>Kontakte</relationshipLabel>
        <relationshipName>Kontakte</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <formula>Text( Owner.P7S1_Sphere__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>P7S1_Sphere</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_Comp__c.object
<CustomObject>
    <description>Firmen des P7S1-Konzerns
diesen Firmen werden Mitarbeiter zugeordnet.
inklusive externen Partnern/Lieferanten, die Mitarbeiter/User bereit stellen</description>
    <label>P7S1 Firma</label>
    <nameField>
        <label>Firmenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P7S1 Firmen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_Emp__c.object
<CustomObject>
    <description>Mitarbeiter des P7S1-Konzerns.
meistens auch User mit Lizenz in Salesforce
enthalten auch externe Mitarbeiter</description>
    <fields>
        <fullName>P7S1_CompName__c</fullName>
        <formula>P7S1_Comp__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Firmenname</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Comp__c</fullName>
        <label>Firma</label>
        <referenceTo>P7S1_Comp__c</referenceTo>
        <relationshipLabel>Mitarbeiter</relationshipLabel>
        <relationshipName>Mitarbeiter</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>P7S1_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kontakt</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mitarbeiter</relationshipLabel>
        <relationshipName>Mitarbeiter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Email__c</fullName>
        <label>E-Mail</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Firstname__c</fullName>
        <label>Vorname</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Lastname__c</fullName>
        <label>Nachname</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Profile__c</fullName>
        <label>Profil</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>DA_Default</fullName>
                </value>
                <value>
                    <fullName>MA_Default</fullName>
                </value>
                <value>
                    <fullName>Max_Default</fullName>
                </value>
                <value>
                    <fullName>P7S1_Applications</fullName>
                </value>
                <value>
                    <fullName>P7S1_Interface</fullName>
                </value>
                <value>
                    <fullName>P7S1_NoRights</fullName>
                </value>
                <value>
                    <fullName>PSD_Default</fullName>
                </value>
                <value>
                    <fullName>SE_Default</fullName>
                </value>
                <value>
                    <fullName>SE_ReadOnly</fullName>
                </value>
                <value>
                    <fullName>Som_Lic_Default</fullName>
                </value>
                <value>
                    <fullName>Som_ReadOnly</fullName>
                </value>
                <value>
                    <fullName>SomDig_AdTech</fullName>
                </value>
                <value>
                    <fullName>SomDig_BI</fullName>
                </value>
                <value>
                    <fullName>SomDig_Billing</fullName>
                </value>
                <value>
                    <fullName>SomDig_PAM</fullName>
                </value>
                <value>
                    <fullName>SomDig_PM</fullName>
                </value>
                <value>
                    <fullName>SomDig_Sales</fullName>
                </value>
                <value>
                    <fullName>SomTv_ADFactory</fullName>
                </value>
                <value>
                    <fullName>SomTv_Conversion</fullName>
                </value>
                <value>
                    <fullName>SomTv_Marketing</fullName>
                </value>
                <value>
                    <fullName>SomTv_RM</fullName>
                </value>
                <value>
                    <fullName>SomTv_Sales</fullName>
                </value>
                <value>
                    <fullName>SomTv_SalesManagement</fullName>
                </value>
                <value>
                    <fullName>SomTv_SalesSteering</fullName>
                </value>
                <value>
                    <fullName>SomTv_TeamCRM</fullName>
                </value>
                <value>
                    <fullName>Sports_Default</fullName>
                </value>
                <value>
                    <fullName>Star_Default</fullName>
                </value>
                <value>
                    <fullName>Systemadministrator</fullName>
                </value>
                <value>
                    <fullName>Ven_Controlling</fullName>
                </value>
                <value>
                    <fullName>Ven_DataManager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Role__c</fullName>
        <label>Rolle</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>P7S1_Unit__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AdF_Admin</fullName>
                </value>
                <value>
                    <fullName>AdF_BrandIntegration</fullName>
                </value>
                <value>
                    <fullName>AdF_Conception</fullName>
                </value>
                <value>
                    <fullName>AdF_ConceptSales</fullName>
                </value>
                <value>
                    <fullName>AdF_Director</fullName>
                </value>
                <value>
                    <fullName>AdF_FinanceSteering</fullName>
                </value>
                <value>
                    <fullName>AdF_GF</fullName>
                </value>
                <value>
                    <fullName>AdF_LicensingSales</fullName>
                </value>
                <value>
                    <fullName>AdF_MediaContentManagement</fullName>
                </value>
                <value>
                    <fullName>AdF_ProjektManagement</fullName>
                </value>
                <value>
                    <fullName>Aer</fullName>
                </value>
                <value>
                    <fullName>App_ExternalUsers</fullName>
                </value>
                <value>
                    <fullName>App_TechnicalUsers</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto_Controlling</fullName>
                </value>
                <value>
                    <fullName>Auto_Sales</fullName>
                </value>
                <value>
                    <fullName>Auto_Steering</fullName>
                </value>
                <value>
                    <fullName>Com_7CommerceInvestments</fullName>
                </value>
                <value>
                    <fullName>Comm</fullName>
                </value>
                <value>
                    <fullName>Comm_Controlling</fullName>
                </value>
                <value>
                    <fullName>Comm_Sales</fullName>
                </value>
                <value>
                    <fullName>Comm_Steering</fullName>
                </value>
                <value>
                    <fullName>COO</fullName>
                </value>
                <value>
                    <fullName>coops</fullName>
                </value>
                <value>
                    <fullName>coops_Controlling</fullName>
                </value>
                <value>
                    <fullName>coops_Sales</fullName>
                </value>
                <value>
                    <fullName>coops_Steering</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>DA</fullName>
                </value>
                <value>
                    <fullName>DA_7Innovate</fullName>
                </value>
                <value>
                    <fullName>SomDe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <label>Sphäre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aer</fullName>
                </value>
                <value>
                    <fullName>Sgn</fullName>
                </value>
                <value>
                    <fullName>SomAt</fullName>
                </value>
                <value>
                    <fullName>SomDe</fullName>
                </value>
                <value>
                    <fullName>Ven</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benutzer (Person)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Mitarbeiter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Username__c</fullName>
        <description>Salesforce-Benutzername. Auch in Sandboxen OHNE Zusatz des Sandboxnamens. Die Synchronisierung hängt am User automatisch den Sandboxnamen an.</description>
        <inlineHelpText>Salesforce-Benutzername. Auch in Sandboxen OHNE Zusatz des Sandboxnamens. Die Synchronisierung hängt am User automatisch den Sandboxnamen an.</inlineHelpText>
        <label>Benutzername</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mitarbeiter</label>
    <nameField>
        <label>Mitarbeiter</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mitarbeiter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>P7S1_Emp__c</fullName>
        <label>Mitarbeiter-Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <description>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</description>
        <inlineHelpText>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</inlineHelpText>
        <label>P7S1_Sphere</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aer</fullName>
                    <color>#666666</color>
                    <label>Aer</label>
                </value>
                <value>
                    <fullName>Sgn</fullName>
                    <color>#BBBBBB</color>
                    <label>Sgn</label>
                </value>
                <value>
                    <fullName>SomAt</fullName>
                    <color>#CC33CC</color>
                    <label>SomAt</label>
                </value>
                <value>
                    <fullName>SomDe</fullName>
                    <color>#FF0000</color>
                    <label>SomDe</label>
                </value>
                <value>
                    <fullName>Ven</fullName>
                    <color>#333399</color>
                    <label>Ven</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/P7S1_Emp_User_Test.cls
@isTest
private class P7S1_Emp_User_Test {

	
	// TODO: Move createTestUser() to cls_P7S1_TestData
	public static User User_TestData;
	
	public static User createTestUser(Boolean p_bInsertObject, String p_sP7S1_Sphere, String p_sProfileName) {
		User_TestData = new User();
		User_TestData.FirstName = 'Harry';
		User_TestData.LastName = 'Hirsch';
		User_TestData.Alias = 'HiHa';
		User_TestData.CompanyName = 'P7S1 Applications GmbH';

		User_TestData.Email = 'harry.hirsch.' + String.valueOf(Math.random()) + '@p7s1applications.de';
		
		String l_sSandbox = cls_P7S1_Utils.getSandboxName(true);
		User_TestData.Username = User_TestData.Email + l_sSandbox;

		User_TestData.ProfileId = cls_P7S1_Utils.getProfileId(p_sProfileName);
		User_TestData.P7S1_Sphere__c = p_sP7S1_Sphere;
		 
		User_TestData.TimeZoneSidKey = 'Europe/Berlin';
		User_TestData.LocaleSidKey = 'de_DE';
		User_TestData.LanguageLocaleKey = 'de';
		User_TestData.EmailEncodingKey = 'UTF-8';
		User_TestData.UserPermissionsMarketingUser = true;
		//UserRoleId

		if (p_bInsertObject) {
			insert User_TestData;
		}
		return User_TestData;
	}
	// TODO
	
    static testMethod void nameIsFormatted() {
        P7S1_Comp__c firma = cls_P7S1_TestData.createTestFirma(true);
        P7S1_Emp__c emp = cls_P7S1_TestData.createTestMitarbeiter(false, firma);
        
        Test.startTest();
        insert emp;
        Test.stopTest();
        
        emp = reloadEmp(emp);
        System.assertEquals(P7S1_Emp_User.getFormattedName(emp), emp.Name);
        
    }	
	
	static testMethod void insertDoesNothing() {
		Account acc = cls_P7S1_TestData.createTestAccount(true);
		P7S1_Comp__c firma = cls_P7S1_TestData.createTestFirma(true, acc);
		Integer l_nCountUser = [SELECT COUNT() FROM User];

		Test.startTest();

		P7S1_Emp__c emp = cls_P7S1_TestData.createTestMitarbeiter(false, firma);
		emp.P7S1_Sync__c = true;
		insert emp;

		System.assertEquals(l_nCountUser, [SELECT COUNT() FROM User]);
		System.assertEquals(1, [SELECT COUNT() FROM P7S1_Emp__c]);

		emp = reloadEmp(emp);
		System.assertEquals(null, emp.P7S1_User__c);

		Test.stopTest();
	}

	static testMethod void updateEmpSyncExistingUser() {
		String l_sUsername = 'superman@p7s1.net';
		//TODO: User l_oUser = cls_P7S1_TestData.createTestUser...
		User l_oUser = createTestUser(false, 'SomDe', 'SomTv_RM');
				
		l_oUser.FirstName = 'Bruce';
		l_oUser.LastName = 'Wayne';
		l_oUser.Email = l_sUsername;
		l_oUser.Username = l_sUsername + cls_P7S1_Utils.getSandboxName(true);

		insert l_oUser;
		Integer l_nCountUser = [SELECT COUNT() FROM User];
	
		Account acc = cls_P7S1_TestData.createTestAccount(true);
		P7S1_Comp__c firma = cls_P7S1_TestData.createTestFirma(true, acc);
		
		P7S1_Emp__c emp = cls_P7S1_TestData.createTestMitarbeiter(false, firma);
		emp.P7S1_Firstname__c = 'Clark';
		emp.P7S1_Lastname__c = 'Kent';
		emp.P7S1_Username__c = l_sUsername;
		
		emp.P7S1_Profile__c = 'SomTv_Sales';
		emp.P7S1_Role__c = 'SomDe';
		emp.P7S1_Sphere__c = 'SomDe';		
		insert emp;

		emp = reloadEmp(emp);
		System.assertEquals(null, emp.P7S1_User__c);
		System.assertEquals(l_nCountUser, [SELECT COUNT() FROM User]);

		// Kein start/stop Test, da dadurch queuebles synchron ausgeführt werden, was zum DML MIXED MODE Fehler führt
		// Test.startTest();

		
		P7S1_Emp_User.i_bIsTest = true;
		emp.P7S1_Sync__c = true;
		update emp;

		//Test.stopTest();

		l_oUser = reloadUser(l_oUser);
		system.debug('### l_oUser.UserName: ' + l_oUser.UserName);
		
		System.assertEquals('Clark', l_oUser.FirstName);
		System.assertEquals('Kent', l_oUser.LastName);
		emp = reloadEmp(emp);
		System.assertEquals(l_oUser.Id, emp.P7S1_User__c);
		System.assertEquals(l_nCountUser, [SELECT COUNT() FROM User]);
	
	}

	/*
	static  void updateEmpWithoutSync() {
		Account acc = cls_P7S1_TestData.createTestAccount(true);
		Contact con = cls_P7S1_TestData.createTestContact(false, acc);
		con.FirstName = 'Bruce';
		con.LastName = 'Wayne';
		con.Email = 'batman@p7s1.net';
		insert con;
		P7S1_Emp__c emp = cls_P7S1_TestData.createTestMitarbeiterWithContact(con);

		emp = reloadEmp(emp);
		System.assertEquals(con.Id, emp.P7S1_Contact__c);
		System.assertEquals(1, [SELECT COUNT() FROM Contact]);

		Test.startTest();

		emp.P7S1_Firstname__c = 'Peter';
		emp.P7S1_Lastname__c = 'Parker';
		emp.P7S1_Username__c = 'spiderman@p7s1.net';
		emp.P7S1_Sync__c = false;
		update emp;

		con = reloadContact(con);
		System.assertEquals('Bruce', con.FirstName);
		System.assertEquals('Wayne', con.LastName);
		System.assertEquals('batman@p7s1.net', con.Email);
		emp = reloadEmp(emp);
		System.assertEquals(con.Id, emp.P7S1_Contact__c);
		System.assertEquals(1, [SELECT COUNT() FROM Contact]);

		Test.stopTest();
	}

	static  void updateEmpWithContact() {
		Account acc = cls_P7S1_TestData.createTestAccount(true);
		Contact con = cls_P7S1_TestData.createTestContact(false, acc);
		con.FirstName = 'Bruce';
		con.LastName = 'Wayne';
		con.Email = 'batman@p7s1.net';
		insert con;
		P7S1_Emp__c emp = cls_P7S1_TestData.createTestMitarbeiterWithContact(con);

		emp = reloadEmp(emp);
		System.assertEquals(con.Id, emp.P7S1_Contact__c);

		List<Contact> cons = loadContacts(emp);
		System.assertEquals(1, cons.size());

		Test.startTest();

		emp.P7S1_Firstname__c = 'Peter';
		emp.P7S1_Lastname__c = 'Parker';
		emp.P7S1_Username__c = 'spiderman@p7s1.net';
		emp.P7S1_Sync__c = true;
		update emp;

		cons = loadContacts(emp);
		System.assertEquals(2, cons.size());

		cons.sort();

		System.assertEquals('Bruce', cons[0].FirstName);
		System.assertEquals('Wayne', cons[0].LastName);
		System.assertEquals('batman@p7s1.net', cons[0].Email);
		System.assertEquals('Peter', cons[1].FirstName);
		System.assertEquals('Parker', cons[1].LastName);
		System.assertEquals('spiderman@p7s1.net', cons[1].Email);

		emp = reloadEmp(emp);
		System.assertEquals(cons[1].Id, emp.P7S1_Contact__c);

		Test.stopTest();
	}

	static  void updateEmpWithouContact() {
		Account acc = cls_P7S1_TestData.createTestAccount(true);
		P7S1_Comp__c firma = cls_P7S1_TestData.createTestFirma(true, acc);
		P7S1_Emp__c emp = cls_P7S1_TestData.createTestMitarbeiter(true, firma);

		emp = reloadEmp(emp);
		System.assertEquals(null, emp.P7S1_Contact__c);

		System.assertEquals(0, [SELECT COUNT() FROM Contact]);

		Test.startTest();

		emp.P7S1_Firstname__c = 'Clark';
		emp.P7S1_Lastname__c = 'Kent';
		emp.P7S1_Username__c = 'superman@p7s1.net';
		emp.P7S1_Sync__c = true;
		update emp;

		List<Contact> cons = loadContacts(emp);
		System.assertEquals(1, cons.size());
		System.assertEquals('Clark', cons[0].FirstName);
		System.assertEquals('Kent', cons[0].LastName);
		System.assertEquals('superman@p7s1.net', cons[0].Email);

		emp = reloadEmp(emp);
		System.assertEquals(cons[0].Id, emp.P7S1_Contact__c);

		Test.stopTest();
	}

	private static List<Contact> loadContacts(P7S1_Emp__c emp) {
		return [SELECT Email, FirstName, LastName, P7S1_Emp__c FROM Contact WHERE P7S1_Emp__c = :emp.Id];
	}
*/
	
	
	private static P7S1_Emp__c reloadEmp(P7S1_Emp__c p_oEmp) {
		return [SELECT Name, P7S1_Username__c, P7S1_Email__c, P7S1_Firstname__c, P7S1_Lastname__c, P7S1_User__c, P7S1_CompName__c FROM P7S1_Emp__c WHERE Id = :p_oEmp.Id];
	}

	private static User reloadUser(User p_oUser) {
		return [SELECT UserName, Email, FirstName, LastName, CompanyName FROM User WHERE Id = :p_oUser.Id];
	}

}