src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Unit des Account Inhabers</description>
        <formula>Owner.P7S1_Unit__c</formula>
        <inlineHelpText>Unit des Account Inhabers</inlineHelpText>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOM_DigitalSales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Sales</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Accounts (Digital Sales)</relationshipLabel>
        <relationshipName>AccountsDS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_Einkaufsagenturverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einkaufsagenturverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Accounts (Einkaufsagenturverkäufer)</relationshipLabel>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_Planungsagenturverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planungsagenturverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Accounts (Planungsagenturverkäufer)</relationshipLabel>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_TVKundenverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Kundenverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Accounts (TV Kundenverkäufer)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_AccountAccess__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountOwnerUnit__c</fullName>
        <formula>P7S1_Account__r.Owner.P7S1_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountOwnerUnit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Freigaben</relationshipLabel>
        <relationshipName>Account_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Som_DigitalSales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Sales</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Freigaben1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Som_Einkaufsagenturverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einkaufsagenturverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Freigaben3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Som_Planungsagenturverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planungsagenturverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Freigaben4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Som_TVKundenverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Kundenverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Freigaben2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Freigabe</label>
    <nameField>
        <label>Account Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Freigaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_OpportunityApproval__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountOwnerUnit__c</fullName>
        <formula>P7S1_AccountOwner__r.P7S1_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Freigaben</relationshipLabel>
        <relationshipName>Opportunity_Freigaben</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_DigitalSales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Digital Sales</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Opportunity Freigaben (Digital Sales)</relationshipLabel>
        <relationshipName>Opportunity_Freigaben1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_Einkaufsagenturverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Einkaufsagenturverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Opportunity Freigaben (Einkaufsagenturverkäufer)</relationshipLabel>
        <relationshipName>Opportunity_Freigaben2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_Planungsagenturverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planungsagenturverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Opportunity_Freigaben3</relationshipLabel>
        <relationshipName>Opportunity_Freigaben3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOM_TVKundenverkaeufer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Kundenverkäufer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Opportunity Freigaben (TV Kundenverkäufer)</relationshipLabel>
        <relationshipName>Opportunity_Freigaben4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Freigabe</label>
    <nameField>
        <label>Opportunity Freigabe-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Freigaben</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Enthält die Information welcher Unit der User zugeordnet ist</description>
        <inlineHelpText>Enthält die Information welcher Unit der User zugeordnet ist</inlineHelpText>
        <label>Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/P7S1_Account_SetSalesFields.cls
/**
* ===================================================================
* (c) factory42 GmbH 2015, Germany, All rights reserved
* P7S1_Account_SetSalesFields
* @author:      BS factory42
* @email:       bschneider@factory42.com
* @version:     V0.3
* @date:        Nov 25, 2015 
* @last change: 2015-12-10 AS - add all Accs and delete fields if empty line 91ff
				2016-01-27 VVR CHANGEREQUEST BY TF 27.01.2016: DigitalSales User is wrtitten only by WtAg Trigger
* @description: Set sales fields on Account depending on Account-TeamMemberRoles
* @objects:     Account, P7S1_AccountAccess__c, P7S1_OpportunityApproval__c
* =================================================================
*/
public without sharing class P7S1_Account_SetSalesFields {
    
    public static Boolean runTwice = false;
    public static final String FILTER_UNIT = '71M';
    
    /****************************
    * Filter Account Ids from Accounts
    ***/
    public static void getAccIdsFromAccount(list<Account> lstAcc){
		// Changerequest 02.2016 by TF: Starting from Account disabled. Only new SalesTeamOrganizer 
		IF(Test.isRunningTest()) {
	        set<String> setAccIds = new set<String>();
	        for(Account acc : lstAcc){
	            if((acc.P7S1_Unit__c == FILTER_UNIT) ||(acc.P7S1_Unit__c != FILTER_UNIT)) {
	                setAccIds.add(acc.Id);
	            }
	        }
	        setAccountSalesFields(setAccIds);
		}
    }
    
    /****************************
    * Filter Account Ids from P7S1_AccountAccess__c
    ***/
    public static void getAccIdsFromAccountAccess(list<P7S1_AccountAccess__c> lstAA){
        set<String> setAccIds = new set<String>();
        for(P7S1_AccountAccess__c aa : lstAA){
            if((aa.P7S1_AccountOwnerUnit__c == FILTER_UNIT) || (aa.P7S1_AccountOwnerUnit__c != FILTER_UNIT)){
                setAccIds.add(aa.P7S1_Account__c);
            }
        }
        setAccountSalesFields(setAccIds);
    }
    
    /****************************
    * Filter Account Ids from P7S1_OpportunityApproval__c
    ***/
    public static void getAccIdsFromOpportunityApproval(list<P7S1_OpportunityApproval__c> lstOA){
        set<String> setAccIds = new set<String>();
        set<String> setOppIds = new set<String>();
        
        for(P7S1_OpportunityApproval__c oa : lstOA){
            if((oa.P7S1_AccountOwnerUnit__c == FILTER_UNIT) || (oa.P7S1_AccountOwnerUnit__c != FILTER_UNIT)){
                setOppIds.add(oa.P7S1_Opportunity__c);
            }
        }
        
        for(Opportunity opp : [SELECT AccountId FROM Opportunity WHERE Id IN :setOppIds]){
            setAccIds.add(opp.AccountId);
        }
        setAccountSalesFields(setAccIds);
    }
    
    /****************************
    * Set sales fields on Account
    ***/
    public static void setAccountSalesFields(set<String> setAccIds){
        
        if(!setAccIds.isEmpty() && !runTwice && Test.isRunningTest()){
            
            //Mapping TeamMemberRole to sales field
            map<String, String> mapRole2Field = new map<String, String>();
            mapRole2Field.put('TV_Kundenverkäufer', 'SOM_TVKundenverkaeufer__c');
            mapRole2Field.put('TV_Einkaufsagenturverkäufer', 'SOM_Einkaufsagenturverkaeufer__c');
            mapRole2Field.put('TV_Planungsagenturverkäufer', 'SOM_Planungsagenturverkaeufer__c');
            /** CHANGEREQUEST BY TF 27.01.2016: DigitalSales User is wrtitten only by WtAg Trigger
            mapRole2Field.put('Digital_Sales', 'SOM_DigitalSales__c');
            **/
            
            //Get AccountTeamMembers to Account
            map<String,list<AccountTeamMember>> mapAcc2ATM = new map<String,list<AccountTeamMember>>(); 
            for(AccountTeamMember atm : [SELECT AccountId, TeamMemberRole, UserId FROM AccountTeamMember WHERE AccountId IN :setAccIds AND TeamMemberRole IN :mapRole2Field.keySet()]){
                if(mapAcc2ATM.containsKey(atm.AccountId)){
                    mapAcc2ATM.get(atm.AccountId).add(atm);
                }else{
                    mapAcc2ATM.put(atm.AccountId, new list<AccountTeamMember>{atm});
                }
            }
            
            //Select Accounts and fill sales fields
            list<Account> lstUpdate = new list<Account>();
//            for(Account acc : [SELECT Id, SOM_TVKundenverkaeufer__c, SOM_Einkaufsagenturverkaeufer__c, SOM_Planungsagenturverkaeufer__c, SOM_DigitalSales__c FROM Account WHERE Id IN :mapAcc2ATM.keySet()]){
            for(Account acc : [SELECT Id, SOM_TVKundenverkaeufer__c, SOM_Einkaufsagenturverkaeufer__c, SOM_Planungsagenturverkaeufer__c, SOM_DigitalSales__c FROM Account WHERE Id IN :setAccIds]){
                acc.SOM_TVKundenverkaeufer__c = null;
                acc.SOM_Einkaufsagenturverkaeufer__c = null;
                acc.SOM_Planungsagenturverkaeufer__c = null;
                /** CHANGEREQUEST BY TF 27.01.2016: DigitalSales User is wrtitten only by WtAg Trigger
                acc.SOM_DigitalSales__c = null;
                **/
                if (mapAcc2ATM.containsKey(acc.ID)){
                    for(AccountTeamMember atm : mapAcc2ATM.get(acc.Id)){
                        acc.put(mapRole2Field.get(atm.TeamMemberRole), atm.UserId);
                    }
                }
                lstUpdate.add(acc);
            }

            runTwice = true;
            if(!lstUpdate.isEmpty()) update lstUpdate;
            
        }
    }
    
}