src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <description>Zuordnung zur jeweiligen Sphere</description>
        <formula>Text ( Owner.P7S1_Sphere__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Zuordnung zur jeweiligen Sphere</inlineHelpText>
        <label>P7S1_Sphere</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>P7S1_Emp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Mitarbeiter im P7S1-Konzern</description>
        <inlineHelpText>Mitarbeiter im P7S1-Konzern</inlineHelpText>
        <label>Mitarbeiter</label>
        <referenceTo>P7S1_Emp__c</referenceTo>
        <relationshipLabel>Kontakte</relationshipLabel>
        <relationshipName>Kontakte</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <formula>Text( Owner.P7S1_Sphere__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>P7S1_Sphere</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_Emp__c.object
<CustomObject>
    <description>Mitarbeiter des P7S1-Konzerns.
meistens auch User mit Lizenz in Salesforce
enthalten auch externe Mitarbeiter</description>
    <fields>
        <fullName>P7S1_AccountId__c</fullName>
        <formula>P7S1_Comp__r.P7S1_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Kontakt</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mitarbeiter</relationshipLabel>
        <relationshipName>Mitarbeiter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Email__c</fullName>
        <label>E-Mail</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Firstname__c</fullName>
        <label>Vorname</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Lastname__c</fullName>
        <label>Nachname</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <label>Sphäre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Aer</fullName>
                </value>
                <value>
                    <fullName>Sgn</fullName>
                </value>
                <value>
                    <fullName>SomAt</fullName>
                </value>
                <value>
                    <fullName>SomDe</fullName>
                </value>
                <value>
                    <fullName>Ven</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_Username__c</fullName>
        <description>Salesforce-Benutzername. Auch in Sandboxen OHNE Zusatz des Sandboxnamens. Die Synchronisierung hängt am User automatisch den Sandboxnamen an.</description>
        <inlineHelpText>Salesforce-Benutzername. Auch in Sandboxen OHNE Zusatz des Sandboxnamens. Die Synchronisierung hängt am User automatisch den Sandboxnamen an.</inlineHelpText>
        <label>Benutzername</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mitarbeiter</label>
    <nameField>
        <label>Mitarbeiter</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mitarbeiter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>P7S1_Emp__c</fullName>
        <label>Mitarbeiter-Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <description>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</description>
        <inlineHelpText>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</inlineHelpText>
        <label>P7S1_Sphere</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aer</fullName>
                    <color>#666666</color>
                    <label>Aer</label>
                </value>
                <value>
                    <fullName>Sgn</fullName>
                    <color>#BBBBBB</color>
                    <label>Sgn</label>
                </value>
                <value>
                    <fullName>SomAt</fullName>
                    <color>#CC33CC</color>
                    <label>SomAt</label>
                </value>
                <value>
                    <fullName>SomDe</fullName>
                    <color>#FF0000</color>
                    <label>SomDe</label>
                </value>
                <value>
                    <fullName>Ven</fullName>
                    <color>#333399</color>
                    <label>Ven</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/P7S1_Emp_Contact.cls
public with sharing class P7S1_Emp_Contact {

    /*
     * Sync contacts based on Mitarbeiter/Emp object
     */
    public static void sync(Map<Id, P7S1_Emp__c> newEmpMap, Map<Id, P7S1_Emp__c> oldEmpMap) {

        Map<Id, P7S1_Emp__c> empMap = new Map<Id, P7S1_Emp__c>();
        Set<String> emailAddresses = new Set<String>();

		// convert Username and Email to LowerCase (same behavior as on User-Object)
		for (P7S1_Emp__c emp : newEmpMap.values()) {
			if (emp.P7S1_Username__c != null) {
				emp.P7S1_Username__c = emp.P7S1_Username__c.toLowerCase();
				emp.P7S1_Email__c = emp.P7S1_Email__c.toLowerCase();
			}
		}

        // Only proceed if 'Sync' checkbox on emp is true and emp has a username
        for (P7S1_Emp__c emp : newEmpMap.values()) {
            if (emp.P7S1_Sync__c && emp.P7S1_Username__c != null) {
                empMap.put(emp.Id, emp);
                emailAddresses.add(emp.P7S1_Username__c);
            }
        }

        if (!empMap.isEmpty()) {
            // Initialize lists which will be used later to insert/update contacts
            List<Contact> contactsToInsert = new List<Contact>();
            List<Contact> contactsToUpdate = new List<Contact>();

            // Build a map of email addresses and corresponding contacts
            Map<String, List<Contact>> emailAddressesContactsMap = new Map<String, List<Contact>>();
            for (P7S1_Emp__c emp : empMap.values()) {
                emailAddressesContactsMap.put(emp.P7S1_Username__c, new List<Contact>());
            }
            for (Contact con : [SELECT Email FROM Contact WHERE P7S1_Sphere__c = 'SomDe' AND Email IN :emailAddresses]) {
                emailAddressesContactsMap.get(con.Email).add(con);
            }

            // Iterate all emps and get the list of contacts with the emp's email address
            for (Id empId : empMap.keySet()) {
                P7S1_Emp__c emp = empMap.get(empId);
                List<Contact> contactsForEmp = emailAddressesContactsMap.get(emp.P7S1_Username__c);

                // If there is no contact with the emp's email address, create a new one with the P7S1_Emp__c lookup and core data fields
                // Only works if P7S1_AccountId__c is set on emp (mandatory for Contact -> Account assignment)
                if (contactsForEmp.isEmpty()) {

                    /* TODO: wieder einkommentieren wenn Contact-Sync aktiviert werden soll:
                    if (emp.P7S1_Lastname__c != null && emp.P7S1_AccountId__c != null) {
                        Contact con = new Contact(
                            P7S1_Emp__c = empId,
                            Email = emp.P7S1_Username__c,
                            FirstName = emp.P7S1_Firstname__c,
                            LastName = emp.P7S1_Lastname__c,
                            AccountId = emp.P7S1_AccountId__c,
                            LeadSource = 'Other'
                        );
                        contactsToInsert.add(con);
                    }
                    */

                // If there are contacts with the emp's email address: set P7S1_Emp__c lookup and transfer core data fields
                } else {
                    for (Contact con : contactsForEmp) {
                        con.P7S1_Emp__c = empId;

                        /* TODO: wieder einkommentieren wenn Contact-Sync aktiviert werden soll:
                        con.Email = emp.P7S1_Username__c;
                        con.FirstName = emp.P7S1_Firstname__c;
                        con.LastName = emp.P7S1_Lastname__c;
                        */

                        contactsToUpdate.add(con);
                    }
                }
            }

            // Insert/update contacts where applicable

            /* TODO: wieder einkommentieren wenn Contact-Sync aktiviert werden soll:
            if (!contactsToInsert.isEmpty()) insert contactsToInsert;
            */

            if (!contactsToUpdate.isEmpty()) update contactsToUpdate;

            // Set P7S1_Contact__c on all emp datasets
            // No need to call update again as this happens in a before context
            contactsToInsert.addAll(contactsToUpdate);
            for (Contact con : contactsToInsert) {
                newEmpMap.get(con.P7S1_Emp__c).P7S1_Contact__c = con.Id;
            }
        }
    }

}