src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SomTv_ForecastK1DokuMN3__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Forecast K1 Doku MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastPro7MAXXMN3__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Forecast Pro7 MAXX MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastSAT1GOLDMN3__c</fullName>
        <label>Forecast SAT.1 GOLD MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastsixxMN3__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Forecast sixx MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiK1Doku__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Opportunities K1 Doku MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiP7MAXX__c</fullName>
        <label>Opportunities P7 MAXX MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiSat1GOLD__c</fullName>
        <label>Opportunities Sat.1 GOLD MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJK1Doku__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Opportunities K1 Doku Vorjahr MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJP7MAXX__c</fullName>
        <label>Opportunities P7 MAXX Vorjahr MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJSat1GOLD__c</fullName>
        <label>Opportunities Sat.1 GOLD Vorjahr MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJsixx__c</fullName>
        <label>Opportunities sixx Vorjahr  MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_Opptisixx__c</fullName>
        <description>wird durch Rollup Helper gefüllt</description>
        <label>Opportunities sixx MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_PrognoseCommitment__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Forecast Commitments Kernsender MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_PrognosePaket__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Forecast Pakete Kernsender MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_PrognoseZubuchung__c</fullName>
        <description>wird durch Rollup Helper befüllt</description>
        <label>Forecast Zubuchungen Kernsender MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>P7S1_Mn3__c</fullName>
        <formula>/* Achtung: Funktioniert nur mit ID15, nicht mit ID18! */

CASE( RecordTypeId ,

/*** 71M TV Opportunities ***/
/*** SomTv_BuchungenOhneVertraege ***/
&apos;012D0000000QmVy&apos; , SomTv_MN3__c ,
/*** SomTv_Commitment ***/
&apos;012D0000000QmVz&apos; , SomTv_MN3__c ,
/*** SomTv_Zubuchung ***/
&apos;012D0000000QmW2&apos; , SomTv_MN3__c ,
/*** SomTv_Paket ***/
&apos;012D0000000QmW0&apos; , SomTv_MN3__c ,
/*** SomTv_SalesPush ***/
&apos;012D0000000QmW1&apos; , SomTv_MN3__c ,

/*** 71M Digital Opportunities
=============== &gt;&gt;&gt;&gt;&gt; TO DO =&gt; Change Value for Digital Amount ***/
/*** Standard ***/
&apos;012200000004j8N&apos; , SomTv_MN3__c ,

/*** AdFactory Opportunities ***/
/*** SomTv_P7S1Intern ***/
&apos;012D0000000QnXP&apos; , 0 ,
/*** SomTv_AdFactory ***/
&apos;012D0000000QmVx&apos; , 0 ,

/*** Sales Excellence Opportunities ***/
&apos;012570000007Qaq&apos; , SomTv_MN3__c , /* Achtung: Funktioniert nur mit ID15, nicht mit ID18! */

/*** d&amp;a Sales Opportunities ***/
&apos;012570000007QjJ&apos; , SomTv_MN3__c,

/*** Maxdome Opportunities ***/
&apos;012570000007Qia&apos; , SomTv_MN3__c,

/*** 7Ventures Opportunities ***/
/*** Ven_Default ***/
&apos;01257000000QqI0&apos; , Ven_FullNetPotentialCurrentYear__c ,

/*** All Other Opportunities ***/
Amount
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MN3 gesamt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>P7S1_StartdateofselectedOppYear__c</fullName>
        <description>Zeigt das Datum 01.01. des für die Opp ausgewählten Jahres an.
Technisch für Aggregationen notwendig</description>
        <formula>DATE ( VALUE ( TEXT ( SomTv_Jahr__c ) ) , 01 , 01 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Startdate of selected Opp Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomTv_Plattform__c</fullName>
        <description>Kernsender
Sixx
Sat Gold</description>
        <inlineHelpText>Bitte wählen Sie die Plattform:
Kernsender
Sixx
Sat Gold</inlineHelpText>
        <label>Plattform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sixx</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Kernsender</fullName>
                </value>
                <value>
                    <fullName>S1G</fullName>
                </value>
                <value>
                    <fullName>P7MAXX</fullName>
                </value>
                <value>
                    <fullName>K1Doku</fullName>
                </value>
                <value>
                    <fullName>Adressable TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SomTv_ForecastTV__c.object
<CustomObject>
    <description>Ganzjährige Eingabe des Forecasts  für TV</description>
    <fields>
        <fullName>SomTV_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forecasts TV</relationshipLabel>
        <relationshipName>Forecasts_TV</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastCommitmentsKernsenderMN3__c</fullName>
        <label>Forecast Commitments Kernsender MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastK1DokuMN3__c</fullName>
        <label>Forecast K1 Doku MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastPaketeKernsenderMN3__c</fullName>
        <label>Forecast Pakete Kernsender MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastPro7MAXXMN3__c</fullName>
        <label>Forecast Pro7 MAXX MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastSAT1GOLDMN3__c</fullName>
        <label>Forecast SAT.1 GOLD MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastTVfueraktuellesJahr__c</fullName>
        <description>Zeigt an, ob dieser Forecast TV für das aktuelle Jahr gilt</description>
        <formula>YEAR ( DATE ( VALUE ( TEXT ( SomTv_Jahr__c ) ) , 1 , 1 ) ) = YEAR ( TODAY() )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Zeigt an, ob dieser Forecast TV für das aktuelle Jahr gilt</inlineHelpText>
        <label>Forecast TV für aktuelles Jahr</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastZubuchungKernsenderMN3__c</fullName>
        <label>Forecast Zubuchung Kernsender MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_ForecastsixxMN3__c</fullName>
        <label>Forecast sixx MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiSat1GOLD__c</fullName>
        <description>Summe der Opportunities Sat.1 GOLD (MN3) aus dem Account</description>
        <formula>SomTV_Account__r.SomTv_OpptiSat1GOLD__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summe der Opportunities Sat.1 GOLD (MN3) aus dem Account</inlineHelpText>
        <label>Opportunities Sat.1 GOLD MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJK1Doku__c</fullName>
        <description>Summe der Opportunities K1 Doku (MN3) des Vorjahres aus dem Account</description>
        <formula>SomTV_Account__r.SomTv_OpptiVJK1Doku__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summe der Opportunities K1 Doku (MN3) des Vorjahres aus dem Account</inlineHelpText>
        <label>Opportunities K1 Doku Vorjahr MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJP7MAXX__c</fullName>
        <description>Summe der Opportunities P7 MAXX (MN3) des Vorjahres aus dem Account</description>
        <formula>SomTV_Account__r.SomTv_OpptiVJP7MAXX__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summe der Opportunities P7 MAXX (MN3) des Vorjahres aus dem Account</inlineHelpText>
        <label>Opportunities P7 MAXX Vorjahr MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJSat1GOLD__c</fullName>
        <description>Summe der Opportunities Sat.1 GOLD (MN3) des Vorjahres aus dem Account</description>
        <formula>SomTV_Account__r.SomTv_OpptiVJSat1GOLD__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summe der Opportunities Sat.1 GOLD (MN3) des Vorjahres aus dem Account</inlineHelpText>
        <label>Opportunities Sat.1 GOLD Vorjahr MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomTv_OpptiVJsixx__c</fullName>
        <description>Summe der Opportunities sixx (MN3) des Vorjahres aus dem Account</description>
        <formula>SomTV_Account__r.SomTv_OpptiVJsixx__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Summe der Opportunities sixx (MN3) des Vorjahres aus dem Account</inlineHelpText>
        <label>Opportunities sixx Vorjahr MN3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Forecast TV</label>
    <nameField>
        <label>Forecast TV</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast TV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_Account_Rollup.cls
public class P7S1_Account_Rollup {
    
 
    
    public static void opportunityToAccountRollups(List<Opportunity> newOppsList, Map<Id, Opportunity> oldOppsMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isAfter) {
        Map<String, string> lastyearPlattformToAccFieldMap = new Map<String, String>{'P7MAXX' => 'SomTv_OpptiVJP7MAXX__c',
            																		 'Sixx'	  => 'SomTv_OpptiVJsixx__c',
                                                                                     'K1Doku' => 'SomTv_OpptiVJK1Doku__c',
                                                                                     'S1G'    => 'SomTv_OpptiVJSat1GOLD__c'};
                                                                                         
        Map<String, string> thisyearPlattformToAccFieldMap = new Map<String, String>{'P7MAXX' => 'SomTv_OpptiP7MAXX__c',
            																		 'Sixx'	  => 'SomTv_Opptisixx__c',
                                                                                     'K1Doku' => 'SomTv_OpptiK1Doku__c',
                                                                                     'S1G'    => 'SomTv_OpptiSat1GOLD__c'};
                                                                                         
		Set<String> oppStageNames = new Set<String>{'Geschlossene und gewonnene', 'Rabatt freigegeben', 'In Briefing', 'Angebot abgegeben'};                                                                              
		
        Integer thisYear = Date.today().year();
        Integer lastYear = Date.today().addYears(-1).year();
        
		Set<Id> parentIDs = new Set<ID>();
        
        if(isInsert && isAfter) {
            
            // on insert, always rollup.
            for(Opportunity opp : newOppsList) {
                if(oppStageNames.contains(opp.StageName))
                	parentIDs.add(opp.AccountID);
            }
            
        } else if(isUpdate && isAfter) {
            
            for(Opportunity opp : newOppsList) {
                Opportunity oldOpp = oldOppsMap.get(opp.Id);
                if(oppStageNames.contains(opp.StageName) || oppStageNames.contains(oldOpp.StageName)) {
                    if(opp.P7S1_StartdateofselectedOppYear__c.year() == thisYear || opp.P7S1_StartdateofselectedOppYear__c.year() == lastYear) {
                        parentIDs.add(opp.AccountID);
                    }
                }
            }

        } else if(isDelete && isAfter) {
            
            for (Id key : oldOppsMap.keySet()) {
                Opportunity opp = oldOppsMap.get(key);
                parentIDs.add(opp.AccountID);
            }
            
        }
        
        List<Account> accountsToUpdate = new List<Account>();
        if(!parentIDs.isEmpty()) accountsToUpdate = new List<Account>([SELECT SomTv_OpptiVJP7MAXX__c, SomTv_OpptiVJsixx__c, SomTv_OpptiVJK1Doku__c, SomTv_OpptiVJSat1GOLD__c, SomTv_OpptiK1Doku__c, SomTv_OpptiP7MAXX__c, SomTv_OpptiSat1GOLD__c, SomTv_Opptisixx__c,
                                                                       (SELECT P7S1_MN3__c, SomTv_Plattform__c, P7S1_StartdateofselectedOppYear__c FROM Opportunities WHERE StageName IN :oppStageNames AND (P7S1_StartdateofselectedOppYear__c = THIS_YEAR OR P7S1_StartdateofselectedOppYear__c = LAST_YEAR))
                                                                       FROM Account
                                                                       WHERE Id IN :parentIDs]);
        
        // Combine this year and last year values.
        List<String> thisAndLastYearAccountFields = new List<String>();
        thisAndLastYearAccountFields.addAll(lastyearPlattformToAccFieldMap.values());
        thisAndLastYearAccountFields.addAll(thisyearPlattformToAccFieldMap.values());
        
        for(Account acc: accountsToUpdate) {
           
            // Set values to 0.
            for(String fieldName : thisAndLastYearAccountFields) {
                acc.put(fieldName, 0);
            }
            
            for(Opportunity opp : acc.Opportunities) {
                
                Integer oppYear = opp.P7S1_StartdateofselectedOppYear__c.year();
                
                if( (oppYear == thisYear || oppYear == lastYear) && (thisyearPlattformToAccFieldMap.containsKey(opp.SomTv_Plattform__c) || lastyearPlattformToAccFieldMap.containsKey(opp.SomTv_Plattform__c))) {
                    
                    String fieldName = oppYear == thisYear ? thisyearPlattformToAccFieldMap.get(opp.SomTv_Plattform__c) : lastyearPlattformToAccFieldMap.get(opp.SomTv_Plattform__c);
                	Decimal acumulatedValue = (Decimal) acc.get(fieldName);
                    Decimal oppValue = (Decimal) opp.get('P7S1_MN3__c');
                    
					acc.put(fieldName, acumulatedValue + oppValue);
                }
            }
            
        }
        
        update accountsToUpdate;
        
    }
    
    
    
    
    public static void forecastToAccountRollups(List<SomTv_ForecastTV__c> newForecastsList, Map<Id, SomTv_ForecastTV__c> oldForecastsMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete, Boolean isAfter) {
        System.debug('+++ forecastToAccountRollups');
        Map<String, String> forecastToAccFieldMap = new Map<String, String>{'SomTv_ForecastK1DokuMN3__c' => 'SomTv_ForecastK1DokuMN3__c',
            																'SomTv_ForecastPro7MAXXMN3__c' => 'SomTv_ForecastPro7MAXXMN3__c',
            																'SomTv_ForecastSAT1GOLDMN3__c' => 'SomTv_ForecastSAT1GOLDMN3__c',
            																'SomTv_ForecastsixxMN3__c' => 'SomTv_ForecastsixxMN3__c',
            																'SomTv_ForecastCommitmentsKernsenderMN3__c' => 'SomTv_PrognoseCommitment__c',
            																'SomTv_ForecastPaketeKernsenderMN3__c' => 'SomTv_PrognosePaket__c',
            																'SomTv_ForecastZubuchungKernsenderMN3__c' => 'SomTv_PrognoseZubuchung__c'};
        Set<Id> parentIDs = new Set<ID>();
        
        if(isInsert && isAfter) {
            // on insert, always rollup.
            System.debug('+++ after insert');
            for(SomTv_ForecastTV__c forecast : newForecastsList) {
                System.debug('+++ after insert forecast loop');
                parentIDs.add(forecast.SomTV_Account__c);
            }
            
        } else if(isUpdate && isAfter) {
            //on update, rollup if any field has changed.
            System.debug('+++ after update');
            for(SomTv_ForecastTV__c forecast : newForecastsList) {
                System.debug('+++ after update forecast loop');
                SomTv_ForecastTV__c oldForecast = oldForecastsMap.get(forecast.Id);
                
                // if parent change, update old and new parent.
                if(forecast.SomTV_Account__c != oldForecast.SomTV_Account__c) parentIDs.addAll(new Set<ID>{forecast.SomTV_Account__c, oldForecast.SomTV_Account__c});
                else {
                    // if at least one field has changed, do rollup.
                    for(String fieldName : forecastToAccFieldMap.keySet()) {
                        if(forecast.get(fieldName) != oldForecast.get(fieldName)) {
                            parentIDs.add(forecast.SomTV_Account__c);
                            continue;
                        }
                    }
                }
            }
        } else if(isDelete && isAfter) {
            System.debug('+++ after delete');
            for (Id key : oldForecastsMap.keySet()) {
                System.debug('+++ after delete forecast loop');
                SomTv_ForecastTV__c forecast = oldForecastsMap.get(key);
                parentIDs.add(forecast.SomTV_Account__c);
            }
        }
        
        
        
        List<Account> accountsToUpdate = new List<Account>();
        if(!parentIDs.isEmpty()) accountsToUpdate = new List<Account>([SELECT SomTv_ForecastK1DokuMN3__c, SomTv_ForecastPro7MAXXMN3__c, SomTv_ForecastSAT1GOLDMN3__c, SomTv_ForecastsixxMN3__c, SomTv_PrognoseCommitment__c, SomTv_PrognosePaket__c,SomTv_PrognoseZubuchung__c,
                                                           (SELECT SomTv_ForecastK1DokuMN3__c, SomTv_ForecastPro7MAXXMN3__c, SomTv_ForecastSAT1GOLDMN3__c, SomTv_ForecastsixxMN3__c, SomTv_ForecastCommitmentsKernsenderMN3__c, SomTv_ForecastPaketeKernsenderMN3__c, SomTv_ForecastZubuchungKernsenderMN3__c FROM Forecasts_TV__r WHERE SomTv_ForecastTVfueraktuellesJahr__c = TRUE)
                                                           FROM Account
                                                           WHERE Id IN :parentIDs]);
        System.debug('+++accountsToUpdate.size: '+accountsToUpdate.size());
        
        for(Account acc: accountsToUpdate) {
            System.debug('+++acc.Forecasts_TV__r.size: '+acc.Forecasts_TV__r.size());
            // Set values to 0.
            for(String fieldName : forecastToAccFieldMap.values()) {
                System.debug('+++forecastToAccFieldMap loop');
                acc.put(fieldName, 0);
            }
            for(SomTv_ForecastTV__c forecast : acc.Forecasts_TV__r) {
                System.debug('+++forecast loop');
                for(String fieldName : forecastToAccFieldMap.keySet()) {
                    System.debug('+++forecast fieldname loop');
                    Decimal acumulatedValue = (Decimal)acc.get(forecastToAccFieldMap.get(fieldName));
                    acumulatedValue = acumulatedValue == NULL ? 0 : acumulatedValue;
                    Decimal currentForecastValue = (Decimal)forecast.get(fieldName);
                    currentForecastValue = currentForecastValue == NULL ? 0 : currentForecastValue;
                    acc.put(forecastToAccFieldMap.get(fieldName), acumulatedValue + currentForecastValue);
                }
            }
        }
        
        update accountsToUpdate;
        
    }

}