src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ven_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Es wird der Account markiert der Customer von Seven Ventures ist.</description>
        <inlineHelpText>Es wird der Account markiert der Customer von Seven Ventures ist.</inlineHelpText>
        <label>Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Investor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Falls der Account bei irgend einen anderen Account als Investor fungiert, wird diese Checkbox gesetzt.</description>
        <inlineHelpText>Falls der Account bei irgend einen anderen Account als Investor fungiert, wird diese Checkbox gesetzt.</inlineHelpText>
        <label>Investor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Target__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account, zu dem keine abgeschlossene Opportunity von Seven Ventures besteht.</description>
        <inlineHelpText>Account, zu dem keine abgeschlossene Opportunity von Seven Ventures besteht.</inlineHelpText>
        <label>Target</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ven_Share__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Share__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <formula>Ven_Shares__c / Ven_Round__r.Ven_all_Shares__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hier werden automatisch die % der Beteiligungen errechnet.</inlineHelpText>
        <label>Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Shareholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Bitte den Shareholder (Account) eingetragen für den verknüpften Account.</inlineHelpText>
        <label>Shareholder</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Shareholder</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Share</label>
    <nameField>
        <displayFormat>CT-{0000000}</displayFormat>
        <label>Share-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Ven_Account_Type.cls
public with sharing class Ven_Account_Type {

    /* Methods for Opportunity trigger */

    public static void setAccountTypeBoxes(List<Opportunity> opps, Set<Id> oppIds, Map<Id, Opportunity> mapOldItems, Boolean isUpdate) {
        Set<Id> accountIdsCustomer = new Set<Id>();
        Set<Id> accountIdsTarget = new Set<Id>();

        Set<Id> venRecordTypeIds = getVenRecordTypeIds();

        for (Opportunity opp : opps) {
            if (venRecordTypeIds.contains(opp.RecordTypeId)) {
                if (isUpdate) {
                    if (mapOldItems.get(opp.Id).AccountId != opp.AccountId) {
                        if (mapOldItems.get(opp.Id).AccountId == null && opp.AccountId != null) {
                            if (opp.Probability >= 100) {
                                accountIdsCustomer.add(opp.AccountId);
                            }
                        } else if (mapOldItems.get(opp.Id).AccountId != null && opp.AccountId == null) {
                            accountIdsTarget.add(mapOldItems.get(opp.Id).AccountId);
                        } else {
                            if (opp.Probability >= 100) {
                                accountIdsCustomer.add(opp.AccountId);
                            }

                            accountIdsTarget.add(mapOldItems.get(opp.Id).AccountId);
                        }
                    } else if (opp.AccountId != null && mapOldItems.get(opp.Id).Probability != opp.Probability) {
                        if (mapOldItems.get(opp.Id).Probability < 100 && opp.Probability >= 100) {
                            accountIdsCustomer.add(opp.AccountId);
                        } else if (mapOldItems.get(opp.Id).Probability >= 100 && opp.Probability < 100) {
                            accountIdsTarget.add(opp.AccountId);
                        }
                    } else if (opp.AccountId != null && opp.Probability >= 100 && !venRecordTypeIds.contains(mapOldItems.get(opp.Id).RecordTypeId)) {
                        accountIdsCustomer.add(opp.AccountId);
                    }
                } else if (opp.AccountId != null && opp.Probability >= 100) {
                    accountIdsCustomer.add(opp.AccountId);
                }
            } else {
                if (isUpdate) {
                    if (opp.AccountId != null && opp.Probability >= 100 && venRecordTypeIds.contains(mapOldItems.get(opp.Id).RecordTypeId)) {
                        accountIdsTarget.add(opp.AccountId);
                    }
                }
            }
        }

        Set<Id> accountIds = new Set<Id>();

        if (!accountIdsCustomer.isEmpty()) {
            accountIds.addAll(accountIdsCustomer);
        }

        if (!accountIdsTarget.isEmpty()) {
            Set<Id> accountIdsTargetV2 = new Set<Id>();

            for (Id accountIdTarget : accountIdsTarget) {
                if (!accountIdsCustomer.contains(accountIdTarget)) {
                    accountIdsTargetV2.add(accountIdTarget);
                }
            }

            accountIdsTarget = checkOtherOpps(oppIds, accountIdsTargetV2);

            if (!accountIdsTarget.isEmpty()) {
                accountIds.addAll(accountIdsTarget);
            }
        }

        List<Account> accountsToUpdate = getAccountsToUpdate(accountIds, accountIdsCustomer, accountIdsTarget);

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }
    }

    public static void setAccountTypeBoxToTarget(List<Opportunity> opps, Set<Id> oppIds) {
        Set<Id> accountIdsTarget = new Set<Id>();

        Set<Id> venRecordTypeIds = getVenRecordTypeIds();

        for (Opportunity opp : opps) {
            if (venRecordTypeIds.contains(opp.RecordTypeId) && opp.AccountId != null && opp.Probability >= 100) {
                accountIdsTarget.add(opp.AccountId);
            }
        }

        if (!accountIdsTarget.isEmpty()) {
            accountIdsTarget = checkOtherOpps(oppIds, accountIdsTarget);
        }

        List<Account> accountsToUpdate = getAccountsToUpdate(accountIdsTarget);

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }
    }

    private static Set<Id> getVenRecordTypeIds() {
        Set<Id> venRecordTypeIds = new Set<Id>();

        for (RecordType venRecordType : [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName LIKE 'Ven_%']) {
            venRecordTypeIds.add(venRecordType.Id);
        }

        return venRecordTypeIds;
    }

    private static Set<Id> checkOtherOpps(Set<Id> oppIds, Set<Id> accountIdsTarget) {
        Set<Id> accountIdsToRemove = new Set<Id>();

        for (Opportunity opp : [SELECT Id, AccountId FROM Opportunity WHERE Id NOT IN :oppIds AND AccountId IN :accountIdsTarget AND Probability >= 100]) {
            accountIdsToRemove.add(opp.AccountId);
        }

        if (!accountIdsToRemove.isEmpty()) {
            for (Id accountIdToRemove : accountIdsToRemove) {
                accountIdsTarget.remove(accountIdToRemove);
            }
        }

        return accountIdsTarget;
    }

    private static List<Account> getAccountsToUpdate(Set<Id> accountIds, Set<Id> accountIdsCustomer, Set<Id> accountIdsTarget) {
        List<Account> accountsToUpdate = new List<Account>();

        if (!accountIds.isEmpty()) {
            for (Account account : [SELECT Id, Ven_Target__c, Ven_Customer__c FROM Account WHERE Id IN :accountIds]) {
                if (accountIdsCustomer.contains(account.Id) && account.Ven_Customer__c != true) {
                    account.Ven_Target__c = false;
                    account.Ven_Customer__c = true;
                    accountsToUpdate.add(account);
                } else if (accountIdsTarget.contains(account.Id)) {
                    account.Ven_Target__c = true;
                    account.Ven_Customer__c = false;
                    accountsToUpdate.add(account);
                }
            }
        }

        return accountsToUpdate;
    }

    private static List<Account> getAccountsToUpdate(Set<Id> accountIdsTarget) {
        List<Account> accountsToUpdate = new List<Account>();

        if (!accountIdsTarget.isEmpty()) {
            for (Account account : [SELECT Id, Ven_Target__c, Ven_Customer__c FROM Account WHERE Id IN :accountIdsTarget]) {
                account.Ven_Target__c = true;
                account.Ven_Customer__c = false;
                accountsToUpdate.add(account);
            }
        }

        return accountsToUpdate;
    }



    /* Methods for Ven_Share trigger */

    public static void setAccountTypeBoxInvestorTrue(List<Ven_Share__c> venCapTables) {
        Set<Id> accountIdsInvestorTrue = new Set<Id>();

        for (Ven_Share__c venCapTable : venCapTables) {
            if (venCapTable.Ven_Shareholder__c != null) {
                accountIdsInvestorTrue.add(venCapTable.Ven_Shareholder__c);
            }
        }

        List<Account> accountsToUpdate = getAccountsToUpdateTrue(accountIdsInvestorTrue);

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }
    }

    public static void setAccountTypeBoxInvestorFalse(List<Ven_Share__c> venCapTables) {
        Set<Id> accountIdsInvestorFalse = new Set<Id>();

        for (Ven_Share__c venCapTable : venCapTables) {
            if (venCapTable.Ven_Shareholder__c != null) {
                accountIdsInvestorFalse.add(venCapTable.Ven_Shareholder__c);
            }
        }

        List<Account> accountsToUpdate = getAccountsToUpdateFalse(accountIdsInvestorFalse);

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }
    }

    private static List<Account> getAccountsToUpdateTrue(Set<Id> accountIdsInvestorTrue) {
        List<Account> accountsToUpdate = new List<Account>();

        if (!accountIdsInvestorTrue.isEmpty()) {
            for (Account account : [SELECT Id, Ven_Investor__c FROM Account WHERE Id IN :accountIdsInvestorTrue AND Ven_Investor__c = false]) {
                account.Ven_Investor__c = true;
                accountsToUpdate.add(account);
            }
        }

        return accountsToUpdate;
    }

    private static List<Account> getAccountsToUpdateFalse(Set<Id> accountIdsInvestorFalse) {
        List<Account> accountsToUpdate = new List<Account>();

        if (!accountIdsInvestorFalse.isEmpty()) {
            for (Account account : [SELECT Id, Ven_Investor__c, (SELECT Id FROM Shareholder__r LIMIT 1) FROM Account WHERE Id IN :accountIdsInvestorFalse]) {
                if (account.Shareholder__r.isEmpty()) {
                    account.Ven_Investor__c = false;
                    accountsToUpdate.add(account);
                }
            }
        }

        return accountsToUpdate;
    }

}