src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ven_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Es wird der Account markiert der Customer von Seven Ventures ist.</description>
        <inlineHelpText>Es wird der Account markiert der Customer von Seven Ventures ist.</inlineHelpText>
        <label>Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Target__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account, zu dem keine abgeschlossene Opportunity von Seven Ventures besteht.</description>
        <inlineHelpText>Account, zu dem keine abgeschlossene Opportunity von Seven Ventures besteht.</inlineHelpText>
        <label>Target</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ven_Financial_Model_Data__c.object
<CustomObject>
    <description>Objekt zur Speicherung der monatlichen Plan- und Istwerte jedes KPIs des Investments.</description>
    <fields>
        <fullName>Financial_Model_Version__c</fullName>
        <description>Stellt die Verbindung zum übergeordneten Objekt her</description>
        <inlineHelpText>bitte Financial Model Version eintragen</inlineHelpText>
        <label>Financial Model Version</label>
        <referenceTo>Ven_Financial_Model_Version__c</referenceTo>
        <relationshipLabel>Financial Model Data</relationshipLabel>
        <relationshipName>Financial_Model_Data</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Value__c</fullName>
        <description>Beinhaltet den Wert des KPI</description>
        <inlineHelpText>Beinhaltet den Wert des KPI</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financial Model Data</label>
    <nameField>
        <label>Financial Model-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Model Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Financial_Model_Version__c.object
<CustomObject>
    <description>SevenVentures gruppiert in diesem Objekt seine Financial Model Daten zu Typversionen der Plan-, Actual- und Budgetdaten.</description>
    <label>Financial Model Version</label>
    <nameField>
        <label>Financial Model Version-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Model Versions</pluralLabel>
    <recordTypes>
        <fullName>Ven_Actual_Data</fullName>
        <active>true</active>
        <description>Actual Data</description>
        <label>Actual Data</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ven_Budget_Data</fullName>
        <active>true</active>
        <description>Budget Data</description>
        <label>Budget Data</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ven_Plan_Data</fullName>
        <active>true</active>
        <description>Plan Data</description>
        <label>Plan Data</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Key_Performance_Indicator__c.object
<CustomObject>
    <description>Liste aller KPIs genutzt durch SevenVentures</description>
    <label>Key Performance Indicator</label>
    <nameField>
        <label>Key Performance Indicator-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Performance Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ven_KeyPerformanceIndicatorBlock__c.object
<CustomObject>
    <fields>
        <fullName>Ven_FullYearView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Full Year View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Last6MonthsView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Last 6 months View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_MonthlyView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monthly View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_YearToDateView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year-to-Date View</label>
        <type>Checkbox</type>
    </fields>
    <label>Key Performance Indicator Block</label>
    <nameField>
        <label>KPI Block</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Performance Indicator Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ven_KeyPerformanceIndicatorBlockEntry__c.object
<CustomObject>
    <fields>
        <fullName>Ven_KeyPerformanceIndicatorBlock__c</fullName>
        <label>Key Performance Indicator Block</label>
        <referenceTo>Ven_KeyPerformanceIndicatorBlock__c</referenceTo>
        <relationshipLabel>Key Performance Indicator Block Entries</relationshipLabel>
        <relationshipName>Ven_KPIBlockEntries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Performance Indicator Block Entry</label>
    <nameField>
        <displayFormat>KPIBE-{0}</displayFormat>
        <label>KPI Block Entry-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Performance Indicator Block Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_KeyPerformanceIndicatorTemplate__c.object
<CustomObject>
    <description>Key Performance Indicator entries</description>
    <label>Key Performance Indicator Template</label>
    <nameField>
        <label>KPI Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Performance Indicator Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ven_KeyPerformanceIndicatorTemplateEntry__c.object
<CustomObject>
    <description>Junction Object to connect Key Performance Indicators to Key Performance Indicator Template</description>
    <fields>
        <fullName>Ven_KeyPerformanceIndicatorBlock__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key Performance Indicator Block</label>
        <referenceTo>Ven_KeyPerformanceIndicatorBlock__c</referenceTo>
        <relationshipLabel>Key Performance Indicator Template Entries</relationshipLabel>
        <relationshipName>Ven_KPITemplateEntries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ven_KeyPerformanceIndicatorTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference a Key Performance Indicator Template</description>
        <inlineHelpText>Reference a Key Performance Indicator Template</inlineHelpText>
        <label>Key Performance Indicator Template</label>
        <referenceTo>Ven_KeyPerformanceIndicatorTemplate__c</referenceTo>
        <relationshipLabel>Key Performance Indicator Template Entries</relationshipLabel>
        <relationshipName>KPI_Template_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Key Performance Indicator Template Entry</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>KPI Template Entry-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Performance Indicator Template Entry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Ven_KPI_StrategicReport_Test.cls
@isTest
private class Ven_KPI_StrategicReport_Test {

    static testMethod void testVenKPIStrategicReport() {
        Account testAccount = cls_P7S1_TestData.createTestAccount(false);
        testAccount.Ven_Target__c = true;
        testAccount.Ven_Customer__c = false;
        insert testAccount;

        Opportunity testOpp = cls_P7S1_TestData.createTestOpportunity(true, testAccount);
        Ven_Key_Performance_Indicator__c testKpi = cls_P7S1_TestData.createTestKPI(true);
        Ven_KeyPerformanceIndicatorBlock__c testKpiBlock = cls_P7S1_TestData.createTestKPIBlock(false);
        testKpiBlock.Ven_YearToDateView__c = true;
        testKpiBlock.Ven_MonthlyView__c = true;
        testKpiBlock.Ven_FullYearView__c = true;
        testKpiBlock.Ven_Last6MonthsView__c = true;
        insert testKpiBlock;
        Ven_KeyPerformanceIndicatorBlockEntry__c testKpiBlockEntry = cls_P7S1_TestData.createTestKPIBlockEntry(true, testKpi, testKpiBlock);
        Ven_KeyPerformanceIndicatorTemplate__c testKpiTemplate = cls_P7S1_TestData.createTestKPITemplate(true);
        Ven_KeyPerformanceIndicatorTemplateEntry__c testKpiTemplateEntry = cls_P7S1_TestData.createTestKPITemplateEntry(true, testKpiTemplate, testKpiBlock);

        Id venActualDataId;
        Id venBudgetDataId;
        Id venPlanDataId;

        for (RecordType recordType : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Ven_Financial_Model_Version__c']) {
            if (recordType.DeveloperName == 'Ven_Actual_Data') {
                venActualDataId = recordType.Id;
            } else if (recordType.DeveloperName == 'Ven_Budget_Data') {
                venBudgetDataId = recordType.Id;
            } else if (recordType.DeveloperName == 'Ven_Plan_Data') {
                venPlanDataId = recordType.Id;
            }
        }

        if (venActualDataId != null) {
            Ven_Financial_Model_Version__c testFinancialModelVersionActualData = cls_P7S1_TestData.createTestFinancialModelVersion(true, venActualDataId, testOpp);

            Ven_Financial_Model_Data__c testFinancialModelDataActualData = cls_P7S1_TestData.createTestFinancialModelData(false, testKpi);
            testFinancialModelDataActualData.Financial_Model_Version__c = testFinancialModelVersionActualData.Id;
            testFinancialModelDataActualData.Ven_Value__c = 10;
            insert testFinancialModelDataActualData;
        }

        if (venBudgetDataId != null) {
            Ven_Financial_Model_Version__c testFinancialModelVersionBudgetData = cls_P7S1_TestData.createTestFinancialModelVersion(true, venBudgetDataId, testOpp);

            Ven_Financial_Model_Data__c testFinancialModelDataBudgetData = cls_P7S1_TestData.createTestFinancialModelData(false, testKpi);
            testFinancialModelDataBudgetData.Financial_Model_Version__c = testFinancialModelVersionBudgetData.Id;
            testFinancialModelDataBudgetData.Ven_Value__c = 20;
            insert testFinancialModelDataBudgetData;
        }

        if (venPlanDataId != null) {
            Ven_Financial_Model_Version__c testFinancialModelVersionPlanData = cls_P7S1_TestData.createTestFinancialModelVersion(true, venPlanDataId, testOpp);

            Ven_Financial_Model_Data__c testFinancialModelDataPlanData = cls_P7S1_TestData.createTestFinancialModelData(false, testKpi);
            testFinancialModelDataPlanData.Financial_Model_Version__c = testFinancialModelVersionPlanData.Id;
            testFinancialModelDataPlanData.Ven_Value__c = 30;
            insert testFinancialModelDataPlanData;
        }

        Task testTask = cls_P7S1_TestData.createTestTask(false);
        testTask.WhatId = testOpp.Id;
        insert testTask;

        Test.startTest();

        Test.setCurrentPage(new PageReference('/apex/Ven_KPI_StrategicReport?oppid=' + testOpp.Id + '&kpiTemplateId=' + testKpiTemplate.Id + '&date=' + system.today().format() + '&renderAs=pdf'));

        Ven_KPI_StrategicReport venStrategicReportController = new Ven_KPI_StrategicReport(new ApexPages.StandardController(new Opportunity()));

        Test.stopTest();
    }

}