src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SomDig_PartnerId__c</fullName>
        <label>Partner ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__ConnectedItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If you cancel a CampaignItem, a second CampaignItem is created to cancel the original. This field links those matching CampaignItems.</description>
        <label>Connected Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Campaign Items (Connected Item)</relationshipLabel>
        <relationshipName>ConnectedItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__LinearDistribution__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Linear Distribution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsSegment__c</fullName>
        <description>Id des M.-Segments, welches an der Belegungseinheit des Werbemittels gepflegt ist. Wird per Formel befüllt. Siehe auch KV 2551 zwecks nähere Infos. Wird für DWH-Schnittstelle benötigt</description>
        <formula>CASESAFEID( ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Mediagattungssegment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Id des M.-Segments, welches an der Belegungseinheit des Werbemittels gepflegt ist. Wird per Formel befüllt.</inlineHelpText>
        <label>Mediagattungs-Segment-Id</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AccountingDate__c</fullName>
        <label>Accounting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__BillingPeriodEndDate__c</fullName>
        <inlineHelpText>Monat der erstellten Rechnung (kann abweichen vom SAP Datum)</inlineHelpText>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoiceDateManual__c</fullName>
        <label>Invoice Date (Manual)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoiceDate__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoicedAmountNet2__c</fullName>
        <label>Invoiced Amount N2</label>
        <summarizedField>ADvendio__InvoiceItem__c.ADvendio__InvoicedAmountNet2__c</summarizedField>
        <summaryFilterItems>
            <field>ADvendio__InvoiceItem__c.ADvendio__ItemRecordType__c</field>
            <operation>notEqual</operation>
            <value>Packet</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__InvoiceItem__c.ADvendio__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentInterval__c</fullName>
        <label>Payment Interval</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentStart__c</fullName>
        <label>Payment Start</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <inlineHelpText>Entwurf: RG-Vorschlag welche freigegeben werden muss
Freigabe: RG-Vorschlag wurde freigegeben und kann im Renchnungslauf
Fakturiert: Rechungslauf erfolgte, aus RG-Vorschlag wurde finale Rechnung
Storno: Rechnung wurde durch neue RG-Storno aufgehoben</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__UniqueKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SomDig_PartnerId__c</fullName>
        <label>SomDig PartnerId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_RG_Empfaenger_P7S1_Konzernmitgl__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RG Empfänger P7S1 Konzernmitglied</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillingCategory__c</fullName>
        <label>Billing Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__BillingPeriodEndDate__c</fullName>
        <formula>ADvendio__Invoice__r.ADvendio__BillingPeriodEndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__BookedQuantity__c</fullName>
        <label>Booked Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__ConnectedItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Connected Item</label>
        <referenceTo>ADvendio__InvoiceItem__c</referenceTo>
        <relationshipLabel>Connected Items</relationshipLabel>
        <relationshipName>ConnectedItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__FromDate__c</fullName>
        <inlineHelpText>Item&apos;s Startdate of complete runtime</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoiceDate__c</fullName>
        <formula>ADvendio__Invoice__r.ADvendio__InvoiceDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoiceItemEndDate__c</fullName>
        <inlineHelpText>Enddate of this Item&apos;s date range in this Invoice</inlineHelpText>
        <label>Invoice Item End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoiceItemStartDate__c</fullName>
        <inlineHelpText>Startdate of this Item&apos;s date range in this Invoice</inlineHelpText>
        <label>Invoice Item Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipName>InvoiceItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoicedAmountNet2__c</fullName>
        <label>Invoiced Amount N2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoicedQuantityMultiplier__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Invoiced Quantity Multiplier</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__LinearDistribution__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This Checkbox defines, if the amount is distributed linear or not. This is used for fix price amounts.</description>
        <inlineHelpText>This Checkbox defines, if the amount is distributed linear or not. This is used for fix price amounts.</inlineHelpText>
        <label>Linear Distribution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Salesprice__c</fullName>
        <label>Salesprice</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__UniqueKey__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ADvendio__UntilDate__c</fullName>
        <inlineHelpText>Item&apos;s Enddate of complete runtime</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Adservertyp__c</fullName>
        <label>Adservertyp</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Mediagattungs_Segement_Name__c</fullName>
        <label>Mediagattungs-Segement Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Close_Date__c</fullName>
        <description>Enter the expected closing date of this media campaign.</description>
        <inlineHelpText>Wann soll die Entscheidung für dieses Angebot fallen, ob das Angebot angenommen oder abgelehnt wird?</inlineHelpText>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__Closed_Lost__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box shows if the media campaign was lost.</description>
        <inlineHelpText>This check box shows if the media campaign was lost.</inlineHelpText>
        <label>Closed/Lost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentInterval__c</fullName>
        <description>Essential for the Billing &amp; Accounting App and needs to be filled.</description>
        <inlineHelpText>Please choose the invoice interval</inlineHelpText>
        <label>Payment Interval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>total account (one Invoice)</fullName>
                </value>
                <value>
                    <fullName>monthly (1 month)</fullName>
                    <default>true</default>
                    <label>monthly (1 month)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentStart__c</fullName>
        <description>Essential for the Billing &amp; Accounting App and needs to be filled.</description>
        <inlineHelpText>First Invoice before or after Campaignstart?</inlineHelpText>
        <label>Payment Start</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ADvendio__PaymentInterval__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>before / during Billingperiod</fullName>
                </value>
                <value>
                    <fullName>after Billingperiod</fullName>
                    <default>true</default>
                    <label>after Billingperiod</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SomDig_Buchungssatz_EaStart_Test.cls
/**
 * Test class for SomDig_Buchungssatz_EaStart.
 */
@IsTest
public with sharing class SomDig_Buchungssatz_EaStart_Test {

	@IsTest
	public static void testEaStartPagination()  {
		Test.StartTest();

		PageReference pr = Page.SomDig_Buchungssatz_EaStart;
		Test.setCurrentPage(pr);		

		SomDig_Buchungssatz_EaStart crtl = new SomDig_Buchungssatz_EaStart();
		
		for (Integer i = 0; i <= SomDig_Buchungssatz_EaStart.MAX_NUMBER_MCS_PER_PAGE; i++) {
			crtl.allMediaCampaigns.add(new ADvendio__MediaCampaign__c(Name=('Test Mc ' + (i+1))));
		}
		
		crtl.initPagination();
		
		System.assertEquals(true, crtl.getHasResult());
		System.assertEquals(2, crtl.getTotalPages());

		System.assertEquals(1, crtl.getPageNumber());
		System.assertEquals(true, crtl.getHasNext());
		System.assertEquals(false, crtl.getHasPrevious());
		
		crtl.next();
		System.assertEquals(2, crtl.getPageNumber());
		System.assertEquals(false, crtl.getHasNext());
		System.assertEquals(true, crtl.getHasPrevious());
		
		crtl.previous();
		System.assertEquals(1, crtl.getPageNumber());
		System.assertEquals(true, crtl.getHasNext());
		System.assertEquals(false, crtl.getHasPrevious());

		crtl.last();
		System.assertEquals(2, crtl.getPageNumber());
		System.assertEquals(false, crtl.getHasNext());
		System.assertEquals(true, crtl.getHasPrevious());
		
		crtl.first();
		System.assertEquals(1, crtl.getPageNumber());
		System.assertEquals(true, crtl.getHasNext());
		System.assertEquals(false, crtl.getHasPrevious());
				
		crtl.filterMediaCampaign.ADvendio__Closed_Lost__c = false;
		crtl.changeProcessRunningDate();

		Test.StopTest();
	}

	@isTest
	public static void testFilterMonthly()  {
		Date today	= Date.newInstance(System.today().year(), System.today().month(), 15);
		
		SomDig_Mediagattungssegment__c mgs			= cls_P7S1_TestData.createTestMediagattungsSegment(true);
				
		ADvendio__MediaCampaign__c mc		= cls_P7S1_TestData.createTestMediaCampaign(true, null, null);
   		ADvendio__Campaign_Item__c ci		= cls_P7S1_TestData.createTestCampaignItem(false, mc, null);
        insert new List<ADvendio__Campaign_Item__c>{ci};
		
		ADvendio__Invoice__c i						= cls_P7S1_TestData.createTestInvoice(false, mc);
		i.ADvendio__Status__c						= 'Invoiced';
		i.ADvendio__PaymentInterval__c				= 'monthly (1 month)';
        i.ADvendio__PaymentStart__c					= 'after Billingperiod';
        i.ADvendio__AccountingDate__c				= today.toStartOfMonth().addMonths(-1);
        i.ADvendio__BillingPeriodEndDate__c			= today.addDays(-20);
        i.ADvendio__InvoiceDateManual__c			= today.toStartOfMonth();
        i.ADvendio__InvoiceDate__c					= today.toStartOfMonth();
        i.SomDig_RG_Empfaenger_P7S1_Konzernmitgl__c	= true;
        i.SomDig_PartnerId__c						= '12345';
		insert i;
        
		ADvendio__InvoiceItem__c ii			= cls_P7S1_TestData.createTestInvoiceItem(false, i , ci);
		ii.ADvendio__Salesprice__c			= 10;
		ii.ADvendio__BookedQuantity__c		= 1000;
		ii.ADvendio__BillingCategory__c		= 'CPM';
        ii.ADvendio__LinearDistribution__c	= true;
		ii.ADvendio__FromDate__c			= today.addDays(-25);
		ii.ADvendio__UntilDate__c			= today.addDays(-19);
		ii.ADvendio__InvoiceItemStartDate__c = today.addDays(-25);
		ii.ADvendio__InvoiceItemEndDate__c	= today.addDays(-19);
		ii.SomDig_Adservertyp__c			= 'DFP';
		ii.SomDig_Mediagattungs_Segement_Name__c = mgs.Name;
		insert ii;

		Test.StartTest();
		SomDig_Buchungssatz_EaStart cls = new SomDig_Buchungssatz_EaStart();
		cls.filterMediaCampaign.ADvendio__Close_Date__c	= today;
		cls.changeProcessRunningDate();
		cls.doSearch();
		
		system.assertEquals(1, cls.allMediaCampaigns.size());
		cls.toggleSelection();

        // Item Storno
        ADvendio__Invoice__c iNeg	= i.clone();
        iNeg.ADvendio__Invoice__c	= i.Id;
        iNeg.ADvendio__Status__c	= 'Invoiced';
        insert iNeg;
        
        ADvendio__InvoiceItem__c iiNeg					= ii.clone();
        iiNeg.ADvendio__InvoicedQuantityMultiplier__c	= -1;
        iiNeg.ADvendio__Invoice__c						= iNeg.Id;
        iiNeg.ADvendio__InvoicedAmountNet2__c			= 10;
        iiNeg.ADvendio__ConnectedItem__c				= ii.Id;
        iiNeg.ADvendio__UniqueKey__c					= 'rtz';//ii.ADvendio__UniqueKey__c + '|tmp|';
        insert iiNeg;
				
		Test.StopTest();
		cls.filterMediaCampaign.ADvendio__Close_Date__c	= today;
		cls.changeProcessRunningDate();
		cls.doSearch();
		
		system.assertEquals(1, cls.allMediaCampaigns.size());
		
		cls.runProcess();
	}

	@isTest
	public static void testFilterTotal()  {
		Date today	= Date.newInstance(System.today().year(), System.today().month(), 15);
		
		SomDig_Mediagattungssegment__c mgs			= cls_P7S1_TestData.createTestMediagattungsSegment(true);
				
		ADvendio__MediaCampaign__c mc		= cls_P7S1_TestData.createTestMediaCampaign(true, null, null);
   		ADvendio__Campaign_Item__c ci		= cls_P7S1_TestData.createTestCampaignItem(false, mc, null);
        insert new List<ADvendio__Campaign_Item__c>{ci};
		
        ADvendio__Invoice__c i				= cls_P7S1_TestData.createTestInvoice(false, mc);
		i.ADvendio__Status__c				= 'Invoiced';
		i.ADvendio__PaymentInterval__c		= 'total account (one Invoice)';
        i.ADvendio__PaymentStart__c			= 'before / during Billingperiod';
        i.ADvendio__AccountingDate__c		= today.toStartOfMonth();
        i.ADvendio__BillingPeriodEndDate__c	= today.addDays(90);
		insert i;
        
		ADvendio__InvoiceItem__c ii			= cls_P7S1_TestData.createTestInvoiceItem(false, i , ci);
		ii.ADvendio__Salesprice__c			= 300;
		ii.ADvendio__BookedQuantity__c		= 1000;
		ii.ADvendio__BillingCategory__c		= 'CPM';
        ii.ADvendio__LinearDistribution__c	= true;
		ii.ADvendio__FromDate__c			= today;
		ii.ADvendio__UntilDate__c			= today.addDays(90);
		ii.ADvendio__InvoiceItemStartDate__c = today;
		ii.ADvendio__InvoiceItemEndDate__c	= today.addDays(90);
		ii.SomDig_Adservertyp__c			= 'DFP';
		ii.SomDig_Mediagattungs_Segement_Name__c = mgs.Name;
		insert ii;

		Test.StartTest();
		SomDig_Buchungssatz_EaStart cls = new SomDig_Buchungssatz_EaStart();
		cls.filterMediaCampaign.ADvendio__Close_Date__c	= today;
		cls.changeProcessRunningDate();
		cls.doSearch();
		
		system.assertEquals(1, cls.allMediaCampaigns.size());
		cls.toggleSelection();

		SomDig_PRAP__c prap	= new SomDig_PRAP__c();
		prap.SomDig_Status__C	= 'Aufgelöst';
		prap.SomDig_Rechnungsposition__c	= ii.Id;
		prap.SomDig_AbgerechneteErloese__c	= 10;
		prap.SomDig_AbzugrenzendeErloese__c	= 10;
		insert prap;

		cls = new SomDig_Buchungssatz_EaStart();
		cls.filterMediaCampaign.ADvendio__Close_Date__c	= today;
		cls.changeProcessRunningDate();
		cls.doSearch();
		
		system.assertEquals(0, cls.allMediaCampaigns.size());
	}
}