src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountVisibility__c</fullName>
        <description>Used for sharing, depends on visibility state
100 = visible (not invalid, not deleted)
50 = invalid (not deleted)
0 = deleted</description>
        <inlineHelpText>Used for sharing, depends on visibility state
100 = visible (not invalid, not deleted)
50 = invalid (not deleted)
0 = deleted</inlineHelpText>
        <label>Account Visibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomTv_CleanUp_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account-Bereinigung 04/2015: soll gelöscht werden (Vorschlag)</description>
        <inlineHelpText>Account-Bereinigung 04/2015: soll gelöscht werden (Vorschlag)</inlineHelpText>
        <label>soll gelöscht werden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ungueltiger_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Dieser Account darf für Angebote und Aufträge nicht mehr verwendet werden - es handelt sich um eine Dublette/Fehleingabe oder die Firma gibt es so nicht.</description>
        <inlineHelpText>This account shall not longer be used  if it is a duplicate, contains incorrect data or the company does not longer exits. To enable or disable, please follow the required approval process</inlineHelpText>
        <label>ungültiger Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>P7S1_AccountVisibility__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for sharing, depends on visibility state 0 = visible (not invalid, not deleted) 50 = invalid (not deleted) 100 = deleted</description>
        <inlineHelpText>Used for sharing, depends on visibility state 0 = visible (not invalid, not deleted) 50 = invalid (not deleted) 100 = deleted</inlineHelpText>
        <label>Account Visibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/P7S1_Account_Visibility_Test.cls
@isTest
public class P7S1_Account_Visibility_Test{

    
    public static testMethod void testAccountVisibility(){
    
        // Test insert, P7S1_AccountVisibility__c must be 0
        Account objAccount = cls_P7S1_TestData.createTestAccount(false);
        objAccount.SomTv_CleanUp_Delete__c = true;
        insert objAccount;
        
        
        objAccount = [SELECT P7S1_AccountVisibility__c FROM Account WHERE ID = :objAccount.ID];
        System.assertEquals(objAccount.P7S1_AccountVisibility__c, 0);
        
        
        
        // Insert Contact
        Contact objContact = cls_P7S1_TestData.createTestContact(true, objAccount);    
        
        
        
        // Change value on Account, P7S1_AccountVisibility__c must be 50 on Account and Contact
        objAccount.SomTv_CleanUp_Delete__c = false;
        objAccount.ungueltiger_Account__c = true;
        update objAccount;
        
        
        objAccount = [SELECT P7S1_AccountVisibility__c FROM Account WHERE ID = :objAccount.ID];
        objContact = [SELECT P7S1_AccountVisibility__c FROM Contact WHERE ID = :objContact.ID];        
        System.assertEquals(objAccount.P7S1_AccountVisibility__c, 50);        
        System.assertEquals(objContact.P7S1_AccountVisibility__c, 50);                
        
        
        
        // Test for 100 value
        objAccount.ungueltiger_Account__c = false;
        update objAccount;
        
        
        objAccount = [SELECT P7S1_AccountVisibility__c FROM Account WHERE ID = :objAccount.ID];
        objContact = [SELECT P7S1_AccountVisibility__c FROM Contact WHERE ID = :objContact.ID];        
        System.assertEquals(objAccount.P7S1_AccountVisibility__c, 100);        
        System.assertEquals(objContact.P7S1_AccountVisibility__c, 100);                        
    }
}