src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ven_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Es wird der Account markiert der Customer von Seven Ventures ist.</description>
        <inlineHelpText>Es wird der Account markiert der Customer von Seven Ventures ist.</inlineHelpText>
        <label>Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Target__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account, zu dem keine abgeschlossene Opportunity von Seven Ventures besteht.</description>
        <inlineHelpText>Account, zu dem keine abgeschlossene Opportunity von Seven Ventures besteht.</inlineHelpText>
        <label>Target</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ven_Key_Performance_Indicator__c.object
<CustomObject>
    <description>Liste aller KPIs genutzt durch SevenVentures</description>
    <label>Key Performance Indicator</label>
    <nameField>
        <label>Key Performance Indicator-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Performance Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ven_KeyPerformanceIndicatorBlock__c.object
<CustomObject>
    <fields>
        <fullName>Ven_FullYearView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Full Year View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Last6MonthsView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Last 6 months View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_MonthlyView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monthly View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_YearToDateView__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year-to-Date View</label>
        <type>Checkbox</type>
    </fields>
    <label>Key Performance Indicator Block</label>
    <nameField>
        <label>KPI Block</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Performance Indicator Blocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ven_KeyPerformanceIndicatorTemplate__c.object
<CustomObject>
    <description>Key Performance Indicator entries</description>
    <label>Key Performance Indicator Template</label>
    <nameField>
        <label>KPI Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Performance Indicator Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Ven_KPI_ChooseTemplate_Test.cls
@isTest
private class Ven_KPI_ChooseTemplate_Test {

    static testMethod void testVenKPIChooseTemplate() {
        Account testAccount = cls_P7S1_TestData.createTestAccount(false);
        testAccount.Name = 'Test Account';
        testAccount.Ven_Target__c = true;
        testAccount.Ven_Customer__c = false;
        testAccount.Phone = '123456789-1';
        testAccount.Fax = '123456789-0';
        testAccount.Website = 'www.testWebsite.com';
        insert testAccount;

        Opportunity testOpp = cls_P7S1_TestData.createTestOpportunity(false, testAccount);
        testOpp.Name = 'Test Opp';
        testOpp.StageName = 'Finished';
        testOpp.CloseDate = Date.today().addDays(7);
        insert testOpp;

        Ven_KeyPerformanceIndicatorBlock__c testKPIBlock = cls_P7S1_TestData.createTestKPIBlock(true);

        Ven_Key_Performance_Indicator__c testKPI = cls_P7S1_TestData.createTestKPI(true);
        Ven_Key_Performance_Indicator__c testKPI2 = cls_P7S1_TestData.createTestKPI(true);

        Test.startTest();

        Test.setCurrentPage(new PageReference('/apex/Ven_KPI_ChooseTemplate?oppid='+testOpp.Id));

        Ven_KPI_ChooseTemplate venChooseKPITemplateController = new Ven_KPI_ChooseTemplate(new ApexPages.StandardController(new Ven_KeyPerformanceIndicatorTemplate__c()));
        venChooseKPITemplateController.actionNewKPITemplate();
        venChooseKPITemplateController.backToKPITemplatePB();
        venChooseKPITemplateController.actionNewKPITemplate();
        venChooseKPITemplateController.newKPITemplate.Name = 'Test Template 2';
        venChooseKPITemplateController.actionNewKPIBlock();
        venChooseKPITemplateController.getCurrentResultSizeFrom();
        venChooseKPITemplateController.getCurrentResultSizeTo();
        venChooseKPITemplateController.getPageNumberSize();
        venChooseKPITemplateController.newKPIBlock.Name = 'Test Block 2';
        venChooseKPITemplateController.newKPIBlock.Ven_MonthlyView__c = true;
        venChooseKPITemplateController.newKPIBlock.Ven_YearToDateView__c = true;
        venChooseKPITemplateController.newKPIBlock.Ven_FullYearView__c = true;
        venChooseKPITemplateController.newKPIBlock.Ven_Last6MonthsView__c = true;
        venChooseKPITemplateController.inputSelectAllChecked = true;
        venChooseKPITemplateController.toggleCheckboxes();
        venChooseKPITemplateController.pageSize = '1';
        venChooseKPITemplateController.setPageSize();
        venChooseKPITemplateController.next();
        venChooseKPITemplateController.previous();
        venChooseKPITemplateController.last();
        venChooseKPITemplateController.first();
        venChooseKPITemplateController.saveNewKPIBlock();
        venChooseKPITemplateController.actionNewKPIBlock();
        venChooseKPITemplateController.backToNewKPITemplatePB();
        venChooseKPITemplateController.kpiteInputHelper.Ven_KeyPerformanceIndicatorBlock__c = testKPIBlock.Id;
        venChooseKPITemplateController.actionAddToKPITemplate();
        venChooseKPITemplateController.kpiBlockIdToRemove = String.valueOf(testKPIBlock.Id);
        venChooseKPITemplateController.actionRemoveKPIBlock();
        venChooseKPITemplateController.saveNewKPITemplate();
        venChooseKPITemplateController.oppInputHelper.CloseDate = system.today();
        venChooseKPITemplateController.openStrategicReport();

        Test.stopTest();
    }

}