src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This reference displays the ad spec to which this price is assigned.</description>
        <inlineHelpText>This reference displays the ad spec to which this price is assigned.</inlineHelpText>
        <label>Ad Spec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdKeyValues__c</fullName>
        <description>This field is filled automatically with the key value string generated by the entered criteria.</description>
        <inlineHelpText>This field is filled automatically with the key value string generated by the entered criteria.</inlineHelpText>
        <label>AdKeyValues</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This formula displays the corresponding ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp;  ADvendio__Ad_Price__r.ADvendio__Ad_Spec__c  , ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.Name)</formula>
        <inlineHelpText>This formula displays the corresponding ad spec.</inlineHelpText>
        <label>Ad Spec</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierungName__c</fullName>
        <description>MGD- Name für RollUps, Reports etc. Info kommt in diesem Fall aus dem Werbemittel, da Objektverweis bis hin zum WMSegment über das Limit von 15 reicht. Siehe auch KV 2551.</description>
        <formula>ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.SomDig_MediagattungsDifferenzierung__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>MGD-Name für RollUps, Reports etc. Info kommt automatisch via Werbemittel aus der Werbeform</inlineHelpText>
        <label>Mediagattungs-Differenzierung Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Multiscreen__c</fullName>
        <description>Kennzeichnet eine Multiscreen Belegungseinheit.</description>
        <formula>ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Multiscreen__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Kennzeichnet eine Multiscreen Belegungseinheit.</inlineHelpText>
        <label>Multiscreen</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Key__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_TargetingProvider__c</fullName>
        <description>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</description>
        <inlineHelpText>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</inlineHelpText>
        <label>Targeting Provider</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATV_PBT</fullName>
                </value>
                <value>
                    <fullName>Autosites</fullName>
                </value>
                <value>
                    <fullName>Diverse Kriterien</fullName>
                </value>
                <value>
                    <fullName>Gesundheit.de</fullName>
                </value>
                <value>
                    <fullName>nugg.ad</fullName>
                </value>
                <value>
                    <fullName>nugg.ad InApp</fullName>
                </value>
                <value>
                    <fullName>Rotationsausschluss</fullName>
                </value>
                <value>
                    <fullName>SmartGeo</fullName>
                </value>
                <value>
                    <fullName>Vereinssites</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
                <value>
                    <fullName>wetter.com CTV</fullName>
                </value>
                <value>
                    <fullName>ZG S71 Paket</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Key</label>
    <nameField>
        <label>Key Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Keys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__KeyLine__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Key Lines</relationshipLabel>
        <relationshipName>KeyLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Line</label>
    <nameField>
        <label>Key Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__KeyValue__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__KeyLine__c</fullName>
        <label>Key Line</label>
        <referenceTo>ADvendio__KeyLine__c</referenceTo>
        <relationshipLabel>Key Values</relationshipLabel>
        <relationshipName>KeyValues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key</label>
        <referenceTo>ADvendio__Key__c</referenceTo>
        <relationshipLabel>Key Values</relationshipLabel>
        <relationshipName>Key_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>equal to</fullName>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Values__c</fullName>
        <label>Values</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Key Value</label>
    <nameField>
        <label>Key Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_AutoPopulationKv.cls
public with sharing class Adv_CampaignItem_AutoPopulationKv {
    // before update, remove Behavioural Targeting=0 from ADvendio__AdKeyValues__c
    public static void removeBt0(Map<Id, ADvendio__Campaign_Item__c> triggerNewMap, Map<Id, ADvendio__Campaign_Item__c> triggerOldMap) {
        Set<Id> changedItemIds = new Set<Id>();
        for (Id id : triggerNewMap.keySet()) {
            if (triggerNewMap.get(id).ADvendio__AdKeyValues__c != triggerOldMap.get(id).ADvendio__AdKeyValues__c) {
                changedItemIds.add(id);
            }
        }
        for (Id id : changedItemIds) {
            triggerNewMap.get(id).ADvendio__AdKeyValues__c = removeBt0String(triggerNewMap.get(id).ADvendio__AdKeyValues__c);
        }
    }
    
    // before insert, remove Behavioural Targeting=0 from ADvendio__AdKeyValues__c
    public static void removeBt0(List<ADvendio__Campaign_Item__c> triggerNew) {
        for (ADvendio__Campaign_Item__c ci : triggerNew) {
            ci.ADvendio__AdKeyValues__c = removeBt0String(ci.ADvendio__AdKeyValues__c);
        }
    }
    
    // remove Behavioural Targeting=0 and operators from a key value string.
    private static String removeBt0String(String kvString) {
        if (kvString != null) {
            return kvString.replace(' OR ((Behavioural Targeting=0))','')
                            .replace('((Behavioural Targeting=0)) OR ','')
                            .replace(' AND (Behavioural Targeting=0)','')
                            .replace('(Behavioural Targeting=0) AND ','')
                            .replace('((Behavioural Targeting=0))','');
        } else {
            return null;
        }
    }
    
    /** Salesforce id of the key named "Behavioural Targeting"*/
    private static String btKeyId {
	    get {
	    	if (btKeyId == null) {
	    		List<ADvendio__Key__c> btKeys = [SELECT Id FROM ADvendio__Key__c WHERE Name='Behavioural Targeting'];
	    		if (btKeys.size() == 1) {
	    			btKeyId = btKeys[0].Id;
	    		}
	    	}
	    	return btKeyId;
	    }
	    set;
    }
    
    /** Add a keyline with Behavioural Targeting=0 if there is one key with SomDig_TargetingProvider__c=nugg.ad*/
    public static void addBt0KeyLine(List<ADvendio__KeyValue__c> triggerNew) {
    	if (btKeyId != null) {
    		// collect data
    		Set<Id> affectedCis = new Set<Id>();
    		for (ADvendio__KeyValue__c kv : [SELECT ADvendio__Key__c, ADvendio__KeyLine__r.ADvendio__CampaignItem__c 
    										FROM ADvendio__KeyValue__c 
    										WHERE Id IN :triggerNew 
    												AND ADvendio__KeyLine__r.ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.SomDig_Multiscreen__c = true
    												AND ADvendio__KeyLine__r.ADvendio__CampaignItem__r.SomDig_MediagattungsDifferenzierungName__c = 'InStream/Video']) {
   				affectedCis.add(kv.ADvendio__KeyLine__r.ADvendio__CampaignItem__c);
    		}
    		// check if Behavioural Targeting=0 is required
	    	Set<Id> ciIdsWithNugAdd = new Set<Id>();
	    	Set<Id> ciIdsWithBt0 = new Set<Id>();
	    	for (ADvendio__KeyValue__c kv : [SELECT Id, ADvendio__Values__c, ADvendio__Key__r.Name, ADvendio__Key__r.SomDig_TargetingProvider__c, 
	    											ADvendio__KeyLine__r.ADvendio__CampaignItem__c, 
	    											ADvendio__KeyLine__r.ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.SomDig_Multiscreen__c 
	    									FROM ADvendio__KeyValue__c 
	    									WHERE ADvendio__KeyLine__r.ADvendio__CampaignItem__c IN :affectedCis]) {
	    		if (kv.ADvendio__Key__r.SomDig_TargetingProvider__c != null && kv.ADvendio__Key__r.SomDig_TargetingProvider__c.contains('nugg.ad')) {
	    			ciIdsWithNugAdd.add(kv.ADvendio__KeyLine__r.ADvendio__CampaignItem__c);
	    		}
	    		if (kv.ADvendio__Key__c == btKeyId && kv.ADvendio__Values__c.startsWith('0')) {
	    			ciIdsWithBt0.add(kv.ADvendio__KeyLine__r.ADvendio__CampaignItem__c);
	    		}
	    	}
	    	
	    	// check for wrong Behavioural Targeting=0 keylines
	    	for (Id ciId : ciIdsWithBt0) {
	    		if (!ciIdsWithNugAdd.contains(ciId)) {
	    			throw new AutoPopulationKeyValuesException('Behavioural Targeting=0 Key Values sind nur in Kombination mit nugg.ad Keys erlaubt. Bitte entfernen Sie Behavioural Targeting=0!');
	    		}
	    	}
	    	
	    	// add key line
	    	List<ADvendio__KeyLine__c> newKeyLines = new List<ADvendio__KeyLine__c>();
	    	for (Id ciId : ciIdsWithNugAdd) {
	    		if (!ciIdsWithBt0.contains(ciId)) {
	    			newKeyLines.add(new ADvendio__KeyLine__c(ADvendio__CampaignItem__c = ciId));
	    		}
	    	}
	    	insert newKeyLines;
	    	
	    	// add key Value
	    	List<ADvendio__KeyValue__c> newKeyValues = new List<ADvendio__KeyValue__c>();
	    	for (ADvendio__KeyLine__c keyLine : newKeyLines) {
	    		newKeyValues.add(new ADvendio__KeyValue__c(ADvendio__KeyLine__c = keyLine.Id, ADvendio__Key__c = btKeyId, ADvendio__Values__c = '0', ADvendio__Operator__c = 'equal to'));
	    	}
	    	insert newKeyValues;
    	} else {
    		if (ApexPages.currentPage() != null) {
    			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, 'Es wurde kein Key mit dem Namen "Behavioural Targeting" gefunden'));
    		}
    	}
    }

	public class AutoPopulationKeyValuesException extends Exception {}
}