src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the ad type assigned to this ad spec.</description>
        <inlineHelpText>This field displays the ad type assigned to this ad spec.</inlineHelpText>
        <label>Ad Type</label>
        <referenceTo>ADvendio__Ad_Type__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Ad_Specs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Type__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter the ad server login to be used with this ad type.</description>
        <inlineHelpText>Enter the ad server login to be used with this ad type.</inlineHelpText>
        <label>AdServer Login</label>
        <referenceTo>ADvendio__AdServer_Logins__c</referenceTo>
        <relationshipLabel>Ad Type</relationshipLabel>
        <relationshipName>Ad_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Type</label>
    <nameField>
        <label>Ad Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__LinearDistribution__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Linear Distribution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__LinearDistribution__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This Checkbox defines, if the amount is distributed linear or not. This is used for fix price amounts.</description>
        <inlineHelpText>This Checkbox defines, if the amount is distributed linear or not. This is used for fix price amounts.</inlineHelpText>
        <label>Linear Distribution</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Zahlungsbedingung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Nimmt die möglichen Zahlungsbedingungen auf um die in der Medienkampagne gewählten Zahlungsbedingungen korrekt an SAP übergeben zu können. 
Erfasst werden Prozentangaben Skonto, Zahlungsbedingungstext, SAP-Code (Bezeichner)</description>
        <inlineHelpText>Nimmt die möglichen Zahlungsbedingungen auf um die in der Medienkampagne gewählten Zahlungsbedingungen korrekt an SAP übergeben zu können. 
Erfasst werden Prozentangaben Skonto, Zahlungsbedingungstext, SAP-Code (Bezeichner)</inlineHelpText>
        <label>Zahlungsbedingung</label>
        <referenceTo>SomDig_Zahlungsbedingung__c</referenceTo>
        <relationshipLabel>Mediakampagnen</relationshipLabel>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Campaign_Item__c</fullName>
        <description>The connection to the campaign item will be assigned automatically when a new campaign item is created.</description>
        <inlineHelpText>The connection to the campaign item will be assigned automatically when a new campaign item is created.</inlineHelpText>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules_NEW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{0}</displayFormat>
        <label>Revenue Schedule No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_InvoiceItem_DeliveryDataImport_Test.cls
@isTest
private with sharing class Adv_InvoiceItem_DeliveryDataImport_Test {

    static testMethod void testDeliveryDataImport() {
        // A Zahlungsbedingung__c
        SomDig_Zahlungsbedingung__c zb1 = cls_P7S1_TestData.createTestZahlungsbedingung(true);

        // An Account
        Account acc1 = cls_P7S1_TestData.createTestAccount(true);

        // A Pricelist
        ADvendio__Pricelist__c pl1 = cls_P7S1_TestData.createTestPricelist(true, null);

        // An AdServerLogin
        RecordType rt = [Select Id From RecordType where SobjectType = 'ADvendio__AdServer_Logins__c' and DeveloperName = 'DFP'];
        ADvendio__AdServer_Logins__c login1 = cls_P7S1_TestData.createTestAdServerLogin(true, rt);

        // An AdType
        rt = [Select Id From RecordType where SobjectType = 'ADvendio__Ad_Type__c' and DeveloperName = 'DFP'];
        ADvendio__Ad_Type__c adtype1 = cls_P7S1_TestData.createTestAdType(false);
        adtype1.ADvendio__AdServer_Login__c=login1.Id;
        adtype1.RecordTypeId=rt.Id;
        insert adtype1;

        // An AdSpec
        ADvendio__Ad_Specs__c spec1 = cls_P7S1_TestData.createTestAdSpec(true, adtype1);

        // An AdPrice
        ADvendio__Ad_price__c price1 = cls_P7S1_TestData.createTestAdPrice(false, spec1, pl1);
        price1.ADvendio__Billing_Category__c='CPM';
        insert price1;

        // A MediaCampaign
        ADvendio__MediaCampaign__c mc1 = cls_P7S1_TestData.createTestMediaCampaign(false, acc1, pl1);
        mc1.ADvendio__Stage__c='Booked';
        mc1.ADvendio__BillMe__c=true;
        insert mc1;

        // A CampaignItem
        ADvendio__Campaign_Item__c ci1 = cls_P7S1_TestData.createTestCampaignItem(false, mc1, price1);
        ci1.ADvendio__Billing_category__c='CPM';
        ci1.ADvendio__LinearDistribution__c=false;
        ci1.ADvendio__from_Date__c=System.today();
        ci1.ADvendio__until_Date__c=System.today();
        insert ci1;

        // Should have only one RS, because start and end-date of CampaignItem is same.
        List<ADvendio__Revenue_Schedule__c> rss = [SELECT Id, ADvendio__InvoiceQuantity__c FROM ADvendio__Revenue_Schedule__c WHERE ADvendio__Campaign_Item__c = :ci1.Id];
        System.assertEquals(1, rss.size());

        for (ADvendio__Revenue_Schedule__c rs : rss) {
            rs.ADvendio__Delivered_AIs__c = 100;
        }
        update rss;

        // Create the pre invoice
        ADvendio__Invoice__c invoice1 = cls_P7S1_TestData.createTestInvoice(false, mc1);
        invoice1.ADvendio__Status__c='Draft';
        insert invoice1;

        ADvendio__InvoiceItem__c invoiceItem1 = cls_P7S1_TestData.createTestInvoiceItem(false, invoice1, ci1);
        invoiceItem1.ADvendio__Salesprice__c = ci1.ADvendio__Sales_Price__c;
        invoiceItem1.ADvendio__BookedQuantity__c = 1;
        invoiceItem1.ADvendio__FromDate__c = ci1.ADvendio__from_Date__c;
        invoiceItem1.ADvendio__UntilDate__c = ci1.ADvendio__until_Date__c;
        insert invoiceItem1;

        Test.startTest();

        //
        // Now test the class.
        //
        Adv_InvoiceItem_DeliveryDataImport ddi = new Adv_InvoiceItem_DeliveryDataImport();
        ddi.setRecordIds(null);
        ddi.addRecordId(invoiceItem1.Id);

        List<ADvendio__InvoiceItem__c> invoiceItems = [SELECT Id, ADvendio__CampaignItem__c, ADvendio__InvoiceItemStartDate__c, ADvendio__InvoiceItemEndDate__c, ADvendio__QuantityDelivered__c FROM ADvendio__InvoiceItem__c WHERE ADvendio__CampaignItem__c = :ci1.Id];
        ddi.execute(null, invoiceItems);

        // Verify
        invoiceItems = [SELECT Id, ADvendio__QuantityDelivered__c FROM ADvendio__InvoiceItem__c WHERE ADvendio__CampaignItem__c = :ci1.Id];

        // Should have only one invoiceItem, and ADvendio__QuantityDelivered__c is set correctly.
        System.assertEquals(1, invoiceItems.size());
        System.assertEquals(100, invoiceItems[0].ADvendio__QuantityDelivered__c);

        Test.stopTest();
    }

    static testMethod void testDeliveryDataImportBatchSchedule() {
        Test.startTest();

        Adv_InvoiceItem_DeliveryDataImport ddi = new Adv_InvoiceItem_DeliveryDataImport();
        ddi.addRecordId(null);

        Database.executeBatch(ddi, 1);

        String sch = '0 0 23 * * ?';

        System.schedule('Test DeliveryDataImport', sch, ddi);

        Test.stopTest();
    }

}