src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AccountingDate__c</fullName>
        <label>Accounting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoiceType__c</fullName>
        <description>Depending on the type (invoice, credit note, credit note cancellation, cancellation) invoices are treated in a different way.</description>
        <inlineHelpText>Ist die Rechnung vom Rechnungs-Typ her eine Rechnung oder aber eine Aufhebung bzw. Stornierung zu einer vorher erstellten und existierenden Rechnung (Rechnungsanpassung).</inlineHelpText>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Credit Note</fullName>
                </value>
                <value>
                    <fullName>Credit Note Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__InvoicedAmountNet2__c</fullName>
        <label>Invoiced Amount N2</label>
        <summarizedField>ADvendio__InvoiceItem__c.ADvendio__InvoicedAmountNet2__c</summarizedField>
        <summaryFilterItems>
            <field>ADvendio__InvoiceItem__c.ADvendio__ItemRecordType__c</field>
            <operation>notEqual</operation>
            <value>Packet</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__InvoiceItem__c.ADvendio__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <inlineHelpText>Entwurf: RG-Vorschlag welche freigegeben werden muss
Freigabe: RG-Vorschlag wurde freigegeben und kann im Renchnungslauf
Fakturiert: Rechungslauf erfolgte, aus RG-Vorschlag wurde finale Rechnung
Storno: Rechnung wurde durch neue RG-Storno aufgehoben</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_AbgerechneterMN2__c</fullName>
        <label>Abgerechneter MN2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_SumInvoices.cls
global class Adv_MediaCampaign_SumInvoices implements Database.Batchable<sObject>, Schedulable {

	private static final String DEFAULT_SOQL = 'SELECT ADvendio__MediaCampaign__c FROM ADvendio__Invoice__c WHERE LastModifiedDate = LAST_N_DAYS:3 AND ADvendio__AccountingDate__c >= LAST_YEAR';
	private String soql;

	public Adv_MediaCampaign_SumInvoices() {
		soql = DEFAULT_SOQL;
	}

	public Adv_MediaCampaign_SumInvoices(String query) {
		soql = query;
	}

	global void execute(SchedulableContext SC) {	
		Database.executeBatch(this);
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		Set<ID> setMediaCampaignIDs = new Set<ID>();
		for(ADvendio__Invoice__c objInvoice : Database.query(soql)) {
			setMediaCampaignIDs.add(objInvoice.ADvendio__MediaCampaign__c);
		}
		return Database.getQueryLocator('SELECT Id, (SELECT ADvendio__InvoicedAmountNet2__c, ADvendio__InvoiceType__c, ADvendio__Status__c FROM ADvendio__Invoices__r WHERE ADvendio__Status__c IN (\'Invoiced\', \'Canceled\') OR (ADvendio__Status__c = \'Reviewed\' AND ADvendio__Invoice__c != NULL)) FROM ADvendio__MediaCampaign__c WHERE Id IN :setMediaCampaignIDs');	
	}

   	global void execute(Database.BatchableContext BC, List<ADvendio__MediaCampaign__c> scope) {
		for(ADvendio__MediaCampaign__c objMC : scope) {
			Decimal sumAmountNet2 = 0;
			for(ADvendio__Invoice__c objInvoice : objMC.ADvendio__Invoices__r) {
				sumAmountNet2 = sumAmountNet2 + objInvoice.ADvendio__InvoicedAmountNet2__c;
			}
			objMC.SomDig_AbgerechneterMN2__c = sumAmountNet2;
		}
		update scope;
	}	
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}