src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_DeliveryDataImport_Test.cls
@isTest
public class Adv_CampaignItem_DeliveryDataImport_Test {
	
    @isTest
    private static void testDeliveryDataImport() {
        
        String sessionId	= UserInfo.getSessionId();
        String orgId		= UserInfo.getOrganizationId();
        String sfURL		= Url.getSalesforceBaseUrl().toExternalForm();
        
        ADvendio__MediaCampaign__c mc	= cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c ci	= cls_P7S1_TestData.createTestCampaignItem(false, mc);
        ci.ADvendio__from_Date__c		= Date.newInstance(system.today().year(), 5, 1);
        ci.ADvendio__until_Date__c		= Date.newInstance(system.today().year(), 12, 31);
        insert ci;

        Test.startTest();
        Adv_CampaignItem_DeliveryDataImport.doDeliveryDataImport(mc.Id, ''+ci.Id, sfURL, null, null);
        Test.stopTest();
    }
}