src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_PositionStatus__c</fullName>
        <description>-Inaktiv: Durchgebuchung im AdServer erfolgt, kein Motiv eingebucht.
-bereit: Werbemittel sind im AdServer eingebucht und aktiviert 
-Auslieferung-normal: DFP meldet tatsätzliche AIs und AIist&gt;=AIsollbisheute
-Auslieferung@Risk: DFP meldet tatsätzliche AIs und AIist&lt;AIsollbisheute
-pausiert: Position in AdServer wurde gestoppt/pausiert (DFP meldet &apos;pausiert&apos;)
-beendet - erfüllt: Enddatum in der Vergangenheit, AIs ist &gt;= AIs Soll 
-beendet - unterliefert: Enddatum in der Vergangenheit, AIs ist &lt; AIs Soll
-NonAdServer: Position enthält ein NonAdServer Produkt</description>
        <inlineHelpText>-Inaktiv:durchgebucht,kein Motiv
-bereit:im AdServer aktiviert
-normal:AIist&gt;=AIsollbisheute
-@Risk:AIist&lt;AIsollbisheute
-pausiert:laufender Flight wurde gestoppt
-erfüllt:beendet &amp; AIist&gt;=AIsoll
-unterliefert:beendet &amp; AIist&lt;AIsoll</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
                <value>
                    <fullName>bereit</fullName>
                </value>
                <value>
                    <fullName>An Adserver übermitteln</fullName>
                    <default>true</default>
                    <label>An Adserver übermitteln</label>
                </value>
                <value>
                    <fullName>Ad Status aktualisieren</fullName>
                </value>
                <value>
                    <fullName>Position pausiert</fullName>
                </value>
                <value>
                    <fullName>Position gestoppt</fullName>
                </value>
                <value>
                    <fullName>NonAdserver</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-normal</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-@Risk</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-erfüllt</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-unterliefert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_NightlyUpdate.cls
global with sharing class Adv_CampaignItem_NightlyUpdate implements Database.Batchable<sObject>, Schedulable {

    global final String i_sQuery;

    global Adv_CampaignItem_NightlyUpdate() {
        i_sQuery = 'SELECT Id, SomDig_PositionStatus__c, ADvendio__Media_Campaign__c, ADvendio__until_Date__c, ADvendio__from_Date__c ' +
                   'FROM ADvendio__Campaign_Item__c ' +
                   'WHERE ADvendio__from_Date__c <= TODAY AND ADvendio__until_Date__c >= TODAY ';
    }
    global Adv_CampaignItem_NightlyUpdate(String p_sQuery) {
        i_sQuery = p_sQuery;
    }

    global Database.QueryLocator start(Database.BatchableContext p_BC) {
        return Database.getQueryLocator(i_sQuery);
    }

    /*
        Description:
        The execute method is called for each batch of records passed to the method.
        Use this method to do all required processing for each chunk of data.
        This method takes the following:
        A reference to the Database.BatchableContext object.
        A list of sObjects, such as List<sObject>, or a list of parameterized types.
        If you are using a Database.QueryLocator, the returned list should be used.
    */
    global void execute(Database.BatchableContext BC,List<sObject> p_scope) {
        List<ADvendio__Campaign_Item__c> l_oListUpdateLineItem = new List<ADvendio__Campaign_Item__c>();
        /*      1. type casting from Sobject to Campaign Line Items
         *      2. preapare the List of Campaign Items
         *      3. do the dummy update so its intiate the trigger
         */
        for (sObject sobj:p_scope) {
            ADvendio__Campaign_Item__c l_oLinitem = (ADvendio__Campaign_Item__c)Sobj;
            l_oListUpdateLineItem.add(l_oLinitem);
        }

        if (l_oListUpdateLineItem!=null && l_oListUpdateLineItem.size()>0) update l_oListUpdateLineItem;
    }

    global void finish(Database.BatchableContext p_BC) {
    }

    global void execute(SchedulableContext p_sc) {
        Database.executeBatch(new Adv_CampaignItem_NightlyUpdate(), 5);
    }

}