src/objects/ADvendio__EnhancedVisitReport__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Reference_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>With this reference you can link the visit report to a media campaign.</description>
        <inlineHelpText>With this reference you can link the visit report to a media campaign.</inlineHelpText>
        <label>Reference to</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipName>MediaCampaign</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Report</label>
    <nameField>
        <label>Visit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <inlineHelpText>Entwurf: RG-Vorschlag welche freigegeben werden muss
Freigabe: RG-Vorschlag wurde freigegeben und kann im Renchnungslauf
Fakturiert: Rechungslauf erfolgte, aus RG-Vorschlag wurde finale Rechnung
Storno: Rechnung wurde durch neue RG-Storno aufgehoben</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_MediacampaignLost__c</fullName>
        <formula>ADvendio__MediaCampaign__r.RecordType.Name =&quot;Auftrag&quot;
&amp;&amp;
 ADvendio__MediaCampaign__r.ADvendio__Propability__c =0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Kampagne storniert?</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Campaign_End_Date__c</fullName>
        <description>This date is automatically filled according to the campaign items. The campain&apos;s last day will be displayed.</description>
        <inlineHelpText>This date is automatically filled according to the campaign items. The campain&apos;s last day will be displayed.</inlineHelpText>
        <label>Campaign End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__Campaign_Start_Date__c</fullName>
        <description>This date is automatically filled according to the campaign items. The campain&apos;s first day will be displayed.</description>
        <inlineHelpText>This date is automatically filled according to the campaign items. The campain&apos;s first day will be displayed.</inlineHelpText>
        <label>Campaign Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__Propability__c</fullName>
        <description>The probability will be calculated automatically according to the campaign&apos;s phase.</description>
        <formula>CASE(1, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(5%)&quot;), TEXT(ADvendio__Stage__c)= &quot;First contact&quot;), 1, 0), 0.05, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(10%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Initial Offer (w/o request)&quot;), 1, 0), 0.1, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(20%)&quot;),TEXT(ADvendio__Stage__c)= &quot;Stage 20%&quot;), 1, 0), 0.2, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(25%)&quot;),TEXT(ADvendio__Stage__c)= &quot;Stage 25%&quot;), 1, 0), 0.25, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(30%)&quot;),TEXT(ADvendio__Stage__c)= &quot;Alternative quote&quot;), 1, 0), 0.3, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(40%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Stage 40%&quot;), 1, 0), 0.4, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(50%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Offer on Request&quot;), 1, 0), 0.5, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(60%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Stage 60%&quot;), 1, 0), 0.6, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(70%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Showed interest&quot;), 1, 0), 0.7, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(75%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Stage 75%&quot;), 1, 0), 0.75, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(80%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Positive Feedback (Agency/Advertiser)&quot;), 1, 0), 0.8, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(90%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Stage 90%&quot;), 1, 0), 0.9, IF(OR(CONTAINS(TEXT(ADvendio__Stage__c), &quot;(100%)&quot;), TEXT(ADvendio__Stage__c)= &quot;Booked&quot;, TEXT(ADvendio__Stage__c)= &quot;IO received&quot;), 1, 0), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The probability will be calculated automatically according to the campaign&apos;s phase.</inlineHelpText>
        <label>Probability (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Buchungssatz__c.object
<CustomObject>
    <description>Objekt in dem alle buchungsrelevanten Daten gespeichert werden</description>
    <fields>
        <fullName>SomDig_Rechnung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rechnung</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Buchungssaetze</relationshipLabel>
        <relationshipName>Buchungssaetze</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Buchungssatz</label>
    <nameField>
        <label>Buchungssatz-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buchungssätze</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_Invoice_PreInvoiceDeleteInsert.cls
/**
 * A schedulable job to create pre-invoices for ADvendio__MediaCampaign__c.
 */
global with sharing class Adv_Invoice_PreInvoiceDeleteInsert implements Schedulable {

    /** The default QUERY. */
    private final static String DEFAULT_QUERY = 'SELECT Id FROM ADvendio__MediaCampaign__c WHERE isDeleted = false '
        + 'AND ADvendio__BillMe__c = true AND ADvendio__Propability__c = 100 '
        + 'AND ADvendio__Campaign_End_Date__c != null '
        + 'AND ADvendio__Campaign_Start_Date__c != null '
        + 'AND(ADvendio__Campaign_End_Date__c = LAST_N_DAYS:60 OR ADvendio__Campaign_End_Date__c = NEXT_YEAR '
        + 'OR (ADvendio__Campaign_End_Date__c = THIS_YEAR AND ADvendio__Campaign_End_Date__c >= TODAY) )';

    /** Ids of ADvendio__MediaCampaign__c to force to check. Mainly used for testing. */
    @TestVisible
    private Set<Id> recIds  = null;

    /** 
     * Constructor
     */
    public Adv_Invoice_PreInvoiceDeleteInsert() {
    }

    /**
     * Set the RecordIds to check. Mainly used for testing.
     * @param   recIds  Record-Ids to set.
     */
    public void setRecordIds(Set<Id> recIds) {
        this.recIds = recIds;
    }

    /**
     * Add a RecordId to check. Mainly used for testing.
     * @param   recId   Record-Id to add.
     */
    public void addRecordId(Id recId) {
        if (this.recIds == null) {
            this.recIds = new Set<Id>();
        }
        this.recIds.add(recId);
    }

    /**
     * Start the creating pre-invoice prozess.
     */
    public void createPreInvoice() {
        String query = DEFAULT_QUERY;

        if (recIds != null) {
            recIds.remove(null);
            if (!recIds.isEmpty()) {
                query += ' AND Id IN (';

                for (Id s : recIds) {
                    query += '\'' + s + '\'' + ',';
                }

                query = query.substring(0, query.length()-1);
                query += ')';
            }
        }

        ADvendio.GenerateInvoiceBatch job = new ADvendio.GenerateInvoiceBatch();

        job.query = query;
        job.batchsize = 1;

        Database.executeBatch(job, 1);
    }

    public void deletePreInvoice() {
        Map<Id, ADvendio__Invoice__c> invoicesToDelete;

        // Query the invoices that are qualified to be deleted. Store it in a map to have the IDs easily accesible.
        if(recIds== null || recIds.isEmpty()){
        	invoicesToDelete = new Map<Id, ADvendio__Invoice__c>([SELECT Id FROM ADvendio__Invoice__c 
                                                                            WHERE ADvendio__Status__c = 'Draft' 
                                                                            AND (SomDig_MediacampaignLost__c = TRUE 
                                                                                OR ADvendio__MediaCampaign__r.ADvendio__BillMe__c = FALSE)]);
        }else{
            invoicesToDelete = new Map<Id, ADvendio__Invoice__c>([SELECT Id FROM ADvendio__Invoice__c 
                                                                            WHERE ADvendio__Status__c = 'Draft' 
                                                                            AND (SomDig_MediacampaignLost__c = TRUE 
                                                                                OR ADvendio__MediaCampaign__r.ADvendio__BillMe__c = FALSE)
                                                                            AND ADvendio__MediaCampaign__c IN :recIds]);
        }
        
        // Query the buchungsatz
        List<SomDig_Buchungssatz__c> buchungsatzToDelete = new List<SomDig_Buchungssatz__c>([SELECT Id FROM SomDig_Buchungssatz__c WHERE SomDig_Rechnung__c IN :invoicesToDelete.keySet()]);

    	delete buchungsatzToDelete;
    	delete invoicesToDelete.values();

    }

    /**
     * Schedule excution routine.
     *
     * @param   sc  Context of the schedule job.
     */
    global void execute(SchedulableContext sc) {
    	deletePreInvoice();
        ADvendio.GenerateInvoiceBatch job = new ADvendio.GenerateInvoiceBatch();

        job.query = DEFAULT_QUERY;
        job.batchsize = 1;

        Database.executeBatch(job, 1);
    }
}