src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizingVersion__c</fullName>
        <label>Optimizing Version</label>
        <referenceTo>ADvendio__OptimizingVersion__c</referenceTo>
        <relationshipLabel>Optimizing Changes</relationshipLabel>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__DateOfActivation__c</fullName>
        <description>Shows the date / time when the Optimizing Version was activated.</description>
        <inlineHelpText>Shows the date / time when the Optimizing Version was activated.</inlineHelpText>
        <label>Date Of Activation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SomDig_ActivationStarting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>KV: 1371. Hilfsfeld: Checkbox welche sofort bei Knopfdruck (Activate) gesetzt wird, damit die Optimierungsversion nicht durch einen Trigger gelöscht wird, der Optimierungsversionen löscht, die noch nicht aktiviert sind.</description>
        <label>ActivationStarting</label>
        <type>Checkbox</type>
    </fields>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_DurationChanged.cls
/*
KV: 02506
Called from Trigger
When Duration Changed on Campaign Item delete open Optimizing Versions
*/
public class Adv_CampaignItem_DurationChanged {
    
    public static void deleteOtherOVs(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){
        
        // Check for which campaign Items the duration has been changed
        Set<ID> setChangedCIs = new Set<ID>();
        for(sObject o : lstNewItems){
            ADvendio__Campaign_Item__c objCI = (ADvendio__Campaign_Item__c) o;
            if(objCI.ADvendio__from_Date__c != mapOldItems.get(objCI.Id).get('ADvendio__from_Date__c') || objCI.ADvendio__until_Date__c != mapOldItems.get(objCI.Id).get('ADvendio__until_Date__c'))
                setChangedCIs.add(o.Id);
        }
        
        if (!setChangedCIs.isEmpty()) {
            // Get all Optimizing Changes, from same campaign and other OVs and check if there are campaign items which has been optimized.
            Set<ID> setDelOVIDs = new Set<ID>();
            for(ADvendio__OptimizingChange__c o : [SELECT ADvendio__CampaignItem__c, ADvendio__OptimizingVersion__c FROM ADvendio__OptimizingChange__c WHERE ADvendio__OptimizingVersion__r.ADvendio__DateOfActivation__c = null AND ADvendio__CampaignItem__c IN :setChangedCIs]) {
                setDelOVIDs.add(o.ADvendio__OptimizingVersion__c);
            }
            
            
            if (!setDelOVIDs.isEmpty()) {
                List<ADvendio__OptimizingVersion__c> listOV = new List<ADvendio__OptimizingVersion__c>([SELECT ID FROM ADvendio__OptimizingVersion__c WHERE ID IN :setDelOVIDs AND ADvendio__DateOfActivation__c = null AND SomDig_ActivationStarting__c = false AND IsDeleted = false]);
                if(!listOV.isEmpty()) delete listOV;
            }
        }
        
    }
    
}