src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Parent_AdServer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If there is a superior ad server ID, you can enter its ID here.</description>
        <inlineHelpText>If there is a superior ad server ID, you can enter its ID here.</inlineHelpText>
        <label>Parent AdServer ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Medium zur Übertragung von Werbebotschaften</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Type__c</fullName>
        <description>Choose which type of ad server ID is concerned.</description>
        <inlineHelpText>Choose which type of ad server ID is concerned.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Site</fullName>
                </value>
                <value>
                    <fullName>Zone</fullName>
                </value>
                <value>
                    <fullName>Zone Group</fullName>
                </value>
                <value>
                    <fullName>Content Category</fullName>
                </value>
                <value>
                    <fullName>Content Unit</fullName>
                </value>
                <value>
                    <fullName>Content Unit Group</fullName>
                </value>
                <value>
                    <fullName>Page</fullName>
                </value>
                <value>
                    <fullName>Page Group</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Format</fullName>
                </value>
                <value>
                    <fullName>Placement</fullName>
                </value>
                <value>
                    <fullName>Ad Unit</fullName>
                </value>
                <value>
                    <fullName>Key</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This formula displays the corresponding ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp;  ADvendio__Ad_Price__r.ADvendio__Ad_Spec__c  , ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.Name)</formula>
        <inlineHelpText>This formula displays the corresponding ad spec.</inlineHelpText>
        <label>Ad Spec</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__DeliveryData__c.object
<CustomObject>
    <description>Detailed delivery data.</description>
    <fields>
        <fullName>ADvendio__AdServerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AdServer-ID, to which the delivery data refer.</description>
        <inlineHelpText>AdServer-ID, to which the delivery data refer.</inlineHelpText>
        <label>Ad Server ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>Delivery Data</relationshipLabel>
        <relationshipName>DeliveryData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <description>Campaign-Item, to which the delivery data refer.</description>
        <inlineHelpText>Campaign-Item, to which the delivery data refer.</inlineHelpText>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Delivery Data</relationshipLabel>
        <relationshipName>DeliveryData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__DeliveredImpressions__c</fullName>
        <description>This field will be automatically filled by a script. It displays the delivered impressions of the assigned campaign item.</description>
        <label>Delivered Impressions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Type__c</fullName>
        <description>Type of the delivery data refer.</description>
        <inlineHelpText>Type of the delivery data refer.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_YearMonth__c</fullName>
        <description>Indiziertes Feld, zur Optimierung zeitbasierter Filter-Abfragen</description>
        <externalId>true</externalId>
        <inlineHelpText>Indiziertes Feld, zur Optimierung zeitbasierter Filter-Abfragen</inlineHelpText>
        <label>YearMonth</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Data</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Delivery Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <description>Enter the site assigned to this placement.</description>
        <inlineHelpText>Enter the site assigned to this placement.</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SomDig_AdServerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AdServer ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_AntizipationsVS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Antizipationsverteilungsschlüssel</label>
        <referenceTo>SomDig_AntizipationsVS__c</referenceTo>
        <relationshipLabel>Belegungseinheiten</relationshipLabel>
        <relationshipName>SomDig_Belegungseinheiten</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lcm_Log__c.object
<CustomObject>
    <description>hier werden interne Logs (z.B. aus Klassen) abgelegt</description>
    <fields>
        <fullName>Lcm_Info_1__c</fullName>
        <label>Lcm Info 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lcm_Info_2__c</fullName>
        <label>Lcm Info 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lcm_Info_3__c</fullName>
        <label>Lcm Info 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lcm_Info_4__c</fullName>
        <label>Lcm Info 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lcm_Info_5__c</fullName>
        <label>Info 5 lang</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lcm_Source__c</fullName>
        <label>Lcm Source</label>
        <type>TextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000000}</displayFormat>
        <label>Log-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Verteilungsschluessel__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_AdServerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gebe hier die AdServerId von Typ &quot;Ad Unit&quot; ein. Bitte in DFP nachprüfen, welche Ad Units zu der Rotation gehören.</description>
        <inlineHelpText>Gebe hier die AdServerId von Typ &quot;Ad Unit&quot; ein. Bitte in DFP nachprüfen, welche Ad Units zu der Rotation gehören.</inlineHelpText>
        <label>AdServer ID</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>ADvendio__AdServer_ID__c.ADvendio__Type__c</field>
                <operation>equals</operation>
                <value>Ad Unit</value>
            </filterItems>
            <filterItems>
                <field>ADvendio__AdServer_ID__c.ADvendio__Site__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>Verteilungsschlüssel</relationshipLabel>
        <relationshipName>SomDig_Verteilungsschluessel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_AntizipationsVS__c</fullName>
        <label>Antizipationsverteilungsschlüssel</label>
        <referenceTo>SomDig_AntizipationsVS__c</referenceTo>
        <relationshipLabel>Verteilungsschlüssel</relationshipLabel>
        <relationshipName>SomDig_Verteilungsschluessel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SomDig_Prozentsatz__c</fullName>
        <label>Prozentsatz</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Verteilungsschlüssel</label>
    <nameField>
        <displayFormat>VS-{000000}</displayFormat>
        <label>Verteilungsschlüssel-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verteilungsschlüssel</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_AntizipationBatch_Temp.cls
global with sharing class Adv_AntizipationBatch_Temp implements Database.Batchable<SObject>, Schedulable {

    private String strParameter;
    private Boolean bDeleteKeys;
    private Boolean bUseNewQuery;

    public Adv_AntizipationBatch_Temp(String strParam, Boolean deleteKeys, Boolean useNewQuery) {
        strParameter = strParam;
        bDeleteKeys = deleteKeys;
        bUseNewQuery = useNewQuery;
    }

    private static SomDig_AntizipationsVS__c genericAZDistKey {
        get {
            if (genericAZDistKey == null) genericAZDistKey = [SELECT Id FROM SomDig_AntizipationsVS__c WHERE Name = 'Generischer Verteilungsschlüssel Rotation' ORDER BY LastModifiedDate LIMIT 1];
            return genericAZDistKey;
        }
        set;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {

        if(bDeleteKeys) deleteExistingDistributionKeys();

        String query = 'SELECT ADvendio__Site__c, ADvendio__Site__r.Name, SomDig_AntizipationsVS__c FROM ADvendio__Placement__c '+strParameter;
        return Database.getQueryLocator(query);
    }

    private void deleteExistingDistributionKeys() {
        // deletes all existing distribution keys except the standard/generic key.
        List<SomDig_AntizipationsVS__c> AZDistributionKeysToDelete = new List<SomDig_AntizipationsVS__c>([SELECT ID FROM SomDig_AntizipationsVS__c WHERE Name != 'Generischer Verteilungsschlüssel Rotation']);
        delete AZDistributionKeysToDelete;
    }

    global void execute(Database.BatchableContext bc, List<sObject> records) {
        datetime startdt = system.now();

        List<ADvendio__Placement__c> placements = (List<ADvendio__Placement__c>)records;
                insert new Lcm_Log__c(Lcm_Info_1__c=placements[0].Id, Lcm_Info_2__c=startdt.format('yyyy-MM-dd kk:mm:ss.SSS'), Lcm_Info_3__c='', Lcm_Info_4__c='35',Lcm_Info_5__c='Start', Lcm_Source__c='Adv_AntizipationBatch');

        // Store set of placement IDs.
        Set<ID> placementIDs = new Set<ID>();
        for(ADvendio__Placement__c placement : placements)
            placementIDs.add(placement.Id);

        // Get a Map of all delivery data for every placement record.
        Map<Id, List<ADvendio__DeliveryData__c>> placementToDeliveryDataMap = getPlacementToDeliveryDataMap(placementIDs);

        // Initiate AZDistributionKey & DistributionKey maps for later bulk insert.
        Map<Id, SomDig_AntizipationsVS__c> placementToAZDistributionKey = new Map<Id, SomDig_AntizipationsVS__c>();
        Map<Id, List<SomDig_Verteilungsschluessel__c>> placementToDistributionKey = new Map<Id, List<SomDig_Verteilungsschluessel__c>>();
        Map<Id, List<SomDig_Verteilungsschluessel__c>> placementToDistributionKeyWithoutAdServerID = new Map<Id, List<SomDig_Verteilungsschluessel__c>>();

        for(ADvendio__Placement__c placement : placements) {

            // if Werbeträger is NOT SevenOne Network
            if(placement.ADvendio__Site__r.Name != 'SevenOne Network') {

                placementToAZDistributionKey.put(placement.Id, new SomDig_AntizipationsVS__c());
                // these Distribution Keys without AdServerIDs are added to different list, and will get an AdServerIDs later in bulk.
                placementToDistributionKeyWithoutAdServerID.put(placement.Id, new List<SomDig_Verteilungsschluessel__c>{new SomDig_Verteilungsschluessel__c(SomDig_Prozentsatz__c = 100)});


            } else if(placementToDeliveryDataMap.containsKey(placement.Id) && !placementToDeliveryDataMap.get(placement.Id).isEmpty()) {
                // if Werbeträger is SevenOne Network & has delivery data

                // Get all the delivery data(not aggregated) related to this Placement.
                List<ADvendio__DeliveryData__c> deliveryDataList = placementToDeliveryDataMap.get(placement.Id);

                // Aggregate the delivery data
                Map<Id, Decimal> aggregatedMap = aggregateDeliveryData(deliveryDataList);

                // remove <1% to top.
                aggregatedMap = removeLowerPercentage(aggregatedMap);

                // Create Distribution Keys.
                List<SomDig_Verteilungsschluessel__c> distKeysToInsert = new List<SomDig_Verteilungsschluessel__c>();
                Decimal totalAmount = getTotalAmount(aggregatedMap);
                for(ID adServerID : aggregatedMap.keySet()) {
                    Decimal percentage = aggregatedMap.get(adServerId)/totalAmount;
                    distKeysToInsert.add(new SomDig_Verteilungsschluessel__c(SomDig_Prozentsatz__c = percentage*100, SomDig_AdServerId__c = adServerID));
                }

                placementToAZDistributionKey.put(placement.Id, new SomDig_AntizipationsVS__c());
                placementToDistributionKey.put(placement.Id, distKeysToInsert);

            } else { // if it doesn't have delivery data.

                // assign generic az dist key.
                placement.SomDig_AntizipationsVS__c = genericAZDistKey.Id;

            }

        }

        // Insert AZ Dist keys so they get an Id.
        insert placementToAZDistributionKey.values();

        // Fill Distribution Keys with missing adServerId.
        placementToDistributionKey.putAll(fillAdServerIDs(placementToDistributionKeyWithoutAdServerID));

        // Assign AZ Dist Keys IDs to child records(Dist Keys)
        List<SomDig_Verteilungsschluessel__c> distKeysToInsert = new List<SomDig_Verteilungsschluessel__c>();
        for(Id placementId : placementToDistributionKey.keySet()) {
            SomDig_AntizipationsVS__c AZDistKey = placementToAZDistributionKey.get(placementId);
            for(SomDig_Verteilungsschluessel__c distKey : placementToDistributionKey.get(placementId)) {
                distKey.SomDig_AntizipationsVS__c = AZDistKey.Id;
                distKeysToInsert.add(distKey);
            }
        }

        //Insert Dist Keys
        insert distKeysToInsert;

        // Assign AZ Dist Keys to Placements.
        for(ADvendio__Placement__c placement : placements) {
            if(placementToAZDistributionKey.containsKey(placement.Id)) {
                placement.SomDig_AntizipationsVS__c = placementToAZDistributionKey.get(placement.Id).Id;
            }
        }

        update placements;

                insert new Lcm_Log__c(Lcm_Info_1__c=placements[0].Id, Lcm_Info_2__c=startdt.format('yyyy-MM-dd kk:mm:ss.SSS'), Lcm_Info_3__c=system.now().format('yyyy-MM-dd kk:mm:ss.SSS'), Lcm_Info_4__c='120',Lcm_Info_5__c='End', Lcm_Source__c='Adv_AntizipationBatch');
    }

    global void finish(Database.BatchableContext bc){
    }

    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 5);
    }

    /*
    * For placement who are not SevenOne Network, we need to find the 'most parenty' adServerId. Here we query up to 5 levels.
    */
    private Map<Id, List<SomDig_Verteilungsschluessel__c>> fillAdServerIDs(Map<Id, List<SomDig_Verteilungsschluessel__c>> placementToDistributionKeyWithoutAdServerID) {

        Map<Id, Id> SiteToPlacementMap = new Map<Id, Id>();
        for(ADvendio__Placement__c placement : [SELECT ADvendio__Site__c FROM ADvendio__Placement__c WHERE ID IN :placementToDistributionKeyWithoutAdServerID.keySet()])
            SiteToPlacementMap.put(placement.Id, placement.ADvendio__Site__c);

        Map<Id, ADvendio__Site__c> sitesWithValidAdServerID = new Map<Id, ADvendio__Site__c>([SELECT Id, (SELECT ID FROM Advendio__AdServer_IDs__r WHERE ADvendio__Type__c = 'Ad Unit' AND (ADvendio__Parent_AdServer_ID__c = NULL OR ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c = NULL) LIMIT 1) FROM ADvendio__Site__c WHERE ID IN :SiteToPlacementMap.values()]);

        for(ID placementID : placementToDistributionKeyWithoutAdServerID.keySet()) {
            Id siteId = SiteToPlacementMap.get(placementID);
            ADvendio__Site__c site = sitesWithValidAdServerID.get(siteId);
            placementToDistributionKeyWithoutAdServerID.get(placementID)[0].SomDig_AdServerId__c = !site.Advendio__AdServer_IDs__r.isEmpty() ? site.Advendio__AdServer_IDs__r[0].Id : null;
        }

        return placementToDistributionKeyWithoutAdServerID;
    }

    private Map<Id, Decimal> aggregateDeliveryData(List<ADvendio__DeliveryData__c> deliveryDataList) {
        Map<Id, Decimal> aggregatedMap = new Map<Id, Decimal>();

        // fill map with aggregated values.
        for(ADvendio__DeliveryData__c deliveryData : deliveryDataList) {
            if(aggregatedMap.containsKey(deliveryData.ADvendio__AdServerID__c)) {
                aggregatedMap.put(deliveryData.ADvendio__AdServerID__c, aggregatedMap.get(deliveryData.ADvendio__AdServerID__c)+deliveryData.ADvendio__DeliveredImpressions__c);
            } else {
                aggregatedMap.put(deliveryData.ADvendio__AdServerID__c, deliveryData.ADvendio__DeliveredImpressions__c);
            }
        }

        return aggregatedMap;
    }

    private Map<Id, Decimal> removeLowerPercentage(Map<Id, Decimal> aggregatedMap) {
        // store the total amount of ai
        Decimal totalAmount = getTotalAmount(aggregatedMap);

        // Find the keys that hold less than 1%, and reassign them to the one that has most Delivery Data.
        Set<Id> keysToDelete = new Set<Id>();
        for(Id adServerId : aggregatedMap.keySet()) {
            Decimal amount = aggregatedMap.get(adServerId);
            if( (amount/totalAmount)*100 < 1 ) {
                keysToDelete.add(adServerId);
            }
        }

        // Delete keys that hold than 1%
        for(Id idToDelete : keysToDelete) aggregatedMap.remove(idToDelete);

        return aggregatedMap;
    }

    //gets the sum of values (Delivered Impressions)
    private Decimal getTotalAmount(Map<Id, Decimal> aggregatedMap) {
        Decimal totalAmount = 0;
        for(Decimal ai : aggregatedMap.values())
            totalAmount = totalAmount + ai;
        return totalAmount;
    }

    // returns a map of all delivery data for a set of Placements.
    private Map<Id, List<ADvendio__DeliveryData__c>> getPlacementToDeliveryDataMap(Set<Id> placementIdSet) {
        Map<Id, List<ADvendio__DeliveryData__c>> placementToDeliveryData = new Map<Id, List<ADvendio__DeliveryData__c>>();

        Decimal thisYearMonth = Integer.valueOf(getYearMonthForDate(Date.today()));
        Decimal previousYearMonth = Integer.valueOf(getYearMonthForDate(Date.today().addMonths(-1)));
        Integer numberOfRows = 0;

        for(ADvendio__DeliveryData__c dd : (bUseNewQuery ? 
            [SELECT ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__c, ADvendio__AdServerID__c, ADvendio__DeliveredImpressions__c FROM ADvendio__DeliveryData__c WHERE ADvendio__Type__c = 'Monthly' AND ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.Name = 'DFP' AND ADvendio__CampaignItem__r.ADvendio__Rate_Discount_4_Name__c != 'Storno mit Leistungsfluss' AND ADvendio__CampaignItem__r.ADvendio__Rate_Discount_4_Name__c != 'Storno ohne Leistungsfluss' AND (SomDig_YearMonth__c >= :previousYearMonth) AND ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__c IN :placementIdSet]
            : 
            [SELECT ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__c, ADvendio__AdServerID__c, ADvendio__DeliveredImpressions__c FROM ADvendio__DeliveryData__c WHERE ADvendio__Type__c = 'Monthly' AND ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.Name = 'DFP' AND ADvendio__CampaignItem__r.ADvendio__Rate_Discount_4_Name__c != 'Storno mit Leistungsfluss' AND ADvendio__CampaignItem__r.ADvendio__Rate_Discount_4_Name__c != 'Storno ohne Leistungsfluss' AND (ADvendio__Month__c = THIS_MONTH OR ADvendio__Month__c = LAST_MONTH) AND ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__c IN :placementIdSet])) {
            numberOfRows++;
            ID placementId = dd.ADvendio__CampaignItem__r.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__c;

            if(placementToDeliveryData.containsKey(placementId)) {
                placementToDeliveryData.get(placementId).add(dd);
            } else {
                placementToDeliveryData.put(placementId, new List<ADvendio__DeliveryData__c> { dd });
            }
        }

        List<Id> listIDs = new List<Id>();
        listIDs.addAll(placementIdSet);
        insert new Lcm_Log__c(Lcm_Info_1__c=listIDs[0], Lcm_Info_2__c='Rows: '+numberOfRows, Lcm_Info_3__c='', Lcm_Info_4__c='216',Lcm_Info_5__c='getPlacementToDeliveryDataMap()', Lcm_Source__c='Adv_AntizipationBatch');

        return placementToDeliveryData;
    }

    private String getYearMonthForDate(Date dt) {
        String strYear = String.valueOf(dt.year());
        String strMonth = String.valueOf(dt.month());
        if(strMonth.length() == 1) strMonth = '0' + strMonth;
        return strYear + strMonth;
    }

}