src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Sales_Price__c</fullName>
        <description>Enter the sales price for this campaign item.</description>
        <inlineHelpText>Enter the sales price for this campaign item.</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_PositionStatus__c</fullName>
        <description>-Inaktiv: Durchgebuchung im AdServer erfolgt, kein Motiv eingebucht.
-bereit: Werbemittel sind im AdServer eingebucht und aktiviert 
-Auslieferung-normal: DFP meldet tatsätzliche AIs und AIist&gt;=AIsollbisheute
-Auslieferung@Risk: DFP meldet tatsätzliche AIs und AIist&lt;AIsollbisheute
-pausiert: Position in AdServer wurde gestoppt/pausiert (DFP meldet &apos;pausiert&apos;)
-beendet - erfüllt: Enddatum in der Vergangenheit, AIs ist &gt;= AIs Soll 
-beendet - unterliefert: Enddatum in der Vergangenheit, AIs ist &lt; AIs Soll
-NonAdServer: Position enthält ein NonAdServer Produkt</description>
        <inlineHelpText>-Inaktiv:durchgebucht,kein Motiv
-bereit:im AdServer aktiviert
-normal:AIist&gt;=AIsollbisheute
-@Risk:AIist&lt;AIsollbisheute
-pausiert:laufender Flight wurde gestoppt
-erfüllt:beendet &amp; AIist&gt;=AIsoll
-unterliefert:beendet &amp; AIist&lt;AIsoll</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
                <value>
                    <fullName>bereit</fullName>
                </value>
                <value>
                    <fullName>An Adserver übermitteln</fullName>
                    <default>true</default>
                    <label>An Adserver übermitteln</label>
                </value>
                <value>
                    <fullName>Ad Status aktualisieren</fullName>
                </value>
                <value>
                    <fullName>Position pausiert</fullName>
                </value>
                <value>
                    <fullName>Position gestoppt</fullName>
                </value>
                <value>
                    <fullName>NonAdserver</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-normal</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-@Risk</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-erfüllt</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-unterliefert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_StatusPAMCockpit__c</fullName>
        <description>beschreibt die Phase nach dem eine MK gebucht ist, bzw. die ownership von SALES zu PAM gewechselt hat.</description>
        <inlineHelpText>neu: keine LIs angelegt
to do: Mindestens EINE Position steht auf Entwurf, Pausiert, -erfüllt o. -unterliefert
planmässig: ALLE haben den Status Bereit o. Auslieferung
abgeschlossen: ALLE beendet und abgerechnet
NonAdserver: ALLE NonAdServer Produkte</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>neu</fullName>
                </value>
                <value>
                    <fullName>planmässig</fullName>
                </value>
                <value>
                    <fullName>to do</fullName>
                </value>
                <value>
                    <fullName>abgeschlossen</fullName>
                </value>
                <value>
                    <fullName>Non AdServer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_WtAgBeziehung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Statt WT und AG wird die Beziehung hier ausgewählt. Infofelder WT und AG von ADvendio  füllen sich dann automatisch per Trigger (siehe KV 1254)</description>
        <inlineHelpText>Statt WT und AG wird die Beziehung hier ausgewählt. Infofelder WT und AG füllen sich dann automatisch</inlineHelpText>
        <label>WT AG Beziehung</label>
        <referenceTo>SomDig_WtAgBeziehung__c</referenceTo>
        <relationshipLabel>Mediakampagnen</relationshipLabel>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_WtAgBeziehung__c.object
<CustomObject>
    <description>Junction-Objekt um Account-Beziehungen darstellen zu können, an denen Datensätze verknüpft werden wie Prognosen, Umsätze etc. (siehe auch Kundenvorgang 995 für eine detaillierte Beschreibung bzw. Anforderung).</description>
    <label>WT AG Beziehung</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WT AG Beziehungsname</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WT AG Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_NightlyUpdate_Test.cls
@isTest
private class Adv_CampaignItem_NightlyUpdate_Test {

    public static Account l_oAccount;
    public static SomDig_WtAgBeziehung__c l_oWtAgBeziehung;
    public static ADvendio__MediaCampaign__c l_oMediaCampaign;
    public static ADvendio__Ad_Specs__c l_oAdSpecs;
    public static ADvendio__Ad_price__c l_oAdPrice;

    private static void createData() {
        l_oMediaCampaign = cls_P7S1_TestData.createTestMediaCampaign(false);
        l_oMediaCampaign.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Auftrag'].Id;
        //l_oMediaCampaign.SomDig_StatusPAMCockpit__c = 'neu';
        insert l_oMediaCampaign;

        l_oAdPrice = cls_P7S1_TestData.createTestAdPrice(true, null, null);
    }

    static void testCampaignItemStatus(String StatusPAM){
        Test.startTest();

        List <ADvendio__Campaign_Item__c> CampaignItemList = new List <ADvendio__Campaign_Item__c>();
        ADvendio__Campaign_Item__c l_oCampaignItem1 = new ADvendio__Campaign_Item__c();
        l_oCampaignItem1.ADvendio__Media_Campaign__c = l_oMediaCampaign.Id;
        l_oCampaignItem1.ADvendio__Quantity__c = 10000;
        l_oCampaignItem1.ADvendio__from_Date__c = system.today();
        l_oCampaignItem1.ADvendio__until_Date__c = system.today()+2;
        l_oCampaignItem1.ADvendio__Sales_Price__c = 30;
        l_oCampaignItem1.ADvendio__Billing_category__c = 'CPM';
        l_oCampaignItem1.ADvendio__Ad_Price__c = l_oAdPrice.Id;
        l_oCampaignItem1.SomDig_PositionStatus__c = 'Entwurf';
        CampaignItemList.add(l_oCampaignItem1);

        ADvendio__Campaign_Item__c l_oCampaignItem2 = new ADvendio__Campaign_Item__c();
        l_oCampaignItem2.ADvendio__Media_Campaign__c = l_oMediaCampaign.Id;
        l_oCampaignItem2.ADvendio__Quantity__c = 10000;
        l_oCampaignItem2.ADvendio__from_Date__c = system.today();
        l_oCampaignItem2.ADvendio__until_Date__c = system.today()+2;
        l_oCampaignItem2.ADvendio__Sales_Price__c = 30;
        l_oCampaignItem2.ADvendio__Billing_category__c = 'CPM';
        l_oCampaignItem2.ADvendio__Ad_Price__c = l_oAdPrice.Id;
        l_oCampaignItem2.SomDig_PositionStatus__c = 'Entwurf';
        CampaignItemList.add(l_oCampaignItem2);
        insert CampaignItemList;

        l_oMediaCampaign.SomDig_StatusPAMCockpit__c = StatusPAM;
        update l_oMediaCampaign;

        Id campItemId = CampaignItemList[0].Id;
        String l_sQuery = 'SELECT Id, SomDig_PositionStatus__c, ADvendio__Media_Campaign__c, ADvendio__until_Date__c, ADvendio__from_Date__c ' +
                            'FROM ADvendio__Campaign_Item__c ' +
                           'WHERE Id = ' + '\'' + campItemId + '\'';
        System.debug('l_sQuery '+l_sQuery +' -- l_oCampaignItem1.Id ' + '\'' + campItemId + '\'' );
        Adv_CampaignItem_NightlyUpdate l_oBatchInst= new Adv_CampaignItem_NightlyUpdate(l_sQuery);
        Id l_ibatchInstanceId = Database.executeBatch(l_oBatchInst);

        Test.stopTest();
    }

    static testMethod void schedule_batch() {
        Test.startTest();

        string l_sCronExp = '0 0 0 15 3 ? 2022';
        // Schedule the test job
        string jobid = system.schedule('test batch job', l_sCronExp, new Adv_CampaignItem_NightlyUpdate() );

        Test.stopTest();
    }

    static testMethod void testCampaignItemStatusExec() {
        createData();
        testCampaignItemStatus('to do');
    }

    static testMethod void testCampaignItemStatusExec1() {
        createData();
        testCampaignItemStatus('NonAdServer');
    }

    static testMethod void testCampaignItemStatusExec2() {
        createData();
        testCampaignItemStatus('Auslieferung-normal');
    }

    static testMethod void testCampaignItemStatusExec3() {
        createData();
        testCampaignItemStatus('bereit');
    }

    static testMethod void testCampaignItemStatusExec4() {
        createData();
        testCampaignItemStatus('abgelaufen-erfüllt');
    }

    static testMethod void testCampaignItemStatusExec5() {
        createData();
        testCampaignItemStatus('pausiert');
    }
}