src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__SelectedAdServerIdInformation__c</fullName>
        <description>This field stores a summary of the selected Targeting Criteria of the Campaign Item to display that information within reports.</description>
        <inlineHelpText>This field stores a summary of the selected Targeting Criteria of the Campaign Item to display that information within reports.</inlineHelpText>
        <label>Selected AdServer ID Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ADvendio__SelectedContentInformation__c</fullName>
        <label>Selected Content Information</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__FieldName__c</fullName>
        <description>something like &quot;Quantity&quot;</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizedValue__c</fullName>
        <description>The new opzimized value.</description>
        <inlineHelpText>The new opzimized value.</inlineHelpText>
        <label>Optimized Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizingVersion__c</fullName>
        <label>Optimizing Version</label>
        <referenceTo>ADvendio__OptimizingVersion__c</referenceTo>
        <relationshipLabel>Optimizing Changes</relationshipLabel>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__OriginalValue__c</fullName>
        <description>The original value before optimization.</description>
        <inlineHelpText>The original value before optimization.</inlineHelpText>
        <label>Original Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipName>OptimizingVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_OptimizingChange_PostalCodes_Test.cls
@isTest
public with sharing class Adv_OptimizingChange_PostalCodes_Test {
	@isTest
	static void testPlzChanged() {

		ADvendio__Pricelist__c priceList	= cls_P7S1_TestData.createTestPricelist(true);
		ADvendio__Ad_price__c adPrice		= cls_P7S1_TestData.createTestAdPrice(true, null, pricelist);

		ADvendio__MediaCampaign__c mc					= cls_P7S1_TestData.createTestMediaCampaign(true, null, priceList);
		
		ADvendio__Campaign_Item__c ci1					= cls_P7S1_TestData.createTestCampaignItem(false, mc, adPrice);
		ci1.ADvendio__SelectedAdServerIdInformation__c	= 'Postal Code: 20097';
		ci1.ADvendio__SelectedContentInformation__c		= '20097';
		
		ADvendio__Campaign_Item__c ci2					= cls_P7S1_TestData.createTestCampaignItem(false, mc, adPrice);
		ci2.ADvendio__SelectedAdServerIdInformation__c	= 'Postal Code: 20097';
		ci2.ADvendio__SelectedContentInformation__c		= '20097';
		
		ADvendio__Campaign_Item__c ci3					= cls_P7S1_TestData.createTestCampaignItem(false, mc, adPrice);
		ci3.ADvendio__SelectedAdServerIdInformation__c	= null;
		ci3.ADvendio__SelectedContentInformation__c		= null;
		
		ADvendio__Campaign_Item__c ci4					= cls_P7S1_TestData.createTestCampaignItem(false, mc, adPrice);
		ci4.ADvendio__SelectedAdServerIdInformation__c	= 'Postal Code: 20097';
		ci4.ADvendio__SelectedContentInformation__c		= '20097';
		
		
		insert new List<ADvendio__Campaign_Item__c> {ci1 ,ci2, ci3, ci4};
		
		ADvendio__OptimizingVersion__c version = new ADvendio__OptimizingVersion__c(ADvendio__MediaCampaign__c=mc.Id);
		insert version;

		ADvendio__OptimizingChange__c change1 = new ADvendio__OptimizingChange__c();
		change1.ADvendio__CampaignItem__c		= ci1.Id;
		change1.ADvendio__OptimizingVersion__c	= version.Id;
		change1.ADvendio__FieldName__c			= 'ADvendio__SelectedAdServerIdInformation__c';
		change1.ADvendio__OptimizedValue__c		= 'Postal Code: 20095';
		change1.ADvendio__OriginalValue__c		= ci1.ADvendio__SelectedAdServerIdInformation__c;

		ADvendio__OptimizingChange__c change2 = new ADvendio__OptimizingChange__c();
		change2.ADvendio__CampaignItem__c		= ci2.Id;
		change2.ADvendio__OptimizingVersion__c	= version.Id;
		change2.ADvendio__FieldName__c			= 'ADvendio__SelectedAdServerIdInformation__c';
		change2.ADvendio__OptimizedValue__c		= null;
		change2.ADvendio__OriginalValue__c		= ci2.ADvendio__SelectedAdServerIdInformation__c;
		
		ADvendio__OptimizingChange__c change3 = new ADvendio__OptimizingChange__c();
		change3.ADvendio__CampaignItem__c		= ci3.Id;
		change3.ADvendio__OptimizingVersion__c	= version.Id;
		change3.ADvendio__FieldName__c			= 'ADvendio__SelectedAdServerIdInformation__c';
		change3.ADvendio__OptimizedValue__c		= 'Postal Code: 20095';
		change3.ADvendio__OriginalValue__c		= ci3.ADvendio__SelectedAdServerIdInformation__c;
		
		ADvendio__OptimizingChange__c change4 = new ADvendio__OptimizingChange__c();
		change4.ADvendio__CampaignItem__c		= ci4.Id;
		change4.ADvendio__OptimizingVersion__c	= version.Id;
		change4.ADvendio__FieldName__c			= 'ADvendio__SelectedContentInformation__c';
		change4.ADvendio__OptimizedValue__c		= '';
		change4.ADvendio__OriginalValue__c		= '20097';

		Test.startTest();
		insert new List<ADvendio__OptimizingChange__c> {change1 ,change2, change3, change4};
		Test.stopTest();
		
		for (ADvendio__OptimizingChange__c oc : [SELECT Id, ADvendio__CampaignItem__c, ADvendio__FieldName__c, ADvendio__OriginalValue__c, ADvendio__OptimizedValue__c FROM ADvendio__OptimizingChange__c WHERE ADvendio__OptimizingVersion__c = :version.Id]) {
			if (oc.ADvendio__CampaignItem__c == ci1.Id) {
				if ('ADvendio__SelectedAdServerIdInformation__c'.equalsIgnoreCase(oc.ADvendio__FieldName__c)) {
					system.assertEquals(change1.ADvendio__OptimizedValue__c, oc.ADvendio__OptimizedValue__c);
					system.assertEquals(change1.ADvendio__OriginalValue__c, oc.ADvendio__OriginalValue__c);
				}
				if ('ADvendio__SelectedContentInformation__c'.equalsIgnoreCase(oc.ADvendio__FieldName__c)) {
					system.assertEquals('20095', oc.ADvendio__OptimizedValue__c);
					system.assertEquals('20097', oc.ADvendio__OriginalValue__c);
				}
			}
			else if (oc.ADvendio__CampaignItem__c == ci2.Id) {
				if ('ADvendio__SelectedAdServerIdInformation__c'.equalsIgnoreCase(oc.ADvendio__FieldName__c)) {
					system.assertEquals(change2.ADvendio__OptimizedValue__c, oc.ADvendio__OptimizedValue__c);
					system.assertEquals(change2.ADvendio__OriginalValue__c, oc.ADvendio__OriginalValue__c);
				}
				if ('ADvendio__SelectedContentInformation__c'.equalsIgnoreCase(oc.ADvendio__FieldName__c)) {
					system.assertEquals(null, oc.ADvendio__OptimizedValue__c);
					system.assertEquals('20097', oc.ADvendio__OriginalValue__c);
				}
			}
			else if (oc.ADvendio__CampaignItem__c == ci3.Id) {
				if ('ADvendio__SelectedAdServerIdInformation__c'.equalsIgnoreCase(oc.ADvendio__FieldName__c)) {
					system.assertEquals(change3.ADvendio__OptimizedValue__c, oc.ADvendio__OptimizedValue__c);
					system.assertEquals(change3.ADvendio__OriginalValue__c, oc.ADvendio__OriginalValue__c);
				}
				if ('ADvendio__SelectedContentInformation__c'.equalsIgnoreCase(oc.ADvendio__FieldName__c)) {
					system.assertEquals('20095', oc.ADvendio__OptimizedValue__c);
					system.assertEquals(null, oc.ADvendio__OriginalValue__c);
				}
			}
			else {
				system.assert(false, 'this change should have been deleted - maybe @future was to slow');
			}
		}
	}
}