src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Distribution__c</fullName>
        <description>Define how the amount of product package is to be distributed among its components.</description>
        <inlineHelpText>Define how the amount of product package is to be distributed among its components.</inlineHelpText>
        <label>Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Linear</fullName>
                </value>
                <value>
                    <fullName>Prorated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Availability__c</fullName>
        <description>The ad server interface will enter the availability during an availabilty request.</description>
        <inlineHelpText>The ad server interface will enter the availability during an availabilty request.</inlineHelpText>
        <label>Availability (planned)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Impressions__c</fullName>
        <description>The ad server interface will enter the delivered impressions here.</description>
        <inlineHelpText>The ad server interface will enter the delivered impressions here. (technical View)</inlineHelpText>
        <label>Delivered Impressions</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__LastAvailabilityForecast__c</fullName>
        <description>Last Availability Forecast run</description>
        <label>Last Availability Forecast</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packet Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Prorated__c</fullName>
        <label>Prorated</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Sales_Price__c</fullName>
        <description>Enter the sales price for this campaign item.</description>
        <inlineHelpText>Enter the sales price for this campaign item.</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_Menge__c</fullName>
        <description>Menge ohne anteiligen Naturalrabatt (Ticket 06323)</description>
        <label>Menge (ohne Naturalrabatt)</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_Naturalrabatt__c</fullName>
        <description>Naturalrabatt in Prozent (Ticket 06323)</description>
        <label>Naturalrabatt</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__FieldName__c</fullName>
        <description>something like &quot;Quantity&quot;</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizedValue__c</fullName>
        <description>The new opzimized value.</description>
        <inlineHelpText>The new opzimized value.</inlineHelpText>
        <label>Optimized Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizingVersion__c</fullName>
        <label>Optimizing Version</label>
        <referenceTo>ADvendio__OptimizingVersion__c</referenceTo>
        <relationshipLabel>Optimizing Changes</relationshipLabel>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipName>OptimizingVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Typ__c</fullName>
        <description>Welchem Netzwerk gehört diese Belegungseinheit an?</description>
        <inlineHelpText>Welchem Netzwerk gehört diese Belegungseinheit an? Achtung dies hat Einfluss auf Auslieferungstyp und Priomodell.</inlineHelpText>
        <label>Netzwerk-Typ</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>71m intern</fullName>
                    <default>true</default>
                    <label>71m intern</label>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_OptimizingChange_DynamicQuantit_Test.cls
@isTest
public with sharing class Adv_OptimizingChange_DynamicQuantit_Test {

    static testMethod void testdynamicQuantityWithNaturalrabatt() {
      
      ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
      placement.SomDig_Typ__c='YouTube';
      insert placement;
      
        // Create 3 ad specs
        List<ADvendio__Ad_Specs__c> lstAdS = new List<ADvendio__Ad_Specs__c>();
        for(Integer i=0;i<3;i++){
            lstAdS.add(cls_P7S1_TestData.createTestAdSpec(false, placement));
            lstAdS[i].ADvendio__Distribution__c = 'Prorated';            
        }

        insert lstAdS;

        // Create 3 ad price
        List<ADvendio__Ad_price__c> lstAdPrice = new List<ADvendio__Ad_price__c>();
        for (Integer i=0;i<3;i++){
            lstAdPrice.add(cls_P7S1_TestData.createTestAdPrice(false, lstAdS[i]));
        }
        insert lstAdPrice;

        ADvendio__MediaCampaign__c mc = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c adCP = cls_P7S1_TestData.createTestCampaignItem(false, mc, lstAdPrice[0]);
        adCP.SomDig_Menge__c = 200;
        adCP.SomDig_Naturalrabatt__c = 10;
        adCP.ADvendio__Quantity__c = 220;
        adCP.ADvendio__Sales_Price__c = 100;
        insert adCP;

        // Create 2 component items
        List<ADvendio__Campaign_Item__c> lstComponents = new List<ADvendio__Campaign_Item__c>();
        ADvendio__Campaign_Item__c ci01 = cls_P7S1_TestData.createTestCampaignItem(false, mc, lstAdPrice[1]);
        ci01.ADvendio__PacketItem__c = adCP.Id;
        ci01.SomDig_Menge__c = 50;
        ci01.SomDig_Naturalrabatt__c = 10;
        ci01.ADvendio__Quantity__c = 55;
        ADvendio__Campaign_Item__c ci02 = cls_P7S1_TestData.createTestCampaignItem(false, mc, lstAdPrice[2]);
        ci02.ADvendio__PacketItem__c = adCP.Id;
        ci02.SomDig_Menge__c = 150;
        ci02.SomDig_NaturalRabatt__c = 10;
        ci02.ADvendio__Quantity__c = 165;
        lstComponents.add(ci01);
        lstComponents.add(ci02);
        insert lstComponents;

    ADvendio__OptimizingVersion__c version = new ADvendio__OptimizingVersion__c(ADvendio__MediaCampaign__c=mc.Id);
    insert version;
    
        
        Test.startTest();

    ADvendio__OptimizingChange__c change10 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci01.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__LastAvailabilityForecast__c',ADvendio__OptimizedValue__c=String.valueOf(DateTime.now().addMinutes(-5)));
    ADvendio__OptimizingChange__c change11 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci01.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__Availability__c',ADvendio__OptimizedValue__c='150');
    ADvendio__OptimizingChange__c change20 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci02.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__LastAvailabilityForecast__c',ADvendio__OptimizedValue__c=String.valueOf(DateTime.now().addMinutes(-5)));
    ADvendio__OptimizingChange__c change21 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci02.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__Availability__c',ADvendio__OptimizedValue__c='50');
        insert new List<ADvendio__OptimizingChange__c>{change10, change11, change20, change21};

    List<ADvendio__OptimizingChange__c> changes = [SELECT Id, ADvendio__OptimizedValue__c, ADvendio__CampaignItem__c, ADvendio__FieldName__c FROM ADvendio__OptimizingChange__c 
        WHERE ADvendio__OptimizingVersion__c = :version.Id AND ADvendio__FieldName__c IN ('ADvendio__Quantity__c', 'ADvendio__Prorated__c', 'SomDig_Menge__c')];
        System.assertEquals(6, changes.size());
        for (ADvendio__OptimizingChange__c change : changes) {
          if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('165', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('75', change.ADvendio__OptimizedValue__c);
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('150', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('55', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('25', change.ADvendio__OptimizedValue__c);
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('50', change.ADvendio__OptimizedValue__c);
          } else {
            System.assert(false, 'some other change? cannot be');
          }
        }

    ci01.ADvendio__Delivered_Impressions__c = 70;
    ci02.ADvendio__Delivered_Impressions__c = 80;
    update new List<ADvendio__Campaign_Item__c>{ci01, ci02};
    
        change10.ADvendio__OptimizedValue__c = String.valueOf(System.now().addMinutes(-3));
        change11.ADvendio__OptimizedValue__c = '8000';
        change20.ADvendio__OptimizedValue__c = String.valueOf(System.now().addMinutes(-3));
        change21.ADvendio__OptimizedValue__c = '2000';
        update new List<ADvendio__OptimizingChange__c>{change10, change11, change20, change21};


    changes = [SELECT Id, ADvendio__OptimizedValue__c, ADvendio__CampaignItem__c, ADvendio__FieldName__c FROM ADvendio__OptimizingChange__c 
        WHERE ADvendio__OptimizingVersion__c = :version.Id AND ADvendio__FieldName__c IN ('ADvendio__Quantity__c', 'ADvendio__Prorated__c', 'SomDig_Menge__c')];
        System.assertEquals(6, changes.size());
        for (ADvendio__OptimizingChange__c change : changes) {
          if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('132', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals(60, Decimal.valueOf(change.ADvendio__OptimizedValue__c));
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('120', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
           System.assertEquals('88', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals(40, Decimal.valueOf(change.ADvendio__OptimizedValue__c));
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('80', change.ADvendio__OptimizedValue__c);
          } else {
            System.assert(false, 'some other change? cannot be');
          }
        }

        Test.stopTest();
    }

    static testMethod void testdynamicQuantityWithoutNaturalrabatt() {
      
      ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
      placement.SomDig_Typ__c='YouTube';
      insert placement;
      
        // Create 3 ad specs
        List<ADvendio__Ad_Specs__c> lstAdS = new List<ADvendio__Ad_Specs__c>();
        for(Integer i=0;i<3;i++){
            lstAdS.add(cls_P7S1_TestData.createTestAdSpec(false, placement));
            lstAdS[i].ADvendio__Distribution__c = 'Prorated';            
        }

        insert lstAdS;

        // Create 3 ad price
        List<ADvendio__Ad_price__c> lstAdPrice = new List<ADvendio__Ad_price__c>();
        for (Integer i=0;i<3;i++){
            lstAdPrice.add(cls_P7S1_TestData.createTestAdPrice(false, lstAdS[i]));
        }
        insert lstAdPrice;

        ADvendio__MediaCampaign__c mc = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c adCP = cls_P7S1_TestData.createTestCampaignItem(false, mc, lstAdPrice[0]);
        adCP.SomDig_Menge__c = 200;
        adCP.ADvendio__Quantity__c = 200;
        adCP.ADvendio__Sales_Price__c = 100;
        insert adCP;

        // Create 2 component items
        List<ADvendio__Campaign_Item__c> lstComponents = new List<ADvendio__Campaign_Item__c>();
        ADvendio__Campaign_Item__c ci01 = cls_P7S1_TestData.createTestCampaignItem(false, mc, lstAdPrice[1]);
        ci01.ADvendio__PacketItem__c = adCP.Id;
        ci01.SomDig_Menge__c = 50;
        ci01.ADvendio__Quantity__c = 50;
        ADvendio__Campaign_Item__c ci02 = cls_P7S1_TestData.createTestCampaignItem(false, mc, lstAdPrice[2]);
        ci02.ADvendio__PacketItem__c = adCP.Id;
        ci02.SomDig_Menge__c = 150;
        ci02.ADvendio__Quantity__c = 150;
        lstComponents.add(ci01);
        lstComponents.add(ci02);
        insert lstComponents;

    ADvendio__OptimizingVersion__c version = new ADvendio__OptimizingVersion__c(ADvendio__MediaCampaign__c=mc.Id);
    insert version;
    
        
        Test.startTest();

    ADvendio__OptimizingChange__c change10 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci01.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__LastAvailabilityForecast__c',ADvendio__OptimizedValue__c=String.valueOf(DateTime.now().addMinutes(-5)));
    ADvendio__OptimizingChange__c change11 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci01.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__Availability__c',ADvendio__OptimizedValue__c='150');
    ADvendio__OptimizingChange__c change20 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci02.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__LastAvailabilityForecast__c',ADvendio__OptimizedValue__c=String.valueOf(DateTime.now().addMinutes(-5)));
    ADvendio__OptimizingChange__c change21 = new ADvendio__OptimizingChange__c(ADvendio__CampaignItem__c=ci02.Id, ADvendio__OptimizingVersion__c = version.Id,
        ADvendio__FieldName__c='ADvendio__Availability__c',ADvendio__OptimizedValue__c='50');
        insert new List<ADvendio__OptimizingChange__c>{change10, change11, change20, change21};

    List<ADvendio__OptimizingChange__c> changes = [SELECT Id, ADvendio__OptimizedValue__c, ADvendio__CampaignItem__c, ADvendio__FieldName__c FROM ADvendio__OptimizingChange__c 
        WHERE ADvendio__OptimizingVersion__c = :version.Id AND ADvendio__FieldName__c IN ('ADvendio__Quantity__c', 'ADvendio__Prorated__c', 'SomDig_Menge__c')];
        System.assertEquals(6, changes.size());
        for (ADvendio__OptimizingChange__c change : changes) {
          if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('150', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('75', change.ADvendio__OptimizedValue__c);
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('150', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('50', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('25', change.ADvendio__OptimizedValue__c);
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('50', change.ADvendio__OptimizedValue__c);
          } else {
            System.assert(false, 'some other change? cannot be');
          }
        }

    ci01.ADvendio__Delivered_Impressions__c = 70;
    ci02.ADvendio__Delivered_Impressions__c = 80;
    update new List<ADvendio__Campaign_Item__c>{ci01, ci02};
    
        change10.ADvendio__OptimizedValue__c = String.valueOf(System.now().addMinutes(-3));
        change11.ADvendio__OptimizedValue__c = '8000';
        change20.ADvendio__OptimizedValue__c = String.valueOf(System.now().addMinutes(-3));
        change21.ADvendio__OptimizedValue__c = '2000';
        update new List<ADvendio__OptimizingChange__c>{change10, change11, change20, change21};


    changes = [SELECT Id, ADvendio__OptimizedValue__c, ADvendio__CampaignItem__c, ADvendio__FieldName__c FROM ADvendio__OptimizingChange__c 
        WHERE ADvendio__OptimizingVersion__c = :version.Id AND ADvendio__FieldName__c IN ('ADvendio__Quantity__c', 'ADvendio__Prorated__c', 'SomDig_Menge__c')];
        System.assertEquals(6, changes.size());
        for (ADvendio__OptimizingChange__c change : changes) {
          if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('120', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals(60, Decimal.valueOf(change.ADvendio__OptimizedValue__c));
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci01.Id) {
            System.assertEquals('120', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Quantity__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
           System.assertEquals('80', change.ADvendio__OptimizedValue__c);
          } else if ('ADvendio__Prorated__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals(40, Decimal.valueOf(change.ADvendio__OptimizedValue__c));
          } else if ('SomDig_Menge__c'.equals(change.ADvendio__FieldName__c) && change.ADvendio__CampaignItem__c==ci02.Id) {
            System.assertEquals('80', change.ADvendio__OptimizedValue__c);
          } else {
            System.assert(false, 'some other change? cannot be');
          }
        }

        Test.stopTest();
    }
    
}