src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the ad type assigned to this ad spec.</description>
        <inlineHelpText>This field displays the ad type assigned to this ad spec.</inlineHelpText>
        <label>Ad Type</label>
        <referenceTo>ADvendio__Ad_Type__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Ad_Specs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstypen__c</fullName>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>Auftragstypen</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AdAudience</fullName>
                </value>
                <value>
                    <fullName>Backfill</fullName>
                </value>
                <value>
                    <fullName>Barter</fullName>
                </value>
                <value>
                    <fullName>Eigenvermarktung</fullName>
                </value>
                <value>
                    <fullName>Eigenwerbung</fullName>
                </value>
                <value>
                    <fullName>Forschung</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standby</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_BT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ist es erlaubt für diese Werbemittel/Produkt Soziademografisches und Behavior Targeting zu nutzen? wenn das Kontrollkästchen gefüllt ist werden die Aufschläge entsprechend aktiv.</description>
        <inlineHelpText>Ist es erlaubt für diese Werbemittel/Produkt Soziademografisches und Behavior Targeting zu nutzen? wenn das Kontrollkästchen gefüllt ist werden die Aufschläge entsprechend aktiv.</inlineHelpText>
        <label>BT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_FC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>FC fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_Targeting_Provider__c</fullName>
        <description>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</description>
        <inlineHelpText>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</inlineHelpText>
        <label>Targeting Provider</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATV_PBT</fullName>
                </value>
                <value>
                    <fullName>Autosites</fullName>
                </value>
                <value>
                    <fullName>Diverse Kriterien</fullName>
                </value>
                <value>
                    <fullName>Gesundheit.de</fullName>
                </value>
                <value>
                    <fullName>nugg.ad</fullName>
                </value>
                <value>
                    <fullName>nugg.ad InApp</fullName>
                </value>
                <value>
                    <fullName>Rotationsausschluss</fullName>
                </value>
                <value>
                    <fullName>SmartGeo</fullName>
                </value>
                <value>
                    <fullName>Vereinssites</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
                <value>
                    <fullName>wetter.com CTV</fullName>
                </value>
                <value>
                    <fullName>ZG S71 Paket</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_iAdFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>iAd fähig</label>
        <type>Checkbox</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Type__c.object
<CustomObject>
    <label>Ad Type</label>
    <nameField>
        <label>Ad Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the ad server ID.</inlineHelpText>
        <label>AdServer ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__AdServer_ID_AdSpec_Assigment__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad spec to which the ad server ID is to be assigned.</description>
        <inlineHelpText>Enter the ad spec to which the ad server ID is to be assigned.</inlineHelpText>
        <label>AdServer ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>AdServer ID AdSpec Assignments</relationshipLabel>
        <relationshipName>Adserver_ID_AdSpec_Assigments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>Enter the ad server ID to which the ad spec is to be assigned.</description>
        <inlineHelpText>Enter the ad server ID to which the ad spec is to be assigned.</inlineHelpText>
        <label>Ad Spec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>AdServer ID AdSpec Assignments</relationshipLabel>
        <relationshipName>AdServer_ID_AdSpec_Assigments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AdServer ID AdSpec Assignment</label>
    <nameField>
        <displayFormat>AAA-{00000}</displayFormat>
        <label>AdServer ID AdSpec Assignment No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AdServer ID AdSpec Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_AdServerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AdServer ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstypen__c</fullName>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>Auftragstypen</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AdAudience</fullName>
                </value>
                <value>
                    <fullName>Barter</fullName>
                </value>
                <value>
                    <fullName>Eigenvermarktung</fullName>
                </value>
                <value>
                    <fullName>Eigenwerbung</fullName>
                </value>
                <value>
                    <fullName>Forschung</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standby</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_BT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>BT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_FC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>FC fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_iAdFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>iAd fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Targeting_Provider__c</fullName>
        <description>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</description>
        <inlineHelpText>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</inlineHelpText>
        <label>Targeting Provider</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATV_PBT</fullName>
                </value>
                <value>
                    <fullName>Autosites</fullName>
                </value>
                <value>
                    <fullName>Diverse Kriterien</fullName>
                </value>
                <value>
                    <fullName>Gesundheit.de</fullName>
                </value>
                <value>
                    <fullName>nugg.ad</fullName>
                </value>
                <value>
                    <fullName>nugg.ad InApp</fullName>
                </value>
                <value>
                    <fullName>Rotationsausschluss</fullName>
                </value>
                <value>
                    <fullName>SmartGeo</fullName>
                </value>
                <value>
                    <fullName>Vereinssites</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
                <value>
                    <fullName>wetter.com CTV</fullName>
                </value>
                <value>
                    <fullName>ZG S71 Paket</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_AdSpec_InheritFromPlacement_Test.cls
@isTest
private with sharing class Adv_AdSpec_InheritFromPlacement_Test {

    static testMethod void adSpecInsertShouldInheritValues() {
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_Auftragstypen__c = 'Forschung;Standard';
        placement.SomDig_FC__c = true;
        placement.SomDig_BT__c = true;
        placement.SomDig_GtFaehig__c = true;
        placement.SomDig_iAdFaehig__c = true;
        placement.Targeting_Provider__c = 'Autosites;nugg.ad';
        insert placement;

        Test.startTest();

        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.stopTest();

        adSpec = [SELECT SomDig_Auftragstypen__c, SomDig_BT__c, SomDig_FC__c, SomDig_GtFaehig__c, SomDig_iAdFaehig__c, SomDig_Targeting_Provider__c FROM ADvendio__Ad_Specs__c WHERE Id = :adSpec.Id];
        System.assertEquals(new Set<String>('Forschung;Standard'.split(';')), new Set<String>(adSpec.SomDig_Auftragstypen__c.split(';')));
        System.assertEquals(true, adSpec.SomDig_BT__c);
        System.assertEquals(true, adSpec.SomDig_FC__c);
        System.assertEquals(true, adSpec.SomDig_GtFaehig__c);
        System.assertEquals(true, adSpec.SomDig_iAdFaehig__c);
        System.assertEquals(new Set<String>('Autosites;nugg.ad'.split(';')), new Set<String>(adSpec.SomDig_Targeting_Provider__c.split(';')));
    }

    static testMethod void adSpecUpdateShouldNotInheritValues() {
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_Auftragstypen__c = 'Forschung;Standard';
        placement.SomDig_BT__c = true;
        placement.SomDig_FC__c = true;
        placement.SomDig_GtFaehig__c = true;
        placement.SomDig_iAdFaehig__c = true;
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.startTest();

        adSpec = [SELECT SomDig_Auftragstypen__c, SomDig_BT__c, SomDig_FC__c, SomDig_GtFaehig__c, SomDig_iAdFaehig__c, SomDig_Targeting_Provider__c FROM ADvendio__Ad_Specs__c WHERE Id = :adSpec.Id];
        adSpec.SomDig_Auftragstypen__c = 'Barter;Performance';
        adSpec.SomDig_BT__c = false;
        adSpec.SomDig_FC__c = false;
        adSpec.SomDig_GtFaehig__c = false;
        adSpec.SomDig_iAdFaehig__c = false;
        update adSpec;

        Test.stopTest();

        adSpec = [SELECT SomDig_Auftragstypen__c, SomDig_BT__c, SomDig_FC__c, SomDig_GtFaehig__c, SomDig_iAdFaehig__c, SomDig_Targeting_Provider__c FROM ADvendio__Ad_Specs__c WHERE Id = :adSpec.Id];
        System.assertEquals(new Set<String>('Barter;Performance'.split(';')), new Set<String>(adSpec.SomDig_Auftragstypen__c.split(';')));
        System.assertEquals(false, adSpec.SomDig_BT__c);
        System.assertEquals(false, adSpec.SomDig_FC__c);
        System.assertEquals(false, adSpec.SomDig_GtFaehig__c);
        System.assertEquals(false, adSpec.SomDig_iAdFaehig__c);
    }

    static testMethod void placementUpdateShouldUpdateValues() {
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_Auftragstypen__c = 'Eigenwerbung';
        placement.SomDig_BT__c = false;
        placement.SomDig_FC__c = false;
        placement.SomDig_GtFaehig__c = false;
        placement.SomDig_iAdFaehig__c = false;
        placement.Targeting_Provider__c = 'Bundesliga;wetter.com';
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.startTest();

        placement.SomDig_Auftragstypen__c = 'Barter;Standard';
        placement.SomDig_BT__c = true;
        placement.SomDig_FC__c = true;
        placement.SomDig_GtFaehig__c = true;
        placement.SomDig_iAdFaehig__c = true;
        placement.Targeting_Provider__c = 'Gesundheit.de;ICQ';
        update placement;

        Test.stopTest();

        adSpec = [SELECT SomDig_Auftragstypen__c, SomDig_BT__c, SomDig_FC__c, SomDig_GtFaehig__c, SomDig_iAdFaehig__c, SomDig_Targeting_Provider__c FROM ADvendio__Ad_Specs__c WHERE Id = :adSpec.Id];
        System.assertEquals(new Set<String>('Barter;Standard'.split(';')), new Set<String>(adSpec.SomDig_Auftragstypen__c.split(';')));
        System.assertEquals(true, adSpec.SomDig_BT__c);
        System.assertEquals(true, adSpec.SomDig_FC__c);
        System.assertEquals(true, adSpec.SomDig_GtFaehig__c);
        System.assertEquals(true, adSpec.SomDig_iAdFaehig__c);
        System.assertEquals(new Set<String>('Gesundheit.de;ICQ'.split(';')), new Set<String>(adSpec.SomDig_Targeting_Provider__c.split(';')));
    }

    static testMethod void placementUpdateShouldOnlyUpdateChangedValues() {
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_Auftragstypen__c = 'Eigenwerbung';
        placement.SomDig_BT__c = false;
        placement.SomDig_FC__c = false;
        placement.SomDig_GtFaehig__c = false;
        placement.SomDig_iAdFaehig__c = false;
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.startTest();

        adSpec = [SELECT SomDig_Auftragstypen__c, SomDig_BT__c, SomDig_FC__c, SomDig_GtFaehig__c, SomDig_iAdFaehig__c, SomDig_Targeting_Provider__c FROM ADvendio__Ad_Specs__c WHERE Id = :adSpec.Id];
        adSpec.SomDig_Auftragstypen__c = 'Eigenwerbung;Standard';
        adSpec.SomDig_iAdFaehig__c = true;
        update adSpec;

        placement.SomDig_BT__c = true;
        placement.SomDig_GtFaehig__c = true;
        update placement;

        Test.stopTest();

        adSpec = [SELECT SomDig_Auftragstypen__c, SomDig_BT__c, SomDig_FC__c, SomDig_GtFaehig__c, SomDig_iAdFaehig__c, SomDig_Targeting_Provider__c FROM ADvendio__Ad_Specs__c WHERE Id = :adSpec.Id];
        System.assertEquals(new Set<String>('Eigenwerbung;Standard'.split(';')), new Set<String>(adSpec.SomDig_Auftragstypen__c.split(';')));
        System.assertEquals(true, adSpec.SomDig_BT__c);
        System.assertEquals(false, adSpec.SomDig_FC__c);
        System.assertEquals(true, adSpec.SomDig_GtFaehig__c);
        System.assertEquals(true, adSpec.SomDig_iAdFaehig__c);
    }

    static testMethod void adSpecInsertShouldInsertAdServerIdAssignments() {
        ADvendio__AdServer_ID__c adServerID = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_AdServerID__c = adServerID.Id;
        insert placement;

        Test.startTest();

        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.stopTest();

        List<ADvendio__AdServer_ID_AdSpec_Assigment__c> assignments = [
            SELECT Id, ADvendio__AdServer_ID__c
              FROM ADvendio__AdServer_ID_AdSpec_Assigment__c
             WHERE ADvendio__Ad_Spec__c = :adSpec.Id];
        System.assertEquals(1, assignments.size());
        System.assertEquals(adServerID.Id, assignments[0].ADvendio__AdServer_ID__c);
    }

    static testMethod void adSpecInsertShouldNotInsertAdServerIdAssignments() {
        ADvendio__AdServer_ID__c adServerID = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(true);

        Test.startTest();

        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.stopTest();

        System.assertEquals(0, [SELECT count() FROM ADvendio__AdServer_ID_AdSpec_Assigment__c WHERE ADvendio__Ad_Spec__c = :adSpec.Id]);
    }

    static testMethod void placementUpdateShouldInsertAdServerIdAssignments() {
        ADvendio__AdServer_ID__c adServerID = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(true);
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.startTest();

        System.assertEquals(0, [SELECT count() FROM ADvendio__AdServer_ID_AdSpec_Assigment__c WHERE ADvendio__Ad_Spec__c = :adSpec.Id]);

        placement.SomDig_AdServerID__c = adServerID.Id;
        update placement;

        Test.stopTest();

        List<ADvendio__AdServer_ID_AdSpec_Assigment__c> assignments = [
            SELECT Id, ADvendio__AdServer_ID__c
              FROM ADvendio__AdServer_ID_AdSpec_Assigment__c
             WHERE ADvendio__Ad_Spec__c = :adSpec.Id];
        System.assertEquals(1, assignments.size());
        System.assertEquals(adServerID.Id, assignments[0].ADvendio__AdServer_ID__c);
    }

    static testMethod void placementUpdateShouldUpdateAdServerIdAssignments() {
        ADvendio__AdServer_ID__c adServerID = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__AdServer_ID__c adServerID_2 = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_AdServerID__c = adServerID.Id;
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.startTest();

        List<ADvendio__AdServer_ID_AdSpec_Assigment__c> oldAssignments = [
            SELECT Id, ADvendio__AdServer_ID__c
              FROM ADvendio__AdServer_ID_AdSpec_Assigment__c
             WHERE ADvendio__Ad_Spec__c = :adSpec.Id];
        System.assertEquals(1, oldAssignments.size());
        System.assertEquals(adServerID.Id, oldAssignments[0].ADvendio__AdServer_ID__c);

        placement.SomDig_AdServerID__c = adServerID_2.Id;
        update placement;

        Test.stopTest();

        List<ADvendio__AdServer_ID_AdSpec_Assigment__c> newAssignments = [
            SELECT Id, ADvendio__AdServer_ID__c
              FROM ADvendio__AdServer_ID_AdSpec_Assigment__c
             WHERE ADvendio__Ad_Spec__c = :adSpec.Id];
        System.assertEquals(1, newAssignments.size());
        System.assertEquals(adServerID_2.Id, newAssignments[0].ADvendio__AdServer_ID__c);
    }

    static testMethod void placementUpdateShouldDeleteAdServerIdAssignments() {
        ADvendio__AdServer_ID__c adServerID = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_AdServerID__c = adServerID.Id;
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.startTest();

        List<ADvendio__AdServer_ID_AdSpec_Assigment__c> assignments = [
            SELECT Id, ADvendio__AdServer_ID__c
              FROM ADvendio__AdServer_ID_AdSpec_Assigment__c
             WHERE ADvendio__Ad_Spec__c = :adSpec.Id];
        System.assertEquals(1, assignments.size());
        System.assertEquals(adServerID.Id, assignments[0].ADvendio__AdServer_ID__c);

        placement.SomDig_AdServerID__c = null;
        update placement;

        Test.stopTest();

        System.assertEquals(0, [SELECT count() FROM ADvendio__AdServer_ID_AdSpec_Assigment__c WHERE ADvendio__Ad_Spec__c = :adSpec.Id]);
    }

    static testMethod void placementChangeShouldUpdateAdServerIdAssignments() {
        ADvendio__AdServer_ID__c adServerID = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__AdServer_ID__c adServerID_2 = cls_P7S1_TestData.createTestAdServerID(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true);

        List<ADvendio__Placement__c> lstPlacements = new List<ADvendio__Placement__c>();
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_AdServerID__c = adServerID.Id;
        lstPlacements.add(placement);
        ADvendio__Placement__c placement2 = cls_P7S1_TestData.createTestPlacement(false);
        placement2.SomDig_AdServerID__c = adServerID_2.Id;
        lstPlacements.add(placement2);
        insert lstPlacements;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);

        Test.startTest();

        List<ADvendio__AdServer_ID_AdSpec_Assigment__c> oldAssignments = [
            SELECT Id, ADvendio__AdServer_ID__c
              FROM ADvendio__AdServer_ID_AdSpec_Assigment__c
             WHERE ADvendio__Ad_Spec__c = :adSpec.Id];
        System.assertEquals(1, oldAssignments.size());
        System.assertEquals(adServerID.Id, oldAssignments[0].ADvendio__AdServer_ID__c);

        adSpec.ADvendio__Placement__c = placement2.Id;
        update adSpec;

        Test.stopTest();

        List<ADvendio__AdServer_ID_AdSpec_Assigment__c> newAssignments = [
            SELECT Id, ADvendio__AdServer_ID__c
              FROM ADvendio__AdServer_ID_AdSpec_Assigment__c
             WHERE ADvendio__Ad_Spec__c = :adSpec.Id];
        System.assertEquals(1, newAssignments.size());
        System.assertEquals(adServerID_2.Id, newAssignments[0].ADvendio__AdServer_ID__c);
    }

}