src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_SACConceptionManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ist an diesem Angebot/Auftrag ein SAC/Conception Manager beteilt?
Hier kann der jeweilige SAC /CM verknüpft werden.</description>
        <inlineHelpText>Ist an diesem Angebot/Auftrag ein SAC/Conception Manager beteilt?
Hier kann der jeweilige SAC /CM verknüpft werden.</inlineHelpText>
        <label>SAC/Conception Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_Conception.cls
// class for KV: 02920
// This class prevents saving when some criteria are not met. See KV.
public class Adv_MediaCampaign_Conception{

    public static Set<ID> setConceptionUsers {
        get {
            if (setConceptionUsers == null) {
                setConceptionUsers = new Set<ID>();
                for(GroupMember o : [SELECT Id, UserOrGroupId FROM GroupMember WHERE Group.Name = 'SomDig_ConceptionUser'])
                    setConceptionUsers.add(o.UserOrGroupId);
            }
            return setConceptionUsers;
        }
        set;
    }

    public static void validate(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){
        for(ADvendio__MediaCampaign__c o : (List<ADvendio__MediaCampaign__c>) lstNewItems){
            if(o.SomDig_SACConceptionManager__c == null && setConceptionUsers.contains(UserInfo.getUserId())){
                o.addError('Das Feld SAC/Conception Manager auf der Mediakampagne darf nicht leer sein.');
            }
        }
    }
}