src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Inventarklasse__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Welche Inventarklasse wird das CampaignItem zugeordnet? Erfolgt per Trigger, Indikatoren ist Rotationstyp an der Belegungseinheit, MG-Differenzierung der Werbeform, Preisgruppe des Werbemittels und Auftragstyp der Preisliste.</description>
        <inlineHelpText>Welche Inventarklasse wird das CampaignItem zugeordnet? Erfolgt per Trigger, Indikatoren ist Rotationstyp an der Belegungseinheit, MG-Differenzierung der Werbeform, Preisgruppe des Werbemittels und Auftragstyp der Preisliste.</inlineHelpText>
        <label>Inventarklasse</label>
        <referenceTo>SomDig_Inventarklasse__c</referenceTo>
        <relationshipLabel>Kampagnen Positionen</relationshipLabel>
        <relationshipName>Kampagnen_Positionen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SomDig_Inventarklasse__c.object
<CustomObject>
    <description>zentrales Objekt für alle Inventarklassen der 71m digital</description>
    <label>Inventarklasse</label>
    <nameField>
        <displayFormat>IN-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarklassen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_Inventarklasse_Batch.cls
global class Adv_CampaignItem_Inventarklasse_Batch implements Database.Batchable<sObject>, Schedulable {
    
    public Adv_CampaignItem_Inventarklasse_Batch() {
        
    }
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, 20);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        String sQuery = 'SELECT SomDig_Inventarklasse__c, ADvendio__Ad_Price__c FROM ADvendio__Campaign_Item__c WHERE SomDig_Inventarklasse__c = NULL';
        
        return Database.getQueryLocator(sQuery);
    }
    
    global void execute(Database.BatchableContext bc, List<ADvendio__Campaign_Item__c> scope) {
        Adv_CampaignItem_Inventarklasse.setInventarklassen(scope);
        update scope;
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }

}