src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_BetreuerPam__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Welcher PAM-Mitarbeiter betreut diese Mediakampagne?</description>
        <inlineHelpText>Welcher PAM-Mitarbeiter betreut diese Mediakampagne?</inlineHelpText>
        <label>Campaign Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00eD0000001Qf2o</value>
            </filterItems>
            <filterItems>
                <field>User.P7S1_Sphere__c</field>
                <operation>equals</operation>
                <value>SomDe</value>
            </filterItems>
            <infoMessage>Wert ist nicht vorhanden bzw. stimmt nicht mit Filterkriterien überein: Der Benutzer muss aktiv sein und das Profil SomDig_PAM haben.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Betreuer_PAM_Mediakampagne</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_BetreuerSales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Welcher Sales-Mitarbeiter betreut diese Mediakampagne?</description>
        <inlineHelpText>Welcher Sales-Mitarbeiter betreut diese Mediakampagne?</inlineHelpText>
        <label>Betreuer Sales</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Id</field>
                <operation>equals</operation>
                <value>00e20000001QBtU</value>
            </filterItems>
            <filterItems>
                <field>User.SomDig_SalesTeam__c</field>
                <operation>contains</operation>
                <value>Düsseldorf, Frankfurt, Hamburg, München, Berlin, ECC, RTA</value>
            </filterItems>
            <infoMessage>Wert ist nicht vorhanden bzw. stimmt nicht mit Filterkriterien überein: Der Benutzer muss aktiv sein, das Profil SomDig_Sales haben und einem Sales-Team zugeordnet sein.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Betreuer_Sales_Mediakampagne</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_Owner_Test.cls
@isTest
private class Adv_MediaCampaign_Owner_Test {

    @TestSetup
    static void test_Setup(){
        List<User> listUsers = new List<User>();
        User PAM_User = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        User Sales_User = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_Sales');
        PAM_User.isActive = true;
        listUsers.add(PAM_User);
        Sales_User.isActive = true;
        listUsers.add(Sales_User);
        update listUsers;
     }

    static testmethod void owner_Should_Be_Current_User_On_Insert() {
        ADvendio__MediaCampaign__c l_oMediaCampaign = cls_P7S1_TestData.createTestMediaCampaign(false);
        l_oMediaCampaign.SomDig_BetreuerSales__c = null;
        l_oMediaCampaign.SomDig_BetreuerPam__c = null;

        Test.startTest();

        insert l_oMediaCampaign;

        Test.stopTest();

        reload_MediaCampaign_And_Assert_OwnerId(l_oMediaCampaign, UserInfo.getUserId());
    }

    static testmethod void owner_Should_Be_Betreuer_PAM_On_Insert() {
        Id PAM_UserId = cls_P7S1_TestData.USER_MAP_PROFILE.get('SomDig_PAM');

        ADvendio__MediaCampaign__c l_oMediaCampaign = cls_P7S1_TestData.createTestMediaCampaign(false);
        l_oMediaCampaign.SomDig_BetreuerSales__c = null;
        l_oMediaCampaign.SomDig_BetreuerPam__c = PAM_UserId;
        l_oMediaCampaign.ADvendio__Stage__c = 'IO received';

        Test.startTest();

        insert l_oMediaCampaign;

        Test.stopTest();

        reload_MediaCampaign_And_Assert_OwnerId(l_oMediaCampaign, PAM_UserId);
    }

    static testmethod void owner_Should_Be_Betreuer_Sales_On_Insert() {
        Id SalesUserId = cls_P7S1_TestData.USER_MAP_PROFILE.get('SomDig_Sales');

        ADvendio__MediaCampaign__c l_oMediaCampaign = cls_P7S1_TestData.createTestMediaCampaign(false);
        l_oMediaCampaign.SomDig_BetreuerSales__c = SalesUserId;
        l_oMediaCampaign.SomDig_BetreuerPam__c = null;

        Test.startTest();

        insert l_oMediaCampaign;

        Test.stopTest();

        reload_MediaCampaign_And_Assert_OwnerId(l_oMediaCampaign, SalesUserId);
    }

    static testmethod void owner_Should_Be_Betreuer_PAM_On_Update() {
        Id PAM_UserId = cls_P7S1_TestData.USER_MAP_PROFILE.get('SomDig_PAM');
        Id SalesUserId = cls_P7S1_TestData.USER_MAP_PROFILE.get('SomDig_Sales');

        ADvendio__MediaCampaign__c l_oMediaCampaign = cls_P7S1_TestData.createTestMediaCampaign(false);
        l_oMediaCampaign.SomDig_BetreuerSales__c = SalesUserId;
        l_oMediaCampaign.SomDig_BetreuerPam__c = PAM_UserId;
        insert l_oMediaCampaign;

        reload_MediaCampaign_And_Assert_OwnerId(l_oMediaCampaign, SalesUserId);

        Test.startTest();

        l_oMediaCampaign.ADvendio__Stage__c = 'Booked';
        update l_oMediaCampaign;

        Test.stopTest();

        reload_MediaCampaign_And_Assert_OwnerId(l_oMediaCampaign, PAM_UserId);
    }

    private static void reload_MediaCampaign_And_Assert_OwnerId(ADvendio__MediaCampaign__c p_oMediaCampaign, Id p_sOwnerId) {
        ADvendio__MediaCampaign__c l_oMediaCampaign = [SELECT Id, OwnerId FROM ADvendio__MediaCampaign__c WHERE Id = :p_oMediaCampaign.Id];
        System.assertEquals(p_sOwnerId, l_oMediaCampaign.OwnerId);
    }
}