src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__DoNotShowOnProposalPDF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not Show on Proposal PDF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__NotRelevantForTurnover__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox controls if the amount is summed up to the related account or not.</description>
        <inlineHelpText>This checkbox controls if the amount is summed up to the related account or not.</inlineHelpText>
        <label>Not Relevant For Turnover</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__ShowOnInvoicePDF__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show on Invoice PDF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_PDFCheckboxes_Test.cls
@isTest
public class Adv_CampaignItem_PDFCheckboxes_Test {

    static testMethod void testSetPDFCheckboxes(){
        

        List<ADvendio__Campaign_Item__c> listCI = new List<ADvendio__Campaign_Item__c>();
        
        ADvendio__Ad_Price__c adprice = cls_P7S1_TestData.createTestAdPrice(true, cls_P7S1_TestData.createTestPricelist(true));
        ADvendio__MediaCampaign__c camp = cls_P7S1_TestData.createTestMediaCampaign(true);

        // Nachlieferung           
        ADvendio__Campaign_Item__c objCINL = cls_P7S1_TestData.createTestCampaignItem(false, camp, adprice);
        objCINL.ADvendio__Rate_Discount_4_Name__c = 'Nachlieferung';
        listCI.add(objCINL);
        
        // Storno mit Leistungsfluss
        ADvendio__Campaign_Item__c objCISML = cls_P7S1_TestData.createTestCampaignItem(false, camp, adprice);
        objCISML.ADvendio__Rate_Discount_4_Name__c = 'Storno mit Leistungsfluss';
        listCI.add(objCISML);

        // Storno ohne Leistungsfluss        
        ADvendio__Campaign_Item__c objCISOL = cls_P7S1_TestData.createTestCampaignItem(false, camp, adprice);
        objCISOL.ADvendio__from_Date__c = Date.today().addDays(1);
        objCISOL.ADvendio__Rate_Discount_4_Name__c = 'Storno ohne Leistungsfluss';
        listCI.add(objCISOL);

        // Default campaign item        
        ADvendio__Campaign_Item__c objCIdef = cls_P7S1_TestData.createTestCampaignItem(false, camp, adprice);
        listCI.add(objCIdef);                 
        
        Test.startTest();
        insert listCI;
        Test.stopTest();        
        
        objCINL = [SELECT ADvendio__DoNotShowOnProposalPDF__c, ADvendio__ShowOnInvoicePDF__c, ADvendio__BillMe__c, ADvendio__NotRelevantForTurnover__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCINL.ID limit 1];
        System.assert(objCINL.ADvendio__DoNotShowOnProposalPDF__c == true);                
        System.assert(objCINL.ADvendio__ShowOnInvoicePDF__c == false);
        System.assert(objCINL.ADvendio__BillMe__c == false);   
        System.assert(objCINL.ADvendio__NotRelevantForTurnover__c == true);                  
        
        objCISML = [SELECT ADvendio__DoNotShowOnProposalPDF__c, ADvendio__ShowOnInvoicePDF__c, ADvendio__BillMe__c, ADvendio__NotRelevantForTurnover__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCISML.ID limit 1];
        System.assert(objCISML.ADvendio__DoNotShowOnProposalPDF__c == true);                
        System.assert(objCISML.ADvendio__ShowOnInvoicePDF__c == false);   
        System.assert(objCISML.ADvendio__BillMe__c == false);   
        System.assert(objCISML.ADvendio__NotRelevantForTurnover__c == true);                          
        
        objCISOL = [SELECT ADvendio__DoNotShowOnProposalPDF__c, ADvendio__ShowOnInvoicePDF__c, ADvendio__BillMe__c, ADvendio__NotRelevantForTurnover__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCISOL.ID limit 1];
        System.assert(objCISOL.ADvendio__DoNotShowOnProposalPDF__c == true);                
        System.assert(objCISOL.ADvendio__ShowOnInvoicePDF__c == false);
        System.assert(objCISOL.ADvendio__BillMe__c == false);   
        System.assert(objCISOL.ADvendio__NotRelevantForTurnover__c == true);

        objCIdef = [SELECT ADvendio__DoNotShowOnProposalPDF__c, ADvendio__ShowOnInvoicePDF__c, ADvendio__BillMe__c, ADvendio__NotRelevantForTurnover__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCIdef.ID limit 1];
        System.assert(objCIdef.ADvendio__DoNotShowOnProposalPDF__c == false);                
        System.assert(objCIdef.ADvendio__ShowOnInvoicePDF__c == true);
        System.assert(objCIdef.ADvendio__BillMe__c == true);   
        System.assert(objCIdef.ADvendio__NotRelevantForTurnover__c == false);                                            
    }
}