src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_DienstleistungbezogeneHelp__c</fullName>
        <description>Hilfsfeld zur Ermittlung der PriorValue (bitte NICHT LÖSCHEN); wird per Trigger befüllt</description>
        <label>Dienstleistungbezogene Positionen Help</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_DienstleistungspositionenHelp__c</fullName>
        <description>Hilfsfeld zur Ermittlung der PriorValue (bitte NICHT LÖSCHEN); wird per Trigger befüllt</description>
        <label>Dienstleistungspositionen Help</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_PopUp_Test.cls
@isTest
private with sharing class Adv_MediaCampaign_PopUp_Test {

    static testmethod void testMedia() {
        ADvendio__Campaign_Item__c ci1 = cls_P7S1_TestData.createTestCampaignItem(true);
        ADvendio__MediaCampaign__c I_otestMediaCampaign = cls_P7S1_TestData.MediaCampaign_TestData;

        Test.startTest();

        ApexPages.StandardController I_osc = new ApexPages.StandardController(I_otestMediaCampaign);
        Adv_MediaCampaign_PopUp I_oMCC = new Adv_MediaCampaign_PopUp(I_osc);

        ADvendio__MediaCampaign__c I_otestMediaCampaign1 = cls_P7S1_TestData.createTestMediaCampaign(false);
        I_otestMediaCampaign.ADvendio__Stage__c = 'Booked';
        I_otestMediaCampaign1.SomDig_DienstleistungbezogeneHelp__c = 0;
        I_otestMediaCampaign1.SomDig_DienstleistungspositionenHelp__c = 0;
        insert I_otestMediaCampaign1;

        ApexPages.StandardController I_osc1 = new ApexPages.StandardController(I_otestMediaCampaign1);
        Adv_MediaCampaign_PopUp I_oMCC1 = new Adv_MediaCampaign_PopUp(I_osc1);

        Test.stopTest();
    }

}