src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_MasterMediaCampaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Feld wird autom. befüllt bei Auftragssplitt mit Info/LookUp der Ursprungskampagne</description>
        <inlineHelpText>Feld wird autom. befüllt bei Auftragssplitt mit Info/LookUp der Ursprungskampagne</inlineHelpText>
        <label>Master-Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Mediakampagnen</relationshipLabel>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_Split_Test.cls
@isTest
private class Adv_MediaCampaign_Split_Test {

    static testMethod void testSplit() {
        ADvendio__MediaCampaign__c mediaCampaign = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(true, mediaCampaign.ADvendio__Pricelist__r);
        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        ADvendio__Campaign_Item__c campaignItem2 = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        List<ADvendio__Campaign_Item__c> items = new List<ADvendio__Campaign_Item__c>{campaignItem1, campaignItem2};
        insert items;

        Test.startTest();

        ApexPages.StandardController ctrl= new ApexPages.StandardController(mediaCampaign);

        Adv_MediaCampaign_Split cls = new Adv_MediaCampaign_Split(ctrl);

        System.assertEquals('showBtnSplit:true','showBtnSplit:'+cls.showBtnSplit);

        for(Adv_MediaCampaign_Split.ItemWrapper w: cls.itmWrappers){
                //user selects only packet item then its component item will follow
                if(w.item.id==items[0].Id)w.selected=true;
        }

        //button split
        PageReference p=cls.back();
        System.assertEquals('button back:true','button back:'+p.getUrl().contains('/'+mediaCampaign.Id));
        p=cls.split();

        //Naviaget to new Media campaign
        System.assertEquals('button split:true','button split:'+(!p.getUrl().contains('/'+mediaCampaign.Id)));

        //splited items
        Map<Id, List<ADvendio__Campaign_Item__c>> mSplitItem=new Map<Id, List<ADvendio__Campaign_Item__c>>();
        for(ADvendio__Campaign_Item__c itm1: [select ADvendio__Media_Campaign__c FROM ADvendio__Campaign_Item__c WHERE
            //New MediaCampaign will lookup to orginal MediaCampaign by reffernce field
            ADvendio__Media_Campaign__c IN (Select Id FROM ADvendio__MediaCampaign__c WHERE SomDig_MasterMediaCampaign__c=:mediaCampaign.Id OR Id=:mediaCampaign.Id)])

            {

            List<ADvendio__Campaign_Item__c> l=mSplitItem.get(itm1.ADvendio__Media_Campaign__c);
            if(l==null)l=new List<ADvendio__Campaign_Item__c>();

            l.add(itm1);
            mSplitItem.put(itm1.ADvendio__Media_Campaign__c,l);

        }

        Test.stopTest();
    }

}