src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__LinearDistribution__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Linear Distribution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__PaymentInterval__c</fullName>
        <description>Essential for the Billing &amp; Accounting App and needs to be filled.</description>
        <inlineHelpText>Please choose the invoice interval</inlineHelpText>
        <label>Payment Interval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>total account (one Invoice)</fullName>
                </value>
                <value>
                    <fullName>monthly (1 month)</fullName>
                    <default>true</default>
                    <label>monthly (1 month)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentStart__c</fullName>
        <description>Essential for the Billing &amp; Accounting App and needs to be filled.</description>
        <inlineHelpText>First Invoice before or after Campaignstart?</inlineHelpText>
        <label>Payment Start</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ADvendio__PaymentInterval__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>before / during Billingperiod</fullName>
                </value>
                <value>
                    <fullName>after Billingperiod</fullName>
                    <default>true</default>
                    <label>after Billingperiod</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_LineareVerteilung.cls
public with sharing class Adv_CampaignItem_LineareVerteilung extends TriggerController{
	/**
	 * Constructor.
	 * @see TriggerController   The base class of trigger controller.
	 */
    public Adv_CampaignItem_LineareVerteilung(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
                                         List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }

    // before Insert
    protected override void runBeforeInsert() {
        getLinearDistributionFromCampaign((List<ADvendio__Campaign_Item__c>) lstNewItems, null);
    }

    // before Update
    protected override void runBeforeUpdate() {
        getLinearDistributionFromCampaign((List<ADvendio__Campaign_Item__c>) lstNewItems, (Map<Id, ADvendio__Campaign_Item__c>) mapOldItems);
    }

    /**
    * force campaign-items to use linear-distribution if their campaign demands for it
    * @param	a list of ADvendio__Campaign_Item__c records (trigger.new)
    * @param	a map of ADvendio__Campaign_Item__c records (trigger.oldMap)
    **/
    private void getLinearDistributionFromCampaign(List<ADvendio__Campaign_Item__c> newItems, Map<Id, ADvendio__Campaign_Item__c> oldItemMap) {
    	Map<Id, ADvendio__MediaCampaign__c> mediaCampaigns	= new Map<Id, ADvendio__MediaCampaign__c>();

    	for (ADvendio__Campaign_Item__c ci : newItems) {
    		if ((	isInsert ||
    				ci.ADvendio__LinearDistribution__c != oldItemMap.get(ci.Id).ADvendio__LinearDistribution__c)
    				&& !ci.ADvendio__LinearDistribution__c
    			) {
    			mediaCampaigns.put(ci.ADvendio__Media_Campaign__c, null);
    		}
    	}

    	if (!mediaCampaigns.isEmpty()) {
    		for (ADvendio__MediaCampaign__c mc : [SELECT Id, ADvendio__PaymentInterval__c, ADvendio__PaymentStart__c FROM ADvendio__MediaCampaign__c WHERE Id IN :mediaCampaigns.keySet()]) {
    			mediaCampaigns.put(mc.Id, mc);
    		}

    		for (ADvendio__Campaign_Item__c ci : newItems) {
    			if ((	isInsert ||
	    				ci.ADvendio__LinearDistribution__c != oldItemMap.get(ci.Id).ADvendio__LinearDistribution__c)
	    				&& !ci.ADvendio__LinearDistribution__c
	    			) {

	    			ADvendio__MediaCampaign__c mc	= mediaCampaigns.get(ci.ADvendio__Media_Campaign__c);
	    			if (Adv_MediaCampaign_LineareVerteilung.isVorkasse(mc)) {
	    				ci.ADvendio__LinearDistribution__c	= true;
	    			}
    			}
    		}
    	}
    }
}