src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Id__c</fullName>
        <description>The ad server interface will enter the ID of the ad when booked to the ad server.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ad server interface will enter the ID of the ad when booked to the ad server.</inlineHelpText>
        <label>Ad Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SomDig_AdServerRelevant__c</fullName>
        <description>True, wenn der RecordType der Werbeform nicht Standard ist. Bei Pakethüllen immer false.</description>
        <formula>ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.DeveloperName != &apos;Standard&apos; &amp;&amp;  RecordType.DeveloperName != &apos;Packet&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>KV 03459. True, wenn der RecordType der Werbeform nicht Standard ist. Bei Pakethüllen immer false.</inlineHelpText>
        <label>SomDig_AdServerRelevant</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_AuftragstypId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Steuert die Auslieferungsprioritäten in den AdServern, die Einschränkung auf mögliche Produkte/Werbemittel, ggf. auch Steuerung von fixem FC bei einigen Auftragstypen &amp; Voreinstellung der Rechnungsstellung etc.</description>
        <inlineHelpText>Bitte die Auftragstypen angeben. Diese steuert die Auslieferungsprioritäten in den AdServern, die Einschränkung auf mögliche Produkte/Werbemittel, ggf. auch Steuerung von fixem FC bei einigen Auftragstypen &amp; Voreinstellung der Rechnungsstellung etc.</inlineHelpText>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Preislisten</relationshipLabel>
        <relationshipName>Preislisten</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_ValidateStatus.cls
// class for KV: 02794
// This class prevents saving when some criteria are not met.
public class Adv_MediaCampaign_ValidateStatus{

    public static void validate(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){

        if(lstNewItems.size() != 1) return;
        
        ADvendio__MediaCampaign__c objMC = (ADvendio__MediaCampaign__c) lstNewItems[0];
        ADvendio__MediaCampaign__c objMCOld = (ADvendio__MediaCampaign__c) mapOldItems.get(objMC.ID);              
        
        // If Set to Booked, (Geschlossen & Gewonnen)
        if(objMC.ADvendio__Stage__c == 'Booked' && objMCOld.ADvendio__Stage__c != 'Booked'){
            
            Boolean bAllowSaving = true;
            
            for(ADvendio__Campaign_Item__c o : [SELECT ADvendio__Media_Campaign__r.ADvendio__Pricelist__r.SomDig_AuftragstypId__r.SomDig_VerhinderungAuftragssetzung__c FROM ADvendio__Campaign_Item__c WHERE RecordType.DeveloperName != 'Packet' AND ADvendio__Media_Campaign__c = :objMC.ID AND SomDig_AdServerRelevant__c = true AND ADvendio__Ad_Id__c = null])
                if(o.ADvendio__Media_Campaign__r.ADvendio__Pricelist__r.SomDig_AuftragstypId__r.SomDig_VerhinderungAuftragssetzung__c)
                    bAllowSaving = false;

            
            if(!bAllowSaving)
                objMC.addError('Mindestens eine AdServer-Relevante Position wurde noch nicht durchgebucht.');       

        }
    }
}