src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the ad server ID.</inlineHelpText>
        <label>AdServer ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Parent_AdServer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If there is a superior ad server ID, you can enter its ID here.</description>
        <inlineHelpText>If there is a superior ad server ID, you can enter its ID here.</inlineHelpText>
        <label>Parent AdServer ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Medium zur Übertragung von Werbebotschaften</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsSegment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gruppierung der gelieferten Produkte nach ihrer Art: z.B. InApp/Mobile, InBrowser/Online, Connected TV/HbbTv, NonMedia usw.</description>
        <inlineHelpText>Gruppierung der gelieferten Produkte nach ihrer Art: z.B. InApp/Mobile, InBrowser/Online, Connected TV/HbbTv, NonMedia usw.</inlineHelpText>
        <label>Mediagattungs-Segment</label>
        <referenceTo>SomDig_MediagattungsSegment__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_TopMediagattungsSegment__c</fullName>
        <description>Da wir in dfp nur max. 4 Stufen der Adunits haben/nutzen reicht in diesem Fall eine Formel welche über diese 4 Stufen die Zuordnung der manuell zugeordneten obersten Ebene an die darunterliegenden Adunits vererbt.</description>
        <formula>IF (ISBLANK(ADvendio__Parent_AdServer_ID__c),
    null,
    IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
        SomDig_MediagattungsSegment__c,
        IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
            ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c,
            IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c,
                IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c,
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c
                   )
               )
           )
       )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Top Mediagattungs-Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_TopSite__c</fullName>
        <formula>IF (ISBLANK(ADvendio__Parent_AdServer_ID__c),
    null,
    IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
        ADvendio__Site__c,
        IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
            ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c,
            IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c,
                IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c,
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c
                   )
               )
           )
       )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Top Site</label>
        <type>Text</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsSegment__c.object
<CustomObject>
    <description>Zwischendifferenzierung/Segmentierung einer Belegungseinheit</description>
    <label>Mediagattungs-Segment</label>
    <nameField>
        <label>Mediagattungs-Segment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Segmente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_AdServerId_AdUnitHierarchy_Test.cls
@isTest
private class Adv_AdServerId_AdUnitHierarchy_Test {

    static testMethod void testAdv_AdServerId_AdUnitHierarchy() {
        Test.startTest();

        ADvendio__Site__c site = cls_P7S1_TestData.createTestSite(true);
        SomDig_MediagattungsSegment__c mg = cls_P7S1_TestData.createTestMediagattungsSegment(true);

        ADvendio__AdServer_ID__c adserv1 = cls_P7S1_TestData.createTestAdServerID(true);

        ADvendio__AdServer_ID__c adserv2 = cls_P7S1_TestData.createTestAdServerID(false);
        adserv2.ADvendio__Parent_AdServer_ID__c = adserv1.Id;
        insert adserv2;

        ADvendio__AdServer_ID__c adserv3 = cls_P7S1_TestData.createTestAdServerID(false);
        adserv3.ADvendio__Parent_AdServer_ID__c = adserv2.Id;
        insert adserv3;

        // Now test the class.
        Adv_AdServerId_AdUnitHierarchy c = new Adv_AdServerId_AdUnitHierarchy();
        c.setRecordIds(null);
        c.addRecordId(adserv2.Id);

        Database.executeBatch(c, 1);

        String sch = '0 0 23 * * ?';
        System.schedule('Test RechnungsproduktErstellen', sch, c);

        // Test logic and etc.
        ADvendio__AdServer_ID__c adserv = [SELECT ADvendio__Site__c, SomDig_MediagattungsSegment__c FROM ADvendio__AdServer_ID__c WHERE Id = :adserv3.Id];

        System.assertEquals(null, adserv.ADvendio__Site__c);
        System.assertEquals(null, adserv.SomDig_MediagattungsSegment__c);

        adserv2.ADvendio__Site__c = site.Id;
        adserv2.SomDig_MediagattungsSegment__c = mg.Id;
        update adserv2;

        adserv = [SELECT ADvendio__Site__c, SomDig_MediagattungsSegment__c, SomDig_TopSite__c, SomDig_TopMediagattungsSegment__c FROM ADvendio__AdServer_ID__c WHERE Id = :adserv3.Id];

        System.assertEquals(null, adserv.ADvendio__Site__c);
        System.assertEquals(null, adserv.SomDig_MediagattungsSegment__c);
        System.assertNotEquals(null, adserv.SomDig_TopSite__c);
        System.assertNotEquals(null, adserv.SomDig_TopMediagattungsSegment__c);

        c.execute(null, new List<ADvendio__AdServer_ID__c> {adserv});

        adserv = [SELECT ADvendio__Site__c, SomDig_MediagattungsSegment__c FROM ADvendio__AdServer_ID__c WHERE Id = :adserv3.Id];

        System.assertEquals(site.Id, adserv.ADvendio__Site__c);
        System.assertEquals(mg.Id, adserv.SomDig_MediagattungsSegment__c);

        Test.stopTest();
    }
}