src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Availability__c</fullName>
        <description>The ad server interface will enter the availability during an availabilty request.</description>
        <inlineHelpText>The ad server interface will enter the availability during an availabilty request.</inlineHelpText>
        <label>Availability (planned)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__LastAvailabilityForecast__c</fullName>
        <description>Last Availability Forecast run</description>
        <label>Last Availability Forecast</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>CASESAFEID(ADvendio__Media_Campaign__r.ADvendio__Pricelist__r.SomDig_AuftragstypId__c)</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Verfuegbarkeitsrelevant__c</fullName>
        <description>Benötigt für KV 02429. An diesem Feld erkennt man, ob die Mediakampagne für die Verfügbarkeitsabfrage relevant ist.</description>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__r.SomDig_Verfuegbarkeitsrelevant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Verfügbarkeitsrelevant</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <fields>
        <fullName>SomDig_Verfuegbarkeitsrelevant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Wenn nicht angehakt, dürfen Positionen der Kampagne in jedem Fall durchgebucht werden.</description>
        <label>Verfügbarkeitsrelevant</label>
        <type>Checkbox</type>
    </fields>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_Remoter_Test.cls
@isTest
public class Adv_CampaignItem_Remoter_Test{

    public static testMethod void CampaignItemRemoterTest(){
        
        // Create Objects
        SomDig_Auftragstyp__c objAT = cls_P7S1_TestData.createTestAuftragstyp(false, 'Test');
        objAT.SomDig_Verfuegbarkeitsrelevant__c = true;
        insert objAT;
        
        
        ADvendio__Pricelist__c objPL = cls_P7S1_TestData.createTestPricelist(true, objAT);
        
        
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.ADvendio__Pricelist__c = objPL.ID;
        insert objMC;
        
        
        // Campaign Item
        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        objCI.ADvendio__LastAvailabilityForecast__c = System.now();
        insert objCI;
        
        objCI.ADvendio__until_Date__c = objCI.ADvendio__until_Date__c.addDays(2);
        objCI.ADvendio__from_Date__c = objCI.ADvendio__from_Date__c.addDays(1);
        update objCI;
        
        objCI.ADvendio__Availability__c = 1;        
        update objCI;        
        
        
        
        // Call Method
        Adv_CampaignItem_Remoter.checkAvailability(objCI.ID);
    }
}