src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This reference displays the ad spec to which this price is assigned.</description>
        <inlineHelpText>This reference displays the ad spec to which this price is assigned.</inlineHelpText>
        <label>Ad Spec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__List_price__c</fullName>
        <description>Enter the list price assigned to the chosen billing category.</description>
        <inlineHelpText>Enter the list price assigned to the chosen billing category.</inlineHelpText>
        <label>List price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <description>This field displays the sites assigned to this ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp; ADvendio__Placement__r.ADvendio__Site__r.Id , ADvendio__Placement__r.ADvendio__Site__r.Name)</formula>
        <inlineHelpText>This field displays the sites assigned to this ad spec.</inlineHelpText>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This formula displays the corresponding ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp;  ADvendio__Ad_Price__r.ADvendio__Ad_Spec__c  , ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.Name)</formula>
        <inlineHelpText>This formula displays the corresponding ad spec.</inlineHelpText>
        <label>Ad Spec</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Impressions__c</fullName>
        <description>The ad server interface will enter the delivered impressions here.</description>
        <inlineHelpText>The ad server interface will enter the delivered impressions here. (technical View)</inlineHelpText>
        <label>Delivered Impressions</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__List_Price__c</fullName>
        <description>The formula displays the list price for this advertising type as defined by the product management.</description>
        <formula>ADvendio__Ad_Price__r.ADvendio__List_price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The formula displays the list price for this advertising type as defined by the product management.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packet Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Sales_Price__c</fullName>
        <description>Enter the sales price for this campaign item.</description>
        <inlineHelpText>Enter the sales price for this campaign item.</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <description>Enter the site assigned to this placement.</description>
        <inlineHelpText>Enter the site assigned to this placement.</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SomDig_Typ__c</fullName>
        <description>Welchem Netzwerk gehört diese Belegungseinheit an?</description>
        <inlineHelpText>Welchem Netzwerk gehört diese Belegungseinheit an? Achtung dies hat Einfluss auf Auslieferungstyp und Priomodell.</inlineHelpText>
        <label>Netzwerk-Typ</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>71m intern</fullName>
                    <default>true</default>
                    <label>71m intern</label>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_PackageSumDelive_Test.cls
@isTest
public with sharing class Adv_CampaignItem_PackageSumDelive_Test {
   static testMethod void testSumPackageDeliveries() {
        // Create a Site
        ADvendio__Site__c adSite = new ADvendio__Site__c(Name = 'Site 1');
        insert adSite;

        // Create a Placement
        List<ADvendio__Placement__c> lstAdP = new List<ADvendio__Placement__c>();
        lstAdP.add(new ADvendio__Placement__c(Name='Placement 1', SomDig_Typ__c='YouTube',ADvendio__Site__c=adSite.Id));
        insert lstAdP;

        // Create 3 ad specs
        List<ADvendio__Ad_Specs__c> lstAdS = new List<ADvendio__Ad_Specs__c>();
        for(Integer i=0;i<3;i++){
            lstAdS.add(new ADvendio__Ad_Specs__c(Name='Ad Spec'+i, ADvendio__Placement__c=lstAdP[0].Id));
        }
        insert lstAdS;

        // Create 3 ad price
        List<ADvendio__Ad_price__c> lstAdPrice = new List<ADvendio__Ad_price__c>();
        for (Integer i=0;i<3;i++){
            lstAdPrice.add(new ADvendio__Ad_price__c(ADvendio__Ad_Spec__c=lstAdS[i].Id, ADvendio__List_price__c=1000));
        }
        insert lstAdPrice;

        ADvendio__MediaCampaign__c adM = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c ciP = new ADvendio__Campaign_Item__c(ADvendio__Billing_category__c='CPM', ADvendio__Ad_Price__c=lstAdPrice[0].Id, ADvendio__Media_Campaign__c=adM.Id, ADvendio__Quantity__c=20, ADvendio__Sales_Price__c=100, ADvendio__from_Date__c=System.today(), ADvendio__until_Date__c=System.today());
        insert ciP;

        // Create 2 component items
        List<ADvendio__Campaign_Item__c> lstComponents = new List<ADvendio__Campaign_Item__c>();
        ADvendio__Campaign_Item__c ci01 = new ADvendio__Campaign_Item__c(ADvendio__PacketItem__c=ciP.Id, ADvendio__Billing_category__c='CPM', ADvendio__Ad_Price__c=lstAdPrice[1].Id, ADvendio__Media_Campaign__c=adM.Id, ADvendio__Quantity__c=5, ADvendio__Sales_Price__c=100, ADvendio__from_Date__c=System.today(), ADvendio__until_Date__c=System.today());
        ADvendio__Campaign_Item__c ci02 = new ADvendio__Campaign_Item__c(ADvendio__PacketItem__c=ciP.Id, ADvendio__Billing_category__c='CPM', ADvendio__Ad_Price__c=lstAdPrice[2].Id, ADvendio__Media_Campaign__c=adM.Id, ADvendio__Quantity__c=15, ADvendio__Sales_Price__c=100, ADvendio__from_Date__c=System.today(), ADvendio__until_Date__c=System.today());
        insert new List<ADvendio__Campaign_Item__c>{ci01, ci02};

        Test.startTest();

        ci01.ADvendio__Delivered_Impressions__c = 15;
        ci02.ADvendio__Delivered_Impressions__c = 5;

        update new List<ADvendio__Campaign_Item__c>{ci01, ci02};

        ciP = [Select Id, ADvendio__Delivered_Impressions__c From ADvendio__Campaign_Item__c Where Id = :ciP.Id];
        System.assertEquals(20, ciP.ADvendio__Delivered_Impressions__c);

        Test.stopTest();
    }    
}