src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the ad server ID.</inlineHelpText>
        <label>AdServer ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Type__c</fullName>
        <description>Choose which type of ad server ID is concerned.</description>
        <inlineHelpText>Choose which type of ad server ID is concerned.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Site</fullName>
                </value>
                <value>
                    <fullName>Zone</fullName>
                </value>
                <value>
                    <fullName>Zone Group</fullName>
                </value>
                <value>
                    <fullName>Content Category</fullName>
                </value>
                <value>
                    <fullName>Content Unit</fullName>
                </value>
                <value>
                    <fullName>Content Unit Group</fullName>
                </value>
                <value>
                    <fullName>Page</fullName>
                </value>
                <value>
                    <fullName>Page Group</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Format</fullName>
                </value>
                <value>
                    <fullName>Placement</fullName>
                </value>
                <value>
                    <fullName>Ad Unit</fullName>
                </value>
                <value>
                    <fullName>Key</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ADvendio__Type__c</field>
                <operation>equals</operation>
                <value>Ad Unit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>P7S1_Format__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_Format__c.object
<CustomObject>
    <description>Formate wie zum Beispiel Anna und die Liebe oder 2 Broke Grils</description>
    <fields>
        <fullName>P7S1_GueltigBis__c</fullName>
        <description>Bis wann ist dieses Format gültig?</description>
        <inlineHelpText>Bis wann ist dieses Format gültig?</inlineHelpText>
        <label>gültig bis</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P7S1_GueltigVon__c</fullName>
        <description>ab wann ist dieses Format gültig?</description>
        <inlineHelpText>Ab wann ist dieses Format gültig?</inlineHelpText>
        <label>gültig von</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cls_P7S1_Format_AdServerLinking_Test.cls
@isTest
public class cls_P7S1_Format_AdServerLinking_Test{
    @isTest
    private static void testFormat_AdServerLinking(){
        P7S1_Format__c I_oFormatObj = new P7S1_Format__c();
        I_oFormatObj.P7S1_GueltigVon__c = System.today();
				I_oFormatObj.P7S1_GueltigBis__c = System.today().addDays(1);
        insert I_oFormatObj;

        String I_sRdTypeId = [Select SobjectType, Name From RecordType Where sobjecttype =: 'ADvendio__AdServer_ID__c' AND Name =: 'DFP'].Id;
        System.assert(I_sRdTypeId != null,'Record Type not found');

        ADvendio__AdServer_ID__c I_oAdServerIdObj = new ADvendio__AdServer_ID__c();
        I_oAdServerIdObj.Name = 'adscale';
        I_oAdServerIdObj.RecordTypeId = I_sRdTypeId;
        I_oAdServerIdObj.P7S1_Format__c = I_oFormatObj.Id;
        I_oAdServerIdObj.ADvendio__Type__c = 'Ad Unit';
        insert I_oAdServerIdObj;

        ADvendio__AdServer_ID__c I_oAdServerIdO = new ADvendio__AdServer_ID__c();
        I_oAdServerIdO.Name = 'adscale';
        I_oAdServerIdO.RecordTypeId = I_sRdTypeId;
        I_oAdServerIdO.ADvendio__Type__c = 'Ad Unit';
        insert I_oAdServerIdO;

        ApexPages.CurrentPage().getParameters().put('formatId',I_oFormatObj.Id);
        cls_P7S1_Format_AdServerLinking I_clsOb = new cls_P7S1_Format_AdServerLinking();
        I_clsOb.i_sSearchText = 'adscale';
        I_clsOb.Search();
        PageReference I_pg2 = I_clsOb.Save();
        System.assert(I_pg2 != null);
        PageReference I_pg3 = I_clsOb.Cancel();
        System.assert(I_pg3 != null);

        List<ADvendio__AdServer_ID__c> I_oAdServerList = new List<ADvendio__AdServer_ID__c>();
        for(Integer i = 0;i < 1000;i++){
            ADvendio__AdServer_ID__c I_oAdServerIdOb = new ADvendio__AdServer_ID__c();
            I_oAdServerIdOb.Name = 'test'+i;
            I_oAdServerIdOb.RecordTypeId = I_sRdTypeId;
            I_oAdServerIdOb.ADvendio__Type__c = 'Ad Unit';
            I_oAdServerList.add(I_oAdServerIdOb);
        }
        insert I_oAdServerList;

        cls_P7S1_Format_AdServerLinking I_clsObj = new cls_P7S1_Format_AdServerLinking();
        I_clsObj.i_sSearchText = 't*';
        I_clsObj.Search();
        PageReference I_pg = I_clsObj.Save();
        System.assert(I_pg != null);
        PageReference I_pg1 = I_clsObj.Cancel();
        System.assert(I_pg1 != null);

    }
}