src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Frequency__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Frequency</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_2_custom__c</fullName>
        <label>Customer Discount custom</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_3__c</fullName>
        <formula>IF( ISNULL(ADvendio__Rate_Discount_3_custom__c), ADvendio__Media_Campaign__r.ADvendio__Rate_Discount_3__c, ADvendio__Rate_Discount_3_custom__c)</formula>
        <label>Agency Discount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_3_custom__c</fullName>
        <label>Agency Discount custom</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4__c</fullName>
        <description>Enter a special discount which will only be applied to this campaign item.</description>
        <inlineHelpText>Enter a special discount which will only be applied to this campaign item.</inlineHelpText>
        <label>Special Discount</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ADvendio__Sales_Price__c</fullName>
        <description>Enter the sales price for this campaign item.</description>
        <inlineHelpText>Enter the sales price for this campaign item.</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__SurchargeB3Abs__c</fullName>
        <description>This surcharge will be added to Gross Amount B3 to get Gross Amount B2.</description>
        <inlineHelpText>This surcharge will be added to Gross Amount B3 to get Gross Amount B2.</inlineHelpText>
        <label>Surcharge B3 (Abs.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__SurchargeB3__c</fullName>
        <description>This surcharge will be added to Gross Amount B3 to get Gross Amount B2.</description>
        <inlineHelpText>This surcharge will be added to Gross Amount B3 to get Gross Amount B2.</inlineHelpText>
        <label>Surcharge B3 (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ADvendio__SurchargeSalesPrice__c</fullName>
        <description>The value from that field will be added to the amount calculation - applicable only for CPM AdPrices.</description>
        <label>Surcharge Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierungName__c</fullName>
        <description>MGD- Name für RollUps, Reports etc. Info kommt in diesem Fall aus dem Werbemittel, da Objektverweis bis hin zum WMSegment über das Limit von 15 reicht. Siehe auch KV 2551.</description>
        <formula>ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.SomDig_MediagattungsDifferenzierung__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>MGD-Name für RollUps, Reports etc. Info kommt automatisch via Werbemittel aus der Werbeform</inlineHelpText>
        <label>Mediagattungs-Differenzierung Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Menge__c</fullName>
        <description>Menge ohne anteiligen Naturalrabatt (Ticket 06323)</description>
        <label>Menge (ohne Naturalrabatt)</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_Naturalrabatt__c</fullName>
        <description>Naturalrabatt in Prozent (Ticket 06323)</description>
        <label>Naturalrabatt</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_RabatteFreigegebenCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hilfsfeld; wird per WF aktiviert, wenn Rabattlimit/Mindestpreis erreicht und nicht genehmigt</description>
        <inlineHelpText>Hilfsfeld, wird automatisch markiert, wenn Rabattlimits überschritten sind und/oder Mindestpreis erreicht ist aber nicht genehmigt</inlineHelpText>
        <label>Rabatte nicht freigegeben</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box shows whether the media campaign is approved.</description>
        <inlineHelpText>This check box shows whether the media campaign is approved.</inlineHelpText>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_3__c</fullName>
        <description>Enter a agency discount which is automatically applied to all campaign items.</description>
        <inlineHelpText>Enter a agency discount which is automatically applied to all campaign items.</inlineHelpText>
        <label>Agency Discount</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Agenturrabatt__c</fullName>
        <description>Benutzerdefinierter Agenturrabatt, übernimmt Werte aus dem ADvendio Feld &quot;ADvendio__Rate_Discount_3__c&quot; (siehe Ticket 06062)</description>
        <label>Agenturrabatt</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Commitment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commitment</label>
        <referenceTo>SomDig_Commitment__c</referenceTo>
        <relationshipLabel>Mediakampagnen</relationshipLabel>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Kundenrabatt_InPage__c</fullName>
        <description>Kundenrabatt-InPage gesamt</description>
        <inlineHelpText>Kundenrabatt-InPage gesamt</inlineHelpText>
        <label>Kundenrabatt-InPage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Kundenrabatt_InStream__c</fullName>
        <description>Kundenrabatt-InStream gesamt</description>
        <inlineHelpText>Kundenrabatt-InStream gesamt</inlineHelpText>
        <label>Kundenrabatt-InStream</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Naturalrabatt_Inpage__c</fullName>
        <description>Naturalrabatt-Inpage gesamt</description>
        <inlineHelpText>Naturalrabatt-Inpage gesamt</inlineHelpText>
        <label>Naturalrabatt-Inpage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_RabatteMKgenehmigt__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Hilfsfeld; wenn belegt - dann sind die Rabatte genehmigt; kann vom Pagelayout entfernt werden</description>
        <inlineHelpText>Hilfsfeld; wenn belegt - dann sind die Rabatte genehmigt</inlineHelpText>
        <label>Rabatte MK genehmigt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_Sonderrabatt_InPage__c</fullName>
        <description>Sonderrabatt-InPage gesamt</description>
        <inlineHelpText>Sonderrabatt-InPage gesamt</inlineHelpText>
        <label>Sonderrabatt-InPage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Sonderrabatt_InStream__c</fullName>
        <description>Sonderrabatt-InStream gesamt</description>
        <inlineHelpText>Sonderrabatt-InStream gesamt</inlineHelpText>
        <label>Sonderrabatt-InStream</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Commitment__c.object
<CustomObject>
    <description>fasst die heutigen Commitments der Division Digital (aufgebaut im Bezug auf WT-AG Beziehung)</description>
    <fields>
        <fullName>SomDig_Kundenrabatt_InPage__c</fullName>
        <description>Kundenrabatt-InPage gesamt</description>
        <inlineHelpText>Kundenrabatt-InPage gesamt</inlineHelpText>
        <label>Kundenrabatt-InPage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Kundenrabatt_InStream__c</fullName>
        <description>Kundenrabatt-InStream gesamt</description>
        <inlineHelpText>Kundenrabatt-InStream gesamt</inlineHelpText>
        <label>Kundenrabatt-InStream</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Naturalrabatt_Inpage__c</fullName>
        <description>Naturalrabatt-Inpage gesamt</description>
        <inlineHelpText>Naturalrabatt-Inpage gesamt</inlineHelpText>
        <label>Naturalrabatt-Inpage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Sonderrabatt_InPage__c</fullName>
        <description>Sonderrabatt-InPage gesamt</description>
        <inlineHelpText>Sonderrabatt-InPage gesamt</inlineHelpText>
        <label>Sonderrabatt-InPage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_Sonderrabatt_InStream__c</fullName>
        <description>Sonderrabatt-InStream gesamt</description>
        <inlineHelpText>Sonderrabatt-InStream gesamt</inlineHelpText>
        <label>Sonderrabatt-InStream</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Commitment Digital</label>
    <nameField>
        <displayFormat>Commitment-Digital-{000}</displayFormat>
        <label>Commitment Digital Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commitments Digital</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_Commitment.cls
/**
 * Commitments and Discounts
 */
global class Adv_CampaignItem_Commitment {

	public final static String PREFIX_MEDIA_CAMP	= Schema.getGlobalDescribe().get('ADvendio__MediaCampaign__c').getDescribe().getKeyPrefix();
	public final static String INPAGE_IND		   = 'InPage';
	public final static String INSTREAM_IND		 = 'InStream';
	public static Boolean doneTracking			  = false;

	/**
	 * Call from a button shown on Commitment "SomDig_CreateMediaCampaign"
	 * @param commId, source Commitment record
	 * @return url with pre-populated data
	 */
	webservice static String generateUrl(String commId) {
		ADvendio__MediaCampaign__c mediaCamp = new ADvendio__MediaCampaign__c(ADvendio__IsApproved__c = true, SomDig_RabatteMKgenehmigt__c=true);
		SomDig_Commitment__c comm = getCommitmentsData(new Set<Id>{Id.valueOf(commId)}).get(Id.valueOf(commId));
		tranCommitmentToMediaCamp(comm, mediaCamp);
		String urlString = '/' + PREFIX_MEDIA_CAMP +  '/e?' + 'nooverride=1&retURL=/'+commId;
		Map<String, String> mValue =  createDefaultValues(comm, mediaCamp);
		for(String fldId : mValue.keySet()){
			urlString += '&' + fldId + '=' + mValue.get(fldId);
		}
		return urlString;
	}

	/**
	* copy campaign discounts to all it's campaign-items if a discount is changed
	* @param	a list of ADvendio__MediaCampaign__c records (trigger.new)
	* @param	a map of ADvendio__MediaCampaign__c records (trigger.oldMap)
	**/
	public static void copyDiscountsToItems(List<ADvendio__MediaCampaign__c> newCampaignList, Map<Id, ADvendio__MediaCampaign__c> oldCampaignMap) {

		Map<Id, ADvendio__MediaCampaign__c> mediaCampaigns  = new Map<Id, ADvendio__MediaCampaign__c>();
		Set<Id> mcIsNotApproved = new Set<Id>();

		// identify and store any involved campaign
		for (ADvendio__MediaCampaign__c mc : newCampaignList) {
			if ( mc.SomDig_Kundenrabatt_InPage__c   != oldCampaignMap.get(mc.Id).SomDig_Kundenrabatt_InPage__c ||
				 mc.SomDig_Kundenrabatt_InStream__c != oldCampaignMap.get(mc.Id).SomDig_Kundenrabatt_InStream__c ||
				 mc.SomDig_Sonderrabatt_InPage__c   != oldCampaignMap.get(mc.Id).SomDig_Sonderrabatt_InPage__c ||
				 mc.SomDig_Sonderrabatt_InStream__c != oldCampaignMap.get(mc.Id).SomDig_Sonderrabatt_InStream__c ||
				 mc.SomDig_Agenturrabatt__c			!= oldCampaignMap.get(mc.Id).SomDig_Agenturrabatt__c ||
				 mc.SomDig_Naturalrabatt_Inpage__c 	!= oldCampaignMap.get(mc.Id).SomDig_Naturalrabatt_Inpage__c
			) {

				if (mc.ADvendio__IsApproved__c  != oldCampaignMap.get(mc.Id).ADvendio__IsApproved__c && !mc.ADvendio__IsApproved__c
				   /* mc.SomDig_Kundenrabatt_InPage__c  > oldCampaignMap.get(mc.Id).SomDig_Kundenrabatt_InPage__c   && mc.SomDig_Kundenrabatt_InPage__c	 >= 65 ||
					mc.SomDig_Kundenrabatt_InStream__c  > oldCampaignMap.get(mc.Id).SomDig_Kundenrabatt_InStream__c && mc.SomDig_Kundenrabatt_InStream__c   >= 65 ||
					mc.SomDig_Sonderrabatt_InPage__c	> oldCampaignMap.get(mc.Id).SomDig_Sonderrabatt_InPage__c   && mc.SomDig_Sonderrabatt_InPage__c	 >= 65 ||
					mc.SomDig_Sonderrabatt_InStream__c  > oldCampaignMap.get(mc.Id).SomDig_Sonderrabatt_InStream__c && mc.SomDig_Sonderrabatt_InStream__c   >= 65 ||
					mc.ADvendio__Rate_Discount_3__c	 > oldCampaignMap.get(mc.Id).ADvendio__Rate_Discount_3__c	&& mc.ADvendio__Rate_Discount_3__c	  >= 65*/
				) {
					mcIsNotApproved.add(mc.Id);
				}
				mediaCampaigns.put(mc.Id, mc);
			}
		}

		Set<String> sonderRabattNamen   = new Set<String>{'Kompensation', 'Nachlieferung', 'Positionsrabatt Natural', 'Storno mit Leistungsfluss', 'Storno ohne Leistungsfluss'};

		List<ADvendio__Campaign_Item__c> campaignItemsToUpdate  = new List<ADvendio__Campaign_Item__c>();
		if (!mediaCampaigns.isEmpty()) {
			// get all campaign-items for changed campaigns
			for (ADvendio__Campaign_Item__c ci : [SELECT Id, SomDig_Menge__c, SomDig_Naturalrabatt__c, ADvendio__Rate_Discount_4_Name__c, SomDig_RabatteFreigegebenCheck__c, 
														 SomDig_MediagattungsDifferenzierungName__c, ADvendio__Rate_Discount_2_custom__c, ADvendio__Rate_Discount_3_custom__c,
														 ADvendio__Rate_Discount_4__c, ADvendio__Media_Campaign__c, ADvendio__Billing_category__c, ADvendio__Sales_Price__c,
														 ADvendio__Frequency__c, ADvendio__SurchargeSalesPrice__c
													FROM ADvendio__Campaign_Item__c
													WHERE ADvendio__Media_Campaign__c IN :mediaCampaigns.keySet() order by ADvendio__Media_Campaign__c asc]) {
				ADvendio__MediaCampaign__c mc	   = mediaCampaigns.get(ci.ADvendio__Media_Campaign__c);
				ADvendio__Campaign_Item__c ciUpdate = new ADvendio__Campaign_Item__c(Id=ci.Id);
				Boolean changed = false;

				if (mcIsNotApproved.contains(ci.ADvendio__Media_Campaign__c)) {
					if (!ci.SomDig_RabatteFreigegebenCheck__c) {
						ciUpdate.SomDig_RabatteFreigegebenCheck__c  = true;
						changed = true;
					}
				}

				if (ci.SomDig_MediagattungsDifferenzierungName__c != null) {
					if (ci.SomDig_MediagattungsDifferenzierungName__c.contains(INSTREAM_IND)) { // InStream
						if (ci.ADvendio__Rate_Discount_2_custom__c != mc.SomDig_Kundenrabatt_InStream__c && mc.SomDig_Kundenrabatt_InStream__c != oldCampaignMap.get(mc.Id).SomDig_Kundenrabatt_InStream__c) { // Kundenrabatt changed
							ciUpdate.ADvendio__Rate_Discount_2_custom__c	= mc.SomDig_Kundenrabatt_InStream__c;
							changed = true;
						}
						if (ci.ADvendio__Rate_Discount_4__c != mc.SomDig_Sonderrabatt_InStream__c && mc.SomDig_Sonderrabatt_InStream__c != oldCampaignMap.get(mc.Id).SomDig_Sonderrabatt_InStream__c) { // Sonderrabatt changed
							if (!sonderRabattNamen.contains(ci.ADvendio__Rate_Discount_4_Name__c)) {
								ciUpdate.ADvendio__Rate_Discount_4__c	   = mc.SomDig_Sonderrabatt_InStream__c;
								changed = true;
							}
						}
					}
					if (ci.SomDig_MediagattungsDifferenzierungName__c.contains(INPAGE_IND)) { // InPage
						if ('CPM'.equalsIgnoreCase(ci.ADvendio__Billing_category__c) && ci.ADvendio__Rate_Discount_4_Name__c != 'Positionsrabatt Natural') {
							if (ci.SomDig_Naturalrabatt__c != mc.SomDig_Naturalrabatt_Inpage__c && mc.SomDig_Naturalrabatt_Inpage__c != oldCampaignMap.get(mc.Id).SomDig_Naturalrabatt_Inpage__c) {
								ci.SomDig_Naturalrabatt__c				= mc.SomDig_Naturalrabatt_Inpage__c;
								ci										= Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci);
								ciUpdate.ADvendio__SurchargeB3__c		= ci.ADvendio__SurchargeB3__c;
								ciUpdate.ADvendio__SurchargeB3Abs__c	= ci.ADvendio__SurchargeB3Abs__c;
								ciUpdate.ADvendio__Quantity__c			= ci.ADvendio__Quantity__c;
								ciUpdate.SomDig_Naturalrabatt__c		= ci.SomDig_Naturalrabatt__c;
								changed = true;
							}
						}
						if (ci.ADvendio__Rate_Discount_2_custom__c != mc.SomDig_Kundenrabatt_InPage__c && mc.SomDig_Kundenrabatt_InPage__c != oldCampaignMap.get(mc.Id).SomDig_Kundenrabatt_InPage__c) { // Kundenrabatt changed
							ciUpdate.ADvendio__Rate_Discount_2_custom__c	= mc.SomDig_Kundenrabatt_InPage__c;
							changed = true;
						}
						if (ci.ADvendio__Rate_Discount_4__c != mc.SomDig_Sonderrabatt_InPage__c && mc.SomDig_Sonderrabatt_InPage__c != oldCampaignMap.get(mc.Id).SomDig_Sonderrabatt_InPage__c) { // Sonderrabatt changed
							if (!sonderRabattNamen.contains(ci.ADvendio__Rate_Discount_4_Name__c)) {
								ciUpdate.ADvendio__Rate_Discount_4__c	   = mc.SomDig_Sonderrabatt_InPage__c;
								changed = true;
							}
						}
					}
				}

				if (ci.ADvendio__Rate_Discount_3_custom__c != mc.SomDig_Agenturrabatt__c && mc.SomDig_Agenturrabatt__c != oldCampaignMap.get(mc.Id).SomDig_Agenturrabatt__c) { // Agency discount changed
					ciUpdate.ADvendio__Rate_Discount_3_custom__c			= mc.SomDig_Agenturrabatt__c;
					changed = true;
				}
				if (changed) { // add campaign-item to the change-list if there are changes
					campaignItemsToUpdate.add(ciUpdate);
				}
			}

			if (!campaignItemsToUpdate.isEmpty()) { // update campaign-items
				update campaignItemsToUpdate;
			}
		}
	}

	/**
	 * Discounts from Commitment should be copied in the fields accordingly while creating.
	 * Called from trigger on ADvendio__Campaign_Item__c before insert
	 * @param newList, list current values
	 */
	public static void setCampaignItemDiscounts(List<ADvendio__Campaign_Item__c> newCampaignItemList) {
		Map<Id, ADvendio__MediaCampaign__c> mediaCampaigns  = new Map<Id, ADvendio__MediaCampaign__c>();

		// store any involved campaign-id
		for (ADvendio__Campaign_Item__c ci : newCampaignItemList) {
			mediaCampaigns.put(ci.ADvendio__Media_Campaign__c, null);
		}

		//store involved campaigns and commitments (ids)
		for (ADvendio__MediaCampaign__c mc : getMediaCampaignData(mediaCampaigns.keySet())) {
			mediaCampaigns.put(mc.Id, mc);
		}

		//copy discounts to new campaign-items
		for (ADvendio__Campaign_Item__c ci : newCampaignItemList) {
			ADvendio__MediaCampaign__c mc   = mediaCampaigns.get(ci.ADvendio__Media_Campaign__c);

			if (ci.SomDig_MediagattungsDifferenzierungName__c != null) {

				if (ci.SomDig_MediagattungsDifferenzierungName__c.contains(INSTREAM_IND)) { // InStream
					if (ci.ADvendio__Rate_Discount_2_custom__c == null) {
						ci.ADvendio__Rate_Discount_2_custom__c  = mc.SomDig_Kundenrabatt_InStream__c;
					}
					if (ci.ADvendio__Rate_Discount_4__c == null) {
						ci.ADvendio__Rate_Discount_4__c		 = mc.SomDig_Sonderrabatt_InStream__c;
					}
					if (ci.ADvendio__RateDiscount2Name__c == null) {
						ci.ADvendio__RateDiscount2Name__c	   = INSTREAM_IND;
					}
					if (ci.ADvendio__Rate_Discount_4_Name__c == null) {
						ci.ADvendio__Rate_Discount_4_Name__c	= INSTREAM_IND;
					}
				}

				if (ci.SomDig_MediagattungsDifferenzierungName__c.contains(INPAGE_IND)) { // InPage
					/*if (ci.SomDig_Naturalrabatt__c == null) {
						if ('CPM'.equalsIgnoreCase(ci.ADvendio__Billing_category__c) && ci.ADvendio__Rate_Discount_4_Name__c != 'Positionsrabatt Natural') {
							ci.SomDig_Naturalrabatt__c			= mc.SomDig_Naturalrabatt_Inpage__c;
							ci									= Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci);
						}
					}*/
					if (ci.ADvendio__Rate_Discount_2_custom__c == null) {
						ci.ADvendio__Rate_Discount_2_custom__c  = mc.SomDig_Kundenrabatt_InPage__c;
					}
					if (ci.ADvendio__Rate_Discount_4__c == null) {
						ci.ADvendio__Rate_Discount_4__c		 = mc.SomDig_Sonderrabatt_InPage__c;
					}
					if (ci.ADvendio__RateDiscount2Name__c == null) {
						ci.ADvendio__RateDiscount2Name__c	   = INPAGE_IND;
					}
					if (ci.ADvendio__Rate_Discount_4_Name__c == null) {
						ci.ADvendio__Rate_Discount_4_Name__c	= INPAGE_IND;
					}
				}
			}

			if (ci.ADvendio__Rate_Discount_3_custom__c == null) {
				ci.ADvendio__Rate_Discount_3_custom__c		  = mc.SomDig_Agenturrabatt__c;
			}
		}
			/* warum?
		List<ADvendio__MediaCampaign__c> mediaCampaignUpdates   = new List<ADvendio__MediaCampaign__c>();
		for (ADvendio__MediaCampaign__c mc : mediaCampaigns.values()) {
			if (commitments.containsKey(mc.SomDig_Commitment__c)) {
				tranCommitmentToMediaCamp(commitments.get(mc.SomDig_Commitment__c), mc);
				mediaCampaignUpdates.add(mc);
			}
		}


		if (!mediaCampaignUpdates.isEmpty()) {
			update mediaCampaignUpdates;
		}*/
	}


	/**
	 * Scan the overall edit screen to find Field Id in metadata
	 * The field must be put into page layout to get pre-populated
	 * @reference: https://force201.wordpress.com/2012/01/22/hack-to-find-field-ids-allows-a-default-ui-new-page-to-be-pre-populated/
	 * @param comm, source Commitment record
	 * @param mediaCamp, related MediaCampaign record
	 * @return mapping field Id to value
	 */
	private static Map<String, String> createDefaultValues(SomDig_Commitment__c comm, ADvendio__MediaCampaign__c mediaCamp) {
		final Set<String> LOOKUP_FLDS = new Set<String>{'ADvendio__Agency__c', 'ADvendio__Account__c', 'SomDig_Commitment__c', 'SomDig_WtAgBeziehung__c'};
		String requiredHTML = '<span class=\"assistiveText\">*</span>';
		// Obtain the magic ids
		PageReference p = new PageReference('/' + PREFIX_MEDIA_CAMP + '/e?nooverride=1');
		// Running test won't go further code execution after getContent()
		String html = Test.isRunningTest() ? Adv_CampaignItem_Commitment_Test.mockEditPageBody : p.getContent().toString();

		Map<String, String> labelToId = new Map<String, String>();
		Matcher m = Pattern.compile('<label for="(.*?)">(<span class="requiredMark">\\*</span>)?(.*?)</label>').matcher(html);
		while (m.find()) {
			String label = m.group(3);
			String id = m.group(1);
			labelToId.put(label.replace(requiredHTML, ''), id);
		}
		// Relate the magic ids to the SObject fields
		Map<String, String> params = new Map<String, String>();
		for (SObjectField field : ADvendio__MediaCampaign__c.SObjectType.getDescribe().fields.getMap().values()) {
			Object value = mediaCamp.get(field);
			if (value != null) {
				DescribeFieldResult f = field.getDescribe();
				String label = f.getLabel();
				String fname = f.getName();
				if (labelToId.containsKey(label)) {
					String valueAsString = '';
					if (f.getType() == DisplayType.Date) {
						valueAsString = ((Date) value).format();
					} else if (f.getType() == DisplayType.Datetime) {
						valueAsString = ((Datetime) value).format();
					} else if (f.getType() == DisplayType.Boolean) {
						valueAsString = ((Boolean) value) ? '1' : '0';
					} else if (LOOKUP_FLDS.contains(fname)) {
						String idValue = '';
						if (fname == 'ADvendio__Agency__c') {
							valueAsString = comm.SomDig_WtAgBeziehung__r.SomDig_Agentur__r.Name;
							idValue = comm.SomDig_WtAgBeziehung__r.SomDig_Agentur__c;
						} else if (fname == 'ADvendio__Account__c') {
							valueAsString = comm.SomDig_WtAgBeziehung__r.SomDig_Werbetreibender__r.Name;
							idValue = comm.SomDig_WtAgBeziehung__r.SomDig_Werbetreibender__c;
						} else if (fname == 'SomDig_Commitment__c') {
							valueAsString = comm.Name;
							idValue = String.valueOf(value);
						} else if (fname == 'SomDig_WtAgBeziehung__c') {
							valueAsString = comm.SomDig_WtAgBeziehung__r.Name;
							idValue = String.valueOf(value);
						}
						params.put(labelToId.get(label) + '_lkid', idValue);
					} else if (f.getType() == DisplayType.Double || f.getType() == DisplayType.Currency || f.getType() == DisplayType.Percent) {
						valueAsString = ClsHelper.formatDecimal((Decimal)value, 2, /*Userinfo.getLocale()*/ 'en_US');
					} else {
						valueAsString = String.valueOf(value);
					}
					params.put(labelToId.get(label), valueAsString);
				}
			}
		}
		return params;
	}

	/**
	 * For the case if by a campaign item, the "Individual Gesamtrabatt Konsekutiv" is great than the "Commitment Gesamtrabatt Konsekutiv",
	 * this campaign item has to be approved.
	 * @param campItem, current Campaign Item
	 * @param campItem, current Campaign Item
	 * @return decimal not null
	 */
	private static Boolean campaignItemRequiresApproval(ADvendio__Campaign_Item__c campItem, ADvendio__MediaCampaign__c mediaCamp) {
		Decimal rab2	= campItem.ADvendio__Rate_Discount_2_custom__c == null ? 0 : campItem.ADvendio__Rate_Discount_2_custom__c;
		Decimal rab3	= campItem.ADvendio__Rate_Discount_3_custom__c == null ? 0 : campItem.ADvendio__Rate_Discount_3_custom__c;
		Decimal rab4	= campItem.ADvendio__Rate_Discount_4__c;

		Decimal valIndividuellGK =  1 - (discountRestValue(rab2) *
										discountRestValue(rab3) *
										discountRestValue(rab4));

		Decimal valCommitmentGK = 0;

		if (campItem.SomDig_MediagattungsDifferenzierungName__c != null) {
			if (campItem.SomDig_MediagattungsDifferenzierungName__c.contains(INPAGE_IND)) {

				if( rab2 >= 65 && rab2 > mediaCamp.SomDig_Kundenrabatt_InPage__c ||
					rab3 >= 65 && rab3 > mediaCamp.SomDig_Agenturrabatt__c ||
					rab4 >= 65 && rab4 > mediaCamp.SomDig_Sonderrabatt_InPage__c) {

					return true;
				}

				valCommitmentGK =	   1 - (discountRestValue(mediaCamp.SomDig_Kundenrabatt_InPage__c) *
											discountRestValue(mediaCamp.SomDig_Agenturrabatt__c) *
											discountRestValue(mediaCamp.SomDig_Sonderrabatt_InPage__c));
			}

			if (campItem.SomDig_MediagattungsDifferenzierungName__c.contains(INSTREAM_IND)) {

				if( rab2 >= 65 && rab2 > mediaCamp.SomDig_Kundenrabatt_InStream__c ||
					rab3 >= 65 && rab3 > mediaCamp.SomDig_Agenturrabatt__c ||
					rab4 >= 65 && rab4 > mediaCamp.SomDig_Sonderrabatt_InStream__c) {

					return true;
				}

				valCommitmentGK =	   1 - (discountRestValue(mediaCamp.SomDig_Kundenrabatt_InStream__c) *
											discountRestValue(mediaCamp.SomDig_Agenturrabatt__c) *
											discountRestValue(mediaCamp.SomDig_Sonderrabatt_InStream__c));
			}
		}

		return valIndividuellGK > valCommitmentGK;

	}

	/**
	 * Make appropriate value
	 * @param val, Decimal value
	 * @return decimal not null
	 */
	private static Decimal discountRestValue(Decimal val) {

		return 1-decValueOf(val)/100;
	}

	/**
	 * Make appropriate value
	 * @param val, Decimal value
	 * @return decimal not null
	 */
	private static Decimal decValueOf(Decimal val) {
		return val == null ? 0 : val;
	}

	/**
	 * Query SomDig_Commitment__c records, should not be invoked in loop
	 * @param commIds, record Ids
	 * @return SomDig_Commitment__c records
	 */
	private static Map<Id, SomDig_Commitment__c> getCommitmentsData(Set<Id> commIds) {
		return new Map<Id, SomDig_Commitment__c> ([Select Name, SomDig_Kundenrabatt_InPage__c, SomDig_Kundenrabatt_InStream__c, SomDig_Agentur_Rabatt__c,
				SomDig_Sonderrabatt_InPage__c, SomDig_Sonderrabatt_InStream__c, SomDig_Naturalrabatt_Inpage__c,
				SomDig_Agentur__c, SomDig_Werbetreibende__c, SomDig_WtAgBeziehung__c, SomDig_WtAgBeziehung__r.Name,
				SomDig_WtAgBeziehung__r.SomDig_Werbetreibender__c, SomDig_WtAgBeziehung__r.SomDig_Werbetreibender__r.Name,
				SomDig_WtAgBeziehung__r.SomDig_Agentur__c, SomDig_WtAgBeziehung__r.SomDig_Agentur__r.Name
				From SomDig_Commitment__c
			  Where Id IN: commIds]);
	}

	/**
	 * Query ADvendio__MediaCampaign__c records, should not be invoked in loop
	 * @param campIds, record Ids
	 * @return ADvendio__MediaCampaign__c records
	 */
	private static List<ADvendio__MediaCampaign__c> getMediaCampaignData(Set<Id> mcIds) {
		return [SELECT Id, Name, SomDig_Commitment__c, SomDig_WtAgBeziehung__c,
				SomDig_Agenturrabatt__c, SomDig_Sonderrabatt_InPage__c,
				SomDig_Sonderrabatt_InStream__c, SomDig_Naturalrabatt_Inpage__c, ADvendio__Agency__c,
				SomDig_Kundenrabatt_InPage__c, SomDig_Kundenrabatt_InStream__c,
				ADvendio__Account__c, OwnerId, ADvendio__IsApproved__c FROM ADvendio__MediaCampaign__c WHERE Id IN: mcIds];
	}

	/**
	 * Transfer Commitment data to MediaCampaign Item
	 * @param comm, SomDig_Commitment__c record
	 * @param mediaCamp, ADvendio__MediaCampaign__c record
	 */
	public static void tranCommitmentToMediaCamp(SomDig_Commitment__c comm, ADvendio__MediaCampaign__c mediaCamp) {
		mediaCamp.SomDig_Kundenrabatt_InPage__c	 = comm.SomDig_Kundenrabatt_InPage__c;
		mediaCamp.SomDig_Kundenrabatt_InStream__c   = comm.SomDig_Kundenrabatt_InStream__c;
		mediaCamp.SomDig_Agenturrabatt__c	  		= comm.SomDig_Agentur_Rabatt__c;
		mediaCamp.SomDig_Sonderrabatt_InPage__c	 = comm.SomDig_Sonderrabatt_InPage__c;
		mediaCamp.SomDig_Sonderrabatt_InStream__c   = comm.SomDig_Sonderrabatt_InStream__c;
		mediaCamp.SomDig_Naturalrabatt_Inpage__c	= comm.SomDig_Naturalrabatt_Inpage__c;
		mediaCamp.ADvendio__Agency__c			   = comm.SomDig_WtAgBeziehung__r.SomDig_Agentur__c;//comm.SomDig_Agentur__c;
		mediaCamp.ADvendio__Account__c			  = comm.SomDig_WtAgBeziehung__r.SomDig_Werbetreibender__c;//comm.SomDig_Werbetreibende__c;
		mediaCamp.SomDig_Commitment__c			  = comm.Id;
		mediaCamp.SomDig_WtAgBeziehung__c		   = comm.SomDig_WtAgBeziehung__c;
	}

	/**
	 * check wether MediaCampaign discounts exeed Commitment discounts
	 * @param comm, SomDig_Commitment__c record
	 * @param mediaCamp, ADvendio__MediaCampaign__c record
	 * @return boolean - false if campaign discoiunst fit commitment discounts; true otherwise
	 */
	private static boolean compareDiscountsWithCommitment(SomDig_Commitment__c comm, ADvendio__MediaCampaign__c mediaCamp) {
		if (mediaCamp.SomDig_Kundenrabatt_InPage__c	 > comm.SomDig_Kundenrabatt_InPage__c ||
			mediaCamp.SomDig_Kundenrabatt_InStream__c   > comm.SomDig_Kundenrabatt_InStream__c ||
			mediaCamp.SomDig_Agenturrabatt__c	 		> comm.SomDig_Agentur_Rabatt__c ||
			mediaCamp.SomDig_Sonderrabatt_InPage__c	 > comm.SomDig_Sonderrabatt_InPage__c ||
			mediaCamp.SomDig_Sonderrabatt_InStream__c   > comm.SomDig_Sonderrabatt_InStream__c ||
			mediaCamp.SomDig_Naturalrabatt_Inpage__c	> comm.SomDig_Naturalrabatt_Inpage__c
			) {
				return true;
			}
		return false;
	}
}