src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mig_ProdiaKey__c</fullName>
        <description>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</description>
        <inlineHelpText>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</inlineHelpText>
        <label>Mig_ProdiaKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__c</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_CpxFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_CpxFaehig__c</formula>
        <label>CPX fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.SomDig_GtFaehig__c</formula>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c</formula>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Metabuchungslogik__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metabuchungslogik</label>
        <referenceTo>SomDig_Metabuchungslogik__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mig_ProdiaKey__c</fullName>
        <description>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</description>
        <inlineHelpText>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</inlineHelpText>
        <label>Mig_ProdiaKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SomDig_BT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ist es erlaubt für diese Werbemittel/Produkt Soziademografisches und Behavior Targeting zu nutzen? wenn das Kontrollkästchen gefüllt ist werden die Aufschläge entsprechend aktiv.</description>
        <inlineHelpText>Ist es erlaubt für diese Werbemittel/Produkt Soziademografisches und Behavior Targeting zu nutzen? wenn das Kontrollkästchen gefüllt ist werden die Aufschläge entsprechend aktiv.</inlineHelpText>
        <label>BT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_CpxFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>Temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>CPX fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_FC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>FC fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Type__c.object
<CustomObject>
    <fields>
        <fullName>Mig_ProdiaKey__c</fullName>
        <description>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</description>
        <inlineHelpText>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</inlineHelpText>
        <label>Mig_ProdiaKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ad Type</label>
    <nameField>
        <label>Ad Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>Mig_ProdiaKey__c</fullName>
        <description>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</description>
        <externalId>true</externalId>
        <inlineHelpText>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</inlineHelpText>
        <label>Mig_ProdiaKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SomDig_BT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>BT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_CpxFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>Temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>CPX fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_FC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>temporär zur Erstellung der Produktmatrix</description>
        <inlineHelpText>temporär zur Erstellung der Produktmatrix</inlineHelpText>
        <label>FC fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>Mig_ProdiaKey__c</fullName>
        <description>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</description>
        <externalId>true</externalId>
        <inlineHelpText>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</inlineHelpText>
        <label>Mig_ProdiaKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SomDig_AuftragstypId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Steuert die Auslieferungsprioritäten in den AdServern, die Einschränkung auf mögliche Produkte/Werbemittel, ggf. auch Steuerung von fixem FC bei einigen Auftragstypen &amp; Voreinstellung der Rechnungsstellung etc.</description>
        <inlineHelpText>Bitte die Auftragstypen angeben. Diese steuert die Auslieferungsprioritäten in den AdServern, die Einschränkung auf mögliche Produkte/Werbemittel, ggf. auch Steuerung von fixem FC bei einigen Auftragstypen &amp; Voreinstellung der Rechnungsstellung etc.</inlineHelpText>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Preislisten</relationshipLabel>
        <relationshipName>Preislisten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <fields>
        <fullName>Mig_ProdiaKey__c</fullName>
        <description>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</description>
        <inlineHelpText>Eindeutiger Schlüssel aus ProDia, der für Abgleich bei Migrataion benötigt wird</inlineHelpText>
        <label>Mig_ProdiaKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SomDig_Metabuchungslogik__c.object
<CustomObject>
    <description>Die Metabuchungslogik (MBL) dient als Regelwerk bei der Erstellung von Werbemitteln/Preisen für die Produktmatrix von ADvendio.</description>
    <fields>
        <fullName>Mig_ProdiaKey__c</fullName>
        <description>Eindeutiger Schlüssel aus ProDia, der für den Abgleich bei der Migration benötigt wird.</description>
        <externalId>true</externalId>
        <inlineHelpText>Eindeutiger Schlüssel aus ProDia, der für den Abgleich bei der Migration benötigt wird.</inlineHelpText>
        <label>ProDia Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Metabuchungslogik</relationshipLabel>
        <relationshipName>Metabuchungslogik</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_CpxFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CPX fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Aktiv</label>
        <type>Checkbox</type>
    </fields>
    <label>Metabuchungslogik</label>
    <nameField>
        <displayFormat>MBL-{0000}</displayFormat>
        <label>MBL-Nr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metabuchungslogik</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_AdPrice_Metabuchungslogik_Test.cls
@isTest
private with sharing class Adv_AdPrice_Metabuchungslogik_Test {

    static testMethod void inactiveMblProhibitsValidAdPrice() {
        createTestInventory();

        SomDig_Metabuchungslogik__c mbl = [SELECT SomDig_IsActive__c FROM SomDig_Metabuchungslogik__c WHERE Mig_ProdiaKey__c = '123'][0];
        mbl.SomDig_IsActive__c = false;
        update mbl;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void validAdPriceConformsToMbl() {
        createTestInventory();

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(result.isSuccess());
        adPrice = [SELECT SomDig_Metabuchungslogik__c FROM ADvendio__Ad_price__c WHERE Id = :adPrice.Id][0];
        SomDig_Metabuchungslogik__c mbl = [SELECT Id FROM SomDig_Metabuchungslogik__c WHERE Mig_ProdiaKey__c = '123'][0];
        System.assertEquals(mbl.Id, adPrice.SomDig_Metabuchungslogik__c);
    }

    static testMethod void invalidAbrechnungsartBreaksMbl() {
        createTestInventory();

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPW';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidAuftragstypBreaksMbl() {
        createTestInventory();

        SomDig_Auftragstyp__c standard = cls_P7S1_TestData.createTestAuftragstyp(true, 'Standard');

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];
        pricelist.SomDig_AuftragstypId__c = standard.Id;
        update pricelist;

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidBtFaehigkeitBreaksMbl() {
        createTestInventory();

        ADvendio__Placement__c placement = [SELECT Id, Name FROM ADvendio__Placement__c WHERE Name = 'MBL Test Placement'][0];
        placement.SomDig_BT__c = false;
        update placement;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidCpxFaehigkeitBreaksMbl() {
        createTestInventory();

        ADvendio__Placement__c placement = [SELECT Id, Name FROM ADvendio__Placement__c WHERE Name = 'MBL Test Placement'][0];
        placement.SomDig_CpxFaehig__c = false;
        update placement;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidFcFaehigkeitBreaksMbl() {
        createTestInventory();

        ADvendio__Placement__c placement = [SELECT Id, Name FROM ADvendio__Placement__c WHERE Name = 'MBL Test Placement'][0];
        placement.SomDig_FC__c = false;
        update placement;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidGtFaehigkeitBreaksMbl() {
        createTestInventory();

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        adSpec.SomDig_GtFaehig__c = false;
        update adSpec;
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidMediagattungsDifferenzierungBreaksMbl() {
        createTestInventory();

        SomDig_MediagattungsDifferenzierung__c instream = cls_P7S1_TestData.createTestMediagattungsDifferenzierung(true, 'InStream/Video');

        ADvendio__Ad_Type__c adType = [SELECT Id, Name FROM ADvendio__Ad_Type__c WHERE Name = 'MBL Test AdType'][0];
        adType.SomDig_MediagattungsDifferenzierung__c = instream.Id;
        update adType;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        update adSpec; // dummy update to fetch new MediagattungsDifferenzierung
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidRotationstypBreaksMbl() {
        createTestInventory();

        ADvendio__Placement__c placement = [SELECT Id, Name FROM ADvendio__Placement__c WHERE Name = 'MBL Test Placement'][0];
        placement.SomDig_Rotationstyp__c = 'Themen-Rotation';
        update placement;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidTkpFaehigkeitBreaksMbl() {
        createTestInventory();

        ADvendio__Placement__c placement = [SELECT Id, Name FROM ADvendio__Placement__c WHERE Name = 'MBL Test Placement'][0];
        placement.SomDig_TkpFaehig__c = false;
        update placement;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidWbFaehigkeitBreaksMbl() {
        createTestInventory();

        ADvendio__Ad_Type__c adType = [SELECT Id, Name FROM ADvendio__Ad_Type__c WHERE Name = 'MBL Test AdType'][0];
        adType.SomDig_WbFaehig__c = false;
        update adType;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void invalidWerbeformgruppeBreaksMbl() {
        createTestInventory();

        ADvendio__Ad_Type__c adType = [SELECT Id, Name FROM ADvendio__Ad_Type__c WHERE Name = 'MBL Test AdType'][0];
        adType.SomDig_Werbeformgruppe__c = 'Sonderwerbeform';
        update adType;

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(!result.isSuccess());
        System.assertEquals(result.getErrors()[0].getMessage(), Adv_AdPrice_Metabuchungslogik.ERROR_MSG);
    }

    static testMethod void debuggingModeAllowsAdPriceCreation() {
        insert new SomDig_Settings__c(SomDig_MetabuchungslogikDebugMode__c = true);

        createTestInventory();

        ADvendio__Ad_Specs__c adSpec = [SELECT Id, Name FROM ADvendio__Ad_Specs__c WHERE Name = 'MBL Test AdSpec'][0];
        ADvendio__Pricelist__c pricelist = [SELECT Id, Name FROM ADvendio__Pricelist__c WHERE Name = 'MBL Test Pricelist'][0];

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec, pricelist);
        adPrice.ADvendio__Billing_Category__c = 'CPW';
        Database.SaveResult result = Database.insert(adPrice, false);

        Test.stopTest();

        System.assert(result.isSuccess());
        adPrice = [SELECT SomDig_Metabuchungslogik__c FROM ADvendio__Ad_price__c WHERE Id = :adPrice.Id][0];
        System.assertEquals(null, adPrice.SomDig_Metabuchungslogik__c);
    }



    static void createTestInventory() {
        SomDig_MediagattungsDifferenzierung__c inpage = cls_P7S1_TestData.createTestMediagattungsDifferenzierung(true, 'InPage/Display');
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.Name = 'MBL Test Placement';
        placement.SomDig_BT__c = true;
        placement.SomDig_CpxFaehig__c = true;
        placement.SomDig_FC__c = true;
        placement.SomDig_GtFaehig__c = true;
        placement.SomDig_Rotationstyp__c = 'Brand-Rotation';
        placement.SomDig_TkpFaehig__c = true;
        insert placement;
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(false, inpage);
        adType.Name = 'MBL Test AdType';
        adType.SomDig_WbFaehig__c = true;
        adType.SomDig_Werbeformgruppe__c = 'Standard';
        insert adType;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(false, placement, adType);
        adSpec.Name = 'MBL Test AdSpec';
        insert adSpec;
        SomDig_Auftragstyp__c forschung = cls_P7S1_TestData.createTestAuftragstyp(true, 'Forschung');
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(false, forschung);
        pricelist.Name = 'MBL Test Pricelist';
        insert pricelist;

        SomDig_Metabuchungslogik__c mbl = createTestMetabuchungslogik(false);
        mbl.Mig_ProdiaKey__c = '123';
        mbl.SomDig_Abrechnungsart__c = 'CPM;CPD';
        mbl.SomDig_Auftragstyp__c = forschung.Id;
        mbl.SomDig_BtFaehig__c = true;
        mbl.SomDig_CpxFaehig__c = true;
        mbl.SomDig_FcFaehig__c = true;
        mbl.SomDig_GtFaehig__c = true;
        mbl.SomDig_Mediagattungsdifferenzierung__c = inpage.Id;
        mbl.SomDig_Rotationstyp__c = 'Network-Rotation;Brand-Rotation';
        mbl.SomDig_TkpFaehig__c = true;
        mbl.SomDig_WbFaehig__c = true;
        mbl.SomDig_Werbeformgruppe__c = 'Standard';
        insert mbl;

        Adv_AdPrice_Metabuchungslogik.manuallyEnabledForTesting = true;
    }

    // TODO: move to cls_P7S1_TestData/P7S1_TestData
    public static SomDig_Metabuchungslogik__c Metabuchungslogik_TestData;
    public static SomDig_Metabuchungslogik__c createTestMetabuchungslogik(Boolean insertObject) {
        Metabuchungslogik_TestData = new SomDig_Metabuchungslogik__c();
        Metabuchungslogik_TestData.SomDig_IsActive__c = true;
        if (insertObject) insert Metabuchungslogik_TestData;
        return Metabuchungslogik_TestData;
    }

}