src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizingVersion__c</fullName>
        <label>Optimizing Version</label>
        <referenceTo>ADvendio__OptimizingVersion__c</referenceTo>
        <relationshipLabel>Optimizing Changes</relationshipLabel>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__DateOfActivation__c</fullName>
        <description>Shows the date / time when the Optimizing Version was activated.</description>
        <inlineHelpText>Shows the date / time when the Optimizing Version was activated.</inlineHelpText>
        <label>Date Of Activation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipName>OptimizingVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_OptimizingVersion_Activate_Test.cls
@isTest
public class Adv_OptimizingVersion_Activate_Test{

    public static testMethod void testOptimizingVersionActivate(){
        
        // Create Campaig
        ADvendio__MediaCampaign__c objCampaign = cls_P7S1_TestData.createTestMediaCampaign(true); 
        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(true, objCampaign);
    
    
    
        // Optimizing Version 1
        ADvendio__OptimizingVersion__c objOV1 = createADvendioOptimizingVersion(false);
        objOV1.ADvendio__MediaCampaign__c = objCampaign.ID;
        insert objOV1;    
        
        ADvendio__OptimizingChange__c objChange1 = createADvendioOptimizingChange(true, objOV1, objCI);        
        
        
        
        // Optimizing Version 2
        ADvendio__OptimizingVersion__c objOV2 = createADvendioOptimizingVersion(false);
        objOV2.ADvendio__MediaCampaign__c = objCampaign.ID;
        insert objOV2;            
        
        ADvendio__OptimizingChange__c objChange2 = createADvendioOptimizingChange(true, objOV2, objCI);        
    
        
        
        
        // Before activation there are two Optimizing Versions
        System.assert(2 == [SELECT COUNT() FROM ADvendio__OptimizingVersion__c WHERE ADvendio__MediaCampaign__c = :objCampaign.ID]);
        
        objOV1.ADvendio__DateOfActivation__c = System.now();
        update objOV1;
        
        
        // After activation there is one Optimizing Versions        
        System.assertEquals(2, [SELECT COUNT() FROM ADvendio__OptimizingVersion__c WHERE ADvendio__MediaCampaign__c = :objCampaign.ID]);        
    }
    
    
    // TODO: move to TESTClass
    public static ADvendio__OptimizingVersion__c createADvendioOptimizingVersion(Boolean isInsert){
        ADvendio__OptimizingVersion__c objOV = new ADvendio__OptimizingVersion__c();
        if(isInsert) insert objOV;
        return objOV;
    }    
    
    public static ADvendio__OptimizingChange__c createADvendioOptimizingChange(Boolean isInsert, ADvendio__OptimizingVersion__c objOV, ADvendio__Campaign_Item__c objCI){
    
        ADvendio__OptimizingChange__c objOC = new ADvendio__OptimizingChange__c();
        objOC.ADvendio__OptimizingVersion__c = objOV.ID;
        objOC.ADvendio__CampaignItem__c = objCI.ID;
        
        if(isInsert) insert objOC;
        return objOC;    
    }    

}