src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Distribution__c</fullName>
        <description>Define how the amount of product package is to be distributed among its components.</description>
        <inlineHelpText>Define how the amount of product package is to be distributed among its components.</inlineHelpText>
        <label>Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Linear</fullName>
                </value>
                <value>
                    <fullName>Prorated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Availability__c</fullName>
        <description>The ad server interface will enter the availability during an availabilty request.</description>
        <inlineHelpText>The ad server interface will enter the availability during an availabilty request.</inlineHelpText>
        <label>Availability (planned)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__LastAvailabilityForecast__c</fullName>
        <description>Last Availability Forecast run</description>
        <label>Last Availability Forecast</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packet Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Prorated__c</fullName>
        <label>Prorated</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Sales_Price__c</fullName>
        <description>Enter the sales price for this campaign item.</description>
        <inlineHelpText>Enter the sales price for this campaign item.</inlineHelpText>
        <label>Sales Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Menge__c</fullName>
        <description>Menge ohne anteiligen Naturalrabatt (Ticket 06323)</description>
        <label>Menge (ohne Naturalrabatt)</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_Naturalrabatt__c</fullName>
        <description>Naturalrabatt in Prozent (Ticket 06323)</description>
        <label>Naturalrabatt</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Typ__c</fullName>
        <description>Welchem Netzwerk gehört diese Belegungseinheit an?</description>
        <inlineHelpText>Welchem Netzwerk gehört diese Belegungseinheit an? Achtung dies hat Einfluss auf Auslieferungstyp und Priomodell.</inlineHelpText>
        <label>Netzwerk-Typ</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>71m intern</fullName>
                    <default>true</default>
                    <label>71m intern</label>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_DynamicQuantity_Test.cls
@isTest
private with sharing class Adv_CampaignItem_DynamicQuantity_Test {

    static testMethod void myUnitTest1() {
        
        ADvendio__Placement__c placement    = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_Typ__c             = 'YouTube';
        insert placement;
        
        // Create 3 ad specs
        List<ADvendio__Ad_Specs__c> lstAdS      = new List<ADvendio__Ad_Specs__c>();
        for(Integer i=0;i<3;i++){
            ADvendio__Ad_Specs__c asp = cls_P7S1_TestData.createTestAdSpec(false, placement);
            asp.ADvendio__Distribution__c   = 'Prorated';
            lstAdS.add(asp);
        }
        insert lstAdS;

        // Create 3 ad price
        List<ADvendio__Ad_price__c> lstAdPrice  = new List<ADvendio__Ad_price__c>();
        for (Integer i=0;i<3;i++){
            lstAdPrice.add(cls_P7S1_TestData.createTestAdPrice(false, lstAdS[i]));
        }
        insert lstAdPrice;

        ADvendio__MediaCampaign__c adM  = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c adCP = cls_P7S1_TestData.createTestCampaignItem(false, adM, lstAdPrice[0]);
        adCP.ADvendio__Quantity__c      = 1100;
        adCP.SomDig_Naturalrabatt__c    = 10;
        adCP.SomDig_Menge__c            = 1000;
        adCP.ADvendio__from_Date__c     = System.Today().addDays(1);        
        adCP.ADvendio__Sales_Price__c   = 100;
        insert adCP;

        // Create 2 component items
        ADvendio__Campaign_Item__c ci01                 = cls_P7S1_TestData.createTestCampaignItem(false, adM, lstAdPrice[1]);
        ci01.ADvendio__PacketItem__c                    = adCP.Id;
        ci01.ADvendio__Quantity__c                      = 440;
        ci01.SomDig_Menge__c                            = 400;
        ci01.SomDig_Naturalrabatt__c                    = 10;

        ADvendio__Campaign_Item__c ci02                 = cls_P7S1_TestData.createTestCampaignItem(false, adM, lstAdPrice[2]);
        ci02.ADvendio__PacketItem__c                    = adCP.Id;
        ci02.ADvendio__Quantity__c                      = 660;
        ci02.SomDig_Menge__c                            = 600;
        ci02.SomDig_Naturalrabatt__c                    = 10;
        insert new List<ADvendio__Campaign_Item__c>{ci01,ci02};

        Test.startTest();

            ci01    = [Select Id, ADvendio__PacketItem__c, SomDig_Menge__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci01.Id];
            System.assertEquals(adCP.Id, ci01.ADvendio__PacketItem__c);
            System.assertEquals(440, ci01.ADvendio__Quantity__c);
            System.assertEquals(400, ci01.SomDig_Menge__c);
    
            ci02    = [Select Id, ADvendio__PacketItem__c, SomDig_Menge__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci02.Id];
            System.assertEquals(adCP.Id, ci02.ADvendio__PacketItem__c);
            System.assertEquals(660, ci02.ADvendio__Quantity__c);
            System.assertEquals(600, ci02.SomDig_Menge__c);
    
            ci01.ADvendio__Availability__c              = 150;
            ci02.ADvendio__Availability__c              = 450;
            update new List<ADvendio__Campaign_Item__c>{ci01,ci02};
    
            ci01    = [Select Id, ADvendio__PacketItem__c, SomDig_Menge__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci01.Id];
            System.assertEquals(275, ci01.ADvendio__Quantity__c);
            System.assertEquals(250, ci01.SomDig_Menge__c);
            
            ci02    = [Select Id, ADvendio__PacketItem__c, SomDig_Menge__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci02.Id];
            System.assertEquals(825, ci02.ADvendio__Quantity__c);
            System.assertEquals(750, ci02.SomDig_Menge__c);

        Test.stopTest();
    }

    static testMethod void myUnitTest2() {
        
        ADvendio__Placement__c placement    = cls_P7S1_TestData.createTestPlacement(false);
        placement.SomDig_Typ__c             = 'YouTube';
        insert placement;
        
        // Create 3 ad specs
        List<ADvendio__Ad_Specs__c> lstAdS      = new List<ADvendio__Ad_Specs__c>();
        for(Integer i=0;i<3;i++){
            ADvendio__Ad_Specs__c asp = cls_P7S1_TestData.createTestAdSpec(false, placement);
            asp.ADvendio__Distribution__c   = 'Prorated';
            lstAdS.add(asp);
        }
        insert lstAdS;

        // Create 3 ad price
        List<ADvendio__Ad_price__c> lstAdPrice  = new List<ADvendio__Ad_price__c>();
        for (Integer i=0;i<3;i++){
            lstAdPrice.add(cls_P7S1_TestData.createTestAdPrice(false, lstAdS[i]));
        }
        insert lstAdPrice;

        ADvendio__MediaCampaign__c adM  = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c adCP = cls_P7S1_TestData.createTestCampaignItem(false, adM, lstAdPrice[0]);
        adCP.ADvendio__Quantity__c      = 1000;
        adCP.ADvendio__from_Date__c     = System.Today().addDays(1);                
        adCP.ADvendio__Sales_Price__c   = 100;
        insert adCP;

        // Create 2 component items
        ADvendio__Campaign_Item__c ci01                 = cls_P7S1_TestData.createTestCampaignItem(false, adM, lstAdPrice[1]);
        ci01.ADvendio__PacketItem__c                    = adCP.Id;
        ci01.ADvendio__Quantity__c                      = 50;
 
        ADvendio__Campaign_Item__c ci02                 = cls_P7S1_TestData.createTestCampaignItem(false, adM, lstAdPrice[2]);
        ci02.ADvendio__PacketItem__c                    = adCP.Id;
        ci02.ADvendio__Quantity__c                      = 150;
        insert new List<ADvendio__Campaign_Item__c>{ci01,ci02};

        Test.startTest();

            ci01    = [Select Id, ADvendio__PacketItem__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci01.Id];
            System.assertEquals(adCP.Id, ci01.ADvendio__PacketItem__c);
            System.assertEquals(50, ci01.ADvendio__Quantity__c);
    
            ci02    = [Select Id, ADvendio__PacketItem__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci02.Id];
            System.assertEquals(adCP.Id, ci02.ADvendio__PacketItem__c);
            System.assertEquals(150, ci02.ADvendio__Quantity__c);
    
            ci01.ADvendio__Availability__c              = 1;
            ci02.ADvendio__Availability__c              = 1000000;
            update new List<ADvendio__Campaign_Item__c>{ci01,ci02};
    
            ci01    = [Select Id, ADvendio__PacketItem__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci01.Id];
            System.assertEquals(1, ci01.ADvendio__Quantity__c);
    
            ci02    = [Select Id, ADvendio__PacketItem__c, ADvendio__Quantity__c, ADvendio__Prorated__c, ADvendio__Availability__c, ADvendio__LastAvailabilityForecast__c From ADvendio__Campaign_Item__c Where Id = :ci02.Id];
            System.assertEquals(999, ci02.ADvendio__Quantity__c);
        Test.stopTest();
    }
}