src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__InvoiceType__c</fullName>
        <description>Depending on the type (invoice, credit note, credit note cancellation, cancellation) invoices are treated in a different way.</description>
        <inlineHelpText>Ist die Rechnung vom Rechnungs-Typ her eine Rechnung oder aber eine Aufhebung bzw. Stornierung zu einer vorher erstellten und existierenden Rechnung (Rechnungsanpassung).</inlineHelpText>
        <label>Invoice Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Credit Note</fullName>
                </value>
                <value>
                    <fullName>Credit Note Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <inlineHelpText>Entwurf: RG-Vorschlag welche freigegeben werden muss
Freigabe: RG-Vorschlag wurde freigegeben und kann im Renchnungslauf
Fakturiert: Rechungslauf erfolgte, aus RG-Vorschlag wurde finale Rechnung
Storno: Rechnung wurde durch neue RG-Storno aufgehoben</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <label>Auftragstyp</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Rechnungsfreigabe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Mit der Checkbox wird der Status des Feldes ADvendio__Status__c auf Reviewed/Freigegeben gesetzt per Feldaktualisierung. Nur diese Rechnungen erscheinen im Rechnungslauf. Siehe KV 2271.</description>
        <inlineHelpText>Nur freigegebene Rechnungen werden im Rechnungslauf aufgeführt. Wenn eine Rechung einer Mediakampagne freigegeben, aber noch nicht fakturiert ist, kann die komplette Kampagne nicht geändert/angepasst werden</inlineHelpText>
        <label>Rechnungsfreigabe</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_BetreuerTeam__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Welches Team und welcher Vermarkter betreut die Mediakampagne im Buchungstool?</description>
        <inlineHelpText>Welches Team und welcher Vermarkter betreut die Mediakampagne im Buchungstool?</inlineHelpText>
        <label>Betreuer Team</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SomDig_BetreuerTeam__c.SomDig_TeamUngueltig__c</field>
                <operation>notEqual</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>SomDig_BetreuerTeam__c</referenceTo>
        <relationshipLabel>Mediakampagne</relationshipLabel>
        <relationshipName>Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_WtAgBeziehung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Statt WT und AG wird die Beziehung hier ausgewählt. Infofelder WT und AG von ADvendio  füllen sich dann automatisch per Trigger (siehe KV 1254)</description>
        <inlineHelpText>Statt WT und AG wird die Beziehung hier ausgewählt. Infofelder WT und AG füllen sich dann automatisch</inlineHelpText>
        <label>WT AG Beziehung</label>
        <referenceTo>SomDig_WtAgBeziehung__c</referenceTo>
        <relationshipLabel>Mediakampagnen</relationshipLabel>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Zahlungsbedingung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Nimmt die möglichen Zahlungsbedingungen auf um die in der Medienkampagne gewählten Zahlungsbedingungen korrekt an SAP übergeben zu können. 
Erfasst werden Prozentangaben Skonto, Zahlungsbedingungstext, SAP-Code (Bezeichner)</description>
        <inlineHelpText>Nimmt die möglichen Zahlungsbedingungen auf um die in der Medienkampagne gewählten Zahlungsbedingungen korrekt an SAP übergeben zu können. 
Erfasst werden Prozentangaben Skonto, Zahlungsbedingungstext, SAP-Code (Bezeichner)</inlineHelpText>
        <label>Zahlungsbedingung</label>
        <referenceTo>SomDig_Zahlungsbedingung__c</referenceTo>
        <relationshipLabel>Mediakampagnen</relationshipLabel>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <recordTypes>
        <fullName>SomDig_Auftrag</fullName>
        <active>true</active>
        <description>verlinkt mit Auftragslayout</description>
        <label>Auftrag</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <fields>
        <fullName>SomDig_Rechnungstellung__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sollen die Mediakampagnen bei diesem Auftragstyp abgerechnet werden? Wenn Checkbox auf WAHR ist, wird eine Rechnung gestellt. Wird via Workflow/Feldaktualisierung auf Mediakampagnen-Basis umgesetzt. Nur Billing-Profil kann die Voreinstellung überschreiben/bearbeiten und Checkbox &quot;Gutschrift&quot; ist nicht aktiv</description>
        <inlineHelpText>Sollen die Mediakampagnen bei diesem Auftragstyp abgerechnet werden? Wenn Checkbox auf WAHR ist, wird eine Rechnung gestellt (wenn Checkbox &quot;Gutschrift&quot; nicht ausgewählt ist). Nur Billing-Profil kann die Voreinstellung überschreiben/bearbeiten</inlineHelpText>
        <label>Rechnungstellung</label>
        <type>Checkbox</type>
    </fields>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <description>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</description>
        <inlineHelpText>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</inlineHelpText>
        <label>P7S1_Sphere</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aer</fullName>
                    <color>#666666</color>
                    <label>Aer</label>
                </value>
                <value>
                    <fullName>Sgn</fullName>
                    <color>#BBBBBB</color>
                    <label>Sgn</label>
                </value>
                <value>
                    <fullName>SomAt</fullName>
                    <color>#CC33CC</color>
                    <label>SomAt</label>
                </value>
                <value>
                    <fullName>SomDe</fullName>
                    <color>#FF0000</color>
                    <label>SomDe</label>
                </value>
                <value>
                    <fullName>Ven</fullName>
                    <color>#333399</color>
                    <label>Ven</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Enthält die Information welcher Unit der User zugeordnet ist</description>
        <inlineHelpText>Enthält die Information welcher Unit der User zugeordnet ist</inlineHelpText>
        <label>Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_IsTeamLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Kennzeichnet einen User als PAM TeamLead. Siehe Ticket 4864.</description>
        <inlineHelpText>Kennzeichnet einen User als PAM TeamLead.</inlineHelpText>
        <label>Is TeamLead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_SalesTeam__c</fullName>
        <description>Hilfsfeld für die SevenOne Media Digital Sales, wird primär für Reportzwecken genutzt (Datensätze wie Oppties etc. werden in den Reports u.a. nach diesen Werten gruppiert). Folgende Infos beinhaltet das Feld: Bereich (Digital), Abteilung (Sales), Unterabteilung (RTA/ECC) und Location; nicht über stringent, Anforderung Fachabteilung. Nachfolger vom Feld 
Vertriebs-Team (VB_Location__c)</description>
        <inlineHelpText>Hilfsfeld für die SOM Digital Sales, wird primär für Reportzwecken genutzt (Datensätze wie Oppties etc. werden in den Reports u.a. nach diesen Werten gruppiert). Bitte bei jedem Digital-Vertriebler auswählen. Nachfolger-Feld von Vertriebs-Team/Location</inlineHelpText>
        <label>Vertriebsteam Digital</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vertrieb Berlin</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Düsseldorf</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Frankfurt</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Hamburg</fullName>
                </value>
                <value>
                    <fullName>Vertrieb München</fullName>
                </value>
                <value>
                    <fullName>Vertrieb ECC</fullName>
                </value>
                <value>
                    <fullName>Vertrieb RTA</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Steuerung</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_FieldValidation_Test.cls
@isTest
public class Adv_MediaCampaign_FieldValidation_Test{

    public static testMethod void testChangeWtAgWhenUserIsNoTeamLeadNorBilling(){
        //When a user that is not billing or Lead changes wtag-beziehung in status auftrag, error should appear.
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        Boolean expectedExceptionThrown = false;

        Test.startTest();

        try{
            // Create WTAG
            SomDig_WtAgBeziehung__c objNewWTAG = cls_P7S1_TestData.createTestWTAG(true, null, null);
            objMC.SomDig_WtAgBeziehung__c = objNewWTAG.ID;
            update objMC;
        }catch(Exception e){
            expectedExceptionThrown =  e.getMessage().contains(Adv_MediaCampaign_FieldValidation.WTAGBEZIEHUNGERROR);
        }

        Test.stopTest();

        System.AssertEquals(expectedExceptionThrown, true);
    }

    public static testMethod void testChangeWtAgWithBillingUser(){
        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' AND P7S1_Unit__c = '71M' LIMIT 1];

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        Boolean exceptionThrown = false;

        Test.startTest();

        System.runAs(objUserBilling) {
            try{
                // Create WTAG
                SomDig_WtAgBeziehung__c objNewWTAG = cls_P7S1_TestData.createTestWTAG(true, null, null);
                objMC.SomDig_WtAgBeziehung__c = objNewWTAG.ID;
                update objMC;
            }catch(Exception e){
               exceptionThrown = true;
            }
        }



        Test.stopTest();

        System.AssertEquals(exceptionThrown, false);
    }

    public static testMethod void testChangeWtAgWithTeamLeadUser(){
        User objUserLead = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserLead.SomDig_IsTeamLead__c = true;
        update objUserLead;

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        Boolean exceptionThrown = false;

        Test.startTest();

        System.runAs(objUserLead) {
            try{
                // Create WTAG
                SomDig_WtAgBeziehung__c objNewWTAG = cls_P7S1_TestData.createTestWTAG(true, null, null);
                objMC.SomDig_WtAgBeziehung__c = objNewWTAG.ID;
                update objMC;
            }catch(Exception e){
                exceptionThrown = true;
            }
        }

        Test.stopTest();

        System.AssertEquals(exceptionThrown, false);
    }

    public static testMethod void testChangeWtAgWithInvoicedInvoices(){
        User objUserLead = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserLead.SomDig_IsTeamLead__c = true;
        update objUserLead;

        // New MC
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        ADvendio__Invoice__c objInv = cls_P7S1_TestData.createTestInvoice(false, objMC);
        objInv.ADvendio__InvoiceType__c = 'Invoice';
        objInv.ADvendio__Status__c = 'Invoiced';
        insert objInv;

        Boolean expectedExceptionThrown = false;

        Test.startTest();

        System.runAs(objUserLead) {
            try{
                // Create WTAG
                SomDig_WtAgBeziehung__c objNewWTAG = cls_P7S1_TestData.createTestWTAG(true, null, null);
                objMC.SomDig_WtAgBeziehung__c = objNewWTAG.ID;
                update objMC;

            }catch(Exception e){
                expectedExceptionThrown =  e.getMessage().contains(Adv_MediaCampaign_FieldValidation.WTAGBEZIEHUNGERROR) ? true : false;
            }
        }

        Test.stopTest();

        System.AssertEquals(expectedExceptionThrown, true);

    }

    public static testMethod void testChangeWtAgWithUnreviewedCancellation(){
        User objUserLead = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserLead.SomDig_IsTeamLead__c = true;
        update objUserLead;

        // New MC
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        ADvendio__Invoice__c objInv = cls_P7S1_TestData.createTestInvoice(false, objMC);
        objInv.ADvendio__InvoiceType__c = 'Invoice';
        objInv.ADvendio__Status__c = 'Cancelled';
        objInv.SomDig_Rechnungsfreigabe__c = false;
        insert objInv;

        ADvendio__Invoice__c objCancel = cls_P7S1_TestData.createTestInvoice(false, objMC);
        objCancel.ADvendio__InvoiceType__c = 'Cancellation';
        objCancel.ADvendio__Status__c = 'Invoiced';
        objCancel.SomDig_Rechnungsfreigabe__c = false;
        insert objCancel;

        Boolean expectedExceptionThrown = false;

        Test.startTest();

        System.runAs(objUserLead) {
            try{
                // Create WTAG
                SomDig_WtAgBeziehung__c objNewWTAG = cls_P7S1_TestData.createTestWTAG(true, null, null);
                objMC.SomDig_WtAgBeziehung__c = objNewWTAG.ID;
                update objMC;

            }catch(Exception e){
                expectedExceptionThrown =  e.getMessage().contains(Adv_MediaCampaign_FieldValidation.WTAGBEZIEHUNGERROR) ? true : false;
            }
        }

        Test.stopTest();

        System.AssertEquals(expectedExceptionThrown, true);

    }

    @isTest
    public static void testCampaignHasChanged(){
        ADvendio__MediaCampaign__c objMC1 = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC1.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC1;
        ADvendio__MediaCampaign__c objMC2 = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC2.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC2;

        Test.startTest();

        Boolean bTeamChanged = Adv_MediaCampaign_FieldValidation.isBetreuerTeamChanged(objMC1, objMC2);
        Boolean bPriceListChanged = Adv_MediaCampaign_FieldValidation.isPriceListChanged(objMC1, objMC2);
        Boolean bFieldChanged = Adv_MediaCampaign_FieldValidation.isFixedFieldChange(objMC1, objMC2);

        Test.stopTest();

        System.assert(!bTeamChanged);
        System.assert(bPriceListChanged);
        System.assert(bFieldChanged);
    }

    @isTest
    public static void testChangeBetreuerTeamAsPAM() {
        User objUserPAM = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserPAM.SomDig_SalesTeam__c = 'test';
        update objUserPAM;


        ADvendio__MediaCampaign__c objMC1 = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC1.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC1;

        Boolean bCatchedExceptionForPAM = false;

        Test.startTest();

        System.runAs(objUserPAM) {

            objMC1.SomDig_BetreuerTeam__c = cls_P7S1_TestData.createTestBetreuerTeam(true).Id;
            try{
                update objMC1;
            } catch(Exception e){
                bCatchedExceptionForPAM = true;
            }

        }

        Test.stopTest();

        System.assertEquals(true, bCatchedExceptionForPAM);
    }

    @isTest
    public static void testChangeBetreuerTeamAsBilling() {
        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' AND P7S1_Unit__c = '71M' LIMIT 1];

        ADvendio__MediaCampaign__c objMC1 = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC1.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC1;

        Boolean bCatchedExceptionForBilling = false;

        Test.startTest();

        System.runAs(objUserBilling) {

            objMC1.SomDig_BetreuerTeam__c = cls_P7S1_TestData.createTestBetreuerTeam(true).Id;
            try{
                update objMC1;
            } catch(Exception e){
                bCatchedExceptionForBilling = true;
            }

        }

        Test.stopTest();

        System.assertEquals(false, bCatchedExceptionForBilling);
    }

    @isTest
    public static void testChangeBetreuerTeamAsVertriebSteuerung() {
        User objUserPAM = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserPAM.SomDig_SalesTeam__c = 'Vertrieb Steuerung';
        update objUserPAM;

        ADvendio__MediaCampaign__c objMC1 = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC1.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC1;

        Boolean bCatchedExceptionForVertriebSteuerung = false;

        Test.startTest();

        System.runAs(objUserPAM) {

            objMC1.SomDig_BetreuerTeam__c = cls_P7S1_TestData.createTestBetreuerTeam(true).Id;
            try{
                update objMC1;
            } catch(Exception e){
                bCatchedExceptionForVertriebSteuerung = true;
            }

        }

        Test.stopTest();

        System.assertEquals(false, bCatchedExceptionForVertriebSteuerung);
    }

    @isTest
    public static void testValidateBillMe(){
        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' AND P7S1_Unit__c = '71M' LIMIT 1];

        System.runAs(objUserBilling) {
            SomDig_Auftragstyp__c auftragstyp = cls_P7S1_TestData.createTestAuftragstyp(false);
            auftragstyp.SomDig_Rechnungstellung__c = false;
            insert auftragstyp;

            ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true, auftragstyp);
            // New MC
            ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false, null, pricelist);
            objMC.RecordTypeID = '012D0000000Qj9BIAS';
            objMC.ADvendio__BillMe__c = false;
            insert objMC;

            ADvendio__Invoice__c objInv = cls_P7S1_TestData.createTestInvoice(false, objMC);
            objInv.ADvendio__Status__c = 'Invoiced';
            objInv.SomDig_Rechnungsfreigabe__c = TRUE;
            insert objInv;

            String sErrorMessage;

            Test.startTest();

            objMC.ADvendio__BillMe__c = !objMC.ADvendio__BillMe__c;

            try {
                update objMC;
            } catch(Exception e) {
                sErrorMessage = e.getMessage();
            }


            Test.stopTest();

            System.assert(sErrorMessage.contains(Label.Adv_MediaCampaign_BillMeValidationError));
            System.assertEquals('Invoice', [SELECT ADvendio__InvoiceType__c FROM ADvendio__Invoice__c WHERE ID = :objInv.Id].ADvendio__InvoiceType__c);
        }
    }

    @isTest
    public static void validateBillMeUserIsTeamLead(){

        User objUserPAM = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserPAM.SomDig_IsTeamLead__c = true;
        update objUserPAM;

        System.runAs(objUserPAM) {
            boolean bCatchedException = false;

            Test.startTest();
            try{
                // New MC
                ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
                objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
                insert objMC;
            }catch(Exception e){
                bCatchedException = true;
            }
            Test.stopTest();

            System.assert(!bCatchedException, 'Validation Rule for billMe fired');
        }
    }

    @isTest
    public static void validateBillMeStornierungReviewed(){
        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' AND P7S1_Unit__c = '71M' LIMIT 1];

        System.runAs(objUserBilling) {
            // New MC
            ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
            objMC.RecordTypeID = '012D0000000Qj9BIAS';
            insert objMC;

            ADvendio__Invoice__c objInv = cls_P7S1_TestData.createTestInvoice(false, objMC);
            objInv.ADvendio__Status__c = 'Reviewed';
            insert objInv;

            objInv.ADvendio__InvoiceType__c = 'Cancellation';
            update objInv;

            Boolean bException = false;
            Test.startTest();

            objMC.ADvendio__BillMe__c = !objMC.ADvendio__BillMe__c;

            try {
                update objMC;
            } catch(Exception e) {
                bException = true;
            }


            Test.stopTest();

            System.assert(bException == false, 'Expected Value: false  Actuall Value: '+bException);
            System.assert([SELECT ADvendio__InvoiceType__c FROM ADvendio__Invoice__c WHERE ID = :objInv.Id] != null);
        }
    }

    @isTest
    public static void validateBillMeGutschrift(){
        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' AND P7S1_Unit__c = '71M' LIMIT 1];

        System.runAs(objUserBilling) {
            // New MC
            SomDig_Zahlungsbedingung__c objZB = cls_P7S1_TestData.createTestZahlungsbedingung(false);
            objZB.SomDig_Skontowert__c = 0.0;
            insert objZB;

            ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
            objMC.RecordTypeID = '012D0000000Qj9BIAS';
            objMC.SomDig_GutschriftPerformance__c = true;
            objMC.SomDig_Zahlungsbedingung__c = objZB.Id;
            insert objMC;

            ADvendio__Invoice__c objInv = cls_P7S1_TestData.createTestInvoice(false, objMC);
            objInv.ADvendio__Status__c = 'Invoiced';
            objInv.SomDig_Rechnungsfreigabe__c = TRUE;
            insert objInv;

            String sErrorMessage;

            Boolean bException = false;
            Test.startTest();

            objMC.ADvendio__BillMe__c = !objMC.ADvendio__BillMe__c;

            try {
                update objMC;
            } catch(Exception e) {
                bException = true;
            }

            Test.stopTest();

            System.assert(bException == false, 'Expected Value: false  Actuall Value: '+bException);
            System.assert([SELECT ADvendio__InvoiceType__c FROM ADvendio__Invoice__c WHERE ID = :objInv.Id] != null);
        }
    }

    @isTest
    public static void testChangeSACConceptionManagerAsBilling() {

        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' AND P7S1_Unit__c = '71M' LIMIT 1];

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        Boolean exceptionThrown = false;

        Test.startTest();

        System.runAs(objUserBilling) {
            try{
                objMC.SomDig_SACConceptionManager__c = objUserBilling.ID;
                update objMC;
            }catch(Exception e){
               exceptionThrown = e.getMessage().contains(Adv_MediaCampaign_FieldValidation.SACCONCEPTIONMANAGERERROR);
            }
        }

        Test.stopTest();

        System.Assert(!exceptionThrown);

    }

    @isTest
    public static void testChangeSACConceptionManagerAsTeamLead() {

        User objUserLead = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserLead.SomDig_IsTeamLead__c = true;
        update objUserLead;

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        Boolean exceptionThrown = false;

        Test.startTest();

        System.runAs(objUserLead) {
            try{
                objMC.SomDig_SACConceptionManager__c = objUserLead.ID;
                update objMC;
            }catch(Exception e){
               exceptionThrown = e.getMessage().contains(Adv_MediaCampaign_FieldValidation.SACCONCEPTIONMANAGERERROR);
            }
        }

        Test.stopTest();

        System.Assert(!exceptionThrown);

    }

    @isTest
    public static void testChangeSACConceptionManagerAsPAM() {

        User objUserPAM = cls_P7S1_TestData.USER_FOR_PROFILE.get('SomDig_PAM');
        objUserPAM.SomDig_IsTeamLead__c = false;
        update objUserPAM;

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.RecordTypeID = cls_P7S1_Utils.getRecordTypeId('ADvendio__MediaCampaign__c', 'SomDig_Auftrag');
        insert objMC;

        Boolean exceptionThrown = false;

        Test.startTest();

        System.runAs(objUserPAM) {
            try{
                objMC.SomDig_SACConceptionManager__c = objUserPAM.ID;
                update objMC;
            }catch(Exception e){
               exceptionThrown = e.getMessage().contains(Adv_MediaCampaign_FieldValidation.SACCONCEPTIONMANAGERERROR);
            }
        }

        Test.stopTest();

        System.Assert(exceptionThrown);

    }


}