src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipName>OptimizingVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_OptimizingVersion_Attachment_Test.cls
@isTest
private class Adv_OptimizingVersion_Attachment_Test {

    @isTest static void testOptimizingVersionCreateAttachment() {              
    
        // Create Campaign
        ADvendio__MediaCampaign__c objCampaign = cls_P7S1_TestData.createTestMediaCampaign(true); 

        // Optimizing Version 
        ADvendio__OptimizingVersion__c objOV = createADvendioOptimizingVersion(false);
        objOV.ADvendio__MediaCampaign__c = objCampaign.ID;
        insert objOV;    
        

        String res = Adv_OptimizingVersion_Attachment.attachPDFToOV( objOV.ID, objCampaign.ID, 'testname' );
          
        System.assert( res == 'SUCCESS' );
    }
    
    // TODO: move to TESTClass
    public static ADvendio__OptimizingVersion__c createADvendioOptimizingVersion(Boolean isInsert){
        ADvendio__OptimizingVersion__c objOV = new ADvendio__OptimizingVersion__c();
        if(isInsert) insert objOV;
        return objOV;
    }      
}