src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__InvoiceDate__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <inlineHelpText>Entwurf: RG-Vorschlag welche freigegeben werden muss
Freigabe: RG-Vorschlag wurde freigegeben und kann im Renchnungslauf
Fakturiert: Rechungslauf erfolgte, aus RG-Vorschlag wurde finale Rechnung
Storno: Rechnung wurde durch neue RG-Storno aufgehoben</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_SapBuchungsdatumAuto__c</fullName>
        <label>Sap Datum Neu</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_InvoiceMonth__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_ClosureDateTime__c</fullName>
        <description>Zeigt  Datum und Zeit an, zu welchem der aktuelle Monat geschlossen wurde.</description>
        <inlineHelpText>Zeigt  Datum und Zeit an, zu welchem der aktuelle Monat geschlossen wurde.</inlineHelpText>
        <label>Monat geschlossen am</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SomDig_Month__c</fullName>
        <label>Monat</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_To__c</fullName>
        <description>Rechnungsdatum bis zu dem inklusive der Monat zugeordnet werden soll</description>
        <inlineHelpText>Rechnungsdatum bis zu dem inklusive der Monat zugeordnet werden soll</inlineHelpText>
        <label>Rechnungsdatum bis</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Year__c</fullName>
        <label>Jahr</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rechnungsmonat</label>
    <nameField>
        <displayFormat>IM-{0000}</displayFormat>
        <label>Rechnungsmonats-Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rechnungsmonate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_Invoice_SapDatum.cls
public with sharing class Adv_Invoice_SapDatum extends TriggerController {

    // Constructor
    public Adv_Invoice_SapDatum(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }

    protected override void runBeforeInsert() {
        assignSapDate((List<ADvendio__Invoice__c>) lstNewItems, NULL);
    }
    protected override void runBeforeUpdate() {
        assignSapDate((List<ADvendio__Invoice__c>) lstNewItems, (Map<Id, ADvendio__Invoice__c>)mapOldItems);
    }

    @testvisible private static List<SomDig_InvoiceMonth__c> cachedInvoiceMonths {
        get {
            if (cachedInvoiceMonths == null) {
                cachedInvoiceMonths = [
                    SELECT SomDig_To__c, SomDig_Month__c, SomDig_Year__c 
                    FROM SomDig_InvoiceMonth__c
                    WHERE SomDig_ClosureDateTime__c = null
                    ORDER BY SomDig_To__c ASC
                ];
            }
            return cachedInvoiceMonths;
        }
        set;
    }

    public static void assignSapDate(List<ADvendio__Invoice__c> newInvoiceList, Map<Id, ADvendio__Invoice__c> oldInvoiceMap) {

        for(ADvendio__Invoice__c invoice : newInvoiceList) {
            if(oldInvoiceMap == null || invoice.ADvendio__InvoiceDate__c != oldInvoiceMap.get(invoice.Id).ADvendio__InvoiceDate__c  || (invoice.ADvendio__Status__c != oldInvoiceMap.get(invoice.Id).ADvendio__Status__c && invoice.ADvendio__Status__c == 'Invoiced')) {
                SomDig_InvoiceMonth__c correctInvoiceMonth = findCorrectInvoiceMonth(invoice.ADvendio__InvoiceDate__c);
                invoice.SomDig_SapBuchungsdatumAuto__c = correctInvoiceMonth != null ? formatInvoiceDate(correctInvoiceMonth.SomDig_Year__c, correctInvoiceMonth.SomDig_Month__c) : formatInvoiceDate(invoice.ADvendio__InvoiceDate__c.year(), invoice.ADvendio__InvoiceDate__c.month());
            }
        }

    }

    private static SomDig_InvoiceMonth__c findCorrectInvoiceMonth(Date invoiceDate) {

        SomDig_InvoiceMonth__c correctInvoiceMonth = null;
        
        for(SomDig_InvoiceMonth__c invoiceMonth : cachedInvoiceMonths) {
            if(invoiceMonth.SomDig_To__c >= invoiceDate) {
                correctInvoiceMonth = invoiceMonth;
                break;
            }
        }

        return correctInvoiceMonth;

    }
 
    private static String formatInvoiceDate(Decimal year, Decimal month) {
        String sMonth = String.valueOf(month);
        if(sMonth.length() == 1) sMonth = '0' + sMonth;
        String sYear = String.valueOf(year);
        return sMonth + '.' + sYear;
    }

}