src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Availability__c</fullName>
        <description>The ad server interface will enter the availability during an availabilty request.</description>
        <inlineHelpText>The ad server interface will enter the availability during an availabilty request.</inlineHelpText>
        <label>Availability (planned)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__BookingQuantity__c</fullName>
        <description>The real quantity being booked by Ad-Server.</description>
        <formula>ROUND(IF(NOT(ISNULL(ADvendio__Total_Impressions__c)), ADvendio__Total_Impressions__c, 
IF( AND(OR(ISPICKVAL( ADvendio__Billing_category__c, &quot;CPD&quot;), ISPICKVAL( ADvendio__Billing_category__c, &quot;Fixed Price&quot;), ISPICKVAL( ADvendio__Billing_category__c, &quot;CPW&quot;), ISPICKVAL( ADvendio__Billing_category__c, &quot;CPMo&quot;), ISPICKVAL( ADvendio__Billing_category__c, &quot;CPY&quot;), ISPICKVAL( ADvendio__Billing_category__c, &quot;CPSec&quot;)), NOT(ISNULL( ADvendio__Guaranteed_AI__c ))), ADvendio__Guaranteed_AI__c, 
IF( AND( NOT(ISNULL(ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__OverbookingFactor__c)), OR( ISPICKVAL( ADvendio__Billing_category__c , &apos;CPC&apos; ), ISPICKVAL( ADvendio__Billing_category__c, &apos;CPM&apos; ))), ADvendio__Quantity__c * (1 + ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__OverbookingFactor__c), ADvendio__Quantity__c))),0)</formula>
        <inlineHelpText>The real quantity being booked by Ad-Server.</inlineHelpText>
        <label>Booking Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Days__c</fullName>
        <description>This field will automatically calculate the amount of days on which this campaign item will be displayed.</description>
        <formula>ADvendio__until_Date__c  -  ADvendio__from_Date__c  + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field will automatically calculate the amount of days on which this campaign item will be displayed.</inlineHelpText>
        <label>Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__LastAvailabilityForecast__c</fullName>
        <description>Last Availability Forecast run</description>
        <label>Last Availability Forecast</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ADvendio__LastBookingProcess__c</fullName>
        <description>Last Booking run</description>
        <label>Last Booking Process</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_DurationAtBooking__c</fullName>
        <description>KV 2429. Wird beim durchbuchen durch einen Process befüllt, der hier die Differenz zwischen Start und Enddatum in Tagen reinschreibt.</description>
        <inlineHelpText>Anzahl der Tage zwischen Start- und Enddatum wenn durchgebucht wurde.</inlineHelpText>
        <label>Duration at Booking</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_LastOptimizationActivationDate__c</fullName>
        <description>KV 01371. Dieses Feld wird mit dem jetzigen Datum aktualisiert, wenn eine Optimierung aktiviert wird, in der die Kampagnenposition optimiert wird.</description>
        <label>Last Optimization Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SomDig_PositionStatus__c</fullName>
        <description>-Inaktiv: Durchgebuchung im AdServer erfolgt, kein Motiv eingebucht.
-bereit: Werbemittel sind im AdServer eingebucht und aktiviert 
-Auslieferung-normal: DFP meldet tatsätzliche AIs und AIist&gt;=AIsollbisheute
-Auslieferung@Risk: DFP meldet tatsätzliche AIs und AIist&lt;AIsollbisheute
-pausiert: Position in AdServer wurde gestoppt/pausiert (DFP meldet &apos;pausiert&apos;)
-beendet - erfüllt: Enddatum in der Vergangenheit, AIs ist &gt;= AIs Soll 
-beendet - unterliefert: Enddatum in der Vergangenheit, AIs ist &lt; AIs Soll
-NonAdServer: Position enthält ein NonAdServer Produkt</description>
        <inlineHelpText>-Inaktiv:durchgebucht,kein Motiv
-bereit:im AdServer aktiviert
-normal:AIist&gt;=AIsollbisheute
-@Risk:AIist&lt;AIsollbisheute
-pausiert:laufender Flight wurde gestoppt
-erfüllt:beendet &amp; AIist&gt;=AIsoll
-unterliefert:beendet &amp; AIist&lt;AIsoll</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
                <value>
                    <fullName>bereit</fullName>
                </value>
                <value>
                    <fullName>An Adserver übermitteln</fullName>
                    <default>true</default>
                    <label>An Adserver übermitteln</label>
                </value>
                <value>
                    <fullName>Ad Status aktualisieren</fullName>
                </value>
                <value>
                    <fullName>Position pausiert</fullName>
                </value>
                <value>
                    <fullName>Position gestoppt</fullName>
                </value>
                <value>
                    <fullName>NonAdserver</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-normal</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-@Risk</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-erfüllt</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-unterliefert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Positionsnr__c</fullName>
        <description>Positionsnummer inkl. Anhang</description>
        <formula>TEXT( ADvendio__PositionNumber__c) &amp; ADvendio__PositionNumberAppendix__c</formula>
        <inlineHelpText>Positionsnummer inkl. Anhang</inlineHelpText>
        <label>Positionsnr.</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Verfuegbarkeitsrelevant__c</fullName>
        <description>Benötigt für KV 02429. An diesem Feld erkennt man, ob die Mediakampagne für die Verfügbarkeitsabfrage relevant ist.</description>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__r.SomDig_Verfuegbarkeitsrelevant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Verfügbarkeitsrelevant</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizingVersion__c</fullName>
        <label>Optimizing Version</label>
        <referenceTo>ADvendio__OptimizingVersion__c</referenceTo>
        <relationshipLabel>Optimizing Changes</relationshipLabel>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__DateOfActivation__c</fullName>
        <description>Shows the date / time when the Optimizing Version was activated.</description>
        <inlineHelpText>Shows the date / time when the Optimizing Version was activated.</inlineHelpText>
        <label>Date Of Activation</label>
        <type>DateTime</type>
    </fields>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SomDig_IsTeamLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Kennzeichnet einen User als PAM TeamLead. Siehe Ticket 4864.</description>
        <inlineHelpText>Kennzeichnet einen User als PAM TeamLead.</inlineHelpText>
        <label>Is TeamLead</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_Remoter.cls
// Class for KV 02429
// Remote button for: Submit_to_AdServerCustom
global with sharing class Adv_CampaignItem_Remoter {
    
    public ID campaignID { get; set; }

    public Adv_CampaignItem_Remoter(){
        campaignID = apexpages.currentpage().getparameters().get('mcID');
    }
    
    @RemoteAction
    global static String checkAvailability(String recordIDs) {
        
        String result = '';
        
        List<ID> setCampIDs = recordIDs.split(',');
        
        // History vom startdate für Step 8 benötigt.
        List<ADvendio__Campaign_Item__c> listCI = new List<ADvendio__Campaign_Item__c>([SELECT Name, RecordType.DeveloperName, ADvendio__Days__c, SomDig_Positionsnr__c, SomDig_DurationAtBooking__c, ADvendio__LastBookingProcess__c, ADvendio__LastAvailabilityForecast__c, SomDig_LastOptimizationActivationDate__c, ADvendio__BookingQuantity__c,ADvendio__Availability__c, ADvendio__Billing_category__c, ADvendio__Media_Campaign__r.SomDig_Verfuegbarkeitsrelevant__c , SomDig_PositionStatus__c, ADvendio__Rate_Discount_4_Name__c, ADvendio__Media_Campaign__r.RecordType.Name, 
                                                                                       (SELECT CreatedDate FROM Histories WHERE Field = 'ADvendio__from_Date__c')
                                                                                        FROM ADvendio__Campaign_Item__c WHERE ID IN :setCampIDs]);
        
        

        ////// Pre-check, bei einer Position Sonderrabatt?
        for(ADvendio__Campaign_Item__c o : listCI){
            System.Debug('####' + o.ADvendio__Media_Campaign__r.RecordType.Name);        
            String sRabatt = o.ADvendio__Rate_Discount_4_Name__c;
            if((sRabatt == 'Nachlieferung' || sRabatt == 'Kompensation' || sRabatt == 'Storno mit Leistungsfluss' || sRabatt == 'Storno ohne Leistungsfluss') && o.ADvendio__Media_Campaign__r.RecordType.Name == 'Angebot')
                return 'Bei mindestens einer Position ist ein unzulässiger Sonderrabatt hinterlegt.';    
        }

        
        ////// Criteria 1: ist Auftragstyp der betroffenden Kampagne "Verfügbarkeitsrelevant"? -> wenn nein, übermitteln
        System.Debug('###Step1');
        if(!listCI[0].ADvendio__Media_Campaign__r.SomDig_Verfuegbarkeitsrelevant__c)
            return 'success';
            
            
        ////// Criteria 2: haben alle Positionen im Angebotsstatus eine Positionsnummer ungleich Null und 0?    
        for(ADvendio__Campaign_Item__c o : listCI){
            if(o.ADvendio__Media_Campaign__r.RecordType.Name == 'Angebot' && (o.SomDig_Positionsnr__c == null || o.SomDig_Positionsnr__c == '0'))
                return 'Bitte erst Dokument erstellen.';
        }


        ////// Criteria 3: Positionsstatus "An Adserver übermitteln"? -> wenn nein, stop
        System.Debug('###Step3');        
        for(ADvendio__Campaign_Item__c o : listCI)
            if(!(o.SomDig_PositionStatus__c == 'An Adserver übermitteln' || o.SomDig_PositionStatus__c == 'NonAdserver'))
                result += 'Die Kampagnenposition ' + o.Name  + ' ist nicht im Status "An Adserver übermitteln".';

        if(result != '')
            return result;



        ////// Criteria 4: Ist mindestens eine Abrechnugsart CPM? -> wenn nein, stop
        System.Debug('###Step4');
        List<ADvendio__Campaign_Item__c> listCICPM = new List<ADvendio__Campaign_Item__c>();
        Set<ID> setCPMIDs = new Set<ID>();
        for (ADvendio__Campaign_Item__c o : listCI)
            if(o.ADvendio__Billing_category__c == 'CPM'){
                listCICPM.add(o);        
                setCPMIDs.add(o.ID);
            }

        if(listCICPM.isEmpty())
            return 'success';
        
        
        //////// Ab hier weiter mit CMPs

        
        // Criteria 5: Gab es eine Optimierung in den letzten 24h
        System.Debug('###Step4');     
        Datetime dt = System.now().addDays(-1);
        Set<ID> setOptimizedCIs = new Set<ID>();
        
        // Get CIs which are optimized
        /*for(ADvendio__OptimizingChange__c o : [SELECT ID, ADvendio__CampaignItem__c FROM ADvendio__OptimizingChange__c WHERE 
                                               ADvendio__OptimizingVersion__r.ADvendio__DateOfActivation__c != null AND 
                                               ADvendio__OptimizingVersion__r.ADvendio__DateOfActivation__c > :dt AND 
                                               ADvendio__CampaignItem__c IN :setCPMIDs])
            setOptimizedCIs.add(o.ADvendio__CampaignItem__c);
          */  

            
        List<ADvendio__Campaign_Item__c> listCPMNotOptimized = new List<ADvendio__Campaign_Item__c>();                    
        for (ADvendio__Campaign_Item__c o : listCICPM)
            if(o.SomDig_LastOptimizationActivationDate__c == null || o.SomDig_LastOptimizationActivationDate__c < dt)
                listCPMNotOptimized.add(o);        
        
        // Wenn keine nicht Optimiert wurde
        if(listCPMNotOptimized.isEmpty())
            return 'success';
            
 
        //////// Ab hier weiter mit CPMs (listCPMNotOptimized)        
        
        
        // Criteria 6: Verfügbarkeitsabfrage durchgeführt?
        System.Debug('###Step5');        
        for(ADvendio__Campaign_Item__c o : listCPMNotOptimized)
            if(o.ADvendio__Availability__c == null)
                result += 'Verfügbarkeitsabfrage nicht durchgeführt bei ' + o.Name + '.\n';

        if(result != '')
            return result;        
        
       
        
        // Criteria 7: Verfügbarkeitsabfrage <3h?
        System.Debug('###Step6');        
        for(ADvendio__Campaign_Item__c o : listCPMNotOptimized)
            if(o.RecordType.DeveloperName != 'Packet' && o.ADvendio__LastAvailabilityForecast__c.addHours(3) < System.now() )
                result += 'Verfügbarkeitsabfrage ist älter als 3 Stunden bei: ' + o.Name  + '.\n';

        if(result != '')
            return result;                
            
            

        // Criteria 8: ADvendio__LastAvailabilityForecast__c
        //ADvendio__BookingQuantity__c - ADvendio__Availability__c <= 0
        System.Debug('###Step7');        
        List<ADvendio__Campaign_Item__c> listNoAvailability = new List<ADvendio__Campaign_Item__c>();                    
        for (ADvendio__Campaign_Item__c o : listCPMNotOptimized){
            if(o.ADvendio__BookingQuantity__c > o.ADvendio__Availability__c)
                listNoAvailability.add(o);                        
        }
        if(listNoAvailability.isEmpty())
            return 'success';        

        
        
        //////// Ab hier weiter mit listNoAvailability
        
        
        // Criteria 9: gibt es ein letztes Datum der Durchbuchung? wenn ja, wurde die laufzeit verlängert? 
        // nur wenn alle verlängert übergeben
        // ansonsten weiter        
        System.Debug('###Step8');                
        
        Integer iNumberOfIncreasedDates = 0;
        for (ADvendio__Campaign_Item__c o : listNoAvailability){            
            if(o.ADvendio__LastBookingProcess__c != null) {           
                
                Boolean bDurationNotChangedAfterLastBookingProcess = false;
                for(ADvendio__Campaign_Item__History h : o.Histories)
                    if(h.CreatedDate > o.ADvendio__LastBookingProcess__c)
                        bDurationNotChangedAfterLastBookingProcess = false;
            
                if(o.SomDig_DurationAtBooking__c > o.ADvendio__Days__c && bDurationNotChangedAfterLastBookingProcess)
                    iNumberOfIncreasedDates++;               
            }
        }
        

        if(iNumberOfIncreasedDates == listNoAvailability.size())
            return 'success';  


        // Criteria 10: is Teamlead
        System.Debug('###Step9');  

        Boolean isTeamLead = [SELECT SomDig_IsTeamLead__c FROM User WHERE ID = :UserInfo.getUserId() LIMIT 1].SomDig_IsTeamLead__c;
        if(isTeamLead)
            return 'success';


        return 'Für eine der Positionen ist nicht ausreichend Verfügbarkeit vorhanden.';
    }
    
}