src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdserverStatus__c</fullName>
        <label>Adserver Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Impressions__c</fullName>
        <description>The ad server interface will enter the delivered impressions here.</description>
        <inlineHelpText>The ad server interface will enter the delivered impressions here. (technical View)</inlineHelpText>
        <label>Delivered Impressions</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_AdServerRelevant__c</fullName>
        <description>True, wenn der RecordType der Werbeform nicht Standard ist. Bei Pakethüllen immer false.</description>
        <formula>ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.DeveloperName != &apos;Standard&apos; &amp;&amp;  RecordType.DeveloperName != &apos;Packet&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>KV 03459. True, wenn der RecordType der Werbeform nicht Standard ist. Bei Pakethüllen immer false.</inlineHelpText>
        <label>SomDig_AdServerRelevant</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Reason_for_refusal__c</fullName>
        <description>If the stage is set on &apos;Lost&apos; you can enter here the reason for refusal.</description>
        <inlineHelpText>If the stage is set on &apos;Lost&apos; you can enter here the reason for refusal.</inlineHelpText>
        <label>Reason for refusal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ADvendio__Stage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Order not applicable</fullName>
                </value>
                <value>
                    <fullName>Price too high</fullName>
                </value>
                <value>
                    <fullName>Competitor chosen</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>No budget</fullName>
                </value>
                <value>
                    <fullName>No advertiser feedback</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_Storno.cls
// class for KV: 02512
public class Adv_MediaCampaign_Storno{

    public static void setToStorno(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){
        
        if(lstNewItems.size() != 1) return;
        
        ADvendio__MediaCampaign__c objMC = (ADvendio__MediaCampaign__c) lstNewItems[0];
        ADvendio__MediaCampaign__c objMCOld = (ADvendio__MediaCampaign__c) mapOldItems.get(objMC.ID);              
        
        // If Set to Cancellation, Offer denied
        if(objMC.ADvendio__Reason_for_refusal__c == 'Cancellation' && objMC.ADvendio__Stage__c == 'Offer denied' && !(objMCOld.ADvendio__Reason_for_refusal__c == 'Cancellation' && objMCOld.ADvendio__Stage__c == 'Offer denied')){

            Boolean bAllowSaving = true;
            
            List<ADvendio__Campaign_Item__c> listCI = new List<ADvendio__Campaign_Item__c>([SELECT SomDig_AdServerRelevant__c, ADvendio__Delivered_Impressions__c, ADvendio__from_Date__c, ADvendio__Rate_Discount_4_Name__c FROM ADvendio__Campaign_Item__c WHERE ADvendio__Media_Campaign__c = :objMC.ID]);
            
            // Filter for Ticket 03817
            if(UserInfo.getProfileId().contains('00eD0000001Qk4n') && objMC.ADvendio__BillMe__c == false) {
                Boolean bAllCIsAreStorno = true;
                for(ADvendio__Campaign_Item__c ci : listCI) {
                    if(ci.ADvendio__Rate_Discount_4_Name__c == null || !ci.ADvendio__Rate_Discount_4_Name__c.contains('Storno')) {
                        bAllCIsAreStorno = false;
                        break;
                    }
                }
                if(bAllCIsAreStorno) return;
            }

            for(ADvendio__Campaign_Item__c o : listCI){                   
                if(o.ADvendio__from_Date__c <= System.Today())                        
                    bAllowSaving = false;
            }
            
            if(bAllowSaving){
                List<ADvendio__Campaign_Item__c> listUpdateCI = new List<ADvendio__Campaign_Item__c>();
                for(ADvendio__Campaign_Item__c o : listCI){
                    if(o.SomDig_AdServerRelevant__c){
                        o.ADvendio__AdserverStatus__c = 'Released';
                        listUpdateCI.add(o);
                    }
                }
                update listUpdateCI;    

            }else
                objMC.addError('Die Mediakampagne darf nicht von Sales storniert werden, da sie bereits angelaufen ist.');       

        }
    }
}