src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__PerformanceIndicator__c</fullName>
        <description>This field shows the current delivery status as a percentage.</description>
        <formula>CASE ( /* Billing Category */
	1,
	IF ( /* use AI */
		TEXT(ADvendio__Billing_category__c) == &quot;CPM&quot; ||
		TEXT(ADvendio__Billing_category__c) == &quot;CPD&quot; ||
		TEXT(ADvendio__Billing_category__c) == &quot;CPW&quot; ||
		TEXT(ADvendio__Billing_category__c) == &quot;CPMo&quot; ||
		TEXT(ADvendio__Billing_category__c) == &quot;Fixed Price&quot;,
		1,
		0
	),

	CASE ( /* Runtime */
 		1,
		IF ( /* running... */
			ADvendio__from_Date__c &lt; TODAY() &amp;&amp;
			ADvendio__until_Date__c &gt;= TODAY() &amp;&amp;
			ADvendio__Delivered_Impressions__c &gt; 0,
			1,
			0
		),
		BLANKVALUE(ADvendio__Delivered_Impressions__c, 0) +
		(
			(
				BLANKVALUE(ADvendio__Delivered_Impressions__c, 0) /
				MAX(TODAY() - ADvendio__from_Date__c,1) *
				(ADvendio__until_Date__c - TODAY() +1)
			)
		),

		IF( /* ended... */
			ADvendio__until_Date__c &lt; TODAY() &amp;&amp;
			ADvendio__Delivered_Impressions__c &gt; 0,
			1,
			0
		),
		BLANKVALUE(ADvendio__Delivered_Impressions__c, 0),

		0
	),

	IF ( /* use clicks */
		TEXT(ADvendio__Billing_category__c) == &quot;CPC&quot;,
		1,
		0
	),

	CASE ( /* Runtime */
 		1,
		IF ( /* running... */
			ADvendio__from_Date__c &lt; TODAY() &amp;&amp;
			ADvendio__until_Date__c &gt;= TODAY() &amp;&amp;
			ADvendio__Delivered_Clicks__c &gt; 0,
			1,
			0
		),
		BLANKVALUE(ADvendio__Delivered_Clicks__c, 0) +
		(
			(
				BLANKVALUE(ADvendio__Delivered_Clicks__c, 0) /
				MAX(TODAY() - ADvendio__from_Date__c,1) *
				(ADvendio__until_Date__c - TODAY() +1)
			)
		),

		IF( /* ended... */
			ADvendio__until_Date__c &lt; TODAY() &amp;&amp;
			ADvendio__Delivered_Clicks__c &gt; 0,
			1,
			0
		),
		BLANKVALUE(ADvendio__Delivered_Clicks__c, 0),
		
		0
	),

	IF ( /* use visible AI */
		TEXT(ADvendio__Billing_category__c) == &quot;vCPM&quot;,
		1,
		0
	),

	CASE ( /* Runtime */
 		1,
		IF ( /* running... */
			ADvendio__from_Date__c &lt; TODAY() &amp;&amp;
			ADvendio__until_Date__c &gt;= TODAY() &amp;&amp;
			ADvendio__AvAsViewableAi__c &gt; 0,
			1,
			0
		),
		BLANKVALUE(ADvendio__AvAsViewableAi__c, 0) +
		(
			(
				BLANKVALUE(ADvendio__AvAsViewableAi__c, 0) /
				MAX(TODAY() - ADvendio__from_Date__c,1) *
				(ADvendio__until_Date__c - TODAY() + 1)
			)
		),

		IF( /* ended... */
			ADvendio__until_Date__c &lt; TODAY() &amp;&amp;
			ADvendio__AvAsViewableAi__c &gt; 0,
			1,
			0
		),
		BLANKVALUE(ADvendio__AvAsViewableAi__c, 0),
		0
	),
	0
) / ADvendio__BookingQuantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field shows the current delivery status as a percentage.</inlineHelpText>
        <label>Performance Indicator</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ADvendio__PositionNumber__c</fullName>
        <label>Position Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_AIClicksSollBisHeute__c</fullName>
        <description>Ais Soll gesamt x ((Aktuelles Datum +1 - Startdatum)/(Enddatum Position +1 - Startdatum Position))</description>
        <formula>IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPC&quot;), (ISPICKVAL(ADvendio__Billing_category__c, &quot;CPM&quot;))), TODAY() &gt;= ADvendio__from_Date__c, TODAY() &lt; ADvendio__until_Date__c, ADvendio__Days__c &gt; 0), 
ADvendio__Quantity__c / ADvendio__Days__c * (TODAY() - ADvendio__from_Date__c + 1), 

IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPC&quot;), (ISPICKVAL(ADvendio__Billing_category__c, &quot;CPM&quot;))), TODAY() &gt;= ADvendio__until_Date__c, ADvendio__Days__c &gt; 0), 
ADvendio__Quantity__c, 

IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPD&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPW&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;Fixed Price&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPMo&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPY&quot;)), TODAY() &gt;= ADvendio__from_Date__c, TODAY() &lt; ADvendio__until_Date__c, ADvendio__Guaranteed_AI__c &gt; 0, ADvendio__Days__c &gt; 0), ADvendio__BookingQuantity__c / ADvendio__Days__c * (TODAY() - ADvendio__from_Date__c + 1), 

IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPD&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPW&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;Fixed Price&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPMo&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPY&quot;)), TODAY() &gt;= ADvendio__until_Date__c, ADvendio__Guaranteed_AI__c &gt; 0, ADvendio__Days__c &gt; 0), ADvendio__BookingQuantity__c, 

Null))))</formula>
        <inlineHelpText>Berechnet die auszuliefernden Impressions oder Clicks tagesaktuell während der Laufzeit des Line-Items, lineare Verteilung</inlineHelpText>
        <label>AI/Clicks SOLL bis Heute</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_AiClicksIst__c</fullName>
        <description>Fügt Anzahl der AIs oder Clicks ein, abhängig von Abrechnungsart</description>
        <formula>CASE( ADvendio__Billing_category__c, &quot;CPM&quot;,  ADvendio__Delivered_Impressions__c , &quot;CPC&quot;,  ADvendio__Delivered_Clicks__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Fügt Anzahl der AIs oder Clicks ein, abhängig von Abrechnungsart</inlineHelpText>
        <label>AI/Clicks IST</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsSegment__c</fullName>
        <description>Id des M.-Segments, welches an der Belegungseinheit des Werbemittels gepflegt ist. Wird per Formel befüllt. Siehe auch KV 2551 zwecks nähere Infos. Wird für DWH-Schnittstelle benötigt</description>
        <formula>CASESAFEID( ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Mediagattungssegment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Id des M.-Segments, welches an der Belegungseinheit des Werbemittels gepflegt ist. Wird per Formel befüllt.</inlineHelpText>
        <label>Mediagattungs-Segment-Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_PositionStatus__c</fullName>
        <description>-Inaktiv: Durchgebuchung im AdServer erfolgt, kein Motiv eingebucht.
-bereit: Werbemittel sind im AdServer eingebucht und aktiviert 
-Auslieferung-normal: DFP meldet tatsätzliche AIs und AIist&gt;=AIsollbisheute
-Auslieferung@Risk: DFP meldet tatsätzliche AIs und AIist&lt;AIsollbisheute
-pausiert: Position in AdServer wurde gestoppt/pausiert (DFP meldet &apos;pausiert&apos;)
-beendet - erfüllt: Enddatum in der Vergangenheit, AIs ist &gt;= AIs Soll 
-beendet - unterliefert: Enddatum in der Vergangenheit, AIs ist &lt; AIs Soll
-NonAdServer: Position enthält ein NonAdServer Produkt</description>
        <inlineHelpText>-Inaktiv:durchgebucht,kein Motiv
-bereit:im AdServer aktiviert
-normal:AIist&gt;=AIsollbisheute
-@Risk:AIist&lt;AIsollbisheute
-pausiert:laufender Flight wurde gestoppt
-erfüllt:beendet &amp; AIist&gt;=AIsoll
-unterliefert:beendet &amp; AIist&lt;AIsoll</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
                <value>
                    <fullName>bereit</fullName>
                </value>
                <value>
                    <fullName>An Adserver übermitteln</fullName>
                    <default>true</default>
                    <label>An Adserver übermitteln</label>
                </value>
                <value>
                    <fullName>Ad Status aktualisieren</fullName>
                </value>
                <value>
                    <fullName>Position pausiert</fullName>
                </value>
                <value>
                    <fullName>Position gestoppt</fullName>
                </value>
                <value>
                    <fullName>NonAdserver</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-normal</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-@Risk</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-erfüllt</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-unterliefert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Risk__c</fullName>
        <description>berechnet Risk (ausschließßlich CPD und CPC Abrechnungsart)</description>
        <formula>IF(TODAY()&gt; ADvendio__from_Date__c  , 1- SomDig_OSIcustom__c, 0)</formula>
        <inlineHelpText>Soll-Ist-Vergleich in % über die gesamte Dauer</inlineHelpText>
        <label>@risk</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SomDig_StatusFlagPosition__c</fullName>
        <description>Status Flag wird über Position Status gesteuert.</description>
        <formula>CASE(SomDig_PositionStatus__c, 
&quot;inaktiv&quot;, IMAGE(&quot;/resource/todo_statusImage&quot;, &quot;Inaktiv&quot;), 
&quot;bereit&quot;, IMAGE(&quot;/resource/according_to_plan_Status_Image&quot;, &quot;eingebucht&quot;), 
&quot;Auslieferung-normal&quot;, IMAGE(&quot;/resource/according_to_plan_Status_Image&quot;, &quot;live&quot;), 
&quot;Auslieferung-@Risk&quot;, IMAGE(&quot;/resource/according_to_plan_Status_Image&quot;, &quot;nicht eingebucht&quot;), 
&quot;abgelaufen-erfüllt&quot;, IMAGE(&quot;/resource/Completed_statusImage&quot;, &quot;beendet erfüllt&quot;), 
&quot;abgelaufen-unterliefert&quot;, IMAGE(&quot;/resource/Completed_statusImage&quot;, &quot;beendet unterliefert&quot;), 
&quot;An Adserver übermitteln&quot;, IMAGE(&quot;/resource/todo_statusImage&quot;, &quot;übermitteln&quot;), 
&quot;Ad Status aktualisieren&quot;, IMAGE(&quot;/resource/todo_statusImage&quot;, &quot;aktualisieren&quot;), 
&quot;Position pausiert&quot;, IMAGE(&quot;/resource/todo_statusImage&quot;, &quot;pausiert&quot;), 
&quot;Position gestoppt&quot;, IMAGE(&quot;/resource/Completed_statusImage&quot;, &quot;gestoppt&quot;), 
null 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Status Flag wird über Position Status gesteuert:
rot: Entwurf, Inaktiv, pausiert
grau: abgelaufen-unterliefert/erfüllt
grün: bereit, Auslieferung-normal/@risk</inlineHelpText>
        <label>Status Flag Position</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Position_Reports_Columns_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>to hide/show the Columns in  Position Report</description>
    <fields>
        <fullName>Is_Displayed__c</fullName>
        <defaultValue>true</defaultValue>
        <description>column will be displayed in Position Report if this Value is checked</description>
        <label>Is Displayed?</label>
        <type>Checkbox</type>
    </fields>
    <label>Position Reports Columns Setting</label>
</CustomObject>

src/classes/Adv_CampaignItem_PositionReport_Test.cls
@isTest
public class Adv_CampaignItem_PositionReport_Test {

    /*
        Method Name  : testCampgnItemsPositionControllerReport
        Parameters   : void
        Return Type  : void
        Description  : This method is used for unit testing the functionalities of Adv_CampaignItem_PositionReport class
        Created By   : Cognizant Technology Solutions
    */
    static testMethod void testCampgnItemsPositionControllerReport() {

        ADvendio__MediaCampaign__c l_oMediaCampaign = cls_P7S1_TestData.createTestMediaCampaign(false);
        l_oMediaCampaign.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Auftrag'].id;
        insert l_oMediaCampaign;

        ADvendio__Campaign_Item__c l_oCampaignItem = cls_P7S1_TestData.createTestCampaignItem(false, l_oMediaCampaign);
        l_oCampaignItem.SomDig_PositionStatus__c = 'bereit';
        insert l_oCampaignItem;

        List<Position_Reports_Columns_Setting__c> l_oListPositionReportsCustomsSetting = new List<Position_Reports_Columns_Setting__c>();
        Position_Reports_Columns_Setting__c reportCustomSetting1 = new Position_Reports_Columns_Setting__c(Name = 'Name',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting1);
        Position_Reports_Columns_Setting__c reportCustomSetting2 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_StatusFlagPosition__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting2);
        Position_Reports_Columns_Setting__c reportCustomSetting3 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_PositionStatus__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting3);
        Position_Reports_Columns_Setting__c reportCustomSetting4 = new Position_Reports_Columns_Setting__c(Name = 'ADvendio__from_Date__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting4);
        Position_Reports_Columns_Setting__c reportCustomSetting5 = new Position_Reports_Columns_Setting__c(Name = 'ADvendio__until_Date__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting5);
        Position_Reports_Columns_Setting__c reportCustomSetting6 = new Position_Reports_Columns_Setting__c(Name = 'ADvendio__PositionNumber__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting6);
        Position_Reports_Columns_Setting__c reportCustomSetting7 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_MediagattungsSegment__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting7);
        Position_Reports_Columns_Setting__c reportCustomSetting8 = new Position_Reports_Columns_Setting__c(Name = 'ADvendio__Billing_category__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting8);
        Position_Reports_Columns_Setting__c reportCustomSetting9 = new Position_Reports_Columns_Setting__c(Name = 'ADvendio__Quantity__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting9);
        Position_Reports_Columns_Setting__c reportCustomSetting10 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_AIClicksSollBisHeute__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting10);
        Position_Reports_Columns_Setting__c reportCustomSetting11 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_AiClicksIst__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting11);
        Position_Reports_Columns_Setting__c reportCustomSetting12 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_Risk__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting12);
        Position_Reports_Columns_Setting__c reportCustomSetting13 = new Position_Reports_Columns_Setting__c(Name = 'ADvendio__PerformanceIndicator__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting13);
        Position_Reports_Columns_Setting__c reportCustomSetting14 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_LineItemInAdServer__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting14);
        Position_Reports_Columns_Setting__c reportCustomSetting15 = new Position_Reports_Columns_Setting__c(Name = 'Status_Screenshot__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting15);
        Position_Reports_Columns_Setting__c reportCustomSetting16 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_PAMKommentar__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting16);
        Position_Reports_Columns_Setting__c reportCustomSetting17 = new Position_Reports_Columns_Setting__c(Name = 'SomDig_Inhaber_Kuerzel__c',Is_Displayed__c = true);
        l_oListPositionReportsCustomsSetting.add(reportCustomSetting17);
        insert l_oListPositionReportsCustomsSetting;

        System.test.startTest();
        Adv_CampaignItem_PositionReport l_oCampgnItemsPositionRprtController = new Adv_CampaignItem_PositionReport();
        l_oCampgnItemsPositionRprtController.i_oCampaignItem.ADvendio__from_Date__c = system.today()-1;
        l_oCampgnItemsPositionRprtController.i_oCampaignItem.ADvendio__until_Date__c = system.today()+3;
        l_oCampgnItemsPositionRprtController.getMediaCampaign();
        for (ADvendio__MediaCampaign__c l_oMediaCampaignTemp : (list<ADvendio__MediaCampaign__c>)l_oCampgnItemsPositionRprtController.i_oStandardSetController.getRecords()) {
            for(ADvendio__Campaign_Item__c l_oCampaignItemTemp : l_oMediaCampaignTemp.Advendio__Advertising_Media__r)
                l_oCampaignItemTemp.SomDig_PAMKommentar2__c = 'test';
        }
        l_oCampgnItemsPositionRprtController.saveInline();
        l_oCampgnItemsPositionRprtController.i_sSortField = 'Name';
        l_oCampgnItemsPositionRprtController.SortToggle();
        l_oCampgnItemsPositionRprtController.getPositionStatus();
        l_oCampgnItemsPositionRprtController.getUser();
        l_oCampgnItemsPositionRprtController.getCampaign();
        l_oCampgnItemsPositionRprtController.getAgency();
        l_oCampgnItemsPositionRprtController.getAdvertiser();
        l_oCampgnItemsPositionRprtController.getOfferNumber();
        l_oCampgnItemsPositionRprtController.i_sListSelectedStatus = new List<String>{'bereit'};
        l_oCampgnItemsPositionRprtController.i_sListSelectedCampaign = new List<String>{'Test Media Campaign'};
        List<Id> l_iListUser = new List<Id>();
        for(User l_oUser : [select Firstname,LastName,Id from User where (Profile.Name = 'SomDig_PAM' OR Profile.Name = 'SomDig_BI') and IsActive=true order by Firstname asc limit 2]){
            l_iListUser.add(l_oUser.id);
        }
        l_oCampgnItemsPositionRprtController.i_sListUserselected = l_iListUser;
        l_oCampgnItemsPositionRprtController.getExportReport();
        l_oCampgnItemsPositionRprtController.i_sSelectedContentType = 'PDF Format';
        l_oCampgnItemsPositionRprtController.CreateReport();
        l_oCampgnItemsPositionRprtController.i_sSelectedContentType = 'Excel Format';
        l_oCampgnItemsPositionRprtController.CreateReport();
        l_oCampgnItemsPositionRprtController.i_sSelectedContentType = 'CSV Format';
        l_oCampgnItemsPositionRprtController.CreateReport();
        l_oCampgnItemsPositionRprtController.i_sAlphaFilter = 'Other';
        l_oCampgnItemsPositionRprtController.refreshController();
        l_oCampgnItemsPositionRprtController.getMediaCampaign();
        l_oCampgnItemsPositionRprtController.i_sAlphaFilter = 'T';
        l_oCampgnItemsPositionRprtController.i_sListUserselected = new List<String>{'Alle'};
        l_oCampgnItemsPositionRprtController.refreshController();
        l_oCampgnItemsPositionRprtController.getMediaCampaign();
        system.test.stoptest();
    }
}