src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__RateCriterion__c</fullName>
        <description>Can be used to filter by adPrices by this field in the SelectSearch page</description>
        <label>Rate Criterion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>bis 5 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 6 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 7 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 10 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 15 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 20 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 25 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 30 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 35 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 40 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 45 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 50 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 55 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 60 Sekunden</fullName>
                </value>
                <value>
                    <fullName>bis 70 Sekunden</fullName>
                </value>
                <value>
                    <fullName>mit Seiteneinfärbung</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src - MTDEV2/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__SelectedContentInformation__c</fullName>
        <label>Selected Content Information</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>ADvendio__AdserverStatus__c</fullName>
        <label>Adserver Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>ADvendio__LineDescription__c</fullName>
        <description>This Field is used on Quote PDF and also submitted to the AdServer when this Campaign Item is relevant for an AdServer.</description>
        <inlineHelpText>Enter a comment to this position which will be shown on the proposal.</inlineHelpText>
        <label>Line Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>ADvendio__SelectedAdServerIdInformation__c</fullName>
        <description>This field stores a summary of the selected Targeting Criteria of the Campaign Item to display that information within reports.</description>
        <inlineHelpText>This field stores a summary of the selected Targeting Criteria of the Campaign Item to display that information within reports.</inlineHelpText>
        <label>Selected AdServer ID Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>SomDig_Freitextnotiz__c</fullName>
        <description>Freitext, welcher der User eintragen kann und im Feld Positionskommentar erscheint. Kommentare bzgl. -NR, -NL, -OTP, -Preiskriterium werden nicht manuell eingetragen, sondern nach dem speichern automatisch ermittelt und im Positionskommentar zusammengefügt.</description>
        <inlineHelpText>Gebe hier deinen (Frei-)Text ein, welcher auf den Dokumenten unter „Positionskommentar“ zusätzlich mit allen weiteren Informationen wie NR, OPT, etc. erscheint (max.120 Zeichen)</inlineHelpText>
        <label>Freitextnotiz (Sichtbarkeit begrenzt!)</label>
        <length>240</length>
        <type>Text</type>
    </fields>

src/objects/ADvendio__Campaign_Item__c.object
    <fields>
        <fullName>SomDig_Retargeting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Bei Aktivieren dieser Checkbox wird der Retargeting Aufschlag des Werbemittels bei der Preisberechnung einbezogen.</description>
        <inlineHelpText>Bei Aktivieren dieser Checkbox wird der Retargeting Aufschlag des Werbemittels bei der Preisberechnung einbezogen.</inlineHelpText>
        <label>Retargeting</label>
        <type>Checkbox</type>
    </fields>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src - MTDEV2/classes/Adv_CampaignItem_FieldChanges_Test.cls
@isTest
public with sharing class Adv_CampaignItem_FieldChanges_Test {

    @isTest (seeAllData=false)
    static public void setPlzWorkaroundTest() {
        
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true);
        ADvendio__MediaCampaign__c mediaCampaign = createTestMediaCampaign(true, pricelist);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, pricelist);
        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        campaignItem1.ADvendio__SelectedAdServerIdInformation__c	= 'TEST:123 ;Postal Code: 12345;';
        ADvendio__Campaign_Item__c campaignItem2 = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);

        Test.startTest();
        insert new List<ADvendio__Campaign_Item__c>{campaignItem1, campaignItem2};

        
        for (ADvendio__Campaign_Item__c ci : [SELECT Id, ADvendio__SelectedContentInformation__c FROM ADvendio__Campaign_Item__c limit 2]) {
        	if (ci.Id == campaignItem1.Id ) {
        		system.assertEquals('12345', ci.ADvendio__SelectedContentInformation__c);
        	}
            else if (ci.Id == campaignItem2.Id ) {
        		system.assertEquals(null, ci.ADvendio__SelectedContentInformation__c);
        	}
        	else {
        		system.assert(false, 'unexpected item!');
        	}
        }

        campaignItem1.ADvendio__SelectedAdServerIdInformation__c	= 'TEST:123 ;Postal Cxxx: 12345;';
        campaignItem2.ADvendio__SelectedAdServerIdInformation__c	= 'Postal Code: 12345,23456';
        update new List<ADvendio__Campaign_Item__c>{campaignItem1, campaignItem2};
        
        for (ADvendio__Campaign_Item__c ci : [SELECT Id, ADvendio__SelectedContentInformation__c FROM ADvendio__Campaign_Item__c limit 2]) {
        	if (ci.Id == campaignItem1.Id ) {
        		system.assertEquals(null, ci.ADvendio__SelectedContentInformation__c);
        	}
            else if (ci.Id == campaignItem2.Id ) {
        		system.assertEquals('12345,23456', ci.ADvendio__SelectedContentInformation__c);
        	}
        	else {
        		system.assert(false, 'unexpected item!');
        	}
        }

        Test.stopTest();
    }
    
    static testMethod void setLineDescriptionOnInsert() {
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true);
        ADvendio__MediaCampaign__c mediaCampaign = createTestMediaCampaign(true, pricelist);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, pricelist);
        adPrice.ADvendio__RateCriterion__c = 'bis 15 Sekunden';
        insert adPrice;

        Test.startTest();

        ADvendio__Campaign_Item__c campaignItem = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Positionsrabatt Natural';
        campaignItem.SomDig_Freitextnotiz__c = 'random text';
        campaignItem.SomDig_Retargeting__c = true;
        insert campaignItem;

        Test.stopTest();

        campaignItem = reloadCampaignItem(campaignItem);
        System.assertEquals('-random text\n-NR\n-Re-Targeting-Aufschlag\n-Videolänge: bis 15 Sekunden', campaignItem.ADvendio__LineDescription__c);
    }

    static testMethod void setLineDescriptionOnUpdate() {
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true);
        ADvendio__MediaCampaign__c mediaCampaign = createTestMediaCampaign(true, pricelist);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, pricelist);
        adPrice.ADvendio__RateCriterion__c = 'bis 20 Sekunden';
        insert adPrice;

        ADvendio__Campaign_Item__c campaignItem = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Nachlieferung';
        campaignItem.SomDig_Freitextnotiz__c = 'random text 1';
        campaignItem.SomDig_Retargeting__c = true;
        insert campaignItem;

        campaignItem = reloadCampaignItem(campaignItem);
        System.assertEquals('-random text 1\n-Nachlieferung\n-Re-Targeting-Aufschlag\n-Videolänge: bis 20 Sekunden', campaignItem.ADvendio__LineDescription__c);

        Test.startTest();

        adPrice.ADvendio__RateCriterion__c = 'bis 30 Sekunden';
        update adPrice;

        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Storno mit Leistungsfluss';
        campaignItem.SomDig_Freitextnotiz__c = 'random text 2';
        campaignItem.SomDig_Retargeting__c = false;
        update campaignItem;

        Test.stopTest();

        campaignItem = reloadCampaignItem(campaignItem);
        System.assertEquals('-random text 2\n-Storno\n-Videolänge: bis 30 Sekunden', campaignItem.ADvendio__LineDescription__c);
    }

    static testMethod void setAdServerStatusOnInsert() {
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true);
        ADvendio__MediaCampaign__c mediaCampaign = createTestMediaCampaign(true, pricelist);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(true, pricelist);

        Test.startTest();

        ADvendio__Campaign_Item__c campaignItem = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Storno mit Leistungsfluss';
        insert campaignItem;

        Test.stopTest();

        campaignItem = reloadCampaignItem(campaignItem);
        System.assertEquals('Released', campaignItem.ADvendio__AdserverStatus__c);
    }

    static testMethod void setAdServerStatusOnUpdate() {
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true);
        ADvendio__MediaCampaign__c mediaCampaign = createTestMediaCampaign(true, pricelist);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(true, pricelist);

        ADvendio__Campaign_Item__c campaignItem = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Nachlieferung';
        campaignItem.ADvendio__from_Date__c = Date.today().addDays(1);
        insert campaignItem;

        campaignItem = reloadCampaignItem(campaignItem);
        System.assertEquals('Active', campaignItem.ADvendio__AdserverStatus__c);

        Test.startTest();

        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Storno ohne Leistungsfluss';
        update campaignItem;

        Test.stopTest();

        campaignItem = reloadCampaignItem(campaignItem);
        System.assertEquals('Released', campaignItem.ADvendio__AdserverStatus__c);
    }

    @isTest
    public static void setLineDescriptionKompensation(){
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true);
        ADvendio__MediaCampaign__c mediaCampaign = createTestMediaCampaign(true, pricelist);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(true, pricelist);

        Test.startTest();

        ADvendio__Campaign_Item__c campaignItem = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Kompensation';
        insert campaignItem;

        Test.stopTest();

        campaignItem = reloadCampaignItem(campaignItem);
        System.assert(campaignItem.ADvendio__LineDescription__c.contains('Kompensation'));
    }

    @isTest
    public static void setLineDescriptionWithoutKompensation(){
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true);
        ADvendio__MediaCampaign__c mediaCampaign = createTestMediaCampaign(true, pricelist);
        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(true, pricelist);

        Test.startTest();

        ADvendio__Campaign_Item__c campaignItem = cls_P7S1_TestData.createTestCampaignItem(false, mediaCampaign, adPrice);
        campaignItem.ADvendio__Rate_Discount_4_Name__c = 'Nachlieferung';
        insert campaignItem;

        Test.stopTest();

        campaignItem = reloadCampaignItem(campaignItem);
        System.assert(!(campaignItem.ADvendio__LineDescription__c.contains('Kompensation')));
    }

    private static ADvendio__Campaign_Item__c reloadCampaignItem(ADvendio__Campaign_Item__c campaignItem) {
        return [
            SELECT ADvendio__AdserverStatus__c, ADvendio__LineDescription__c
              FROM ADvendio__Campaign_Item__c
             WHERE Id = :campaignItem.Id
        ];
    }



    // TODO: in TestData auslagern
    public static ADvendio__MediaCampaign__c createTestMediaCampaign(Boolean insertObject, ADvendio__Pricelist__c pricelist) {
        return cls_P7S1_TestData.createTestMediaCampaign(insertObject, null, pricelist, null);
    }


}