src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_PositionStatus__c</fullName>
        <description>-Inaktiv: Durchgebuchung im AdServer erfolgt, kein Motiv eingebucht.
-bereit: Werbemittel sind im AdServer eingebucht und aktiviert 
-Auslieferung-normal: DFP meldet tatsätzliche AIs und AIist&gt;=AIsollbisheute
-Auslieferung@Risk: DFP meldet tatsätzliche AIs und AIist&lt;AIsollbisheute
-pausiert: Position in AdServer wurde gestoppt/pausiert (DFP meldet &apos;pausiert&apos;)
-beendet - erfüllt: Enddatum in der Vergangenheit, AIs ist &gt;= AIs Soll 
-beendet - unterliefert: Enddatum in der Vergangenheit, AIs ist &lt; AIs Soll
-NonAdServer: Position enthält ein NonAdServer Produkt</description>
        <inlineHelpText>-Inaktiv:durchgebucht,kein Motiv
-bereit:im AdServer aktiviert
-normal:AIist&gt;=AIsollbisheute
-@Risk:AIist&lt;AIsollbisheute
-pausiert:laufender Flight wurde gestoppt
-erfüllt:beendet &amp; AIist&gt;=AIsoll
-unterliefert:beendet &amp; AIist&lt;AIsoll</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
                <value>
                    <fullName>bereit</fullName>
                </value>
                <value>
                    <fullName>An Adserver übermitteln</fullName>
                    <default>true</default>
                    <label>An Adserver übermitteln</label>
                </value>
                <value>
                    <fullName>Ad Status aktualisieren</fullName>
                </value>
                <value>
                    <fullName>Position pausiert</fullName>
                </value>
                <value>
                    <fullName>Position gestoppt</fullName>
                </value>
                <value>
                    <fullName>NonAdserver</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-normal</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-@Risk</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-erfüllt</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-unterliefert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_StatusPAMCockpit__c</fullName>
        <description>beschreibt die Phase nach dem eine MK gebucht ist, bzw. die ownership von SALES zu PAM gewechselt hat.</description>
        <inlineHelpText>neu: keine LIs angelegt
to do: Mindestens EINE Position steht auf Entwurf, Pausiert, -erfüllt o. -unterliefert
planmässig: ALLE haben den Status Bereit o. Auslieferung
abgeschlossen: ALLE beendet und abgerechnet
NonAdserver: ALLE NonAdServer Produkte</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>neu</fullName>
                </value>
                <value>
                    <fullName>planmässig</fullName>
                </value>
                <value>
                    <fullName>to do</fullName>
                </value>
                <value>
                    <fullName>abgeschlossen</fullName>
                </value>
                <value>
                    <fullName>Non AdServer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_Status_Test.cls
@isTest
public with sharing class Adv_MediaCampaign_Status_Test {

    // TODO: write REAL tests

    static testMethod void testMediaCampaignStatusUpdate() {
        ADvendio__Campaign_Item__c l_oCampaignItem1 = cls_P7S1_TestData.createTestCampaignItem(false);

        ADvendio__MediaCampaign__c l_oMediaCampaign = cls_P7S1_TestData.MediaCampaign_TestData;

        ADvendio__Campaign_Item__c l_oCampaignItem2 = cls_P7S1_TestData.createTestCampaignItem(false, l_oMediaCampaign, cls_P7S1_TestData.AdPrice_TestData);

        List<ADvendio__Campaign_Item__c> cil = new List<ADvendio__Campaign_Item__c>();
        cil.add(l_oCampaignItem1);
        cil.add(l_oCampaignItem2);
        insert cil;

        cil = new List<ADvendio__Campaign_Item__c>();

        Test.startTest();

        l_oMediaCampaign.SomDig_StatusPAMCockpit__c = 'to do';
        update l_oMediaCampaign;

        l_oCampaignItem1.SomDig_PositionStatus__c = 'Auslieferung-normal';
        //update l_oCampaignItem1;
        cil.add(l_oCampaignItem1);

        l_oCampaignItem2.SomDig_PositionStatus__c = 'bereit';
        //update l_oCampaignItem2;
        cil.add(l_oCampaignItem2);
        update cil;

        Test.stopTest();
    }

}