src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This reference displays the ad spec to which this price is assigned.</description>
        <inlineHelpText>This reference displays the ad spec to which this price is assigned.</inlineHelpText>
        <label>Ad Spec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This formula displays the corresponding ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp;  ADvendio__Ad_Price__r.ADvendio__Ad_Spec__c  , ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.Name)</formula>
        <inlineHelpText>This formula displays the corresponding ad spec.</inlineHelpText>
        <label>Ad Spec</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Availability__c</fullName>
        <description>The ad server interface will enter the availability during an availabilty request.</description>
        <inlineHelpText>The ad server interface will enter the availability during an availabilty request.</inlineHelpText>
        <label>Availability (planned)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__PacketItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packet Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Prorated__c</fullName>
        <label>Prorated</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_BelegungseinheitTyp__c</fullName>
        <description>KV 02614. In diesem Feld steht die der Typ der Belegungseinheit des Werbemittels der Kampagnenposition.</description>
        <formula>TEXT(ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Typ__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Belegungseinheit Typ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Menge__c</fullName>
        <description>Menge ohne anteiligen Naturalrabatt (Ticket 06323)</description>
        <label>Menge (ohne Naturalrabatt)</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_SumDeliveredImpressions__c</fullName>
        <label>SomDig_SumDeliveredImpressions</label>
        <summarizedField>ADvendio__DeliveryData__c.ADvendio__DeliveredImpressions__c</summarizedField>
        <summaryFilterItems>
            <field>ADvendio__DeliveryData__c.ADvendio__Type__c</field>
            <operation>equals</operation>
            <value>Täglich</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__DeliveryData__c.ADvendio__CampaignItem__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__PacketComponent__c.object
<CustomObject>
    <description>Defines packet and its components products.</description>
    <fields>
        <fullName>ADvendio__ComponentAdPrice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Ad-Price of current component Ad-Spec being used within the packet. It will be considered only if the Distribution of packet Ad-Spec is &apos;Individual&apos;.</description>
        <inlineHelpText>Enter the Ad-Price of current component Ad-Spec being used within the packet. It will be considered only if the Distribution of packet Ad-Spec is &apos;Individual&apos;.</inlineHelpText>
        <label>Component AdPrice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ADvendio__Ad_price__c.ADvendio__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ADvendio__Ad_price__c.ADvendio__Ad_Spec__c</field>
                <operation>equals</operation>
                <valueField>$Source.ADvendio__ComponentAdSpec__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketAdSpec__c</fullName>
        <description>The packet AdSpec, to which a component AdSpec belongs.</description>
        <inlineHelpText>The packet AdSpec, to which a component AdSpec belongs.</inlineHelpText>
        <label>Packet AdSpec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Prorated__c</fullName>
        <label>Ratio</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Packet Component</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Packet Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packet Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_DynamicQuantity.cls
public with sharing class Adv_CampaignItem_DynamicQuantity extends TriggerController {

    public Adv_CampaignItem_DynamicQuantity(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
                                            List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }

    protected override void runBeforeUpdate() {
        calculateQuantityOfPacketComponentItem((List<ADvendio__Campaign_Item__c>) lstNewItems, (Map<Id, ADvendio__Campaign_Item__c>) mapNewItems, (Map<Id, ADvendio__Campaign_Item__c>) mapOldItems);
    }


    private void calculateQuantityOfPacketComponentItem(List<ADvendio__Campaign_Item__c> lstNewRecords, Map<Id, ADvendio__Campaign_Item__c> mapNewRecords, Map<Id, ADvendio__Campaign_Item__c> mapOldRecords) {
        if(SomDig_SOQLOptimizer.iDynamicQuantityRun > 4) return;
                
        Map<Id, List<ADvendio__Campaign_Item__c>> mPacketItemId2ComponentItems = new Map<Id, List<ADvendio__Campaign_Item__c>>();
        for (ADvendio__Campaign_Item__c ci : lstNewRecords) {
            if (ci.ADvendio__PacketItem__c != null && ci.ADvendio__Availability__c != mapOldRecords.get(ci.ID).ADvendio__Availability__c) {
                List<ADvendio__Campaign_Item__c> components = mPacketItemId2ComponentItems.get(ci.ADvendio__PacketItem__c);
                if (components == null) {
                    components = new List<ADvendio__Campaign_Item__c>();
                    mPacketItemId2ComponentItems.put(ci.ADvendio__PacketItem__c, components);
                }
                components.add(ci);
            }
        }

        if (mPacketItemId2ComponentItems.isEmpty()) return;

        List<ADvendio__Campaign_Item__c> listCampaignItems = new List<ADvendio__Campaign_Item__c>([Select SomDig_Menge__c, ADvendio__Quantity__c,ADvendio__Availability__c, ADvendio__from_Date__c, ADvendio__Until_Date__c,
                                                                                                  (Select SomDig_BelegungseinheitTyp__c, ADvendio__Availability__c, SomDig_SumDeliveredImpressions__c From ADvendio__PacketComponents__r Where ADvendio__Billing_category__c='CPM' order by ADvendio__Availability__c)
                                                                                                   From ADvendio__Campaign_Item__c Where Id IN :mPacketItemId2ComponentItems.keySet()
                                                                                                   AND ADvendio__Billing_category__c='CPM'
                                                                                                   AND ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Distribution__c = 'Prorated'
                                                                                                   AND ADvendio__from_Date__c >= TODAY]);
   

        if(!listCampaignItems.isEmpty())
            SomDig_SOQLOptimizer.iDynamicQuantityRun++;
        
        
        Set<ID> setHeaders = new Set<ID>();
        for (ADvendio__Campaign_Item__c objPaket : listCampaignItems){        
            List<ADvendio__Campaign_Item__c> components = objPaket.ADvendio__PacketComponents__r;

            if(components.size() != mPacketItemId2ComponentItems.get(objPaket.ID).size()) return;
            
            ADvendio__Campaign_Item__c ci1 = mPacketItemId2ComponentItems.get(objPaket.ID)[0];
            ADvendio__Campaign_Item__c ci2 = mPacketItemId2ComponentItems.get(objPaket.ID)[1];               
        
            if(ci1.SomDig_BelegungseinheitTyp__c  != 'YouTube' && ci2.SomDig_BelegungseinheitTyp__c  != 'YouTube')
                continue;
                                     
            
            Decimal dNumber1 = ci1.ADvendio__Availability__c == null || ci1.ADvendio__Availability__c < 10 ? 10 : ci1.ADvendio__Availability__c;
            Decimal dNumber2 = ci2.ADvendio__Availability__c == null || ci2.ADvendio__Availability__c < 10 ? 10 : ci2.ADvendio__Availability__c;
            
            if (objPaket.SomDig_Menge__c == null || objPaket.SomDig_Menge__c == 0) {
	            Decimal dQuan1 = objPaket.ADvendio__Quantity__c * (dNumber1 / (dNumber1 + dNumber2));    
	            ci1.ADvendio__Quantity__c = dNumber1 < dNumber2 ? dQuan1.round(System.RoundingMode.UP) : dQuan1.round(System.RoundingMode.DOWN);                   
	            ci2.ADvendio__Quantity__c = objPaket.ADvendio__Quantity__c - ci1.ADvendio__Quantity__c;
	            
	            ci1.ADvendio__Prorated__c = (ci1.ADvendio__Quantity__c/objPaket.ADvendio__Quantity__c)*100;
	            ci2.ADvendio__Prorated__c = (ci2.ADvendio__Quantity__c/objPaket.ADvendio__Quantity__c)*100;
            }
            else {
            	Decimal dQuan1 = objPaket.SomDig_Menge__c * (dNumber1 / (dNumber1 + dNumber2));    
	            ci1.SomDig_Menge__c = dNumber1 < dNumber2 ? dQuan1.round(System.RoundingMode.UP) : dQuan1.round(System.RoundingMode.DOWN);                   
	            ci2.SomDig_Menge__c = objPaket.SomDig_Menge__c - ci1.SomDig_Menge__c;        

	            ci1.ADvendio__Prorated__c = (ci1.SomDig_Menge__c/objPaket.SomDig_Menge__c)*100;
	            ci2.ADvendio__Prorated__c = (ci2.SomDig_Menge__c/objPaket.SomDig_Menge__c)*100;
	            ci1	= Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci1);
	            ci2	= Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci2);
            }
            
            setHeaders.add(objPaket.ID);
        }
        
        if (!setHeaders.isEmpty()){ 
            Adv_CampaignItem_DynamicQuantity.updateHeaders(setHeaders);            
        }        
        
    }
    
    @future
    public static void updateHeaders(Set<ID> setHeaders){
        List<ADvendio__Campaign_Item__c> listHeader = new List<ADvendio__Campaign_Item__c>([SELECT ADvendio__Prorated__c FROM ADvendio__Campaign_Item__c WHERE ID IN :setHeaders]);
        for(ADvendio__Campaign_Item__c o : listHeader)
            o.ADvendio__Prorated__c = o.ADvendio__Prorated__c == null ? 100 : null;     
        
        update listHeader;
    }    
}