src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the ad type assigned to this ad spec.</description>
        <inlineHelpText>This field displays the ad type assigned to this ad spec.</inlineHelpText>
        <label>Ad Type</label>
        <referenceTo>ADvendio__Ad_Type__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Ad_Specs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Type__c.object
<CustomObject>
    <label>Ad Type</label>
    <nameField>
        <label>Ad Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Id__c</fullName>
        <description>The ad server interface will enter the ID of the ad when booked to the ad server.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ad server interface will enter the ID of the ad when booked to the ad server.</inlineHelpText>
        <label>Ad Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__AdserverStatus__c</fullName>
        <label>Adserver Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__DeliveredAIsManual__c</fullName>
        <label>Delivered AIs (manual)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizationExclusion__c</fullName>
        <description>Reason why this Campaign Item must not be optimized. Optimization is possible if this field is null, otherwise the reason is displayed.</description>
        <inlineHelpText>Reason why this Campaign Item must not be optimized. Leave blank to allow optimization.</inlineHelpText>
        <label>Optimization Exclusion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__PositionReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If a CampaignItem is optimized the new optimized CampaignItem needs a reference to the original CampaignItem.</description>
        <inlineHelpText>If a CampaignItem is optimized the new optimized CampaignItem needs a reference to the original CampaignItem.</inlineHelpText>
        <label>Position Reference</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Campaign Items (Position Reference)</relationshipLabel>
        <relationshipName>ReferingPositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Campaign_Item__c</fullName>
        <description>The connection to the campaign item will be assigned automatically when a new campaign item is created.</description>
        <inlineHelpText>The connection to the campaign item will be assigned automatically when a new campaign item is created.</inlineHelpText>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules_NEW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__DeliveredAIsManual__c</fullName>
        <description>This field can be used to override the Delivered AIs manually</description>
        <label>Delivered AIs (manual)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{0}</displayFormat>
        <label>Revenue Schedule No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-CRM-FAILED/classes/Adv_CampaignItem_Storno_Test.cls
@isTest
public class Adv_CampaignItem_Storno_Test {

    static testMethod void testupdateFieldsWithouthDeliveredAIs(){

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true);

        ADvendio__Campaign_Item__c objCIPositiv = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        objCIPositiv.ADvendio__from_Date__c = Date.today().addDays(1);
        insert objCIPositiv;


        ADvendio__Campaign_Item__c objCINegativ = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        objCINegativ.ADvendio__PositionReference__c  = objCIPositiv.ID;
        objCINegativ.ADvendio__Quantity__c = (-1) * objCIPositiv.ADvendio__Quantity__c;
        objCINegativ.ADvendio__from_Date__c = Date.today().addDays(1);
        objCINegativ.ADvendio__OptimizationExclusion__c = 'This is a canceled Campaign Item from a previous optimization.';
        insert objCINegativ;


        Test.startTest();
        objCIPositiv = [SELECT ADvendio__rate_discount_4_name__c, ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCIPositiv.ID];
        System.assert(objCIPositiv.ADvendio__rate_discount_4_name__c == 'Storno ohne Leistungsfluss');
        System.assert(objCIPositiv.ADvendio__AdserverStatus__c == 'Released');

        objCINegativ = [SELECT ADvendio__rate_discount_4_name__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCINegativ.ID];
        System.assert(objCINegativ.ADvendio__rate_discount_4_name__c == 'Storno ohne Leistungsfluss');

        Test.stopTest();
    }


    static testMethod void testupdateFieldsWithDeliveredAIs(){

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true);

        ADvendio__Campaign_Item__c objCIPositiv = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        insert objCIPositiv;

        ADvendio__Revenue_Schedule__c objRS = createTestRevenueSchedule(true, objCIPositiv);


        ADvendio__Campaign_Item__c objCINegativ = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        objCINegativ.ADvendio__PositionReference__c  = objCIPositiv.ID;
        objCINegativ.ADvendio__Quantity__c = (-1) * objCIPositiv.ADvendio__Quantity__c;
        objCINegativ.ADvendio__OptimizationExclusion__c = 'This is a canceled Campaign Item from a previous optimization.';
        insert objCINegativ;


        Test.startTest();
        objCIPositiv = [SELECT ADvendio__rate_discount_4_name__c, ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCIPositiv.ID];
        System.assert(objCIPositiv.ADvendio__rate_discount_4_name__c != 'Storno ohne Leistungsfluss');
        System.assert(objCIPositiv.ADvendio__AdserverStatus__c != 'Released');

        objCINegativ = [SELECT ADvendio__rate_discount_4_name__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCINegativ.ID];
        System.assert(objCINegativ.ADvendio__rate_discount_4_name__c != 'Storno ohne Leistungsfluss');

        Test.stopTest();
    }



    static testMethod void testupdateFieldsNonAdServer(){

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true);

        ADvendio__Campaign_Item__c objCIPositiv = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        insert objCIPositiv;



        // Negative position NonAdserver
        ADvendio__Ad_Type__c objAdType = cls_P7S1_TestData.createTestAdType(false);
        objAdType.RecordTypeId  = Schema.SObjectType.ADvendio__Ad_Type__c.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
        insert objAdType;


        ADvendio__Ad_Specs__c objAdSpec = cls_P7S1_TestData.createTestAdSpec(true, objAdType);
        ADvendio__Ad_price__c objAdPrice =  cls_P7S1_TestData.createTestAdPrice(true, objAdSpec);


        ADvendio__Campaign_Item__c objCINegativ = cls_P7S1_TestData.createTestCampaignItem(false, objMC, objAdPrice);
        objCINegativ.ADvendio__PositionReference__c  = objCIPositiv.ID;
        objCINegativ.ADvendio__Quantity__c = (-1) * objCIPositiv.ADvendio__Quantity__c;
        objCINegativ.ADvendio__from_Date__c = objCINegativ.ADvendio__from_Date__c.addDays(-5);
        objCINegativ.ADvendio__OptimizationExclusion__c = 'This is a canceled Campaign Item from a previous optimization.';
        insert objCINegativ;


        Test.startTest();
        objCIPositiv = [SELECT ADvendio__rate_discount_4_name__c, ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCIPositiv.ID];
        System.assert(objCIPositiv.ADvendio__rate_discount_4_name__c != 'Storno ohne Leistungsfluss');
        System.assert(objCIPositiv.ADvendio__AdserverStatus__c != 'Released');

        objCINegativ = [SELECT ADvendio__rate_discount_4_name__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCINegativ.ID];
        System.assert(objCINegativ.ADvendio__rate_discount_4_name__c != 'Storno ohne Leistungsfluss');

        Test.stopTest();
    }

    @isTest
    private static void testResetAdIdOnStornoOhneLeistungsfluss() {

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true);

        ADvendio__Campaign_Item__c objCIPositiv = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        objCIPositiv.ADvendio__from_Date__c = Date.today().addDays(1);
        objCIPositiv.ADvendio__Ad_Id__c = '123';
        insert objCIPositiv;

        ADvendio__Campaign_Item__c objCINegativ = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        objCINegativ.ADvendio__PositionReference__c  = objCIPositiv.ID;
        objCINegativ.ADvendio__Quantity__c = (-1) * objCIPositiv.ADvendio__Quantity__c;
        objCINegativ.ADvendio__from_Date__c = Date.today().addDays(1);
        objCINegativ.ADvendio__OptimizationExclusion__c = 'This is a canceled Campaign Item from a previous optimization.';

        Test.startTest();

        objCIPositiv.ADvendio__Ad_Id__c = null;

        upsert new List<ADvendio__Campaign_Item__c>{objCIPositiv, objCINegativ};

        Test.stopTest();

        // The values in asserts are expected, but due to strange system behaviour it's no working.
        // Works via UI!
        //System.assertEquals('123', [SELECT ADvendio__Ad_Id__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCIPositiv.ID].ADvendio__Ad_Id__c);
        //System.assertEquals(null, [SELECT ADvendio__Ad_Id__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCINegativ.ID].ADvendio__Ad_Id__c);

    }





    // TODO: move to testclass
    public static ADvendio__Revenue_Schedule__c createTestRevenueSchedule(Boolean insertObject, ADvendio__Campaign_Item__c campaignItem) {
        ADvendio__Revenue_Schedule__c objRS = new ADvendio__Revenue_Schedule__c();
        objRS.ADvendio__Campaign_Item__c = campaignItem.ID;
        objRS.ADvendio__DeliveredAIsManual__c = 1000;
        if (insertObject) insert objRS;
        return objRS;
    }
}