src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__c</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_BtFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.SomDig_BT__c</formula>
        <label>BT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_CpxFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_CpxFaehig__c</formula>
        <label>CPX fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_FcFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.SomDig_FC__c</formula>
        <label>FC fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.SomDig_GtFaehig__c</formula>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c</formula>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Metabuchungslogik__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Metabuchungslogik</label>
        <referenceTo>SomDig_Metabuchungslogik__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <formula>TEXT(ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Rotationstyp__c)</formula>
        <label>Rotationstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_TkpFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_TkpFaehig__c</formula>
        <label>TKP fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_WbFaehig__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_WbFaehig__c</formula>
        <label>WB fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_Werbeformgruppe__c</fullName>
        <formula>TEXT(ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_Werbeformgruppe__c)</formula>
        <label>Werbeformgruppe</label>
        <type>Text</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsDifferenzierung__c.object
<CustomObject>
    <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
    <label>Mediagattungs-Differenzierung</label>
    <nameField>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Differenzierungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Metabuchungslogik__c.object
<CustomObject>
    <description>Die Metabuchungslogik (MBL) dient als Regelwerk bei der Erstellung von Werbemitteln/Preisen für die Produktmatrix von ADvendio.</description>
    <fields>
        <fullName>SomDig_Abrechnungsart__c</fullName>
        <label>Abrechnungsart</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Festpreis</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Metabuchungslogik</relationshipLabel>
        <relationshipName>Metabuchungslogik</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_BtFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_CpxFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CPX fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_FcFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FC fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_GtFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GT fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Aktiv</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mediagattungs-Differenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipLabel>Metabuchungslogik</relationshipLabel>
        <relationshipName>Metabuchungslogik</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <label>Rotationstyp</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Network-Rotation</fullName>
                </value>
                <value>
                    <fullName>Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Site-Rotation</fullName>
                </value>
                <value>
                    <fullName>Themen-Rotation</fullName>
                </value>
                <value>
                    <fullName>TV-Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Umfeld</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_TkpFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TKP fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_WbFaehig__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WB Fähig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_Werbeformgruppe__c</fullName>
        <label>Werbeformgruppe</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>Sonderwerbeform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Metabuchungslogik</label>
    <nameField>
        <displayFormat>MBL-{0000}</displayFormat>
        <label>MBL-Nr</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metabuchungslogik</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>SomDig_MetabuchungslogikDebugMode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Metabuchungslogik Debug Mode</label>
        <type>Checkbox</type>
    </fields>
    <label>SomDig Settings</label>
</CustomObject>

src/classes/Adv_AdPrice_Metabuchungslogik.cls
public with sharing class Adv_AdPrice_Metabuchungslogik {

    public static String ERROR_MSG = 'Werbemittelpreis konnte nicht gespeichert werden, weil er nicht der Metabuchungslogik entspricht.';

    static List<SomDig_Metabuchungslogik__c> METABUCHUNGSLOGIK;
    @testVisible static Boolean manuallyEnabledForTesting;

    static {
            String activeMBLQuery = cls_P7S1_Utils.getStandardQuery('SomDig_Metabuchungslogik__c');
            activeMBLQuery += ' WHERE SomDig_IsActive__c = true';
            METABUCHUNGSLOGIK = Database.query(activeMBLQuery);

            manuallyEnabledForTesting = false;
    }


    public static void checkAdPriceConfiguration(List<ADvendio__Ad_price__c> listAdPrices) {
        for (ADvendio__Ad_price__c adPrice : listAdPrices) {
            SomDig_Metabuchungslogik__c mbl = findValidMbl(adPrice);

            if (mbl != null) {
                adPrice.SomDig_Metabuchungslogik__c = mbl.Id;
            } else if (!SomDig_Settings__c.getInstance().SomDig_MetabuchungslogikDebugMode__c && (!Test.isRunningTest() || manuallyEnabledForTesting)) {
                adPrice.addError(ERROR_MSG);
            }
        }
    }

    static SomDig_Metabuchungslogik__c findValidMbl(ADvendio__Ad_price__c adPrice) {
        SomDig_Metabuchungslogik__c validMbl;

        for (SomDig_Metabuchungslogik__c mbl : METABUCHUNGSLOGIK) {
            Set<String> abrechnungsartenSet = new Set<String>(mbl.SomDig_Abrechnungsart__c.split(';'));
            Set<String> rotationstypenSet = new Set<String>(mbl.SomDig_Rotationstyp__c.split(';'));

            if (
                // Abrechnungsart, SomDig_Abrechnungsart__c
                (mbl.SomDig_Abrechnungsart__c == null || abrechnungsartenSet.contains(adPrice.ADvendio__Billing_Category__c)) &&

                // Auftragstyp, SomDig_Auftragstyp__c
                (mbl.SomDig_Auftragstyp__c == null || mbl.SomDig_Auftragstyp__c == adPrice.SomDig_Auftragstyp__c) &&

                // BT fähig, SomDig_BtFaehig__c
                mbl.SomDig_BtFaehig__c == adPrice.SomDig_BtFaehig__c &&

                // CPX fähig, SomDig_CpxFaehig__c
                mbl.SomDig_CpxFaehig__c == adPrice.SomDig_CpxFaehig__c &&

                // FC fähig, SomDig_FcFaehig__c
                mbl.SomDig_FcFaehig__c == adPrice.SomDig_FcFaehig__c &&

                // GT fähig, SomDig_GtFaehig__c
                mbl.SomDig_GtFaehig__c == adPrice.SomDig_GtFaehig__c &&

                // Mediagattungsdifferenzierung, SomDig_Mediagattungsdifferenzierung__c
                (mbl.SomDig_MediagattungsDifferenzierung__c == null || mbl.SomDig_MediagattungsDifferenzierung__c == adPrice.SomDig_MediagattungsDifferenzierung__c) &&

                // Rotationstyp, SomDig_Rotationstyp__c
                (mbl.SomDig_Rotationstyp__c == null || rotationstypenSet.contains(adPrice.SomDig_Rotationstyp__c)) &&

                // TKP fähig, SomDig_TkpFaehig__c
                mbl.SomDig_TkpFaehig__c == adPrice.SomDig_TkpFaehig__c &&

                // WB Fähig, SomDig_WbFaehig__c
                mbl.SomDig_WbFaehig__c == adPrice.SomDig_WbFaehig__c &&

                // Werbeformgruppe, SomDig_Werbeformgruppe__c
                (mbl.SomDig_Werbeformgruppe__c == null || mbl.SomDig_Werbeformgruppe__c == adPrice.SomDig_Werbeformgruppe__c)
            ) {
                validMbl = mbl;
                break;
            }
        }

        return validMbl;
    }

}