src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_DienstleistungbezogeneHelp__c</fullName>
        <description>Hilfsfeld zur Ermittlung der PriorValue (bitte NICHT LÖSCHEN); wird per Trigger befüllt</description>
        <label>Dienstleistungbezogene Positionen Help</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_DienstleistungbezogenePositionen__c</fullName>
        <description>Hilfsfeld; zeigt wie viele LI hängen zusammen mit einem &quot;DienstleistungsLI&quot;; wird benutzt um zu verhindern, daß eine MK zum Auftrag wird ohne, daß DienstleistunsLI angelegt ist</description>
        <inlineHelpText>zeigt wie viele LI hängen zusammen mit einem &quot;DienstleistungsLI&quot;</inlineHelpText>
        <label>Dienstleistungbezogene Positionen</label>
        <summaryFilterItems>
            <field>ADvendio__Campaign_Item__c.SomDig_Produktion_Erforderlich__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__Campaign_Item__c.ADvendio__Media_Campaign__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SomDig_DienstleistungspositionenHelp__c</fullName>
        <description>Hilfsfeld zur Ermittlung der PriorValue (bitte NICHT LÖSCHEN); wird per Trigger befüllt</description>
        <label>Dienstleistungspositionen Help</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_Dienstleistungspositionen__c</fullName>
        <description>zeigt die Anzahl von Dienstleistungsrelevanten LIs, von Werbeformen, die intern produziert werden; wird benutzt um zu verhindern, daß eine MK zum Auftrag wird, ohne, daß Dien</description>
        <inlineHelpText>zeigt die Anzahl von Dienstleistungsrelevanten LIs, von Werbeformen, die intern produziert werden</inlineHelpText>
        <label>Dienstleistungspositionen</label>
        <summaryFilterItems>
            <field>ADvendio__Campaign_Item__c.SomDig_Werbeform__c</field>
            <operation>contains</operation>
            <value>Motiverstellung</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__Campaign_Item__c.ADvendio__Media_Campaign__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_Dienstleistung.cls
public with sharing class Adv_MediaCampaign_Dienstleistung {

    public static void handlePopUpFieldsBeforeUpdate(List<ADvendio__MediaCampaign__c> newList, Map<Id, ADvendio__MediaCampaign__c> oldMap){
       for (ADvendio__MediaCampaign__c I_oMC : newList) {
           I_oMC.SomDig_DienstleistungbezogeneHelp__c = oldMap.get(I_oMC.Id).SomDig_DienstleistungbezogenePositionen__c;
           I_oMC.SomDig_DienstleistungspositionenHelp__c = oldMap.get(I_oMC.Id).SomDig_Dienstleistungspositionen__c;
       }
    }
}