src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Clicks__c</fullName>
        <description>The ad server interface will enter the delivered clicks here.</description>
        <inlineHelpText>The ad server interface will enter the delivered clicks here.</inlineHelpText>
        <label>Delivered Clicks</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Impressions__c</fullName>
        <description>The ad server interface will enter the delivered impressions here.</description>
        <inlineHelpText>The ad server interface will enter the delivered impressions here. (technical View)</inlineHelpText>
        <label>Delivered Impressions</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packet Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__FieldName__c</fullName>
        <description>something like &quot;Quantity&quot;</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__NewCiIdentifier__c</fullName>
        <description>Use an identifier to pool changes for completly new Campaign Items, which have no old values and no (correct) reference to one original Campaign Item.</description>
        <inlineHelpText>Use an identifier to pool changes for completly new Campaign Items.</inlineHelpText>
        <label>New Campaign Item Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizedValue__c</fullName>
        <description>The new opzimized value.</description>
        <inlineHelpText>The new opzimized value.</inlineHelpText>
        <label>Optimized Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_OptimizingChange_ReduceAmount.cls
/*
Used in Trigger "Adv_OptimizingChange".
Checks if Amount was reduced, and prevents user from saving.
KV: 02452
*/
public class Adv_OptimizingChange_ReduceAmount{

    public static void checkAmountReduced(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){
        
        // Get CIs from OCs
        Set<ID> setCampaignItemID = new Set<ID>();
        for(sObject o : lstNewItems)
            setCampaignItemID.add((ID)o.get('ADvendio__CampaignItem__c'));
                
        Map<ID, ADvendio__Campaign_Item__c> mapCI = new Map<ID, ADvendio__Campaign_Item__c>([SELECT ADvendio__Billing_category__c, ADvendio__Delivered_Impressions__c, ADvendio__Delivered_Clicks__c FROM ADvendio__Campaign_Item__c WHERE ID IN :setCampaignItemID AND ADvendio__PacketItem__c = null]);
        
        for(sObject o : lstNewItems){
            ADvendio__OptimizingChange__c objOC = (ADvendio__OptimizingChange__c) o;

            ADvendio__Campaign_Item__c objCI = new ADvendio__Campaign_Item__c();
            if(mapCI.containsKey(objOC.ADvendio__CampaignItem__c))
                objCI = mapCI.get(objOC.ADvendio__CampaignItem__c);                                                   
    
            
            
            if(objOC.ADvendio__FieldName__c == 'advendio__quantity__c' && objCI != null  && objOC.ADvendio__NewCiIdentifier__c == null){
                
                if(objCI.ADvendio__Billing_category__c == 'CPM')
                    if(objCI.ADvendio__Delivered_Impressions__c != null)
                        if(Double.valueOf(objOC.ADvendio__OptimizedValue__c) < objCI.ADvendio__Delivered_Impressions__c)                
                            o.addError('Die Menge darf nicht unter den bereits ausgelieferten AIs liegen.');                        


                if(objCI.ADvendio__Billing_category__c == 'CPC')
                    if(objCI.ADvendio__Delivered_Clicks__c != null)
                        if(Double.valueOf(objOC.ADvendio__OptimizedValue__c) < objCI.ADvendio__Delivered_Clicks__c)                
                            o.addError('Die Menge darf nicht unter den bereits ausgelieferten AIs liegen.');                        

            }
        }                        
    }
}