src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__c</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c</formula>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <formula>TEXT(ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Rotationstyp__c)</formula>
        <label>Rotationstyp</label>
        <type>Text</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the ad type assigned to this ad spec.</description>
        <inlineHelpText>This field displays the ad type assigned to this ad spec.</inlineHelpText>
        <label>Ad Type</label>
        <referenceTo>ADvendio__Ad_Type__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Ad_Specs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <description>Hilfsfeld um die Info auf KampagnePosition zu übertragen; wird per Trigger befüllt; ist kein Formelfeld weil wir an Formellimits stoßen würden (KV 2551)</description>
        <inlineHelpText>Hier wird automatisch (per Code) der Name der M.-Differenzierung befüllt, welcher an der Werbeform gepflegt ist</inlineHelpText>
        <label>Mediagattungs-Differenzierung Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <formula>TEXT(ADvendio__Placement__r.SomDig_Rotationstyp__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rotationstyp</label>
        <type>Text</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Type__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
        <inlineHelpText>Gruppierung der einzelenen Werbeformen nach ihrer Art</inlineHelpText>
        <label>Mediagattungs-Differenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipLabel>Werbeformen</relationshipLabel>
        <relationshipName>Werbeformen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Type</label>
    <nameField>
        <label>Ad Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>CASESAFEID(ADvendio__Media_Campaign__r.ADvendio__Pricelist__r.SomDig_AuftragstypId__c)</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <description>Id der M.-Differenzierung, welche an der Werbeform des Werbemittels gepflegt ist. Wird per Formel befüllt. Siehe auch KV 2551 zwecks nähere Infos. Wird für DWH-Schnittstelle benötigt</description>
        <formula>CASESAFEID( ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Id der M.-Differenzierung, welche an der Werbeform des Werbemittels gepflegt ist. Wird per Formel befüllt.</inlineHelpText>
        <label>Mediagattungs-Differenzierung-Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <formula>TEXT(ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Rotationstyp__c)</formula>
        <label>Rotationstyp</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__RateCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Rate Category for this placement. Rate categories can be used to group placements. You can define a rate category &quot;Run of Network&quot; where you group all run-of-network placements. With the help of this criteria rates can be easily mass updated.</inlineHelpText>
        <label>Rate Category</label>
        <referenceTo>ADvendio__RateCategory__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <description>Ordnet eine Belegungseinheit (früher Marktsegment) einem Typ zu. Dies ist u.a. wichtig für die korrekte Ermittlung der Inventarklassen bei Werbemittel/Produkten welche diese Belegungseinehiet nutzen.</description>
        <inlineHelpText>Ordnet eine Belegungseinheit (früher Marktsegment) einem Typ zu. Dies ist u.a. wichtig für die korrekte Ermittlung der Inventarklassen bei Werbemittel/Produkten welche diese Belegungseinehiet nutzen.</inlineHelpText>
        <label>Rotationstyp</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Network-Rotation</fullName>
                </value>
                <value>
                    <fullName>Site-Rotation</fullName>
                </value>
                <value>
                    <fullName>Themen-Rotation</fullName>
                </value>
                <value>
                    <fullName>TV-Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Umfeld</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Inventarklasse__c.object
<CustomObject>
    <description>zentrales Objekt für alle Inventarklassen der 71m digital</description>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Welche Mediagattungs-Diffenrenzierung ist für diese Inventarklasse relevant? Info kommt an der Position via Werbeform.</description>
        <inlineHelpText>Welche Mediagattungs-Diffenrenzierung ist für diese Inventarklasse relevant? Info kommt an der Position via Werbeform.</inlineHelpText>
        <label>Mediagattungs-Differenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipLabel>Inventarklassen</relationshipLabel>
        <relationshipName>Inventarklassen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <description>Auch Inventarklassifizierungs-Name. Info an der Position kommt über die Belegungseinheit.</description>
        <inlineHelpText>Auch Inventarklassifizierungs-Name. Info an der Position kommt über die Belegungseinheit.</inlineHelpText>
        <label>Rotationstyp</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Network-Rotation</fullName>
                </value>
                <value>
                    <fullName>Site-Rotation</fullName>
                </value>
                <value>
                    <fullName>Themen-Rotation</fullName>
                </value>
                <value>
                    <fullName>TV-Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Umfeld</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventarklasse</label>
    <nameField>
        <displayFormat>IN-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarklassen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_Inventarklasse_Test.cls
@isTest
private with sharing class Adv_CampaignItem_Inventarklasse_Test {

    @testSetup
    static void createTestData() {
        SomDig_Auftragstyp__c auftragstyp = cls_P7S1_TestData.createTestAuftragstyp(true, 'Standard');
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true, auftragstyp);
        cls_P7S1_TestData.createTestMediaCampaign(true, null, pricelist);

        SomDig_MediagattungsDifferenzierung__c mgDiff = cls_P7S1_TestData.createTestMediagattungsDifferenzierung(true, 'InPage/Display');
        ADvendio__RateCategory__c preismerkmal = createTestRateCategory(true, 'Preisgruppe 1');
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(false);
        adType.SomDig_MediagattungsDifferenzierung__c = mgDiff.Id;
        insert adType;
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.ADvendio__RateCategory__c = preismerkmal.Id;
        placement.SomDig_Rotationstyp__c = 'Brand-Rotation';
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement, adType);
        cls_P7S1_TestData.createTestAdPrice(true, adSpec, pricelist);

        createTestInventarklasse(true, 'X');
    }
    
    static testMethod void testBatch() {
        delete [SELECT ID FROM SomDig_Inventarklasse__c];
        
        ADvendio__MediaCampaign__c mediaCampaign = [SELECT Id FROM ADvendio__MediaCampaign__c LIMIT 1];
        ADvendio__Ad_price__c adPrice = [SELECT Id FROM ADvendio__Ad_price__c LIMIT 1];

        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem1 = [SELECT SomDig_Inventarklasse__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem1.Id];
        System.assertEquals(null, campaignItem1.SomDig_Inventarklasse__c);
        
        createTestInventarklasse(true, 'X');
        
        Test.startTest();
        
		Database.executeBatch(new Adv_CampaignItem_Inventarklasse_Batch(), 1);
        
        Test.stopTest();
        
        campaignItem1 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem1.Id];
        System.assertEquals('X', campaignItem1.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);
        
    }

    static testMethod void addingPreismerkmal() {
        ADvendio__MediaCampaign__c mediaCampaign = [SELECT Id FROM ADvendio__MediaCampaign__c LIMIT 1];
        ADvendio__Ad_price__c adPrice = [SELECT Id FROM ADvendio__Ad_price__c LIMIT 1];

        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem1 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem1.Id];
        System.assertEquals('X', campaignItem1.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.startTest();

        ADvendio__RateCategory__c preismerkmal = [SELECT Id FROM ADvendio__RateCategory__c LIMIT 1];
        SomDig_Inventarklasse__c inventarklasse = createTestInventarklasse(false, 'A1');
        inventarklasse.SomDig_Preismerkmal__c = preismerkmal.Id;
        insert inventarklasse;

        ADvendio__Campaign_Item__c campaignItem2 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem2 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem2.Id];
        System.assertEquals('A1', campaignItem2.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.stopTest();
    }

    static testMethod void addingMediagattungsDifferenzierung() {
        ADvendio__MediaCampaign__c mediaCampaign = [SELECT Id FROM ADvendio__MediaCampaign__c LIMIT 1];
        ADvendio__Ad_price__c adPrice = [SELECT Id FROM ADvendio__Ad_price__c LIMIT 1];

        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem1 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem1.Id];
        System.assertEquals('X', campaignItem1.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.startTest();

        SomDig_MediagattungsDifferenzierung__c mgDiff = [SELECT Id FROM SomDig_MediagattungsDifferenzierung__c LIMIT 1];
        SomDig_Inventarklasse__c inventarklasse = createTestInventarklasse(false, 'A2');
        inventarklasse.SomDig_MediagattungsDifferenzierung__c = mgDiff.Id;
        insert inventarklasse;

        ADvendio__Campaign_Item__c campaignItem2 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem2 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem2.Id];
        System.assertEquals('A2', campaignItem2.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.stopTest();
    }

    static testMethod void addingAuftragstyp() {
        ADvendio__MediaCampaign__c mediaCampaign = [SELECT Id FROM ADvendio__MediaCampaign__c LIMIT 1];
        ADvendio__Ad_price__c adPrice = [SELECT Id FROM ADvendio__Ad_price__c LIMIT 1];

        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem1 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem1.Id];
        System.assertEquals('X', campaignItem1.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.startTest();

        SomDig_Auftragstyp__c auftragstyp = [SELECT Id FROM SomDig_Auftragstyp__c LIMIT 1];
        SomDig_Inventarklasse__c inventarklasse = createTestInventarklasse(false, 'A3');
        inventarklasse.SomDig_AuftragstypId__c = auftragstyp.Id;
        insert inventarklasse;

        ADvendio__Campaign_Item__c campaignItem2 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem2 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem2.Id];
        System.assertEquals('A3', campaignItem2.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.stopTest();
    }

    static testMethod void addingRotationstyp() {
        ADvendio__MediaCampaign__c mediaCampaign = [SELECT Id FROM ADvendio__MediaCampaign__c LIMIT 1];
        ADvendio__Ad_price__c adPrice = [SELECT Id FROM ADvendio__Ad_price__c LIMIT 1];

        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem1 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem1.Id];
        System.assertEquals('X', campaignItem1.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.startTest();

        SomDig_Inventarklasse__c inventarklasse = createTestInventarklasse(false, 'A4');
        inventarklasse.SomDig_Rotationstyp__c = 'Brand-Rotation';
        insert inventarklasse;

        ADvendio__Campaign_Item__c campaignItem2 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem2 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem2.Id];
        System.assertEquals('A4', campaignItem2.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.stopTest();
    }

    static testMethod void addingWerbeformdatensatztyp() {
        ADvendio__MediaCampaign__c mediaCampaign = [SELECT Id FROM ADvendio__MediaCampaign__c LIMIT 1];
        ADvendio__Ad_price__c adPrice = [SELECT Id FROM ADvendio__Ad_price__c LIMIT 1];

        ADvendio__Campaign_Item__c campaignItem1 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem1 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem1.Id];
        System.assertEquals('X', campaignItem1.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.startTest();

        SomDig_Inventarklasse__c inventarklasse = createTestInventarklasse(false, 'A5');
        inventarklasse.SomDig_WerbeformDatensatztyp__c = 'DFP';
        insert inventarklasse;

        ADvendio__Campaign_Item__c campaignItem2 = cls_P7S1_TestData.createTestCampaignItem(true, mediaCampaign, adPrice);
        campaignItem2 = [SELECT SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c FROM ADvendio__Campaign_Item__c WHERE Id = :campaignItem2.Id];
        System.assertEquals('A5', campaignItem2.SomDig_Inventarklasse__r.SomDig_InventarklasseNummer__c);

        Test.stopTest();
    }



    // TODO: move to TestData
    public static SomDig_Inventarklasse__c Inventarklasse_TestData;
    public static SomDig_Inventarklasse__c createTestInventarklasse(Boolean insertObject, String nummer) {
        Inventarklasse_TestData = new SomDig_Inventarklasse__c();
        Inventarklasse_TestData.SomDig_InventarklasseNummer__c = nummer;
        if (insertObject) insert Inventarklasse_TestData;
        return Inventarklasse_TestData;
    }

    // TODO: move to TestData
    public static ADvendio__RateCategory__c RateCategory_TestData;
    public static ADvendio__RateCategory__c createTestRateCategory(Boolean insertObject, String name) {
        RateCategory_TestData = new ADvendio__RateCategory__c();
        RateCategory_TestData.Name = name;
        if (insertObject) insert RateCategory_TestData;
        return RateCategory_TestData;
    }

}