src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the ad server ID.</inlineHelpText>
        <label>AdServer ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Type__c</fullName>
        <description>Choose which type of ad server ID is concerned.</description>
        <inlineHelpText>Choose which type of ad server ID is concerned.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Site</fullName>
                </value>
                <value>
                    <fullName>Zone</fullName>
                </value>
                <value>
                    <fullName>Zone Group</fullName>
                </value>
                <value>
                    <fullName>Content Category</fullName>
                </value>
                <value>
                    <fullName>Content Unit</fullName>
                </value>
                <value>
                    <fullName>Content Unit Group</fullName>
                </value>
                <value>
                    <fullName>Page</fullName>
                </value>
                <value>
                    <fullName>Page Group</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Format</fullName>
                </value>
                <value>
                    <fullName>Placement</fullName>
                </value>
                <value>
                    <fullName>Ad Unit</fullName>
                </value>
                <value>
                    <fullName>Key</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_KeineLieferzahlen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Wenn diese Checkbox gesetzt ist, werden Lieferdaten für diese Adserver-Id direkt nach deren Anlage gelöscht.</description>
        <inlineHelpText>Wenn diese Checkbox gesetzt ist, werden Lieferdaten für diese Adserver-Id direkt nach deren Anlage gelöscht.</inlineHelpText>
        <label>Keine Lieferzahlen</label>
        <type>Checkbox</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__DeliveryData__c.object
<CustomObject>
    <description>Detailed delivery data.</description>
    <fields>
        <fullName>ADvendio__AdServerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AdServer-ID, to which the delivery data refer.</description>
        <inlineHelpText>AdServer-ID, to which the delivery data refer.</inlineHelpText>
        <label>Ad Server ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>Delivery Data</relationshipLabel>
        <relationshipName>DeliveryData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <description>Campaign-Item, to which the delivery data refer.</description>
        <inlineHelpText>Campaign-Item, to which the delivery data refer.</inlineHelpText>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Delivery Data</relationshipLabel>
        <relationshipName>DeliveryData</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Day__c</fullName>
        <description>Day, to which the delivery data relates. If the &quot;Type&quot; is Monthly, it should be the first day of the month.</description>
        <inlineHelpText>Day, to which the delivery data relates. If the &quot;Type&quot; is Monthly, it should be the first day of the month.</inlineHelpText>
        <label>Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__Type__c</fullName>
        <description>Type of the delivery data refer.</description>
        <inlineHelpText>Type of the delivery data refer.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Delivery Data</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Delivery Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_DeliveryData_Test.cls
@isTest
public class Adv_DeliveryData_Test {
    @isTest (seeAllData=false)
    public static void testDeleteTecnicalDeliveryData() {
     //   cls_P7S1_TestData.createTestCampaignItem(true, new advendio__ad_price__c(id='a0O25000004DBlA'));
		ADvendio__Campaign_Item__c ci		= cls_P7S1_TestData.createTestCampaignItem(true);
        ADvendio__Adserver_Id__c techAsi	= cls_P7S1_TestData.createTestAdServerID(false);
        techAsi.SomDig_KeineLieferzahlen__c = true;
        ADvendio__Adserver_Id__c asi		= cls_P7S1_TestData.createTestAdServerID(false);
        asi.SomDig_KeineLieferzahlen__c 	= false;
        insert new List<ADvendio__Adserver_Id__c>{techAsi, asi};

        ADvendio__DeliveryData__c dd1		= new ADvendio__DeliveryData__c(
            									ADvendio__AdServerID__c		= asi.Id,
            									ADvendio__CampaignItem__c	= ci.Id,
            									ADvendio__Day__c			= ci.ADvendio__from_Date__c,
            									ADvendio__Type__c			= 'monthly'
        									);
        ADvendio__DeliveryData__c dd2		= new ADvendio__DeliveryData__c(
            									ADvendio__AdServerID__c		= techAsi.Id,
            									ADvendio__CampaignItem__c	= ci.Id,
            									ADvendio__Day__c			= ci.ADvendio__from_Date__c,
            									ADvendio__Type__c			= 'monthly'
        									);
        insert new List<ADvendio__DeliveryData__c>{dd1, dd2}; // dd2 will be deleted - this happens asynchronous and can not be tested here
    }
}