src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Tick the check box to activate this ad price.</description>
        <inlineHelpText>Tick the check box to activate this ad price.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Placement__c</fullName>
        <formula>CASESAFEID(ADvendio__Ad_Spec__r.ADvendio__Placement__c)</formula>
        <label>Placement</label>
        <type>Text</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Key__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>In the KeyValue Manager and Media Configuration, only active marked records will be available.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_TargetingProvider__c</fullName>
        <description>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</description>
        <inlineHelpText>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</inlineHelpText>
        <label>Targeting Provider</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATV_PBT</fullName>
                </value>
                <value>
                    <fullName>Autosites</fullName>
                </value>
                <value>
                    <fullName>Diverse Kriterien</fullName>
                </value>
                <value>
                    <fullName>Gesundheit.de</fullName>
                </value>
                <value>
                    <fullName>nugg.ad</fullName>
                </value>
                <value>
                    <fullName>nugg.ad InApp</fullName>
                </value>
                <value>
                    <fullName>Rotationsausschluss</fullName>
                </value>
                <value>
                    <fullName>SmartGeo</fullName>
                </value>
                <value>
                    <fullName>Vereinssites</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
                <value>
                    <fullName>wetter.com CTV</fullName>
                </value>
                <value>
                    <fullName>ZG S71 Paket</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Key</label>
    <nameField>
        <label>Key Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Keys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__KeyAdPriceAssignment__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdPrice__c</fullName>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Key Ad Price Assignments</relationshipLabel>
        <relationshipName>KeyAdPriceAssignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Key__c</fullName>
        <label>Key</label>
        <referenceTo>ADvendio__Key__c</referenceTo>
        <relationshipLabel>Key Ad Price Assignments</relationshipLabel>
        <relationshipName>KeyAdPriceAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Ad Price Assignment</label>
    <nameField>
        <displayFormat>KAP-{00000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Ad Price Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>In the AdSpecs &amp; Rates Manager, Inventory &amp; Rates Manager, Content Wizard, Booking Calendar and AGOF Connect, only active marked records will be available.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Targeting_Provider__c</fullName>
        <description>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</description>
        <inlineHelpText>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</inlineHelpText>
        <label>Targeting Provider</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATV_PBT</fullName>
                </value>
                <value>
                    <fullName>Autosites</fullName>
                </value>
                <value>
                    <fullName>Diverse Kriterien</fullName>
                </value>
                <value>
                    <fullName>Gesundheit.de</fullName>
                </value>
                <value>
                    <fullName>nugg.ad</fullName>
                </value>
                <value>
                    <fullName>nugg.ad InApp</fullName>
                </value>
                <value>
                    <fullName>Rotationsausschluss</fullName>
                </value>
                <value>
                    <fullName>SmartGeo</fullName>
                </value>
                <value>
                    <fullName>Vereinssites</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
                <value>
                    <fullName>wetter.com CTV</fullName>
                </value>
                <value>
                    <fullName>ZG S71 Paket</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_AdPrice_AssignKeys.cls
global with sharing class Adv_AdPrice_AssignKeys implements Database.Batchable<sObject> {

    static final Set<String> FESTPLATZIERUNGEN = new Set<String>{'CPD', 'CPW', 'Fixed Price'};
    static final String ROTATIONSAUSSCHLUSS = 'Rotationsausschluss';

    private Map<Id, ADvendio__Placement__c> i_placementsMap;

    public Adv_AdPrice_AssignKeys(List<ADvendio__Placement__c> placementsList) {
        this.i_placementsMap = new Map<Id, ADvendio__Placement__c>(placementsList);
    }

    global Iterable<sObject> start(Database.BatchableContext BC) {
        return [
                SELECT ADvendio__Billing_Category__c, SomDig_Placement__c
                  FROM ADvendio__Ad_price__c
                 WHERE SomDig_Placement__c IN :this.i_placementsMap.keySet()
                   AND ADvendio__Active__c = true
        ];
    }

    global void execute(Database.BatchableContext BC, List<ADvendio__Ad_price__c> adPricesList) {
        System.debug('### this.i_placementsMap: ' + this.i_placementsMap);
        System.debug('### adPricesList: ' + adPricesList);

        assignKeysToAdPrices(this.i_placementsMap, new Map<Id, ADvendio__Ad_price__c>(adPricesList));
    }

    global void finish(Database.BatchableContext BC) {
    }


    public static void runFromAdPriceTrigger(Map<Id, ADvendio__Ad_price__c> newAdPricesMap, Map<Id, ADvendio__Ad_price__c> oldAdPricesMap) {
        Map<Id, ADvendio__Placement__c> relevantPlacementsMap = new Map<Id, ADvendio__Placement__c>();
        Map<Id, ADvendio__Ad_price__c> relevantAdPricesMap = new Map<Id, ADvendio__Ad_price__c>();

        Set<Id> placementIdsSet = new Set<Id>();

        for (ADvendio__Ad_price__c adPrice : newAdPricesMap.values()) {
            if (oldAdPricesMap == null || adPrice.ADvendio__Billing_Category__c != oldAdPricesMap.get(adPrice.Id).ADvendio__Billing_Category__c) {
                relevantAdPricesMap.put(adPrice.Id, adPrice);
                placementIdsSet.add(adPrice.SomDig_Placement__c);
            }
        }

        if (!relevantAdPricesMap.isEmpty()) {
            relevantPlacementsMap = new Map<Id, ADvendio__Placement__c>([
                SELECT Targeting_Provider__c
                  FROM ADvendio__Placement__c
                 WHERE Id IN :placementIdsSet
            ]);
        }

        assignKeysToAdPrices(relevantPlacementsMap, relevantAdPricesMap);
    }

    public static void runFromPlacementTrigger(Map<Id, ADvendio__Placement__c> newPlacementsMap, Map<Id, ADvendio__Placement__c> oldPlacementsMap) {
        List<ADvendio__Placement__c> relevantPlacementsList = new List<ADvendio__Placement__c>();

        for (ADvendio__Placement__c placement : newPlacementsMap.values()) {
            if (placement.Targeting_Provider__c != oldPlacementsMap.get(placement.Id).Targeting_Provider__c) {
                relevantPlacementsList.add(placement);
            }
        }

        if (!relevantPlacementsList.isEmpty()) {
            Database.executeBatch(new Adv_AdPrice_AssignKeys(relevantPlacementsList), 50);
        }
    }

    private static void assignKeysToAdPrices(Map<Id, ADvendio__Placement__c> placementsMap, Map<Id, ADvendio__Ad_price__c> adPricesMap) {
        if (!placementsMap.isEmpty() && !adPricesMap.isEmpty()) {
            List<ADvendio__KeyAdPriceAssignment__c> deleteableAssignmentsList = new List<ADvendio__KeyAdPriceAssignment__c>();
            List<ADvendio__KeyAdPriceAssignment__c> insertableAssignmentsList = new List<ADvendio__KeyAdPriceAssignment__c>();

            Map<Id, Set<String>> placementIdTargetingProvidersMap = getPlacementIdTargetingProvidersMap(placementsMap);
            Map<String, List<ADvendio__Key__c>> targetingProviderKeysMap = getTargetingProviderKeysMap(placementsMap);

            Map<Id, List<ADvendio__Ad_price__c>> placementIdAdPricesMap = new Map<Id, List<ADvendio__Ad_price__c>>();
            Map<Id, List<ADvendio__KeyAdPriceAssignment__c>> adPriceIdAssignmentsMap = new Map<Id, List<ADvendio__KeyAdPriceAssignment__c>>();

            for (ADvendio__Ad_price__c adPrice : adPricesMap.values()) {
                if (!placementIdAdPricesMap.containsKey(adPrice.SomDig_Placement__c)) {
                    placementIdAdPricesMap.put(adPrice.SomDig_Placement__c, new List<ADvendio__Ad_price__c>());
                }
                placementIdAdPricesMap.get(adPrice.SomDig_Placement__c).add(adPrice);
            }

            for (ADvendio__KeyAdPriceAssignment__c assignment : [
                SELECT ADvendio__AdPrice__c, ADvendio__Key__c, ADvendio__Key__r.SomDig_TargetingProvider__c
                  FROM ADvendio__KeyAdPriceAssignment__c
                 WHERE ADvendio__AdPrice__c IN :adPricesMap.keySet()
            ]) {
                if (!adPriceIdAssignmentsMap.containsKey(assignment.ADvendio__AdPrice__c)) {
                    adPriceIdAssignmentsMap.put(assignment.ADvendio__AdPrice__c, new List<ADvendio__KeyAdPriceAssignment__c>());
                }
                adPriceIdAssignmentsMap.get(assignment.ADvendio__AdPrice__c).add(assignment);
            }

            for (Id placementId : placementsMap.keySet()) {
                if (placementIdAdPricesMap.get(placementId) == null || placementIdAdPricesMap.get(placementId).isEmpty()) continue;

                Set<String> targetingProvidersSet = placementIdTargetingProvidersMap.get(placementId);

                for (ADvendio__Ad_price__c adPrice : placementIdAdPricesMap.get(placementId)) {
                    Boolean isFestplatzierung = FESTPLATZIERUNGEN.contains(adPrice.ADvendio__Billing_Category__c);

                    Map<Id, ADvendio__KeyAdPriceAssignment__c> existingAssignmentsMatrix = new Map<Id, ADvendio__KeyAdPriceAssignment__c>();

                    if (adPriceIdAssignmentsMap.get(adPrice.Id) != null) {
                        for (ADvendio__KeyAdPriceAssignment__c assignment : adPriceIdAssignmentsMap.get(adPrice.Id)) {
                            existingAssignmentsMatrix.put(assignment.ADvendio__Key__c, assignment);
                        }
                    }

                    for (String targetingProvider : targetingProvidersSet) {
                        if (targetingProviderKeysMap.get(targetingProvider) == null) continue;

                        if (!isFestplatzierung || targetingProvider == ROTATIONSAUSSCHLUSS) {
                            for (ADvendio__Key__c key : targetingProviderKeysMap.get(targetingProvider)) {
                                if (existingAssignmentsMatrix.containsKey(key.Id)) {
                                    existingAssignmentsMatrix.remove(key.Id);
                                } else {
                                    insertableAssignmentsList.add(new ADvendio__KeyAdPriceAssignment__c(
                                        ADvendio__AdPrice__c = adPrice.Id,
                                        ADvendio__Key__c = key.Id
                                    ));
                                }
                            }
                        }
                    }

                    deleteableAssignmentsList.addAll(existingAssignmentsMatrix.values());
                }
            }

            if (!insertableAssignmentsList.isEmpty()) insert insertableAssignmentsList;
            if (!deleteableAssignmentsList.isEmpty()) delete deleteableAssignmentsList;
        }
    }



    private static Map<Id, Set<String>> getPlacementIdTargetingProvidersMap(Map<Id, ADvendio__Placement__c> placementsMap) {
        Map<Id, Set<String>> placementIdTargetingProvidersMap = new Map<Id, Set<String>>();

        for (ADvendio__Placement__c placement : placementsMap.values()) {
                placementIdTargetingProvidersMap.put(placement.Id, new Set<String>());

                if (placement.Targeting_Provider__c != null) {
                    for (String targetingProvider : placement.Targeting_Provider__c.split(';')) {
                        placementIdTargetingProvidersMap.get(placement.Id).add(targetingProvider);
                    }
                }
        }

        return placementIdTargetingProvidersMap;
    }

    private static Map<String, List<ADvendio__Key__c>> getTargetingProviderKeysMap(Map<Id, ADvendio__Placement__c> placementsMap) {
        Map<String, List<ADvendio__Key__c>> targetingProviderKeysMap = new Map<String, List<ADvendio__Key__c>>();
        Set<String> targetingProvidersSet = new Set<String>();

        for (ADvendio__Placement__c placement : placementsMap.values()) {
            if (placement.Targeting_Provider__c != null) {
                for (String targetingProvider : placement.Targeting_Provider__c.split(';')) {
                    targetingProvidersSet.add(targetingProvider);
                }
            }
        }

        for (ADvendio__Key__c key : [
            SELECT SomDig_TargetingProvider__c
              FROM ADvendio__Key__c
             WHERE SomDig_TargetingProvider__c IN :targetingProvidersSet
        ]) {
            if (!targetingProviderKeysMap.containsKey(key.SomDig_TargetingProvider__c)) {
                targetingProviderKeysMap.put(key.SomDig_TargetingProvider__c, new List<ADvendio__Key__c>());
            }
            targetingProviderKeysMap.get(key.SomDig_TargetingProvider__c).add(key);
        }

        return targetingProviderKeysMap;
    }

}