src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This reference displays the ad spec to which this price is assigned.</description>
        <inlineHelpText>This reference displays the ad spec to which this price is assigned.</inlineHelpText>
        <label>Ad Spec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__c</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c</formula>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <formula>TEXT(ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Rotationstyp__c)</formula>
        <label>Rotationstyp</label>
        <type>Text</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <description>Hilfsfeld um die Info auf KampagnePosition zu übertragen; wird per Trigger befüllt; ist kein Formelfeld weil wir an Formellimits stoßen würden (KV 2551)</description>
        <inlineHelpText>Hier wird automatisch (per Code) der Name der M.-Differenzierung befüllt, welcher an der Werbeform gepflegt ist</inlineHelpText>
        <label>Mediagattungs-Differenzierung Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Preismerkmal__c</fullName>
        <formula>ADvendio__Placement__r.ADvendio__RateCategory__r.Name</formula>
        <label>Preismerkmal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <formula>TEXT(ADvendio__Placement__r.SomDig_Rotationstyp__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rotationstyp</label>
        <type>Text</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This formula displays the corresponding ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp;  ADvendio__Ad_Price__r.ADvendio__Ad_Spec__c  , ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.Name)</formula>
        <inlineHelpText>This formula displays the corresponding ad spec.</inlineHelpText>
        <label>Ad Spec</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>CASESAFEID(ADvendio__Media_Campaign__r.ADvendio__Pricelist__r.SomDig_AuftragstypId__c)</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Inventarklasse__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Welche Inventarklasse wird das CampaignItem zugeordnet? Erfolgt per Trigger, Indikatoren ist Rotationstyp an der Belegungseinheit, MG-Differenzierung der Werbeform, Preisgruppe des Werbemittels und Auftragstyp der Preisliste.</description>
        <inlineHelpText>Welche Inventarklasse wird das CampaignItem zugeordnet? Erfolgt per Trigger, Indikatoren ist Rotationstyp an der Belegungseinheit, MG-Differenzierung der Werbeform, Preisgruppe des Werbemittels und Auftragstyp der Preisliste.</inlineHelpText>
        <label>Inventarklasse</label>
        <referenceTo>SomDig_Inventarklasse__c</referenceTo>
        <relationshipLabel>Kampagnen Positionen</relationshipLabel>
        <relationshipName>Kampagnen_Positionen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <description>Id der M.-Differenzierung, welche an der Werbeform des Werbemittels gepflegt ist. Wird per Formel befüllt. Siehe auch KV 2551 zwecks nähere Infos. Wird für DWH-Schnittstelle benötigt</description>
        <formula>CASESAFEID( ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Id der M.-Differenzierung, welche an der Werbeform des Werbemittels gepflegt ist. Wird per Formel befüllt.</inlineHelpText>
        <label>Mediagattungs-Differenzierung-Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <formula>TEXT(ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Rotationstyp__c)</formula>
        <label>Rotationstyp</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_AuftragstypId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Steuert die Auslieferungsprioritäten in den AdServern, die Einschränkung auf mögliche Produkte/Werbemittel, ggf. auch Steuerung von fixem FC bei einigen Auftragstypen &amp; Voreinstellung der Rechnungsstellung etc.</description>
        <inlineHelpText>Bitte die Auftragstypen angeben. Diese steuert die Auslieferungsprioritäten in den AdServern, die Einschränkung auf mögliche Produkte/Werbemittel, ggf. auch Steuerung von fixem FC bei einigen Auftragstypen &amp; Voreinstellung der Rechnungsstellung etc.</inlineHelpText>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Preislisten</relationshipLabel>
        <relationshipName>Preislisten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Inventarklasse__c.object
<CustomObject>
    <description>zentrales Objekt für alle Inventarklassen der 71m digital</description>
    <fields>
        <fullName>SomDig_AuftragstypId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Inventarklassen</relationshipLabel>
        <relationshipName>Inventarklassen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Welche Mediagattungs-Diffenrenzierung ist für diese Inventarklasse relevant? Info kommt an der Position via Werbeform.</description>
        <inlineHelpText>Welche Mediagattungs-Diffenrenzierung ist für diese Inventarklasse relevant? Info kommt an der Position via Werbeform.</inlineHelpText>
        <label>Mediagattungs-Differenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipLabel>Inventarklassen</relationshipLabel>
        <relationshipName>Inventarklassen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Preismerkmal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preismerkmal</label>
        <referenceTo>ADvendio__RateCategory__c</referenceTo>
        <relationshipLabel>Inventarklassen</relationshipLabel>
        <relationshipName>Inventarklassen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <description>Auch Inventarklassifizierungs-Name. Info an der Position kommt über die Belegungseinheit.</description>
        <inlineHelpText>Auch Inventarklassifizierungs-Name. Info an der Position kommt über die Belegungseinheit.</inlineHelpText>
        <label>Rotationstyp</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Network-Rotation</fullName>
                </value>
                <value>
                    <fullName>Site-Rotation</fullName>
                </value>
                <value>
                    <fullName>Themen-Rotation</fullName>
                </value>
                <value>
                    <fullName>TV-Brand-Rotation</fullName>
                </value>
                <value>
                    <fullName>Umfeld</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_WerbeformDatensatztyp__c</fullName>
        <description>Dient der Identifizierung, ob es ein Adserverprodukt ist oder nicht. Wenn Adserverprodukt, muss der Adserver ausgewählt sein. Wenn Non-Adserverprodukt, ist es Standard.</description>
        <inlineHelpText>Dient der Identifizierung, ob es ein Adserverprodukt ist oder nicht. Wenn Adserverprodukt, muss der Adserver ausgewählt sein. Wenn Non-Adserverprodukt, ist es Standard.</inlineHelpText>
        <label>Werbeform Datensatztyp</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DFP</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inventarklasse</label>
    <nameField>
        <displayFormat>IN-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarklassen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_Inventarklasse.cls
public with sharing class Adv_CampaignItem_Inventarklasse {

    public static void setInventarklassen(List<ADvendio__Campaign_Item__c> campaignItemsList) {
        List<SomDig_Inventarklasse__c> inventarklassenList = [
            SELECT SomDig_Auftragstyp__c, SomDig_WerbeformDatensatztyp__c, SomDig_Rotationstyp__c,
                   SomDig_MediagattungsDifferenzierung__c, SomDig_Preismerkmal__c
              FROM SomDig_Inventarklasse__c
        ];
        Set<Id> adPriceIdsSet = new Set<Id>();

        for (ADvendio__Campaign_Item__c ci : campaignItemsList) {
            adPriceIdsSet.add(ci.ADvendio__Ad_Price__c);
        }

        Map<Id, ADvendio__Ad_price__c> adPricesMap = new Map<Id, ADvendio__Ad_price__c>([
                SELECT ADvendio__Pricelist__r.SomDig_AuftragstypId__r.Name, ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.Name,
                       ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Rotationstyp__c,
                       ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c,
                       ADvendio__Ad_Spec__r.ADvendio__Placement__r.ADvendio__RateCategory__c
                  FROM ADvendio__Ad_price__c
                 WHERE Id IN :adPriceIdsSet
        ]);

        for (ADvendio__Campaign_Item__c ci : campaignItemsList) {
            SomDig_Inventarklasse__c bestMatching = null;

            for (SomDig_Inventarklasse__c inventarklasse : inventarklassenList) {

                // Testen ob die Inventarklasse passt
                if ((inventarklasse.SomDig_Auftragstyp__c == null
                            || inventarklasse.SomDig_Auftragstyp__c == adPricesMap.get(ci.ADvendio__Ad_Price__c).ADvendio__Pricelist__r.SomDig_AuftragstypId__r.Name)
                        && (inventarklasse.SomDig_WerbeformDatensatztyp__c == null
                            || inventarklasse.SomDig_WerbeformDatensatztyp__c == adPricesMap.get(ci.ADvendio__Ad_Price__c).ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.Name)
                        && (inventarklasse.SomDig_Rotationstyp__c == null
                            || inventarklasse.SomDig_Rotationstyp__c == adPricesMap.get(ci.ADvendio__Ad_Price__c).ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Rotationstyp__c)
                        && (inventarklasse.SomDig_MediagattungsDifferenzierung__c == null
                            || inventarklasse.SomDig_MediagattungsDifferenzierung__c == adPricesMap.get(ci.ADvendio__Ad_Price__c).ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c)
                        && (inventarklasse.SomDig_Preismerkmal__c == null
                            || inventarklasse.SomDig_Preismerkmal__c == adPricesMap.get(ci.ADvendio__Ad_Price__c).ADvendio__Ad_Spec__r.ADvendio__Placement__r.ADvendio__RateCategory__c)) {

                    // Testen ob die Inventarklasse besser passt, als die bisher am besten passende.
                    if (bestMatching == null
                            || (inventarklasse.SomDig_Preismerkmal__c != null && bestMatching.SomDig_Preismerkmal__c == null)
                            || (inventarklasse.SomDig_MediagattungsDifferenzierung__c != null && bestMatching.SomDig_MediagattungsDifferenzierung__c == null)
                            || (inventarklasse.SomDig_Rotationstyp__c != null && bestMatching.SomDig_Rotationstyp__c == null)
                            || (inventarklasse.SomDig_WerbeformDatensatztyp__c != null && bestMatching.SomDig_WerbeformDatensatztyp__c == null)
                            || (inventarklasse.SomDig_Auftragstyp__c != null && bestMatching.SomDig_Auftragstyp__c == null)
                    ) {
                        bestMatching = inventarklasse;
                    }
                }
            }

            if (bestMatching != null) {
                ci.SomDig_Inventarklasse__c = bestMatching.Id;
            }
        }
    }

}