src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the ad type assigned to this ad spec.</description>
        <inlineHelpText>This field displays the ad type assigned to this ad spec.</inlineHelpText>
        <label>Ad Type</label>
        <referenceTo>ADvendio__Ad_Type__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Ad_Specs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <description>This field displays the sites assigned to this ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp; ADvendio__Placement__r.ADvendio__Site__r.Id , ADvendio__Placement__r.ADvendio__Site__r.Name)</formula>
        <inlineHelpText>This field displays the sites assigned to this ad spec.</inlineHelpText>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Mediagattung__c</fullName>
        <description>Hilfsfeld um die Info auf KampagnePosition zu übertragen; wird per Trigger befüllt; ist kein Formelfeld weil wir an Formellimits stoßen würden (KV 2551)</description>
        <inlineHelpText>Hier wird automatisch (per Code) der Name der M.-Gattung befüllt, welcher am Werbeträger gepflegt ist</inlineHelpText>
        <label>Mediagattung Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <description>Hilfsfeld um die Info auf KampagnePosition zu übertragen; wird per Trigger befüllt; ist kein Formelfeld weil wir an Formellimits stoßen würden (KV 2551)</description>
        <inlineHelpText>Hier wird automatisch (per Code) der Name der M.-Differenzierung befüllt, welcher an der Werbeform gepflegt ist</inlineHelpText>
        <label>Mediagattungs-Differenzierung Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsSegment__c</fullName>
        <description>Hilfsfeld um die Info auf KampagnePosition zu übertragen; wird per Trigger befüllt; ist kein Formelfeld weil wir an Formellimits stoßen würden (KV 2551)</description>
        <inlineHelpText>Hier wird automatisch (per Code) der Name des M.-Segments befüllt, welche an der Belegungseinheit gepflegt ist</inlineHelpText>
        <label>Mediagattungs-Segment Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Type__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
        <inlineHelpText>Gruppierung der einzelenen Werbeformen nach ihrer Art</inlineHelpText>
        <label>Mediagattungs-Differenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipLabel>Werbeformen</relationshipLabel>
        <relationshipName>Werbeformen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Type</label>
    <nameField>
        <label>Ad Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <description>Enter the site assigned to this placement.</description>
        <inlineHelpText>Enter the site assigned to this placement.</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SomDig_Mediagattungssegment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Mediagattungs-Segment</label>
        <referenceTo>SomDig_MediagattungsSegment__c</referenceTo>
        <relationshipLabel>Belegungseinheiten</relationshipLabel>
        <relationshipName>Belegungseinheiten</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Site__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Mediagattung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Die erste Klassifizierung/Zuordnung des Werbeträgers zu einer Mediagattung (TV/Digital/Text)</description>
        <inlineHelpText>Klassifizierung/Zuordnung des Werbeträgers zu einer Mediagattung (TV/Digital/Text)</inlineHelpText>
        <label>Mediagattung</label>
        <referenceTo>SomDig_Mediagattung__c</referenceTo>
        <relationshipLabel>Werbeträger</relationshipLabel>
        <relationshipName>Werbetraeger</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Mediagattung__c.object
<CustomObject>
    <description>Die erste Klassifizierung/Zuordnung des Werbeträgers zu einer Mediagattung (TV/Digital/Text)</description>
    <label>Mediagattung</label>
    <nameField>
        <label>Mediagattung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsDifferenzierung__c.object
<CustomObject>
    <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
    <label>Mediagattungs-Differenzierung</label>
    <nameField>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Differenzierungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsSegment__c.object
<CustomObject>
    <description>Zwischendifferenzierung/Segmentierung einer Belegungseinheit</description>
    <label>Mediagattungs-Segment</label>
    <nameField>
        <label>Mediagattungs-Segment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Segmente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_AdSpec_MediagattungFields.cls
//KV 02551
public class Adv_AdSpec_MediagattungFields{

    public static void updateFields(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){
        
        Set<ID> setBelegungsEinheitIDs = new Set<ID>();
        for(sObject o : Trigger.new)
            setBelegungsEinheitIDs.add((ID)o.get('ADvendio__Placement__c'));
        

        Map<ID, ADvendio__Placement__c> mapPlacements = new Map<ID, ADvendio__Placement__c>([SELECT ADvendio__Site__r.SomDig_Mediagattung__r.Name, SomDig_Mediagattungssegment__r.Name FROM ADvendio__Placement__c WHERE ID IN :setBelegungsEinheitIDs]);
        
        
        Set<ID> setWerbeFormIDs = new Set<ID>();
        for(sObject o : Trigger.new)
            setWerbeFormIDs.add((ID)o.get('ADvendio__Ad_Type__c'));
        
        Map<ID, ADvendio__Ad_Type__c> mapAdTypes = new Map<ID, ADvendio__Ad_Type__c>([SELECT SomDig_MediagattungsDifferenzierung__r.Name FROM ADvendio__Ad_Type__c WHERE ID IN :setWerbeFormIDs]);
                        



        for(sObject o : Trigger.new){
            ADvendio__Ad_Specs__c objSpec = (ADvendio__Ad_Specs__c) o;
            if(mapPlacements.containsKey(objSpec.ADvendio__Placement__c)){
            
                //SomDig_Mediagattung__c            
                if(mapPlacements.get(objSpec.ADvendio__Placement__c).ADvendio__Site__r.SomDig_Mediagattung__r.Name != null)
                    objSpec.SomDig_Mediagattung__c = mapPlacements.get(objSpec.ADvendio__Placement__c).ADvendio__Site__r.SomDig_Mediagattung__r.Name;
                    
                    
                //SomDig_MediagattungsSegment__c                    
                if(mapPlacements.get(objSpec.ADvendio__Placement__c).SomDig_Mediagattungssegment__r.Name != null)
                    objSpec.SomDig_MediagattungsSegment__c = mapPlacements.get(objSpec.ADvendio__Placement__c).SomDig_Mediagattungssegment__r.Name;                    
            }
            
            
            
            // MGD: WM,WF,MGD 
            //SomDig_MediagattungsDifferenzierung__c                    
            if(mapAdTypes.containsKey(objSpec.ADvendio__Ad_Type__c)){
                if(mapAdTypes.get(objSpec.ADvendio__Ad_Type__c).SomDig_MediagattungsDifferenzierung__r.Name != null)
                      objSpec.SomDig_MediagattungsDifferenzierung__c = mapAdTypes.get(objSpec.ADvendio__Ad_Type__c).SomDig_MediagattungsDifferenzierung__r.Name;      
            
            }
        }
    }

}