src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Id__c</fullName>
        <description>The ad server interface will enter the ID of the ad when booked to the ad server.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ad server interface will enter the ID of the ad when booked to the ad server.</inlineHelpText>
        <label>Ad Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Additional_Ad_Ids__c</fullName>
        <description>This field is used for entering additional ad Ids which for example haven&apos;t been booked via the interface.</description>
        <inlineHelpText>Diese Feld dient der Eingabe von mehr als einer LineItem - ID vom Adserver - bei der Fakturierung/Reporting werden diese addiert.</inlineHelpText>
        <label>Additional Ad Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Amount_B2APEX__c</fullName>
        <label>Amount (B2) (apex)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__Amount_B3APEX__c</fullName>
        <label>Amount (B3) (apex)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__ConnectedItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If you cancel a CampaignItem, a second CampaignItem is created to cancel the original. This field links those matching CampaignItems.</description>
        <label>Connected Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Campaign Items (Connected Item)</relationshipLabel>
        <relationshipName>ConnectedItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Clicks__c</fullName>
        <description>The ad server interface will enter the delivered clicks here.</description>
        <inlineHelpText>The ad server interface will enter the delivered clicks here.</inlineHelpText>
        <label>Delivered Clicks</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Impressions__c</fullName>
        <description>The ad server interface will enter the delivered impressions here.</description>
        <inlineHelpText>The ad server interface will enter the delivered impressions here. (technical View)</inlineHelpText>
        <label>Delivered Impressions</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizationExclusion__c</fullName>
        <description>Reason why this Campaign Item must not be optimized. Optimization is possible if this field is null, otherwise the reason is displayed.</description>
        <inlineHelpText>Reason why this Campaign Item must not be optimized. Leave blank to allow optimization.</inlineHelpText>
        <label>Optimization Exclusion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__PositionReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If a CampaignItem is optimized the new optimized CampaignItem needs a reference to the original CampaignItem.</description>
        <inlineHelpText>If a CampaignItem is optimized the new optimized CampaignItem needs a reference to the original CampaignItem.</inlineHelpText>
        <label>Position Reference</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Campaign Items (Position Reference)</relationshipLabel>
        <relationshipName>ReferingPositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Query_Inventory__c</fullName>
        <defaultValue>true</defaultValue>
        <description>With this checkbox, you can regulate whether an inventory query shall be possible for this campaign item.</description>
        <inlineHelpText>With this checkbox, you can regulate whether an inventory query shall be possible for this campaign item.</inlineHelpText>
        <label>Query Inventory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Submit_to_AdServer__c</fullName>
        <defaultValue>true</defaultValue>
        <description>With this checkbox, you can regulate whether this campaign item shall be transmitted to the ad server. After an update, this checkbox has to be checked again.</description>
        <inlineHelpText>With this checkbox, you can regulate whether this campaign item shall be transmitted to the ad server. After an update, this checkbox has to be checked again.</inlineHelpText>
        <label>Submit to AdServer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__SurchargeB2Abs__c</fullName>
        <description>This surcharge will be added to Gross Amount B2 to get Gross Amount B1.</description>
        <inlineHelpText>This surcharge will be added to Gross Amount B2 to get Gross Amount B1.</inlineHelpText>
        <label>Surcharge B2 (Abs.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ADvendio__SurchargeB3Abs__c</fullName>
        <description>This surcharge will be added to Gross Amount B3 to get Gross Amount B2.</description>
        <inlineHelpText>This surcharge will be added to Gross Amount B3 to get Gross Amount B2.</inlineHelpText>
        <label>Surcharge B3 (Abs.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SomDig_Menge__c</fullName>
        <description>Menge ohne anteiligen Naturalrabatt (Ticket 06323)</description>
        <label>Menge (ohne Naturalrabatt)</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_Naturalrabatt__c</fullName>
        <description>Naturalrabatt in Prozent (Ticket 06323)</description>
        <label>Naturalrabatt</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_Naturalrabatt_Test.cls
/**
 *	Testabdeckung für Adv_CampaignItem_Naturalrabatt
 */
@isTest
private class Adv_CampaignItem_Naturalrabatt_Test {

	@isTest
	static void presetNaturalrabatt() {
		
		ADvendio__Pricelist__c rc			= cls_P7S1_TestData.createTestPricelist(true);
		
		ADvendio__Ad_price__c ap			= cls_P7S1_TestData.createTestAdPrice(true, rc);
		ADvendio__MediaCampaign__c mc		= cls_P7S1_TestData.createTestMediaCampaign(true, null, rc);
		
		ADvendio__Campaign_Item__c ci1		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap); // no SomDig_Menge__c, SomDig_Naturalrabatt__c
		ci1.ADvendio__Quantity__c			= 1000;
		
		ADvendio__Campaign_Item__c ci2		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap); // no SomDig_Menge__c
		ci2.ADvendio__Quantity__c			= 1000;
		ci2.SomDig_Naturalrabatt__c			= 10;
		
		ADvendio__Campaign_Item__c ci3		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap);
		ci3.ADvendio__Quantity__c			= 1100;
		ci3.SomDig_Menge__c					= 1000;
		ci3.SomDig_Naturalrabatt__c			= 10;
		
		List<ADvendio__Campaign_Item__c> cis	= new List<ADvendio__Campaign_Item__c>{ci1, ci2, ci3};
		insert cis;
		
		Test.startTest();
		for (ADvendio__Campaign_Item__c ci : [SELECT Id, SomDig_Menge__c, ADvendio__Quantity__c, SomDig_Naturalrabatt__c FROM ADvendio__Campaign_Item__c WHERE Id IN :cis]) {
			if (ci.Id == ci1.Id) {
				system.assertEquals(1000.0,	ci.SomDig_Menge__c);
				system.assertEquals(1000.0,	ci.ADvendio__Quantity__c);
				system.assertEquals(0,		ci.SomDig_Naturalrabatt__c);
			}
			if (ci.Id == ci2.Id) {
				system.assertEquals(1000.0,	ci.SomDig_Menge__c);
				system.assertEquals(1000.0,	ci.ADvendio__Quantity__c);
				system.assertEquals(10,		ci.SomDig_Naturalrabatt__c);
			}
			if (ci.Id == ci3.Id) {
				system.assertEquals(1000.0,	ci.SomDig_Menge__c);
				system.assertEquals(1100.0,	ci.ADvendio__Quantity__c);
				system.assertEquals(10,		ci.SomDig_Naturalrabatt__c);
			}
		}

		try {
			ci3.SomDig_Menge__c					= null;
			update ci3;
		}
		catch (Exception e) {
			system.debug(e.getMessage());
			system.assert(e.getMessage().contains(Label.ADvendio.Required_field_missing_BA + ' ' + ADvendio__Campaign_Item__c.SomDig_Menge__c.getDescribe().getLabel()));
		}
		Test.stopTest();
	}
	
	@isTest
	static void setNaturalrabatt() {
		
		ADvendio__Pricelist__c rc			= cls_P7S1_TestData.createTestPricelist(true);
		
		ADvendio__Ad_price__c ap			= cls_P7S1_TestData.createTestAdPrice(true, rc);
		ADvendio__MediaCampaign__c mc		= cls_P7S1_TestData.createTestMediaCampaign(true, null, rc);
		
		ADvendio__Campaign_Item__c ci1		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap); 
		ci1.SomDig_Menge__c					= 1000;
		ci1.SomDig_Naturalrabatt__c			= 0;
		
		ADvendio__Campaign_Item__c ci2		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap);
		ci2.SomDig_Menge__c					= 1000;
		ci2.SomDig_Naturalrabatt__c			= 100;
		
		ADvendio__Campaign_Item__c ci3		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap);
		ci3.SomDig_Menge__c					= 1000;
		ci3.SomDig_Naturalrabatt__c			= 300;
		
		Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci1);
		Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci2);
		Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci3);
		
		List<ADvendio__Campaign_Item__c> cis	= new List<ADvendio__Campaign_Item__c>{ci1, ci2, ci3};
		insert cis;
		
		Test.startTest();
		for (ADvendio__Campaign_Item__c ci : [SELECT Id, ADvendio__Amount_B2APEX__c, ADvendio__Amount_B3APEX__c, ADvendio__SurchargeB3Abs__c, SomDig_Menge__c, ADvendio__Quantity__c, SomDig_Naturalrabatt__c FROM ADvendio__Campaign_Item__c WHERE Id IN :cis]) {
			system.debug(ci);
			if (ci.Id == ci1.Id) {
				system.assertEquals(1000.0,		ci.SomDig_Menge__c);
				system.assertEquals(1000.0,		ci.ADvendio__Quantity__c);
				system.assertEquals(0,			ci.ADvendio__SurchargeB3Abs__c);
				system.assertEquals(0,			ci.SomDig_Naturalrabatt__c);
				system.assertEquals(30,			ci.ADvendio__Amount_B3APEX__c);
				system.assertEquals(30,			ci.ADvendio__Amount_B2APEX__c);
			}
			if (ci.Id == ci2.Id) {
				system.assertEquals(1000.0,		ci.SomDig_Menge__c);
				system.assertEquals(2000.0,		ci.ADvendio__Quantity__c);
				system.assertEquals(100,		ci.SomDig_Naturalrabatt__c);
				system.assertEquals(-30,		ci.ADvendio__SurchargeB3Abs__c);
				system.assertEquals(60,			ci.ADvendio__Amount_B3APEX__c);
				system.assertEquals(30,			ci.ADvendio__Amount_B2APEX__c);
			}
			if (ci.Id == ci3.Id) {
				system.assertEquals(1000.0,		ci.SomDig_Menge__c);
				system.assertEquals(4000.0,		ci.ADvendio__Quantity__c);
				system.assertEquals(300,		ci.SomDig_Naturalrabatt__c);
				system.assertEquals(-90,		ci.ADvendio__SurchargeB3Abs__c);
				system.assertEquals(120,		ci.ADvendio__Amount_B3APEX__c);
				system.assertEquals(30,		ci.ADvendio__Amount_B2APEX__c);
			}
		}
		Test.stopTest();
	}

	
	@isTest
	static void setNegativeQuantityOnCancellation() {
		
		ADvendio__Pricelist__c rc			= cls_P7S1_TestData.createTestPricelist(true);
		
		ADvendio__Ad_price__c ap			= cls_P7S1_TestData.createTestAdPrice(true, rc);
		ADvendio__MediaCampaign__c mc		= cls_P7S1_TestData.createTestMediaCampaign(true, null, rc);
		
		ADvendio__Campaign_Item__c ci1		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap); 
		ci1.SomDig_Menge__c					= 1000;
		ci1.SomDig_Naturalrabatt__c			= 0;
		
		ADvendio__Campaign_Item__c ci2		= cls_P7S1_TestData.createTestCampaignItem(false, mc, ap);
		ci2.SomDig_Menge__c					= 1000;
		ci2.SomDig_Naturalrabatt__c			= 100;
		
		ci1	= Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci1);
		ci2	= Adv_CampaignItem_Naturalrabatt.setNaturalrabatt(ci2);
		
		List<ADvendio__Campaign_Item__c> cis	= new List<ADvendio__Campaign_Item__c>{ci1, ci2};
		insert cis;
		
		List<String> campaignItemFieldsToQuery = new List<String>();
		for (Schema.SObjectField soField : Sobjecttype.ADvendio__Campaign_Item__c.fields.getMap().values()) {
			if (soField.getDescribe().isCreateable()) {
				campaignItemFieldsToQuery.add(soField.getDescribe().getName());
			}
		}
		String campaignItemFieldsString	= String.join(campaignItemFieldsToQuery, ',');
		
		ADvendio__Campaign_Item__c ci1Clone	= new ADvendio__Campaign_Item__c();
		ADvendio__Campaign_Item__c ci2Clone	= new ADvendio__Campaign_Item__c();
		
		Test.startTest();
		for (ADvendio__Campaign_Item__c ci : (List<ADvendio__Campaign_Item__c>)Database.query('SELECT Id, '+campaignItemFieldsString+' FROM ADvendio__Campaign_Item__c WHERE Id IN :cis')) {
			if (ci.Id == ci1.Id) {
				ci1	= ci;
				system.assertEquals(1000.0, ci.SomDig_Menge__c);
				system.assertEquals(1000.0, ci.ADvendio__Quantity__c);
				system.assertEquals(0, ci.SomDig_Naturalrabatt__c);
				system.assertEquals(30, ci.ADvendio__Amount_B3APEX__c);
				system.assertEquals(0, ci.ADvendio__SurchargeB3Abs__c);
				ci1Clone										= ci.clone();
				ci1Clone.ADvendio__Ad_Id__c						= null;
				ci1Clone.ADvendio__Additional_Ad_Ids__c			= null;
				ci1Clone.ADvendio__Quantity__c					= - ci.ADvendio__Quantity__c;
				ci1Clone.ADvendio__SurchargeB2Abs__c			= ci.ADvendio__SurchargeB2Abs__c != null ? - ci.ADvendio__SurchargeB2Abs__c : null;
				ci1Clone.ADvendio__SurchargeB3Abs__c			= ci.ADvendio__SurchargeB3Abs__c != null ? - ci.ADvendio__SurchargeB3Abs__c : null;
				ci1Clone.ADvendio__Submit_to_AdServer__c		= false;
				ci1Clone.ADvendio__Query_Inventory__c			= false;
				ci1Clone.ADvendio__Delivered_Clicks__c			= null;
				ci1Clone.ADvendio__Delivered_Impressions__c		= null;
				ci1Clone.ADvendio__OptimizationExclusion__c		= Label.ADvendio.ExclusionContra;
				ci1Clone.ADvendio__PositionReference__c			= ci.Id;
				ci1Clone.ADvendio__ConnectedItem__c				= ci.Id;
			}
			if (ci.Id == ci2.Id) {
				ci2	= ci;
				system.assertEquals(1000.0, ci.SomDig_Menge__c);
				system.assertEquals(2000.0, ci.ADvendio__Quantity__c);
				system.assertEquals(100, ci.SomDig_Naturalrabatt__c);
				system.assertEquals(60, ci.ADvendio__Amount_B3APEX__c);
				system.assertEquals(-30, ci.ADvendio__SurchargeB3Abs__c);
				ci2Clone										= ci.clone();
				ci2Clone.ADvendio__Ad_Id__c						= null;
				ci2Clone.ADvendio__Additional_Ad_Ids__c			= null;
				ci2Clone.ADvendio__Quantity__c					= - ci.ADvendio__Quantity__c;
				ci2Clone.ADvendio__SurchargeB2Abs__c			= ci.ADvendio__SurchargeB2Abs__c != null ? - ci.ADvendio__SurchargeB2Abs__c : null;
				ci2Clone.ADvendio__SurchargeB3Abs__c			= ci.ADvendio__SurchargeB3Abs__c != null ? - ci.ADvendio__SurchargeB3Abs__c : null;
				ci2Clone.ADvendio__Submit_to_AdServer__c		= false;
				ci2Clone.ADvendio__Query_Inventory__c			= false;
				ci2Clone.ADvendio__Delivered_Clicks__c			= null;
				ci2Clone.ADvendio__Delivered_Impressions__c		= null;
				ci2Clone.ADvendio__OptimizationExclusion__c		= Label.ADvendio.ExclusionContra;
				ci2Clone.ADvendio__PositionReference__c			= ci.Id;
				ci2Clone.ADvendio__ConnectedItem__c				= ci.Id;
			}
		}
		
		cis	= new List<ADvendio__Campaign_Item__c>{ci1Clone, ci2Clone};
		insert cis;
		
		for (ADvendio__Campaign_Item__c ci : (List<ADvendio__Campaign_Item__c>)Database.query('SELECT Id, '+campaignItemFieldsString+' FROM ADvendio__Campaign_Item__c WHERE Id IN :cis')) {
			if (ci.Id == ci1Clone.Id) {
				system.assertEquals(-ci1.SomDig_Menge__c.setScale(2, System.RoundingMode.HALF_UP),			ci.SomDig_Menge__c);
				system.assertEquals(-ci1.ADvendio__Quantity__c.setScale(2, System.RoundingMode.HALF_UP),	ci.ADvendio__Quantity__c);
				system.assertEquals(ci1.SomDig_Naturalrabatt__c,											ci.SomDig_Naturalrabatt__c);
				system.assertEquals(-ci1.ADvendio__Amount_B3APEX__c,										ci.ADvendio__Amount_B3APEX__c);
				system.assertEquals(-ci1.ADvendio__SurchargeB3Abs__c,										ci.ADvendio__SurchargeB3Abs__c);
			}
			if (ci.Id == ci2Clone.Id) {
				system.assertEquals(-ci2.SomDig_Menge__c.setScale(2, System.RoundingMode.HALF_UP),			ci.SomDig_Menge__c);
				system.assertEquals(-ci2.ADvendio__Quantity__c.setScale(2, System.RoundingMode.HALF_UP),	ci.ADvendio__Quantity__c);
				system.assertEquals(ci2.SomDig_Naturalrabatt__c,											ci.SomDig_Naturalrabatt__c);
				system.assertEquals(-ci2.ADvendio__Amount_B3APEX__c,										ci.ADvendio__Amount_B3APEX__c);
				system.assertEquals(-ci2.ADvendio__SurchargeB3Abs__c,										ci.ADvendio__SurchargeB3Abs__c);
			}
		}
		Test.stopTest();
	}
}