src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdserverStatus__c</fullName>
        <label>Adserver Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Reason_for_refusal__c</fullName>
        <description>If the stage is set on &apos;Lost&apos; you can enter here the reason for refusal.</description>
        <inlineHelpText>If the stage is set on &apos;Lost&apos; you can enter here the reason for refusal.</inlineHelpText>
        <label>Reason for refusal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ADvendio__Stage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Order not applicable</fullName>
                </value>
                <value>
                    <fullName>Price too high</fullName>
                </value>
                <value>
                    <fullName>Competitor chosen</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>No budget</fullName>
                </value>
                <value>
                    <fullName>No advertiser feedback</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>P7S1_Sphere__c</fullName>
        <description>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</description>
        <inlineHelpText>Steuert das Hüllenmodel (Sphere) für alle Unternehmensbereiche welche die zentrale sf.com-Instance nutzen - steuert und Datentechnisch voneinander trennt.</inlineHelpText>
        <label>P7S1_Sphere</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aer</fullName>
                    <color>#666666</color>
                    <label>Aer</label>
                </value>
                <value>
                    <fullName>Sgn</fullName>
                    <color>#BBBBBB</color>
                    <label>Sgn</label>
                </value>
                <value>
                    <fullName>SomAt</fullName>
                    <color>#CC33CC</color>
                    <label>SomAt</label>
                </value>
                <value>
                    <fullName>SomDe</fullName>
                    <color>#FF0000</color>
                    <label>SomDe</label>
                </value>
                <value>
                    <fullName>Ven</fullName>
                    <color>#333399</color>
                    <label>Ven</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_SalesTeam__c</fullName>
        <description>Hilfsfeld für die SevenOne Media Digital Sales, wird primär für Reportzwecken genutzt (Datensätze wie Oppties etc. werden in den Reports u.a. nach diesen Werten gruppiert). Folgende Infos beinhaltet das Feld: Bereich (Digital), Abteilung (Sales), Unterabteilung (RTA/ECC) und Location; nicht über stringent, Anforderung Fachabteilung. Nachfolger vom Feld 
Vertriebs-Team (VB_Location__c)</description>
        <inlineHelpText>Hilfsfeld für die SOM Digital Sales, wird primär für Reportzwecken genutzt (Datensätze wie Oppties etc. werden in den Reports u.a. nach diesen Werten gruppiert). Bitte bei jedem Digital-Vertriebler auswählen. Nachfolger-Feld von Vertriebs-Team/Location</inlineHelpText>
        <label>Vertriebsteam Digital</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vertrieb Berlin</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Düsseldorf</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Frankfurt</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Hamburg</fullName>
                </value>
                <value>
                    <fullName>Vertrieb München</fullName>
                </value>
                <value>
                    <fullName>Vertrieb ECC</fullName>
                </value>
                <value>
                    <fullName>Vertrieb RTA</fullName>
                </value>
                <value>
                    <fullName>Vertrieb Steuerung</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_Storno_Test.cls
@isTest
public class Adv_MediaCampaign_Storno_Test{

    @isTest
    public static void cancelMKwithCI(){

        // Create Objects
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        
        // Set Date in Future
        objCI.ADvendio__from_Date__c = System.today().addDays(30);
        objCI.ADvendio__until_Date__c = System.today().addDays(30);        
        insert objCI;

        Test.startTest();

        // Set Mediacampaign to Storno
        objMC.ADvendio__Reason_for_refusal__c = 'Cancellation';
        objMC.ADvendio__Stage__c = 'Offer denied';
        update objMC;

        Test.stopTest();

        objCI = [SELECT ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCI.Id];
        System.assertEquals('Released',objCI.ADvendio__AdserverStatus__c);

    }

    @isTest
    public static void cancelMKwithBilling(){
        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' LIMIT 1];

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.ADvendio__BillMe__c = false;
        insert objMC;

        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        // Set Date in Future
        objCI.ADvendio__from_Date__c = System.today().addDays(30);
        objCI.ADvendio__until_Date__c = System.today().addDays(30); 
        objCI.ADvendio__Rate_Discount_4_Name__c = 'Storno ohne Leistungsfluss';
        insert objCI;

        objCI.ADvendio__AdserverStatus__c = '';
        update objCI;

        Test.startTest();

        objCI = [SELECT ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCI.Id];
        System.assertNotEquals('Released',objCI.ADvendio__AdserverStatus__c);

        System.runAs(objUserBilling) {
            // Set Mediacampaign to Storno
            objMC.ADvendio__Reason_for_refusal__c = 'Cancellation';
            objMC.ADvendio__Stage__c = 'Offer denied';
            update objMC;
        }

        Test.stopTest();

        objCI = [SELECT ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCI.Id];
        System.assertNotEquals('Released',objCI.ADvendio__AdserverStatus__c);

    }

    @isTest
    public static void cancelMKwithBillingAndNoStorno(){
        User objUserBilling = [SELECT Id, IsActive, Name, P7S1_Sphere__c, ProfileId, Profile.Name, Username, SomDig_SalesTeam__c FROM User WHERE IsActive = true AND Profile.Name = 'SomDig_Billing' LIMIT 1];

        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.ADvendio__BillMe__c = false;
        insert objMC;

        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        // Set Date in Future
        objCI.ADvendio__from_Date__c = System.today().addDays(30);
        objCI.ADvendio__until_Date__c = System.today().addDays(30); 
        insert objCI;

        Test.startTest();

        objCI = [SELECT ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCI.Id];
        System.assertNotEquals('Released',objCI.ADvendio__AdserverStatus__c);

        System.runAs(objUserBilling) {
            // Set Mediacampaign to Storno
            objMC.ADvendio__Reason_for_refusal__c = 'Cancellation';
            objMC.ADvendio__Stage__c = 'Offer denied';
            update objMC;
        }

        Test.stopTest();

        objCI = [SELECT ADvendio__AdserverStatus__c FROM ADvendio__Campaign_Item__c WHERE ID = :objCI.Id];
        System.assertEquals('Released',objCI.ADvendio__AdserverStatus__c);

    }

    @isTest
    public static void cancelMKwithOldCI() {
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(false);
        objMC.ADvendio__BillMe__c = false;
        insert objMC;

        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(false, objMC);
        // Set Date in Future
        objCI.ADvendio__from_Date__c = System.today().addDays(-1);
        objCI.ADvendio__until_Date__c = System.today().addDays(30); 
        insert objCI;

        Test.startTest();


        // Set Mediacampaign to Storno
        objMC.ADvendio__Reason_for_refusal__c = 'Cancellation';
        objMC.ADvendio__Stage__c = 'Offer denied';

        Boolean catchedError = false;

        try {
            update objMC;
        } catch(Exception e) {
            catchedError = true;
        }

        Test.stopTest();

        System.assert(catchedError);

    }
    
}