src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_DienstleistungbezogeneHelp__c</fullName>
        <description>Hilfsfeld zur Ermittlung der PriorValue (bitte NICHT LÖSCHEN); wird per Trigger befüllt</description>
        <label>Dienstleistungbezogene Positionen Help</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_DienstleistungbezogenePositionen__c</fullName>
        <description>Hilfsfeld; zeigt wie viele LI hängen zusammen mit einem &quot;DienstleistungsLI&quot;; wird benutzt um zu verhindern, daß eine MK zum Auftrag wird ohne, daß DienstleistunsLI angelegt ist</description>
        <inlineHelpText>zeigt wie viele LI hängen zusammen mit einem &quot;DienstleistungsLI&quot;</inlineHelpText>
        <label>Dienstleistungbezogene Positionen</label>
        <summaryFilterItems>
            <field>ADvendio__Campaign_Item__c.SomDig_Produktion_Erforderlich__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__Campaign_Item__c.ADvendio__Media_Campaign__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SomDig_DienstleistungspositionenHelp__c</fullName>
        <description>Hilfsfeld zur Ermittlung der PriorValue (bitte NICHT LÖSCHEN); wird per Trigger befüllt</description>
        <label>Dienstleistungspositionen Help</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_Dienstleistungspositionen__c</fullName>
        <description>zeigt die Anzahl von Dienstleistungsrelevanten LIs, von Werbeformen, die intern produziert werden; wird benutzt um zu verhindern, daß eine MK zum Auftrag wird, ohne, daß Dien</description>
        <inlineHelpText>zeigt die Anzahl von Dienstleistungsrelevanten LIs, von Werbeformen, die intern produziert werden</inlineHelpText>
        <label>Dienstleistungspositionen</label>
        <summaryFilterItems>
            <field>ADvendio__Campaign_Item__c.SomDig_Werbeform__c</field>
            <operation>contains</operation>
            <value>Motiverstellung</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__Campaign_Item__c.ADvendio__Media_Campaign__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_PopUp.cls
/*
    This class controls execution of pop up alert.
    Whenever a Field M(Field : SomDig_DienstleistungbezogenePositionen__c) is greater than
    N(Field : SomDig_Dienstleistungspositionen__c ) it will show an alert.
*/
public class Adv_MediaCampaign_PopUp {

    //Class Variables
    public Boolean i_bcheckM{get;set;}
    public String i_surl{get;set;}

    //Constructor
    public Adv_MediaCampaign_PopUp(ApexPages.StandardController sc){
        i_bcheckM = false;
        ADvendio__MediaCampaign__c I_oMediaId = (ADvendio__MediaCampaign__c)sc.getRecord();

        //Set of phases for which alert will be shown
        Set<String> I_sPhasesList = new Set<String>{'Stage 25%','Offer on Request','Stage 75%','Stage 90%','Booked'};

        //Quering Media Campaingn Record
        List<ADvendio__MediaCampaign__c> I_oMediaRecordList = new List<ADvendio__MediaCampaign__c>([Select id,SomDig_DienstleistungbezogenePositionen__c,SomDig_Dienstleistungspositionen__c, SomDig_DienstleistungbezogeneHelp__c, SomDig_DienstleistungspositionenHelp__c
                                                    from ADvendio__MediaCampaign__c
                                                    where id=:I_oMediaId.Id AND ADvendio__Stage__c in: I_sPhasesList]);

        //Checking whether M(Field : SomDig_DienstleistungbezogenePositionen__c) > N (Field : SomDig_Dienstleistungspositionen__c )
        if(I_oMediaRecordList.size() > 0){
            ADvendio__MediaCampaign__c I_oMediaRecord = I_oMediaRecordList.get(0);
            if(I_oMediaRecord.SomDig_DienstleistungbezogenePositionen__c != I_oMediaRecord.SomDig_DienstleistungbezogeneHelp__c ||
                I_oMediaRecord.SomDig_Dienstleistungspositionen__c != I_oMediaRecord.SomDig_DienstleistungspositionenHelp__c){

                if(I_oMediaRecord.SomDig_DienstleistungbezogenePositionen__c > I_oMediaRecord.SomDig_Dienstleistungspositionen__c ){
                    i_bcheckM = true;
                }
            }
            else
            {
                 i_bcheckM = false;
            }
        }
    }
}