src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillingStatus__c</fullName>
        <label>Billing Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <inlineHelpText>Entwurf: RG-Vorschlag welche freigegeben werden muss
Freigabe: RG-Vorschlag wurde freigegeben und kann im Renchnungslauf
Fakturiert: Rechungslauf erfolgte, aus RG-Vorschlag wurde finale Rechnung
Storno: Rechnung wurde durch neue RG-Storno aufgehoben</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the connected Campaign Item</description>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipName>InvoiceItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__FieldName__c</fullName>
        <description>something like &quot;Quantity&quot;</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizedValue__c</fullName>
        <description>The new opzimized value.</description>
        <inlineHelpText>The new opzimized value.</inlineHelpText>
        <label>Optimized Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SomDig_IsTeamLead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Kennzeichnet einen User als PAM TeamLead. Siehe Ticket 4864.</description>
        <inlineHelpText>Kennzeichnet einen User als PAM TeamLead.</inlineHelpText>
        <label>Is TeamLead</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_OptimizingChange_Storno.cls
/*
Used in Trigger "Adv_OptimizingChange".
Creates an Optimizing change record which sets the "Verkaufspreis" to 0, if the user chose "Storno mit Leistungsfluss" or "Kompensation"
KV 2517
*/
public class Adv_OptimizingChange_Storno extends TriggerController{

    public static final Id BILLING_PROFILE_ID	= '00eD0000001Qk4n';
    public static final Id SYSADM_PROFILE_ID	= '00e20000000lfOj';
    public static final Id BI_PROFILE_ID		= '00e570000012uRg';

     public Adv_OptimizingChange_Storno(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
                                        List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }
    
    protected override void runBeforeInsert() {
        preventStornoOhneLeistungsfluss((List<ADvendio__OptimizingChange__c>) lstNewItems);
        preventStornoMitLeistungsfluss((List<ADvendio__OptimizingChange__c>) lstNewItems);
    }
    
    private void preventStornoOhneLeistungsfluss(List<ADvendio__OptimizingChange__c> optChanges) {
    	Set<Id> canceldCampaignItems	= new Set<Id>();
    	for (ADvendio__OptimizingChange__c change : optChanges) {
    		if ('advendio__billingstatus__c'.equalsIgnoreCase(change.ADvendio__FieldName__c) &&
    			'canceled'.equalsIgnoreCase(change.ADvendio__OptimizedValue__c)) { // cancelled position (X)
    			canceldCampaignItems.add(change.ADvendio__CampaignItem__c);
    		}
    	}
    	
    	Set<Id> blockedCampaignItems	= new Set<Id>();
    	if (!canceldCampaignItems.isEmpty()) {
    		for (ADvendio__Campaign_Item__c ci : [SELECT Id  FROM ADvendio__Campaign_Item__c WHERE Id IN :canceldCampaignItems AND ADvendio__From_Date__c <= TODAY]) {
    			blockedCampaignItems.add(ci.Id);
    		}
    	}
    	
    	if (!blockedCampaignItems.isEmpty()) {
    		for (ADvendio__OptimizingChange__c change : optChanges) {
    			if (blockedCampaignItems.contains(change.ADvendio__CampaignItem__c)) {
    				change.addError('Es darf kein Positionstorno vor Leistungsfluss durchgeführt werden, wenn die Position bereits gestartet ist.');
	    		}
    		}
    	}
    }
    
	private void preventStornoMitLeistungsfluss(List<ADvendio__OptimizingChange__c> optChanges){
        Set<Id> canceldCampaignItems = new Set<Id>();
		for (ADvendio__OptimizingChange__c change : optChanges) {
            if(change.ADvendio__FieldName__c == 'advendio__rate_discount_4_name__c' && change.ADvendio__OptimizedValue__c == 'Storno mit Leistungsfluss') {
                canceldCampaignItems.add(change.ADvendio__CampaignItem__c);
			}
		}
		
		if(canceldCampaignItems.size() > 0){
            // Check if there are Invoiced or Reviewed Invoices for the optimized Campaign Items
            Integer invoiceItems = [SELECT Count() FROM ADVendio__InvoiceItem__c WHERE ADvendio__CampaignItem__c IN :canceldCampaignItems AND (ADvendio__Invoice__r.ADvendio__Status__c = 'Invoiced' OR ADvendio__Invoice__r.ADvendio__Status__c = 'Reviewed')];
            
            if(invoiceItems > 0 || (!isUserBilling() && !isUserAdmin() && !isUserTeamLead() && !isUserBI())) {
                optChanges[0].addError(Label.Adv_OptimizingChange_Storno_ErrorMessage);
            }
        }
	}

    @TestVisible
    private static Boolean isUserAdmin() {
        return UserInfo.getProfileId().contains(SYSADM_PROFILE_ID);
    }

    @TestVisible
    private static Boolean isUserBilling() {
        return UserInfo.getProfileId().contains(BILLING_PROFILE_ID);
    }

    @TestVisible
    private static Boolean isUserBI() {
        return UserInfo.getProfileId().contains(BI_PROFILE_ID);
    }   

    @TestVisible
    private static Boolean isUserTeamLead() {
        return currentUser.SomDig_IsTeamLead__c;
    }

    private static User currentUser {
        get {
            if(currentUser == null) currentUser = [SELECT SomDig_IsTeamLead__c FROM User WHERE ID = :UserInfo.getUserId() LIMIT 1];
            return currentUser;
        }
        set; 
    }

}