src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter Advertiser to whom the media campaign should be assigned.</description>
        <inlineHelpText>Enter Advertiser to whom the media campaign should be assigned.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Account_Agency</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>AccountIntermediary</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Media Campaigns (Account)</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter Agency to whom the media campaign should be assigned.</description>
        <inlineHelpText>Enter Agency to whom the media campaign should be assigned.</inlineHelpText>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>Account_Client</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>AccountIntermediary</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Media Campaigns (Agency)</relationshipLabel>
        <relationshipName>Campaign0s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_WtAgBeziehung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Statt WT und AG wird die Beziehung hier ausgewählt. Infofelder WT und AG von ADvendio  füllen sich dann automatisch per Trigger (siehe KV 1254)</description>
        <inlineHelpText>Statt WT und AG wird die Beziehung hier ausgewählt. Infofelder WT und AG füllen sich dann automatisch</inlineHelpText>
        <label>WT AG Beziehung</label>
        <referenceTo>SomDig_WtAgBeziehung__c</referenceTo>
        <relationshipLabel>Mediakampagnen</relationshipLabel>
        <relationshipName>Mediakampagnen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_WtAgBeziehung__c.object
<CustomObject>
    <description>Junction-Objekt um Account-Beziehungen darstellen zu können, an denen Datensätze verknüpft werden wie Prognosen, Umsätze etc. (siehe auch Kundenvorgang 995 für eine detaillierte Beschreibung bzw. Anforderung).</description>
    <fields>
        <fullName>SomDig_Agentur__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Hinterlegung des Agentur-Accounts in der Beziehung. 
Hinweis: Bei Direktbucher wird dieses Feld leer gelassen!</description>
        <inlineHelpText>Hinterlegung des Agentur-Accounts in der Beziehung. 
Hinweis: Bei Direktbucher wird dieses Feld leer gelassen!</inlineHelpText>
        <label>Agentur</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012D0000000QgmP</value>
            </filterItems>
            <infoMessage>Datensatztyp des ausgewählten Accounts muss &quot;Agentur&quot; sein, was aktuell nicht der Fall ist. Daher bitte am Account den Datensatztyp vorher noch ändern.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WT AG Beziehungen (Agentur)</relationshipLabel>
        <relationshipName>AG_Beziehungen</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Werbetreibender__c</fullName>
        <description>Hinterlegung des Werbetreibeder-Accounts in der Beziehung</description>
        <inlineHelpText>Hinterlegung des Werbetreibeder-Accounts in der Beziehung</inlineHelpText>
        <label>Werbetreibender</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012200000004c9A</value>
            </filterItems>
            <infoMessage>Datensatztyp des ausgewählten Accounts muss &quot;Werbetreibender&quot; sein, was aktuell nicht der Fall ist. Daher bitte am Account den Datensatztyp vorher noch ändern.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WT AG Beziehungen (Werbetreibender)</relationshipLabel>
        <relationshipName>WT_Beziehungen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WT AG Beziehung</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WT AG Beziehungsname</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WT AG Beziehungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_WtAgBeziehung.cls
public with sharing class Adv_MediaCampaign_WtAgBeziehung extends TriggerController {

    // Constructor
    public Adv_MediaCampaign_WtAgBeziehung(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
                                           List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }

    protected override void runBeforeInsert() {
        copyCustomAccountLockupsToADvendioAccountLookups((List<ADvendio__MediaCampaign__c>) lstNewItems, NULL);
    }

    protected override void runBeforeUpdate() {
        copyCustomAccountLockupsToADvendioAccountLookups((List<ADvendio__MediaCampaign__c>) lstNewItems, (Map<Id, ADvendio__MediaCampaign__c>) mapOldItems);
    }

    private void copyCustomAccountLockupsToADvendioAccountLookups(List<ADvendio__MediaCampaign__c> l_oListNewMediaCampaigns, Map<Id, ADvendio__MediaCampaign__c> l_oMapOldMediaCampaigns) {
        Map<Id, SomDig_WtAgBeziehung__c> l_oMapWtAgBeziehungen = new Map<Id, SomDig_WtAgBeziehung__c>();


        for (ADvendio__MediaCampaign__c l_oMediaCampaign : l_oListNewMediaCampaigns) {
            // Only copy WT and AG lookups from SomDig_WtAgBeziehung__c if
            // - the MediaCampaign is of RecordType 'Angebot' AND either
            //   - the MediaCampaign is inserted (i.e. l_oMapOldMediaCampaigns is NULL)
            //   - OR the MediaCampaign's lookup to SomDig_WtAgBeziehung__c has changed

            if (l_oMapOldMediaCampaigns == NULL || l_oMediaCampaign.SomDig_WtAgBeziehung__c != l_oMapOldMediaCampaigns.get(l_oMediaCampaign.Id).SomDig_WtAgBeziehung__c) 
                l_oMapWtAgBeziehungen.put(l_oMediaCampaign.SomDig_WtAgBeziehung__c, null);

        }

        if (!l_oMapWtAgBeziehungen.isEmpty()) {
            for (SomDig_WtAgBeziehung__c l_oWtAgBeziehung : [SELECT Id, SomDig_Werbetreibender__c, SomDig_Agentur__c
                                                               FROM SomDig_WtAgBeziehung__c
                                                              WHERE Id IN :l_oMapWtAgBeziehungen.keySet()]) {

                l_oMapWtAgBeziehungen.put(l_oWtAgBeziehung.Id, l_oWtAgBeziehung);
            }

            for (ADvendio__MediaCampaign__c l_oMediaCampaign : l_oListNewMediaCampaigns) {
                if (l_oMediaCampaign.SomDig_WtAgBeziehung__c != null) {
                    SomDig_WtAgBeziehung__c l_oWtAgBeziehung = l_oMapWtAgBeziehungen.get(l_oMediaCampaign.SomDig_WtAgBeziehung__c);
                    l_oMediaCampaign.ADvendio__Account__c = l_oWtAgBeziehung.SomDig_Werbetreibender__c;
                    l_oMediaCampaign.ADvendio__Agency__c = l_oWtAgBeziehung.SomDig_Agentur__c;
                } else {
                    l_oMediaCampaign.ADvendio__Account__c = null;
                    l_oMediaCampaign.ADvendio__Agency__c = null;
                }
            }
        }
    }

}