src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__CampaignItem__c</fullName>
        <label>Campaign Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizingVersion__c</fullName>
        <label>Optimizing Version</label>
        <referenceTo>ADvendio__OptimizingVersion__c</referenceTo>
        <relationshipLabel>Optimizing Changes</relationshipLabel>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipName>OptimizingVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_DurationChanged_Test.cls
@isTest
public class Adv_CampaignItem_DurationChanged_Test {
    
    
    @isTest
    public static void testdeleteOtherOVs() {
        
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(true, objMC);
        
        ADvendio__OptimizingVersion__c objOV = createADvendioOptimizingVersion(true);
        ADvendio__OptimizingChange__c objOC = createADvendioOptimizingChange(true, objOV, objCI);
        
        ADvendio__OptimizingVersion__c objOV2 = createADvendioOptimizingVersion(true);
        
        Test.startTest();
        
        System.assertEquals(2, [SELECT count() FROM ADvendio__OptimizingVersion__c]);
        
        objCI.ADvendio__until_Date__c = Date.today().addDays(9);
        update objCI;
        
        Test.stopTest();
        
        System.assertEquals(1, [SELECT count() FROM ADvendio__OptimizingVersion__c]);
        
    }
    
    
    
    // TODO: move to TESTClass
    public static ADvendio__OptimizingVersion__c createADvendioOptimizingVersion(Boolean isInsert){
        ADvendio__OptimizingVersion__c objOV = new ADvendio__OptimizingVersion__c();
        if(isInsert) insert objOV;
        return objOV;
    }    
    
    public static ADvendio__OptimizingChange__c createADvendioOptimizingChange(Boolean isInsert, ADvendio__OptimizingVersion__c objOV, ADvendio__Campaign_Item__c objCI){
        
        ADvendio__OptimizingChange__c objOC = new ADvendio__OptimizingChange__c();
        objOC.ADvendio__OptimizingVersion__c = objOV.ID;
        objOC.ADvendio__CampaignItem__c = objCI.ID;
        
        if(isInsert) insert objOC;
        return objOC;    
    }    
    
}