src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_KeineLieferzahlen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Wenn diese Checkbox gesetzt ist, werden Lieferdaten für diese Adserver-Id direkt nach deren Anlage gelöscht.</description>
        <inlineHelpText>Wenn diese Checkbox gesetzt ist, werden Lieferdaten für diese Adserver-Id direkt nach deren Anlage gelöscht.</inlineHelpText>
        <label>Keine Lieferzahlen</label>
        <type>Checkbox</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__DeliveryData__c.object
<CustomObject>
    <description>Detailed delivery data.</description>
    <fields>
        <fullName>ADvendio__AdServerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AdServer-ID, to which the delivery data refer.</description>
        <inlineHelpText>AdServer-ID, to which the delivery data refer.</inlineHelpText>
        <label>Ad Server ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>Delivery Data</relationshipLabel>
        <relationshipName>DeliveryData</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Data</label>
    <nameField>
        <displayFormat>DD-{0}</displayFormat>
        <label>Delivery Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_DeliveryData.cls
public class Adv_DeliveryData extends TriggerController {

    // Constructor
    public Adv_DeliveryData(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
                            List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }

    protected override void runAfterInsert() {
        deleteTechnicalDeliveryData((List<ADvendio__DeliveryData__c>) lstNewItems, NULL);
    }
    
    private void deleteTechnicalDeliveryData(List<ADvendio__DeliveryData__c> ddList, Map<Id, ADvendio__DeliveryData__c> oldMapDD) {
        
        List<Id> technicalDDs	= new List<Id>();
        for (ADvendio__DeliveryData__c dd : [SELECT Id FROM ADvendio__DeliveryData__c WHERE Id IN :ddList AND ADvendio__AdServerID__r.SomDig_KeineLieferzahlen__c = TRUE]) {
        	technicalDDs.add(dd.Id);
        }

        if (!technicalDDs.isEmpty()) {
            deleteDeliveryData(technicalDDs);
        }
    }
    
    @future
    static void deleteDeliveryData(List<Id> deliveryDataIds) {
        delete [SELECT Id FROM ADvendio__DeliveryData__c WHERE Id IN :deliveryDataIds];
    }
}