src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This reference displays the ad spec to which this price is assigned.</description>
        <inlineHelpText>This reference displays the ad spec to which this price is assigned.</inlineHelpText>
        <label>Ad Spec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This formula displays the corresponding ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp;  ADvendio__Ad_Price__r.ADvendio__Ad_Spec__c  , ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.Name)</formula>
        <inlineHelpText>This formula displays the corresponding ad spec.</inlineHelpText>
        <label>Ad Spec</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packet Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Prorated__c</fullName>
        <label>Prorated</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_BelegungseinheitTyp__c</fullName>
        <description>KV 02614. In diesem Feld steht die der Typ der Belegungseinheit des Werbemittels der Kampagnenposition.</description>
        <formula>TEXT(ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Typ__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Belegungseinheit Typ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_SumDeliveredImpressions__c</fullName>
        <label>SomDig_SumDeliveredImpressions</label>
        <summarizedField>ADvendio__DeliveryData__c.ADvendio__DeliveredImpressions__c</summarizedField>
        <summaryFilterItems>
            <field>ADvendio__DeliveryData__c.ADvendio__Type__c</field>
            <operation>equals</operation>
            <value>Täglich</value>
        </summaryFilterItems>
        <summaryForeignKey>ADvendio__DeliveryData__c.ADvendio__CampaignItem__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__PacketComponent__c.object
<CustomObject>
    <description>Defines packet and its components products.</description>
    <fields>
        <fullName>ADvendio__ComponentAdPrice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Ad-Price of current component Ad-Spec being used within the packet. It will be considered only if the Distribution of packet Ad-Spec is &apos;Individual&apos;.</description>
        <inlineHelpText>Enter the Ad-Price of current component Ad-Spec being used within the packet. It will be considered only if the Distribution of packet Ad-Spec is &apos;Individual&apos;.</inlineHelpText>
        <label>Component AdPrice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ADvendio__Ad_price__c.ADvendio__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>ADvendio__Ad_price__c.ADvendio__Ad_Spec__c</field>
                <operation>equals</operation>
                <valueField>$Source.ADvendio__ComponentAdSpec__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketAdSpec__c</fullName>
        <description>The packet AdSpec, to which a component AdSpec belongs.</description>
        <inlineHelpText>The packet AdSpec, to which a component AdSpec belongs.</inlineHelpText>
        <label>Packet AdSpec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ADvendio__Prorated__c</fullName>
        <label>Ratio</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Packet Component</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Packet Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packet Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_DynQuanBatch.cls
global class Adv_CampaignItem_DynQuanBatch implements Database.Batchable<sObject>, Schedulable {

    private String query;
    
    private Date lastDate	= System.today().addDays(-3);

    public final static String DEFAULT_QUERY = 'SELECT Id,ADvendio__Prorated__c, ADvendio__Quantity__c, ADvendio__until_Date__c, (SELECT ID, SomDig_SumDeliveredImpressions__c, SomDig_BelegungseinheitTyp__c FROM ADvendio__PacketComponents__r) FROM ADvendio__Campaign_Item__c WHERE ADvendio__from_Date__c < TODAY AND ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Distribution__c = \'Prorated\'';

	webservice static String startDynamicQuantityBatch(String campaignId) {
		if (campaignId != null && campaignId != '') {
			Adv_CampaignItem_DynQuanBatch qb	= new Adv_CampaignItem_DynQuanBatch();
			String query	= '';
			query	= Adv_CampaignItem_DynQuanBatch.DEFAULT_QUERY;
			query	+= ' AND Id = :campaignId';
			
			qb.execute(null, Database.query(query));
			
			return 'Die Mengen-Verteilung für die Position ist abgeschlossen';
		}
		return 'Bitte wähle eine Kampagnen-Position aus';
	}

    public Adv_CampaignItem_DynQuanBatch(){
        query = DEFAULT_QUERY;
        query += ' AND ADvendio__until_Date__c > :lastDate';
    }

    public Adv_CampaignItem_DynQuanBatch(String sQuery){
        query = sQuery;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<ADvendio__Campaign_Item__c> scope){
        List<ADvendio__Campaign_Item__c> listUpdateCIs = new List<ADvendio__Campaign_Item__c>();
        for (ADvendio__Campaign_Item__c objPaket : scope){
            
            if(objPaket.ADvendio__PacketComponents__r.size() < 2) continue;

            ADvendio__Campaign_Item__c ci1 = objPaket.ADvendio__PacketComponents__r[0];
            ADvendio__Campaign_Item__c ci2 = objPaket.ADvendio__PacketComponents__r[1];

            if(ci1.SomDig_BelegungseinheitTyp__c  != 'YouTube' && ci2.SomDig_BelegungseinheitTyp__c  != 'YouTube')
                continue;

            // If nothin was delivered, take 10 AI
            Decimal iDelivered1 = ci1.SomDig_SumDeliveredImpressions__c == 0 ? 10 : ci1.SomDig_SumDeliveredImpressions__c;
            Decimal iDelivered2 = ci2.SomDig_SumDeliveredImpressions__c == 0 ? 10 : ci2.SomDig_SumDeliveredImpressions__c;

            Decimal dQuan1 = objPaket.ADvendio__Quantity__c * (iDelivered1 / (iDelivered1 + iDelivered2));
            ci1.ADvendio__Quantity__c = iDelivered1 < iDelivered2 ? dQuan1.round(System.RoundingMode.UP) : dQuan1.round(System.RoundingMode.DOWN);
            ci2.ADvendio__Quantity__c = objPaket.ADvendio__Quantity__c - ci1.ADvendio__Quantity__c;

            ci1.ADvendio__Prorated__c = (ci1.ADvendio__Quantity__c/objPaket.ADvendio__Quantity__c)*100;
            ci2.ADvendio__Prorated__c = (ci2.ADvendio__Quantity__c/objPaket.ADvendio__Quantity__c)*100;

            listUpdateCIs.add(ci1);
            listUpdateCIs.add(ci2);
            
            objPaket.ADvendio__Prorated__c = objPaket.ADvendio__Prorated__c == null ? 100 : null;  
            listUpdateCIs.add(objPaket);
        }
        update listUpdateCIs;
    }

    global void finish(Database.BatchableContext BC){
    }

    global void execute(SchedulableContext sc) {
        Database.executebatch(new Adv_CampaignItem_DynQuanBatch());
    }
}