src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This reference displays the ad spec to which this price is assigned.</description>
        <inlineHelpText>This reference displays the ad spec to which this price is assigned.</inlineHelpText>
        <label>Ad Spec</label>
        <referenceTo>ADvendio__Ad_Specs__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Id__c</fullName>
        <description>The ad server interface will enter the ID of the ad when booked to the ad server.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ad server interface will enter the ID of the ad when booked to the ad server.</inlineHelpText>
        <label>Ad Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Spec__c</fullName>
        <description>This formula displays the corresponding ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp;  ADvendio__Ad_Price__r.ADvendio__Ad_Spec__c  , ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.Name)</formula>
        <inlineHelpText>This formula displays the corresponding ad spec.</inlineHelpText>
        <label>Ad Spec</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__AdserverStatus__c</fullName>
        <label>Adserver Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__PositionReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If a CampaignItem is optimized the new optimized CampaignItem needs a reference to the original CampaignItem.</description>
        <inlineHelpText>If a CampaignItem is optimized the new optimized CampaignItem needs a reference to the original CampaignItem.</inlineHelpText>
        <label>Position Reference</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Campaign Items (Position Reference)</relationshipLabel>
        <relationshipName>ReferingPositions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Stornoposition__c</fullName>
        <description>KV 03537. True, wenn die Position storniert wurde. Erkennbar am Feld &quot;Optimierungsausschluss&quot;.
Refactored logic in ticket 06005.</description>
        <formula>CONTAINS(ADvendio__OptimizationExclusion__c, &apos;Dies ist eine Stornierungsposition einer früheren Optimierung.&apos;) || 
CONTAINS(ADvendio__OptimizationExclusion__c, &apos;Diese Kampagnenposition wurde bereits optimiert.&apos;) || 
CONTAINS(ADvendio__OptimizationExclusion__c, &apos;This is a canceled Campaign Item&apos;) ||
NOT(ISBLANK(ADvendio__ConnectedItem__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>True, wenn die Position storniert wurde.</inlineHelpText>
        <label>Stornoposition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_SumDeliveredAIsManual__c</fullName>
        <description>KV 03563. Rollup der Lieferzahlen aus dem Unterobjekt &quot;Umsatzplan&quot;.</description>
        <inlineHelpText>Summe der Gelieferten AIs aus &quot;Umsatzplan&quot;.</inlineHelpText>
        <label>Sum Delivered AIs (manual)</label>
        <summarizedField>ADvendio__Revenue_Schedule__c.ADvendio__DeliveredAIsManual__c</summarizedField>
        <summaryForeignKey>ADvendio__Revenue_Schedule__c.ADvendio__Campaign_Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src-CRM-FAILED/classes/Adv_CampaignItem_Storno.cls
/*
KV: 02453
When a Campaign-Item with negative amount
*/
public class Adv_CampaignItem_Storno {

    private static Map<Id, String> campaignItemToAdIdMap = new Map<Id, String>();

    public static void storeAdIds(List<ADvendio__Campaign_Item__c> lstNewItems, Map<Id, ADvendio__Campaign_Item__c> mapOldItems) {
        for(ADvendio__Campaign_Item__c objCI : lstNewItems) {
          if(objCI.ADvendio__Ad_Id__c == null && mapOldItems.get(objCI.Id).ADvendio__Ad_Id__c != null && !campaignItemToAdIdMap.containsKey(objCI.Id)) {
            campaignItemToAdIdMap.put(objCI.Id, mapOldItems.get(objCI.Id).ADvendio__Ad_Id__c);
          }
        }
    }

    public static void updateFields(List<ADvendio__Campaign_Item__c> lstNewItems, Boolean isAfter){
        if(!isAfter || !SomDig_SOQLOptimizer.bCampaignItemStorno_Run) return;
        // Prepare map to the Delivered AIs from related Object
        Set<ID> setCIIDs = new Set<ID>();
        for(ADvendio__Campaign_Item__c o : lstNewItems){
            if( o.ADvendio__Quantity__c < 0 &&
              o.SomDig_Stornoposition__c &&
              o.ADvendio__from_Date__c > system.today()
              ){
                
                setCIIDs.add(o.ID);
            }
        }

        if(!setCIIDs.isEmpty()){
            // Get Campaign Updates to update
            Set<ID> setUpdateRelatedCIs = new Set<ID>();
            Set<ID> setUpdateNegativeCIs = new Set<ID>();
            System.Debug('+++++SELECT Adv_CampaignItem_Storno');
            for(ADvendio__Campaign_Item__c o : [SELECT ID, ADvendio__from_Date__c, ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.DeveloperName, ADvendio__PositionReference__c, ADvendio__PositionReference__r.SomDig_SumDeliveredAIsManual__c FROM ADvendio__Campaign_Item__c WHERE ID IN :setCIIDs]){
                // Skip if NonAdServer & Startdate in the Past
               if(o.ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.DeveloperName == 'Standard' && o.ADvendio__from_Date__c < System.Today()){
                  continue;
               }

               // Check if related Position (positive) has delivered AIs
               if(o.ADvendio__PositionReference__c != null && o.ADvendio__PositionReference__r.SomDig_SumDeliveredAIsManual__c != 0){
                  continue;
               }

               setUpdateNegativeCIs.add(o.ID);
               if(o.ADvendio__PositionReference__c != null){
                  setUpdateRelatedCIs.add(o.ADvendio__PositionReference__c);
               }
            }


            // Update Negative CIs
            if(!setUpdateNegativeCIs.isEmpty() || !setUpdateRelatedCIs.isEmpty()){
                System.Debug('+++++SELECT Adv_CampaignItem_Storno');
                List<ADvendio__Campaign_Item__c> listNegativeCIs = new List<ADvendio__Campaign_Item__c>([SELECT ID FROM ADvendio__Campaign_Item__c WHERE ID IN :setUpdateNegativeCIs OR ID IN :setUpdateRelatedCIs]);
                for(ADvendio__Campaign_Item__c o : listNegativeCIs){
                    o.ADvendio__rate_discount_4_name__c = 'Storno ohne Leistungsfluss';

                    if(setUpdateRelatedCIs.contains(o.ID)) {
                      o.ADvendio__AdserverStatus__c = 'Released';
                      if(campaignItemToAdIdMap.containsKey(o.Id)) {
                         o.ADvendio__Ad_Id__c = campaignItemToAdIdMap.get(o.Id);
                      }
                     
                    }
                }
                //SomDig_SOQLOptimizer.bCampaignItemStorno_Run = false; // deactivated for Ticket 04411.
                update listNegativeCIs;
            }
        }
    }
}