src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Billing_Category__c</fullName>
        <description>Enter the billing category for this price.</description>
        <inlineHelpText>Enter the billing category for this price.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__c</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <formula>ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.SomDig_MediagattungsDifferenzierung__c</formula>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the ad type assigned to this ad spec.</description>
        <inlineHelpText>This field displays the ad type assigned to this ad spec.</inlineHelpText>
        <label>Ad Type</label>
        <referenceTo>ADvendio__Ad_Type__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Ad_Specs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <description>This field displays the sites assigned to this ad spec.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp; ADvendio__Placement__r.ADvendio__Site__r.Id , ADvendio__Placement__r.ADvendio__Site__r.Name)</formula>
        <inlineHelpText>This field displays the sites assigned to this ad spec.</inlineHelpText>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <description>Hilfsfeld um die Info auf KampagnePosition zu übertragen; wird per Trigger befüllt; ist kein Formelfeld weil wir an Formellimits stoßen würden (KV 2551)</description>
        <inlineHelpText>Hier wird automatisch (per Code) der Name der M.-Differenzierung befüllt, welcher an der Werbeform gepflegt ist</inlineHelpText>
        <label>Mediagattungs-Differenzierung Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Type__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
        <inlineHelpText>Gruppierung der einzelenen Werbeformen nach ihrer Art</inlineHelpText>
        <label>Mediagattungs-Differenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipLabel>Werbeformen</relationshipLabel>
        <relationshipName>Werbeformen</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Type</label>
    <nameField>
        <label>Ad Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Key__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_TargetingProvider__c</fullName>
        <description>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</description>
        <inlineHelpText>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</inlineHelpText>
        <label>Targeting Provider</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATV_PBT</fullName>
                </value>
                <value>
                    <fullName>Autosites</fullName>
                </value>
                <value>
                    <fullName>Diverse Kriterien</fullName>
                </value>
                <value>
                    <fullName>Gesundheit.de</fullName>
                </value>
                <value>
                    <fullName>nugg.ad</fullName>
                </value>
                <value>
                    <fullName>nugg.ad InApp</fullName>
                </value>
                <value>
                    <fullName>Rotationsausschluss</fullName>
                </value>
                <value>
                    <fullName>SmartGeo</fullName>
                </value>
                <value>
                    <fullName>Vereinssites</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
                <value>
                    <fullName>wetter.com CTV</fullName>
                </value>
                <value>
                    <fullName>ZG S71 Paket</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Key</label>
    <nameField>
        <label>Key Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Keys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__KeyAdPriceAssignment__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Key__c</fullName>
        <label>Key</label>
        <referenceTo>ADvendio__Key__c</referenceTo>
        <relationshipLabel>Key Ad Price Assignments</relationshipLabel>
        <relationshipName>KeyAdPriceAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Ad Price Assignment</label>
    <nameField>
        <displayFormat>KAP-{00000000}</displayFormat>
        <label>Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Ad Price Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <description>Enter the site assigned to this placement.</description>
        <inlineHelpText>Enter the site assigned to this placement.</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Targeting_Provider__c</fullName>
        <description>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</description>
        <inlineHelpText>Zusammenfassung von Keys zu einer Gruppe, welche über einen technischen Dienstleister/Site/Seitenbetreiber zur Verfügung gestellt werden können. Vereinfacht die Zuordnung von mehreren Keys zu Werbemittel/Produkten.</inlineHelpText>
        <label>Targeting Provider</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ATV_PBT</fullName>
                </value>
                <value>
                    <fullName>Autosites</fullName>
                </value>
                <value>
                    <fullName>Diverse Kriterien</fullName>
                </value>
                <value>
                    <fullName>Gesundheit.de</fullName>
                </value>
                <value>
                    <fullName>nugg.ad</fullName>
                </value>
                <value>
                    <fullName>nugg.ad InApp</fullName>
                </value>
                <value>
                    <fullName>Rotationsausschluss</fullName>
                </value>
                <value>
                    <fullName>SmartGeo</fullName>
                </value>
                <value>
                    <fullName>Vereinssites</fullName>
                </value>
                <value>
                    <fullName>wetter.com</fullName>
                </value>
                <value>
                    <fullName>wetter.com CTV</fullName>
                </value>
                <value>
                    <fullName>ZG S71 Paket</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsDifferenzierung__c.object
<CustomObject>
    <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
    <label>Mediagattungs-Differenzierung</label>
    <nameField>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Differenzierungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_AdPrice_AssignKeys_Test.cls
@isTest
public with sharing class Adv_AdPrice_AssignKeys_Test {

    static testMethod void adPriceInsert() {
        ADvendio__Key__c key1 = cls_P7S1_TestData.createTestKey(false);
        key1.SomDig_TargetingProvider__c = 'nugg.ad';
        ADvendio__Key__c key2 = cls_P7S1_TestData.createTestKey(false);
        key2.SomDig_TargetingProvider__c = 'Rotationsausschluss';
        ADvendio__Key__c key3 = cls_P7S1_TestData.createTestKey(false);
        key3.SomDig_TargetingProvider__c = 'non-existent targeting provider';
        insert new List<ADvendio__Key__c>{ key1, key2, key3 };

        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.Targeting_Provider__c = 'nugg.ad;Rotationsausschluss';
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement);

        System.assertEquals(0, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        insert adPrice;

        Test.stopTest();

        System.assertEquals(2, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);
    }

    static testMethod void adPriceInsertWithInvalidBillingCategory() {
        ADvendio__Key__c key1 = cls_P7S1_TestData.createTestKey(false);
        key1.SomDig_TargetingProvider__c = 'nugg.ad';
        ADvendio__Key__c key2 = cls_P7S1_TestData.createTestKey(false);
        key2.SomDig_TargetingProvider__c = 'Rotationsausschluss';
        ADvendio__Key__c key3 = cls_P7S1_TestData.createTestKey(false);
        key3.SomDig_TargetingProvider__c = 'non-existent targeting provider';
        insert new List<ADvendio__Key__c>{ key1, key2, key3 };

        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.Targeting_Provider__c = 'nugg.ad;Rotationsausschluss';
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement);

        System.assertEquals(0, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);

        Test.startTest();

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec);
        adPrice.ADvendio__Billing_Category__c = 'CPD';
        insert adPrice;

        Test.stopTest();

        System.assertEquals(1, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);
    }

    static testMethod void adPriceBulk() {
        ADvendio__Key__c key = cls_P7S1_TestData.createTestKey(false);
        key.SomDig_TargetingProvider__c = 'nugg.ad';
        insert key;

        SomDig_MediagattungsDifferenzierung__c mgdiff = cls_P7S1_TestData.createTestMediagattungsDifferenzierung(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true, mgdiff);
        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.Targeting_Provider__c = 'nugg.ad';
        insert placement;

        List<ADvendio__Ad_Specs__c> adSpecsList = new List<ADvendio__Ad_Specs__c>();
        for (Integer i = 0; i < 200; i++) {
            adSpecsList.add(cls_P7S1_TestData.createTestAdSpec(false, placement, adType));
        }
        insert adSpecsList;

        SomDig_Auftragstyp__c auftragstyp = cls_P7S1_TestData.createTestAuftragstyp(true);
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true, auftragstyp);

        System.assertEquals(0, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);

        Test.startTest();

        List<ADvendio__Ad_price__c> adPricesList = new List<ADvendio__Ad_price__c>();
        for (Integer i = 0; i < 200; i++) {
            ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpecsList[i], pricelist);
            if (Math.mod(i, 2) == 0) {
                adPrice.ADvendio__Billing_Category__c = 'CPM';
            } else {
                adPrice.ADvendio__Billing_Category__c = 'CPD';
            }
            adPricesList.add(adPrice);
        }
        insert adPricesList;

        Test.stopTest();

        System.assertEquals(100, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);
    }

    static testMethod void adPriceUpdate() {
        ADvendio__Key__c key1 = cls_P7S1_TestData.createTestKey(false);
        key1.SomDig_TargetingProvider__c = 'nugg.ad';
        ADvendio__Key__c key2 = cls_P7S1_TestData.createTestKey(false);
        key2.SomDig_TargetingProvider__c = 'Rotationsausschluss';
        ADvendio__Key__c key3 = cls_P7S1_TestData.createTestKey(false);
        key3.SomDig_TargetingProvider__c = 'non-existent targeting provider';
        insert new List<ADvendio__Key__c>{ key1, key2, key3 };

        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.Targeting_Provider__c = 'nugg.ad;Rotationsausschluss';
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement);

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec);
        adPrice.ADvendio__Billing_Category__c = 'CPD';
        insert adPrice;

        System.assertEquals(1, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);

        Test.startTest();

        adPrice.ADvendio__Billing_Category__c = 'CPM';
        update adPrice;

        Test.stopTest();

        System.assertEquals(2, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);
    }

    static testMethod void placementUpdate() {
        ADvendio__Key__c key1 = cls_P7S1_TestData.createTestKey(false);
        key1.SomDig_TargetingProvider__c = 'nugg.ad';
        ADvendio__Key__c key2 = cls_P7S1_TestData.createTestKey(false);
        key2.SomDig_TargetingProvider__c = 'Rotationsausschluss';
        insert new List<ADvendio__Key__c>{ key1, key2 };

        ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false);
        placement.Targeting_Provider__c = 'nugg.ad;Rotationsausschluss';
        insert placement;
        ADvendio__Ad_Specs__c adSpec = cls_P7S1_TestData.createTestAdSpec(true, placement);

        ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpec);
        adPrice.ADvendio__Billing_Category__c = 'CPM';
        insert adPrice;

        System.assertEquals(2, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);

        Test.startTest();

        placement.Targeting_Provider__c = 'nugg.ad';
        update placement;

        Test.stopTest();

        System.assertEquals(1, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);
    }

    static testMethod void placementBulk() {
        ADvendio__Key__c key1 = cls_P7S1_TestData.createTestKey(false);
        key1.SomDig_TargetingProvider__c = 'nugg.ad';
        ADvendio__Key__c key2 = cls_P7S1_TestData.createTestKey(false);
        key2.SomDig_TargetingProvider__c = 'Rotationsausschluss';
        insert new List<ADvendio__Key__c>{ key1, key2 };

        SomDig_MediagattungsDifferenzierung__c mgdiff = cls_P7S1_TestData.createTestMediagattungsDifferenzierung(true);
        ADvendio__Ad_Type__c adType = cls_P7S1_TestData.createTestAdType(true, mgdiff);
        ADvendio__Site__c site = cls_P7S1_TestData.createTestSite(true);

        List<ADvendio__Placement__c> placementsList = new List<ADvendio__Placement__c>();
        for (Integer i = 0; i < 50; i++) {
            ADvendio__Placement__c placement = cls_P7S1_TestData.createTestPlacement(false, site);
            placement.Targeting_Provider__c = 'nugg.ad';
            placementsList.add(placement);
        }
        insert placementsList;

        List<ADvendio__Ad_Specs__c> adSpecsList = new List<ADvendio__Ad_Specs__c>();
        for (Integer i = 0; i < 50; i++) {
            adSpecsList.add(cls_P7S1_TestData.createTestAdSpec(false, placementsList[i], adType));
        }
        insert adSpecsList;

        SomDig_Auftragstyp__c auftragstyp = cls_P7S1_TestData.createTestAuftragstyp(true);
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true, auftragstyp);

        List<ADvendio__Ad_price__c> adPricesList = new List<ADvendio__Ad_price__c>();
        for (Integer i = 0; i < 50; i++) {
            ADvendio__Ad_price__c adPrice = cls_P7S1_TestData.createTestAdPrice(false, adSpecsList[i], pricelist);
            adPrice.ADvendio__Billing_Category__c = 'CPM';
            adPricesList.add(adPrice);
        }
        insert adPricesList;

        System.assertEquals(50, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);

        Test.startTest();

        for (ADvendio__Placement__c placement : placementsList) {
            placement.Targeting_Provider__c = 'nugg.ad;Rotationsausschluss';
        }
        update placementsList;

        Test.stopTest();

        System.assertEquals(100, [SELECT count() FROM ADvendio__KeyAdPriceAssignment__c]);
    }

}