src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the ad server ID.</inlineHelpText>
        <label>AdServer ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Parent_AdServer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If there is a superior ad server ID, you can enter its ID here.</description>
        <inlineHelpText>If there is a superior ad server ID, you can enter its ID here.</inlineHelpText>
        <label>Parent AdServer ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Medium zur Übertragung von Werbebotschaften</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Type__c</fullName>
        <description>Choose which type of ad server ID is concerned.</description>
        <inlineHelpText>Choose which type of ad server ID is concerned.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Site</fullName>
                </value>
                <value>
                    <fullName>Zone</fullName>
                </value>
                <value>
                    <fullName>Zone Group</fullName>
                </value>
                <value>
                    <fullName>Content Category</fullName>
                </value>
                <value>
                    <fullName>Content Unit</fullName>
                </value>
                <value>
                    <fullName>Content Unit Group</fullName>
                </value>
                <value>
                    <fullName>Page</fullName>
                </value>
                <value>
                    <fullName>Page Group</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Format</fullName>
                </value>
                <value>
                    <fullName>Placement</fullName>
                </value>
                <value>
                    <fullName>Ad Unit</fullName>
                </value>
                <value>
                    <fullName>Key</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsSegment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gruppierung der gelieferten Produkte nach ihrer Art: z.B. InApp/Mobile, InBrowser/Online, Connected TV/HbbTv, NonMedia usw.</description>
        <inlineHelpText>Gruppierung der gelieferten Produkte nach ihrer Art: z.B. InApp/Mobile, InBrowser/Online, Connected TV/HbbTv, NonMedia usw.</inlineHelpText>
        <label>Mediagattungs-Segment</label>
        <referenceTo>SomDig_MediagattungsSegment__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_TopMediagattungsSegment__c</fullName>
        <description>Da wir in dfp nur max. 4 Stufen der Adunits haben/nutzen reicht in diesem Fall eine Formel welche über diese 4 Stufen die Zuordnung der manuell zugeordneten obersten Ebene an die darunterliegenden Adunits vererbt.</description>
        <formula>IF (ISBLANK(ADvendio__Parent_AdServer_ID__c),
    null,
    IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
        SomDig_MediagattungsSegment__c,
        IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
            ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c,
            IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c,
                IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c,
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.SomDig_MediagattungsSegment__c
                   )
               )
           )
       )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Top Mediagattungs-Segment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_TopSite__c</fullName>
        <formula>IF (ISBLANK(ADvendio__Parent_AdServer_ID__c),
    null,
    IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
        ADvendio__Site__c,
        IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
            ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c,
            IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c,
                IF (ISBLANK(ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__c),
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c,
                    ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Parent_AdServer_ID__r.ADvendio__Site__c
                   )
               )
           )
       )
   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Top Site</label>
        <type>Text</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsSegment__c.object
<CustomObject>
    <description>Zwischendifferenzierung/Segmentierung einer Belegungseinheit</description>
    <label>Mediagattungs-Segment</label>
    <nameField>
        <label>Mediagattungs-Segment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Segmente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_AdServerId_AdUnitHierarchy.cls
/**
 * A batchable and schedulable class to maintain some data in AdUnitHierarchy
 *
 */
global with sharing class Adv_AdServerId_AdUnitHierarchy implements Database.Batchable<SObject>, Database.Stateful, Schedulable {

    /** Batch size. */
    private Integer batchSize       = 100;

    /** Ids of ADvendio__AdServer_ID__c to check. Mainly used for testing. */
    private Set<Id> recIds          = null;

    /** A count for counting number of batches processed. */
    private Integer totalBatchs     = 0;

    /** A count for counting number of accounts processed. */
    private Integer totalRecords    = 0;

    /**
     * Constructor.
     */
    public Adv_AdServerId_AdUnitHierarchy() {
    }

    /**
     * Set the RecordIds to check. Mainly used for testing.
     * @param   recIds  Record-Ids to set.
     */
    public void setRecordIds(Set<Id> recIds) {
        this.recIds = recIds;
    }

    /**
     * Add a RecordId to check. Mainly used for testing.
     * @param   recId   Record-Id to add.
     */
    public void addRecordId(Id recId) {
        if (this.recIds == null) {
            this.recIds = new Set<Id>();
        }
        this.recIds.add(recId);
    }

    /**
     * Batch job start routine.
     *
     * @param   bc  Context of the batchable job.
     */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT ADvendio__Site__c, SomDig_MediagattungsSegment__c, SomDig_TopSite__c, SomDig_TopMediagattungsSegment__c ' +
                         'FROM ADvendio__AdServer_ID__c ' +
                        'WHERE isDeleted = false ' +
                          'AND ADvendio__Parent_AdServer_ID__c != null ' +
                          'AND ADvendio__Type__c = \'Ad Unit\'';


        if (recIds != null) {
            recIds.remove(null);
            if (!recIds.isEmpty()) {
                query += ' AND Id IN :recIds';
            }
        }

        return Database.getQueryLocator(query);
    }

    /**
     * Batch job execution routine.
     *
     * It sums revenues of opportunities of accounts.
     *
     * @param   bc      Context of the batchable job.
     * @param   records List of sObject to process.
     */
    global void execute(Database.BatchableContext bc, List<sObject> records) {
        totalBatchs++;
        totalRecords += records.size();

        System.debug('\n\nAdv_AdServerId_AdUnitHierarchy: Execute: TotalBatchs = ' + totalBatchs + ', TotalRecords = ' + totalRecords + ', SizeOfBatchRecords = ' + records.size() + ', BatchJobId = ' + (bc == null ? '' : bc.getJobId()) + '\n');

        List<ADvendio__AdServer_ID__c> toUpdateRecords = new List<ADvendio__AdServer_ID__c>();

        Id siteId = null, mediagattungId = null;
        for (ADvendio__AdServer_ID__c rec : (List<ADvendio__AdServer_ID__c>)records) {
            Boolean alreadyAdded = false;
            //if (rec.ADvendio__Site__c != null || rec.SomDig_MediagattungsSegment__c != null || rec.SomDig_TopSite__c != null || rec.SomDig_TopMediagattungsSegment__c != null) {
                // Issue: SOMDIG-21
                siteId = rec.SomDig_TopSite__c == null ? null : Id.valueOf(rec.SomDig_TopSite__c);
                mediagattungId = rec.SomDig_TopMediagattungsSegment__c == null ? null : Id.valueOf(rec.SomDig_TopMediagattungsSegment__c);
                if (siteId != null && mediagattungId != null && (siteId != rec.ADvendio__Site__c || mediagattungId != rec.SomDig_MediagattungsSegment__c)) {
                    rec.ADvendio__Site__c = siteId;
                    rec.SomDig_MediagattungsSegment__c = mediagattungId;
                    toUpdateRecords.add(rec);
                    alreadyAdded = true;
                }
            //}
        }

        if (!toUpdateRecords.isEmpty()) {
            update toUpdateRecords;
        }
    }

    /**
     * Batch job completion routine.
     *
     * @param   bc  Context of the batchable job.
     */
    global void finish(Database.BatchableContext bc){
        AsyncApexJob job = (bc == null ? null : [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :bc.getJobId()]);
        System.debug('\n\nAdv_AdServerId_AdUnitHierarchy: Finish: TotalBatchs = ' + totalBatchs + ', TotalRecords = ' + totalRecords + ', ' + job + '\n');
    }

    /**
     * Schedule excution routine.
     *
     * @param   sc  Context of the schedule job.
     */
    global void execute(SchedulableContext sc) {
        Database.executeBatch(this, batchSize);
    }


}