src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the ad server ID.</inlineHelpText>
        <label>AdServer ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__AdServer_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Connect this ad server ID to the ad server login on which the ad server ID can be found.</description>
        <inlineHelpText>Connect this ad server ID to the ad server login on which the ad server ID can be found.</inlineHelpText>
        <label>AdServer Login</label>
        <referenceTo>ADvendio__AdServer_Logins__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>DART_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__AdServer_Name__c</fullName>
        <description>Enter the name of the ad server, in order to be able to differentiate between the ad server Ids of different ad servers in a list view.</description>
        <inlineHelpText>Enter the name of the ad server, in order to be able to differentiate between the ad server Ids of different ad servers in a list view.</inlineHelpText>
        <label>AdServer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Parent_AdServer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If there is a superior ad server ID, you can enter its ID here.</description>
        <inlineHelpText>If there is a superior ad server ID, you can enter its ID here.</inlineHelpText>
        <label>Parent AdServer ID</label>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Medium zur Übertragung von Werbebotschaften</inlineHelpText>
        <label>Site</label>
        <referenceTo>ADvendio__Site__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Type__c</fullName>
        <description>Choose which type of ad server ID is concerned.</description>
        <inlineHelpText>Choose which type of ad server ID is concerned.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Site</fullName>
                </value>
                <value>
                    <fullName>Zone</fullName>
                </value>
                <value>
                    <fullName>Zone Group</fullName>
                </value>
                <value>
                    <fullName>Content Category</fullName>
                </value>
                <value>
                    <fullName>Content Unit</fullName>
                </value>
                <value>
                    <fullName>Content Unit Group</fullName>
                </value>
                <value>
                    <fullName>Page</fullName>
                </value>
                <value>
                    <fullName>Page Group</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Format</fullName>
                </value>
                <value>
                    <fullName>Placement</fullName>
                </value>
                <value>
                    <fullName>Ad Unit</fullName>
                </value>
                <value>
                    <fullName>Key</fullName>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__UniqueKey__c</fullName>
        <description>Enter a UniqueKey (recommended: syntax) for this ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter a UniqueKey (recommended: syntax) for this ad server ID.</inlineHelpText>
        <label>UniqueKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>P7S1_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ADvendio__Type__c</field>
                <operation>equals</operation>
                <value>Ad Unit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>P7S1_Format__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsSegment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gruppierung der gelieferten Produkte nach ihrer Art: z.B. InApp/Mobile, InBrowser/Online, Connected TV/HbbTv, NonMedia usw.</description>
        <inlineHelpText>Gruppierung der gelieferten Produkte nach ihrer Art: z.B. InApp/Mobile, InBrowser/Online, Connected TV/HbbTv, NonMedia usw.</inlineHelpText>
        <label>Mediagattungs-Segment</label>
        <referenceTo>SomDig_MediagattungsSegment__c</referenceTo>
        <relationshipLabel>AdServer IDs</relationshipLabel>
        <relationshipName>AdServer_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__AdServer_Logins__c.object
<CustomObject>
    <label>AdServer Login</label>
    <nameField>
        <displayFormat>ASL-{000}</displayFormat>
        <label>AdServer Login No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AdServer Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Site__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__UniqueKey__c</fullName>
        <description>Enter a UniqueKey (recommended: syntax) for this site.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter a UniqueKey (recommended: syntax) for this site.</inlineHelpText>
        <label>UniqueKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_Format__c.object
<CustomObject>
    <description>Formate wie zum Beispiel Anna und die Liebe oder 2 Broke Grils</description>
    <label>Format</label>
    <nameField>
        <label>Format-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsSegment__c.object
<CustomObject>
    <description>Zwischendifferenzierung/Segmentierung einer Belegungseinheit</description>
    <label>Mediagattungs-Segment</label>
    <nameField>
        <label>Mediagattungs-Segment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Segmente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cls_P7S1_Format_AdServerLinking.cls
/*
    Used to link Formate object's record with AdServerId object's records.
*/
public class cls_P7S1_Format_AdServerLinking{
    List<ADvendio__AdServer_ID__c> i_oListAdServer;
    String i_sFormatId;
    public String i_sSearchText {get;set;}
    public List<cls_ModelClass> i_clsModelList{get;set;}
    Set<Id> i_sAdServerIds;
    public P7S1_Format__c i_oFormatObj{get;set;}

    //Constructor
    public cls_P7S1_Format_AdServerLinking() {
        i_clsModelList = new List<cls_ModelClass>();
        i_sAdServerIds = new Set<Id>();
        i_oListAdServer = new List<ADvendio__AdServer_ID__c>();

        //Getting formate object's record Id
        i_sFormatId = ApexPages.CurrentPage().getParameters().get('formatId');

        if(i_sFormatId != null)
            i_oFormatObj = [SELECT Id, Name FROM P7S1_Format__c WHERE Id=:i_sFormatId];

        if(i_sFormatId != null){
            i_oListAdServer = [SELECT Name,ADvendio__AdServer_Login__c,ADvendio__AdServer_Name__c,P7S1_Format__c ,
                          ADvendio__AdServer_ID__c,ADvendio__UniqueKey__c,SomDig_MediagattungsSegment__c,
                          ADvendio__Parent_AdServer_ID__c,ADvendio__Site__c
                          FROM ADvendio__AdServer_ID__c Where P7S1_Format__c =: i_sFormatId];
        }

        //Creating assigned records list
        if(i_oListAdServer.size() > 0){
            for(ADvendio__AdServer_ID__c I_AdObj : i_oListAdServer){
                cls_ModelClass I_cls_Model = new cls_ModelClass();
                I_cls_Model.i_Check = true;
                I_cls_Model.i_oAdObj = I_AdObj;
                i_clsModelList.add(I_cls_Model);
                i_sAdServerIds.add(I_AdObj.id);
            }
        }

        //Show message when recods are aleardy assigned to formate object
        if(i_clsModelList.size() > 0)
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Following records are already assigned to format object.If you want to assign more records than use search to get records.'));
    }

    //To search AdServerIds's records
    public void Search() {
        List<cls_ModelClass> I_clsTempModelList = new List<cls_ModelClass>();
        for(cls_ModelClass I_obj : i_clsModelList){
            if(I_obj.i_Check)
                I_clsTempModelList.add(I_obj);
        }
        i_clsModelList = new List<cls_ModelClass>();
        i_clsModelList = I_clsTempModelList;

        //Search Text
        String I_sTempSearchText = '';
        if(i_sSearchText != null && i_sSearchText.trim().length() > 0){
            if(i_sSearchText.contains('*')){
                I_sTempSearchText = i_sSearchText;
                I_sTempSearchText = I_sTempSearchText.remove('*');
                I_sTempSearchText = 'like \'%'+ I_sTempSearchText + '%\' ';
            }else{
                I_sTempSearchText = i_sSearchText;
                I_sTempSearchText = 'like \''+I_sTempSearchText+'\' ';
            }
        }

        i_oListAdServer = new List<ADvendio__AdServer_ID__c>();
        String I_sType = 'Ad Unit';
        String I_sRType = 'DFP';

        String I_sQuery = 'SELECT Name,ADvendio__AdServer_Login__c,ADvendio__AdServer_Name__c,P7S1_Format__c ,'+
                         'ADvendio__AdServer_ID__c,ADvendio__UniqueKey__c,SomDig_MediagattungsSegment__c, '+
                         'ADvendio__Parent_AdServer_ID__c,ADvendio__Site__c '+
                         'FROM ADvendio__AdServer_ID__c '+
                         'Where RecordType.Name =: I_sRType '+
                         'AND ADvendio__Type__c =: I_sType '+
                         'AND (Name ' + I_sTempSearchText +
                         'OR ADvendio__AdServer_Name__c '+ I_sTempSearchText +
                         'OR ADvendio__AdServer_Login__r.Name '+ I_sTempSearchText +')';

        i_oListAdServer = Database.Query(I_sQuery);

        if(i_oListAdServer.size() > 0){
            if(i_oListAdServer.size() >= 1000){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'More than 1000 records found.Please narrow your search criteria.'));

                I_sQuery = 'SELECT Name,ADvendio__AdServer_Login__c,ADvendio__AdServer_Name__c,P7S1_Format__c ,'+
                         'ADvendio__AdServer_ID__c,ADvendio__UniqueKey__c,SomDig_MediagattungsSegment__c, '+
                         'ADvendio__Parent_AdServer_ID__c,ADvendio__Site__c '+
                         'FROM ADvendio__AdServer_ID__c '+
                         'Where RecordType.Name =: I_sRType '+
                         'AND ADvendio__Type__c =: I_sType '+
                         'AND (Name ' + I_sTempSearchText +
                         'OR ADvendio__AdServer_Name__c '+ I_sTempSearchText +
                         'OR ADvendio__AdServer_Login__r.Name '+ I_sTempSearchText +') LIMIT 1000';

                i_oListAdServer = Database.Query(I_sQuery);

                for(ADvendio__AdServer_ID__c I_AdObj : i_oListAdServer){
                    cls_ModelClass I_cls_Model = new cls_ModelClass();
                    I_cls_Model.i_Check = false;
                    I_cls_Model.i_oAdObj = I_AdObj;
                    if(i_sAdServerIds.contains(I_AdObj.Id))
                        continue;
                    if(i_clsModelList.size() < 1000)
                        i_clsModelList.add(I_cls_Model);
                }
            }else{
                for(ADvendio__AdServer_ID__c I_AdObj : i_oListAdServer){
                    cls_ModelClass I_cls_Model = new cls_ModelClass();
                    I_cls_Model.i_Check = false;
                    I_cls_Model.i_oAdObj = I_AdObj;
                    if(i_sAdServerIds.contains(I_AdObj.Id))
                        continue;
                    if(i_clsModelList.size() < 1000)
                        i_clsModelList.add(I_cls_Model);

                }
            }
        }
    }

    /*
        To link Formate records with AdServerId.
        Assign new AdServerId to Formate Object.
        Returning to formate record's detail page.
        @return pg
    */
    public PageReference save() {
        List<ADvendio__AdServer_ID__c> I_oTempListAdServer = new List<ADvendio__AdServer_ID__c>();
        for(cls_ModelClass I_obj : i_clsModelList){
            if(I_obj.i_Check){
                I_obj.i_oAdObj.P7S1_Format__c = i_sFormatId;
            }else{
                if(i_sAdServerIds.contains(I_obj.i_oAdObj.Id)){
                    I_obj.i_oAdObj.P7S1_Format__c = null;
                }
            }
            I_oTempListAdServer.add(I_obj.i_oAdObj);
        }

        //Updateing AdServerId's Records
        update I_oTempListAdServer;
        PageReference pg = new PageReference('/'+i_sFormatId);
        pg.setRedirect(true);
        return pg;
    }

    //To cancel submission of records
    public PageReference Cancel(){
        PageReference pg = new PageReference('/'+i_sFormatId);
        pg.setRedirect(true);
        return pg;
    }

    //Wrapper class
    public class cls_ModelClass{
        public Boolean i_Check{get;set;}
        public ADvendio__AdServer_ID__c i_oAdObj{get;set;}
    }
}