src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Rate Card which is assigned to this Ad Price. A position can only be added to a Media Campaign, if it has been assigned to the same Rate Card.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Ad Prices</relationshipLabel>
        <relationshipName>Ad_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>ADvendio__Pricelist__r.SomDig_AuftragstypId__c</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Media_Campaign__c</fullName>
        <description>This reference names the appendant media campaign.</description>
        <inlineHelpText>This reference names the appendant media campaign.</inlineHelpText>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Advertising_Media</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <formula>CASESAFEID(ADvendio__Media_Campaign__r.ADvendio__Pricelist__r.SomDig_AuftragstypId__c)</formula>
        <label>Auftragstyp</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Invoice__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>ADvendio__Invoice__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentDueDate__c</fullName>
        <label>Payment Due Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentInterval__c</fullName>
        <label>Payment Interval</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentStart__c</fullName>
        <label>Payment Start</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Status__c</fullName>
        <inlineHelpText>Entwurf: RG-Vorschlag welche freigegeben werden muss
Freigabe: RG-Vorschlag wurde freigegeben und kann im Renchnungslauf
Fakturiert: Rechungslauf erfolgte, aus RG-Vorschlag wurde finale Rechnung
Storno: Rechnung wurde durch neue RG-Storno aufgehoben</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoiced</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <label>Auftragstyp</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentDueDate__c</fullName>
        <description>Essential for the Billing &amp; Accounting App and needs to be filled.</description>
        <inlineHelpText>Payment due at the beginning or the end of the interval?</inlineHelpText>
        <label>Payment Due Date</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ADvendio__PaymentInterval__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>due to beginning of interval</fullName>
                    <default>true</default>
                    <label>due to beginning of interval</label>
                </value>
                <value>
                    <fullName>due to the end of interval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentInterval__c</fullName>
        <description>Essential for the Billing &amp; Accounting App and needs to be filled.</description>
        <inlineHelpText>Please choose the invoice interval</inlineHelpText>
        <label>Payment Interval</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>total account (one Invoice)</fullName>
                </value>
                <value>
                    <fullName>monthly (1 month)</fullName>
                    <default>true</default>
                    <label>monthly (1 month)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__PaymentStart__c</fullName>
        <description>Essential for the Billing &amp; Accounting App and needs to be filled.</description>
        <inlineHelpText>First Invoice before or after Campaignstart?</inlineHelpText>
        <label>Payment Start</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ADvendio__PaymentInterval__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>before / during Billingperiod</fullName>
                </value>
                <value>
                    <fullName>after Billingperiod</fullName>
                    <default>true</default>
                    <label>after Billingperiod</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Rate Cards for the whole Media Campaign. If a Rate Card is selected, only items from this Rate Card can be added to the Media Campaign.</inlineHelpText>
        <label>Rate Card</label>
        <referenceTo>ADvendio__Pricelist__c</referenceTo>
        <relationshipLabel>Media Campaigns</relationshipLabel>
        <relationshipName>Media_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Pricelist__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <description>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</description>
        <formula>SomDig_AuftragstypId__r.Name</formula>
        <inlineHelpText>Hilfsfeld für die DWH-Schnittstelle. Liefert Auftragstyp als Text.</inlineHelpText>
        <label>Auftragstyp DWH</label>
        <type>Text</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <fields>
        <fullName>SomDig_Rechnungstellung__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Sollen die Mediakampagnen bei diesem Auftragstyp abgerechnet werden? Wenn Checkbox auf WAHR ist, wird eine Rechnung gestellt. Wird via Workflow/Feldaktualisierung auf Mediakampagnen-Basis umgesetzt. Nur Billing-Profil kann die Voreinstellung überschreiben/bearbeiten und Checkbox &quot;Gutschrift&quot; ist nicht aktiv</description>
        <inlineHelpText>Sollen die Mediakampagnen bei diesem Auftragstyp abgerechnet werden? Wenn Checkbox auf WAHR ist, wird eine Rechnung gestellt (wenn Checkbox &quot;Gutschrift&quot; nicht ausgewählt ist). Nur Billing-Profil kann die Voreinstellung überschreiben/bearbeiten</inlineHelpText>
        <label>Rechnungstellung</label>
        <type>Checkbox</type>
    </fields>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Adv_Invoice_PreInvoiceDeleteInsert_Test.cls
@isTest
private class Adv_Invoice_PreInvoiceDeleteInsert_Test {

    @isTest
    static void testAdv_Invoice_PreInvoiceDeleteInsert() {
        ADvendio__MediaCampaign__c mc1 = cls_P7S1_TestData.createTestMediaCampaign(false);
        mc1.Name='Test MediaCampaign 1';
        mc1.ADvendio__BillMe__c=true;
        mc1.ADvendio__Stage__c='Booked';
        mc1.ADvendio__PaymentStart__c='after Billingperiod';
        mc1.ADvendio__PaymentDueDate__c='due to the end of interval';
        mc1.ADvendio__PaymentInterval__c='monthly';
        insert mc1;

        ADvendio__Campaign_Item__c ci1 = cls_P7S1_TestData.createTestCampaignItem(true, mc1);

        Test.startTest();
        // Now test the right class.
        // Can't verify the results because it will call a batch job.
        // So just test it for code coverage.
        Adv_Invoice_PreInvoiceDeleteInsert c = new Adv_Invoice_PreInvoiceDeleteInsert();

        c.setRecordIds(null);

        c.addRecordId(mc1.Id);

        c.createPreInvoice();

        String sch = '0 0 23 * * ?';

        System.schedule('Test Adv_Invoice_PreInvoiceDeleteInsert', sch, c);

        Test.stopTest();
    }

    @isTest
    static void addRecordId(){
        ADVendio__Ad_Price__c price = cls_P7S1_TestData.createTestAdPrice(true, cls_P7S1_TestData.createTestAdSpec(true));
        ADvendio__Campaign_Item__c campItem1 = cls_P7S1_TestData.createTestCampaignItem(true, cls_P7S1_TestData.createTestMediaCampaign(true), price);
        
        Test.startTest();
        Adv_Invoice_PreInvoiceDeleteInsert c = new Adv_Invoice_PreInvoiceDeleteInsert();
        c.addRecordId(campItem1.ADvendio__Media_Campaign__c);
        Test.stopTest();

        System.assert(c.recIds != null && c.recIds.contains(campItem1.ADvendio__Media_Campaign__c));
    }

    @isTest
    static void setRecordIds(){
        ADVendio__Ad_Price__c price = cls_P7S1_TestData.createTestAdPrice(true, cls_P7S1_TestData.createTestAdSpec(true));
        ADvendio__Campaign_Item__c campItem1 = cls_P7S1_TestData.createTestCampaignItem(true, cls_P7S1_TestData.createTestMediaCampaign(true), price);
        ADvendio__Campaign_Item__c campItem2 = cls_P7S1_TestData.createTestCampaignItem(true, cls_P7S1_TestData.createTestMediaCampaign(true), price);
        
        Set<Id> setIds = new Set<Id>();
        setIds.add(campItem1.ADvendio__Media_Campaign__c);
        setIds.add(campItem2.ADvendio__Media_Campaign__c);

        Test.startTest();
        Adv_Invoice_PreInvoiceDeleteInsert c = new Adv_Invoice_PreInvoiceDeleteInsert();
        c.setRecordIds(setIds);
        Test.stopTest();

        System.assert(c.recIds != null && c.recIds.containsAll(setIds));
    }

    @isTest
    static void deletePreInvoiceWithBillMeFalse(){
        SomDig_Auftragstyp__c auftragstyp = cls_P7S1_TestData.createTestAuftragstyp(false);
        auftragstyp.SomDig_Rechnungstellung__c = false;
        insert auftragstyp;
        ADvendio__Pricelist__c pricelist = cls_P7S1_TestData.createTestPricelist(true, auftragstyp);
        
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true, null, pricelist);
        objMC.ADvendio__BillMe__c = false;
        update objMC;
        
        ADvendio__Invoice__c invoice = cls_P7S1_TestData.createTestInvoice(false, objMC);
        invoice.ADvendio__Status__c = 'Draft';
        insert invoice;
		
        Test.startTest();
        new Adv_Invoice_PreInvoiceDeleteInsert().deletePreInvoice();
        Test.stopTest();

        System.assert([SELECT Id FROM ADvendio__Invoice__c].size() == 0);

    }

    @isTest
    static void deletePreInvoiceWithBillMeTrue(){
        ADvendio__MediaCampaign__c camp = cls_P7S1_TestData.createTestMediaCampaign(false);
        camp.ADvendio__BillMe__c = true;
        camp.ADvendio__Stage__c = 'Booked';
        insert camp;

        ADvendio__Invoice__c invoice = cls_P7S1_TestData.createTestInvoice(false, camp);
        invoice.ADvendio__Status__c = 'Draft';
        insert invoice;

        Test.startTest();
        new Adv_Invoice_PreInvoiceDeleteInsert().deletePreInvoice();
        Test.stopTest();

        System.assert([SELECT Id FROM ADvendio__Invoice__c].size() > 0);

    }

    @isTest
    static void deletePreInvoiceWithAnValidInvoice(){
        ADvendio__Invoice__c invoice = cls_P7S1_TestData.createTestInvoice(false, cls_P7S1_TestData.createTestMediaCampaign(true));
        invoice.ADvendio__Status__c = 'Invoiced';
        insert invoice;

        Test.startTest();
        new Adv_Invoice_PreInvoiceDeleteInsert().deletePreInvoice();
        Test.stopTest();

        System.assert([SELECT Id FROM ADvendio__Invoice__c].size() > 0);

    }
}