src/objects/ADvendio__AdServer_ID__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServer_ID__c</fullName>
        <description>Enter the ad server ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the ad server ID.</inlineHelpText>
        <label>AdServer ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AdServer ID</label>
    <nameField>
        <label>AdServer ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__AdServerTeamAssignment__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdServerID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AdServer ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ADvendio__AdServer_ID__c.ADvendio__Type__c</field>
                <operation>equals</operation>
                <value>Team</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ADvendio__AdServer_ID__c</referenceTo>
        <relationshipLabel>AdServer Team Assignments</relationshipLabel>
        <relationshipName>AdServerTeamAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__MediaCampaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Media Campaign</label>
        <referenceTo>ADvendio__MediaCampaign__c</referenceTo>
        <relationshipLabel>AdServer Team Assignments</relationshipLabel>
        <relationshipName>AdServerTeamAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AdServer Team Assignment</label>
    <nameField>
        <label>AdServerTeamAssignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdServer Team Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_SomEntities.cls
/*
KV 02260
Creates an AdServerTeamAssignment when a Mediacampaign is Created
*/

public class Adv_MediaCampaign_SomEntities {

    public static void createAdServerTeamAssignment(List<sObject> lstNewItems){
    
        List<ADvendio__AdServer_ID__c> listAdID = new List<ADvendio__AdServer_ID__c>([SELECT ID FROM ADvendio__AdServer_ID__c WHERE Name = 'SOM_entities']);
        
        List<ADvendio__AdServerTeamAssignment__c> listNewASTA = new List<ADvendio__AdServerTeamAssignment__c>();
        if(!listAdID.isEmpty()){
            for(sObject ci : lstNewItems){            
                listNewASTA.add(new ADvendio__AdServerTeamAssignment__c(Name = 'SOM_entities', ADvendio__MediaCampaign__c = ci.ID, ADvendio__AdServerID__c = listAdID[0].ID));
            }        
        }
        
        insert listNewASTA;
    }           
}