src/objects/ADvendio__Ad_price__c.object
<CustomObject>
    <label>Ad Price</label>
    <nameField>
        <displayFormat>AP-{0}</displayFormat>
        <label>Ad Price No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ad Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__Ad_Specs__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Distribution__c</fullName>
        <description>Define how the amount of product package is to be distributed among its components.</description>
        <inlineHelpText>Define how the amount of product package is to be distributed among its components.</inlineHelpText>
        <label>Distribution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Linear</fullName>
                </value>
                <value>
                    <fullName>Prorated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__FC_Period__c</fullName>
        <description>Choose the unit for the FC.</description>
        <inlineHelpText>Choose the unit for the FC.</inlineHelpText>
        <label>FC Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>minute</fullName>
                </value>
                <value>
                    <fullName>session</fullName>
                </value>
                <value>
                    <fullName>hour</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>week</fullName>
                </value>
                <value>
                    <fullName>month</fullName>
                </value>
                <value>
                    <fullName>year</fullName>
                </value>
                <value>
                    <fullName>campaign</fullName>
                </value>
                <value>
                    <fullName>browser</fullName>
                </value>
                <value>
                    <fullName>visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__FC_Quantity__c</fullName>
        <description>Enter the amount of impressions for this ad spec&apos;s FC.</description>
        <inlineHelpText>Enter the amount of impressions for this ad spec&apos;s FC.</inlineHelpText>
        <label>FC Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the placement assigned to the ad spec.</description>
        <inlineHelpText>This field displays the placement assigned to the ad spec.</inlineHelpText>
        <label>Placement</label>
        <referenceTo>ADvendio__Placement__c</referenceTo>
        <relationshipLabel>Ad Specs</relationshipLabel>
        <relationshipName>Advertisement_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ad Spec</label>
    <nameField>
        <label>Ad Spec Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__AdDayOfWeek__c</fullName>
        <description>List the days on which the ad shall be displayed.</description>
        <inlineHelpText>List the days on which the ad shall be displayed.</inlineHelpText>
        <label>AdDayOfWeek</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Ad_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This look-up relation displays the connection to the ad price.</description>
        <inlineHelpText>This look-up relation displays the connection to the ad price.</inlineHelpText>
        <label>Ad Price</label>
        <referenceTo>ADvendio__Ad_price__c</referenceTo>
        <relationshipLabel>Campaign Items</relationshipLabel>
        <relationshipName>Campaign_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__Availability__c</fullName>
        <description>The ad server interface will enter the availability during an availabilty request.</description>
        <inlineHelpText>The ad server interface will enter the availability during an availabilty request.</inlineHelpText>
        <label>Availability (planned)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__FC_Period__c</fullName>
        <description>Choose the unit for the FC.</description>
        <inlineHelpText>Choose the unit for the FC.</inlineHelpText>
        <label>FC Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>minute</fullName>
                </value>
                <value>
                    <fullName>session</fullName>
                </value>
                <value>
                    <fullName>hour</fullName>
                </value>
                <value>
                    <fullName>day</fullName>
                </value>
                <value>
                    <fullName>week</fullName>
                </value>
                <value>
                    <fullName>month</fullName>
                </value>
                <value>
                    <fullName>campaign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__FC_Quantity__c</fullName>
        <description>Enter the number of impressions for a certain period of time for this campaign item.</description>
        <inlineHelpText>Enter the number of impressions for a certain period of time for this campaign item.</inlineHelpText>
        <label>FC Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__PacketItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Packet Item</label>
        <referenceTo>ADvendio__Campaign_Item__c</referenceTo>
        <relationshipLabel>Packet Components</relationshipLabel>
        <relationshipName>PacketComponents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_BelegungseinheitTyp__c</fullName>
        <description>KV 02614. In diesem Feld steht die der Typ der Belegungseinheit des Werbemittels der Kampagnenposition.</description>
        <formula>TEXT(ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Placement__r.SomDig_Typ__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Belegungseinheit Typ</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Verteilung__c</fullName>
        <description>KV 02614. In diesem Feld steht die Verteilungart, des Werbemittels des ADPrices.</description>
        <formula>TEXT(ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Distribution__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Verteilung</label>
        <type>Text</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ADvendio__Placement__c.object
<CustomObject>
    <fields>
        <fullName>SomDig_Typ__c</fullName>
        <description>Welchem Netzwerk gehört diese Belegungseinheit an?</description>
        <inlineHelpText>Welchem Netzwerk gehört diese Belegungseinheit an? Achtung dies hat Einfluss auf Auslieferungstyp und Priomodell.</inlineHelpText>
        <label>Netzwerk-Typ</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>71m intern</fullName>
                    <default>true</default>
                    <label>71m intern</label>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_ResetAvailability_Test.cls
@isTest
public class Adv_CampaignItem_ResetAvailability_Test {

    @isTest (seeAllData=false)
    public static void testSetAvailability(){
        ADvendio__MediaCampaign__c mc	= cls_P7S1_TestData.createTestMediaCampaign(true);
        
        // Create Component with SomDig_BelegungseinheitTyp__c = 'YouTube'
        ADvendio__Placement__c objPlacement_YT		= cls_P7S1_TestData.createTestPlacement(false);
        objPlacement_YT.SomDig_Typ__c = 'YouTube';

        ADvendio__Placement__c objPlacement_noYT	= cls_P7S1_TestData.createTestPlacement(false);
        insert new List<ADvendio__Placement__c>{objPlacement_YT, objPlacement_noYT};
        
        ADvendio__Ad_Specs__c objSpec_Package		= cls_P7S1_TestData.createTestAdSpec(false, objPlacement_noYT);
        objSpec_Package.ADvendio__Distribution__c	= 'Prorated';
        ADvendio__Ad_Specs__c objSpec_YT			= cls_P7S1_TestData.createTestAdSpec(false, objPlacement_YT);
        ADvendio__Ad_Specs__c objSpec_noYT			= cls_P7S1_TestData.createTestAdSpec(false, objPlacement_noYT);
        insert new List<ADvendio__Ad_Specs__c>{objSpec_Package,objSpec_YT, objSpec_noYT};
            
        ADvendio__Ad_price__c objPrice_package	= cls_P7S1_TestData.createTestAdPrice(false, objSpec_Package);
        ADvendio__Ad_price__c objPrice_YT		= cls_P7S1_TestData.createTestAdPrice(false, objSpec_YT);
        ADvendio__Ad_price__c objPrice_noYT		= cls_P7S1_TestData.createTestAdPrice(false, objSpec_noYT);
        insert new List<ADvendio__Ad_price__c>{objPrice_YT, objPrice_noYT, objPrice_package};

        // Create Paket
        ADvendio__Campaign_Item__c objCIPaket		= cls_P7S1_TestData.createTestCampaignItem(true, mc, objPrice_package);
        system.debug([select id, SomDig_Verteilung__c from ADvendio__Campaign_Item__c]);
        
        ADvendio__Campaign_Item__c objCIComponent_YT	= cls_P7S1_TestData.createTestCampaignItem(false, mc, objPrice_YT);
        objCIComponent_YT.Name							= 'Component YT';
        objCIComponent_YT.ADvendio__PacketItem__c		= objCIPaket.Id;
        objCIComponent_YT.ADvendio__Availability__c		= 1231;
        
        ADvendio__Campaign_Item__c objCIComponent_noYT	= cls_P7S1_TestData.createTestCampaignItem(false, mc, objPrice_noYT);
        objCIComponent_noYT.Name						= 'Component no YT';
        objCIComponent_noYT.ADvendio__PacketItem__c		= objCIPaket.Id;
        objCIComponent_noYT.ADvendio__Availability__c	= 1232;

        ADvendio__Campaign_Item__c objCI_noYT		= cls_P7S1_TestData.createTestCampaignItem(false, mc, objPrice_noYT);
        objCI_noYT.Name								= 'no YT';
        objCI_noYT.ADvendio__Availability__c		= 1233;
        
        ADvendio__Campaign_Item__c objCI_YT			= cls_P7S1_TestData.createTestCampaignItem(false, mc, objPrice_YT);
        objCI_YT.Name								= 'YT';
        objCI_YT.ADvendio__Availability__c			= 1234;
        objCI_YT.ADvendio__FC_Period__c				= 'day';
        objCI_YT.ADvendio__FC_Quantity__c 			= 1;
        
        List<ADvendio__Campaign_Item__c> campaignItems	= new List<ADvendio__Campaign_Item__c>{objCIComponent_YT, objCIComponent_noYT, objCI_noYT, objCI_YT};
        insert campaignItems;
        
        Test.startTest();
        
        objCIComponent_noYT.ADvendio__until_Date__c	= objCIComponent_noYT.ADvendio__until_Date__c.addDays(1);
        objCI_noYT.ADvendio__AdDayOfWeek__c			= 'Monday';
        //objCI_YT.ADvendio__FC_Quantity__c			= 2;
        update campaignItems;
            
        Test.stopTest();        
        
        for (ADvendio__Campaign_Item__c ci :[SELECT Id, Name, ADvendio__Availability__c, ADvendio__PacketItem__c, SomDig_BelegungseinheitTyp__c, SomDig_Verteilung__c
                              				 FROM ADvendio__Campaign_Item__c
                                             WHERE ID IN :campaignItems]) {
                                                 system.debug(ci);
        	if (ci.Id == objCI_noYT.Id) {
            	system.assertEquals(null, ci.ADvendio__Availability__c);
            }
            else if (ci.Id == objCI_YT.Id) {
            //	system.assertEquals(null, ci.ADvendio__Availability__c);
            }
            else if (ci.Id == objCIComponent_noYT.Id) {
            	system.assertEquals(objCIComponent_noYT.ADvendio__Availability__c, ci.ADvendio__Availability__c);
            }
            else if (ci.Id == objCIComponent_YT.Id) {
            	system.assertEquals(objCIComponent_YT.ADvendio__Availability__c, ci.ADvendio__Availability__c);
            }
        }
    }
}