src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Ad_Id__c</fullName>
        <description>The ad server interface will enter the ID of the ad when booked to the ad server.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ad server interface will enter the ID of the ad when booked to the ad server.</inlineHelpText>
        <label>Ad Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__AdserverStatus__c</fullName>
        <label>Adserver Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Billing_category__c</fullName>
        <description>Enter the billing category for this campaign item.</description>
        <inlineHelpText>Enter the billing category for this campaign item.</inlineHelpText>
        <label>Billing Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPM</fullName>
                    <default>true</default>
                    <label>CPM</label>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPO</fullName>
                </value>
                <value>
                    <fullName>CPD</fullName>
                </value>
                <value>
                    <fullName>CPW</fullName>
                </value>
                <value>
                    <fullName>CPMo</fullName>
                </value>
                <value>
                    <fullName>CPY</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Clicks__c</fullName>
        <description>The ad server interface will enter the delivered clicks here.</description>
        <inlineHelpText>The ad server interface will enter the delivered clicks here.</inlineHelpText>
        <label>Delivered Clicks</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__Delivered_Impressions__c</fullName>
        <description>The ad server interface will enter the delivered impressions here.</description>
        <inlineHelpText>The ad server interface will enter the delivered impressions here. (technical View)</inlineHelpText>
        <label>Delivered Impressions</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__LastBookingProcess__c</fullName>
        <description>Last Booking run</description>
        <label>Last Booking Process</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizationExclusion__c</fullName>
        <description>Reason why this Campaign Item must not be optimized. Optimization is possible if this field is null, otherwise the reason is displayed.</description>
        <inlineHelpText>Reason why this Campaign Item must not be optimized. Leave blank to allow optimization.</inlineHelpText>
        <label>Optimization Exclusion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Quantity__c</fullName>
        <description>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</description>
        <inlineHelpText>Enter an amount, dependent on billing category. CPM = impressions, CPC = clicks, CPD = amount of days, etc.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ADvendio__StatusSubmittedToAdServer__c</fullName>
        <description>This field displays the status of the campaign item once it has been pushed to an AdServer.</description>
        <inlineHelpText>This field displays the status of the campaign item once it has been pushed to an AdServer.</inlineHelpText>
        <label>Status submitted to AdServer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__from_Date__c</fullName>
        <description>Enter the campaign item&apos;s start date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s start date of period.</inlineHelpText>
        <label>From (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ADvendio__until_Date__c</fullName>
        <description>Enter the campaign item&apos;s end date of period.</description>
        <inlineHelpText>Enter the campaign item&apos;s end date of period.</inlineHelpText>
        <label>Until (Date)</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_AIClicksSollBisHeute__c</fullName>
        <description>Ais Soll gesamt x ((Aktuelles Datum +1 - Startdatum)/(Enddatum Position +1 - Startdatum Position))</description>
        <formula>IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPC&quot;), (ISPICKVAL(ADvendio__Billing_category__c, &quot;CPM&quot;))), TODAY() &gt;= ADvendio__from_Date__c, TODAY() &lt; ADvendio__until_Date__c, ADvendio__Days__c &gt; 0), 
ADvendio__Quantity__c / ADvendio__Days__c * (TODAY() - ADvendio__from_Date__c + 1), 

IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPC&quot;), (ISPICKVAL(ADvendio__Billing_category__c, &quot;CPM&quot;))), TODAY() &gt;= ADvendio__until_Date__c, ADvendio__Days__c &gt; 0), 
ADvendio__Quantity__c, 

IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPD&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPW&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;Fixed Price&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPMo&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPY&quot;)), TODAY() &gt;= ADvendio__from_Date__c, TODAY() &lt; ADvendio__until_Date__c, ADvendio__Guaranteed_AI__c &gt; 0, ADvendio__Days__c &gt; 0), ADvendio__BookingQuantity__c / ADvendio__Days__c * (TODAY() - ADvendio__from_Date__c + 1), 

IF( 
AND(OR(ISPICKVAL(ADvendio__Billing_category__c, &quot;CPD&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPW&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;Fixed Price&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPMo&quot;), ISPICKVAL(ADvendio__Billing_category__c, &quot;CPY&quot;)), TODAY() &gt;= ADvendio__until_Date__c, ADvendio__Guaranteed_AI__c &gt; 0, ADvendio__Days__c &gt; 0), ADvendio__BookingQuantity__c, 

Null))))</formula>
        <inlineHelpText>Berechnet die auszuliefernden Impressions oder Clicks tagesaktuell während der Laufzeit des Line-Items, lineare Verteilung</inlineHelpText>
        <label>AI/Clicks SOLL bis Heute</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SomDig_AdServerRelevant__c</fullName>
        <description>True, wenn der RecordType der Werbeform nicht Standard ist. Bei Pakethüllen immer false.</description>
        <formula>ADvendio__Ad_Price__r.ADvendio__Ad_Spec__r.ADvendio__Ad_Type__r.RecordType.DeveloperName != &apos;Standard&apos; &amp;&amp;  RecordType.DeveloperName != &apos;Packet&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>KV 03459. True, wenn der RecordType der Werbeform nicht Standard ist. Bei Pakethüllen immer false.</inlineHelpText>
        <label>SomDig_AdServerRelevant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_LastAdServerStatusChange__c</fullName>
        <description>KV 01371. Wird durch einen Workflow mit dem aktuellen Date/Time befüllt, wenn sich der AdServerStatus ändert und wenn vorher ein Wert im AdServerStatus stand.</description>
        <label>Last AdServer Status Change</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SomDig_LastAdServerStatusProcess__c</fullName>
        <description>KV 01371. Wird bei jedem Knopfdruck von &quot;UpdateAdStatusInAdServerCustom&quot; mit dem jetzigen Datum befüllt.</description>
        <label>Last AdServerStatus Process</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SomDig_LastOptimizationActivationDate__c</fullName>
        <description>KV 01371. Dieses Feld wird mit dem jetzigen Datum aktualisiert, wenn eine Optimierung aktiviert wird, in der die Kampagnenposition optimiert wird.</description>
        <label>Last Optimization Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SomDig_MotivEingebucht__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Status &quot;eingebucht&quot;: Abhängig vom AdServer - falls AdServer nicht kann - manuell / falls AdServer kann - automatisch (Bedingung: Position im Adserver hat mindestens 1 Creative und Position ist aktiv geschaltet)</description>
        <inlineHelpText>Ist das Motiv im Adserver eingebucht bzw. hinterlegt?</inlineHelpText>
        <label>Motiv eingebucht</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SomDig_PositionStatus__c</fullName>
        <description>-Inaktiv: Durchgebuchung im AdServer erfolgt, kein Motiv eingebucht.
-bereit: Werbemittel sind im AdServer eingebucht und aktiviert 
-Auslieferung-normal: DFP meldet tatsätzliche AIs und AIist&gt;=AIsollbisheute
-Auslieferung@Risk: DFP meldet tatsätzliche AIs und AIist&lt;AIsollbisheute
-pausiert: Position in AdServer wurde gestoppt/pausiert (DFP meldet &apos;pausiert&apos;)
-beendet - erfüllt: Enddatum in der Vergangenheit, AIs ist &gt;= AIs Soll 
-beendet - unterliefert: Enddatum in der Vergangenheit, AIs ist &lt; AIs Soll
-NonAdServer: Position enthält ein NonAdServer Produkt</description>
        <inlineHelpText>-Inaktiv:durchgebucht,kein Motiv
-bereit:im AdServer aktiviert
-normal:AIist&gt;=AIsollbisheute
-@Risk:AIist&lt;AIsollbisheute
-pausiert:laufender Flight wurde gestoppt
-erfüllt:beendet &amp; AIist&gt;=AIsoll
-unterliefert:beendet &amp; AIist&lt;AIsoll</inlineHelpText>
        <label>Position Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>inaktiv</fullName>
                </value>
                <value>
                    <fullName>bereit</fullName>
                </value>
                <value>
                    <fullName>An Adserver übermitteln</fullName>
                    <default>true</default>
                    <label>An Adserver übermitteln</label>
                </value>
                <value>
                    <fullName>Ad Status aktualisieren</fullName>
                </value>
                <value>
                    <fullName>Position pausiert</fullName>
                </value>
                <value>
                    <fullName>Position gestoppt</fullName>
                </value>
                <value>
                    <fullName>NonAdserver</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-normal</fullName>
                </value>
                <value>
                    <fullName>Auslieferung-@Risk</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-erfüllt</fullName>
                </value>
                <value>
                    <fullName>abgelaufen-unterliefert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SomgDig_LastDurationChange__c</fullName>
        <description>KV 1371. Dieses Feld wird durch einen Workflow mit dem jetzigen Datum aktualisiert, wenn sich das Start oder End Datum der Kampagnenposition ändert.</description>
        <label>Last Duration Change</label>
        <type>DateTime</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_PositionStatus.cls
/*
KV: 01371, 02982
Called from Trigger
Controlls Position-Status
*/
public class Adv_CampaignItem_PositionStatus extends TriggerController{
    public Adv_CampaignItem_PositionStatus(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
                                        List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }
    
    protected override void runBeforeInsert() {
        handleManualAdIds((List<ADvendio__Campaign_Item__c>) lstNewItems, null);
    }

    protected override void runBeforeUpdate() {
        handleManualAdIds((List<ADvendio__Campaign_Item__c>) lstNewItems, (Map<Id, ADvendio__Campaign_Item__c>) mapOldItems);
    }

    private void handleManualAdIds(List<ADvendio__Campaign_Item__c> campaignItems, Map<Id, ADvendio__Campaign_Item__c> oldCampaignItemsById) {
        for (ADvendio__Campaign_Item__c ci : campaignItems) {
            if ((isInsert || oldCampaignItemsById.get(ci.Id).ADvendio__Ad_Id__c  == null) &&
               	ci.ADvendio__Ad_Id__c != null) {
                ci.ADvendio__LastBookingProcess__c			= system.now();
                ci.ADvendio__StatusSubmittedToAdServer__c	= 'Created';
                ci.SomDig_MotivEingebucht__c				= true;
            }
        }
    }
    
    public static void setStatus(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){

        Map<ID, Schema.RecordTypeInfo> mapRecordTypes = Schema.SObjectType.ADvendio__Campaign_Item__c.getRecordTypeInfosById();
        
        
        for(sObject ci : lstNewItems){
            
            ADvendio__Campaign_Item__c o = (ADvendio__Campaign_Item__c) ci;
            
            Boolean bMotivGebucht = o.SomDig_MotivEingebucht__c;           
            String sADServerStatus = o.ADvendio__AdserverStatus__c;             
            String sBillingCat = o.ADvendio__Billing_category__c;
            String sSubmitStatus = o.ADvendio__StatusSubmittedToAdServer__c;
            String sOptiExclusion = o.ADvendio__OptimizationExclusion__c != null ? o.ADvendio__OptimizationExclusion__c : ''; 

            String sRT = mapRecordTypes.containsKey(o.RecordTypeId) ? mapRecordTypes.get(o.RecordTypeId).getName() : '';
            
            Double dDeliveredImp     = o.ADvendio__Delivered_Impressions__c != null ? o.ADvendio__Delivered_Impressions__c : 0;             
            Double dDeliveredClick   = o.ADvendio__Delivered_Clicks__c      != null ? o.ADvendio__Delivered_Clicks__c : 0;  
            Double dSollbisHeute     = o.SomDig_AIClicksSollBisHeute__c     != null ? o.SomDig_AIClicksSollBisHeute__c : 0;    
            Double dQuan             = o.ADvendio__Quantity__c              != null ? o.ADvendio__Quantity__c : 0;       
            
            //  If a date is null set to 01.01.1980
            Datetime dtNull = Datetime.newInstance(1980, 1, 1, 0, 0, 0);
            Datetime Now = System.today();
            Datetime BD  = o.ADvendio__LastBookingProcess__c             != null ? o.ADvendio__LastBookingProcess__c : dtNull;
            Datetime AOD = o.SomDig_LastOptimizationActivationDate__c    != null ? o.SomDig_LastOptimizationActivationDate__c : dtNull;
            Datetime UFD = o.SomgDig_LastDurationChange__c               != null ? o.SomgDig_LastDurationChange__c : dtNull;
            Datetime SAD = o.SomDig_LastAdServerStatusChange__c          != null ? o.SomDig_LastAdServerStatusChange__c : dtNull;
            Datetime SAS = o.SomDig_LastAdServerStatusProcess__c         != null ? o.SomDig_LastAdServerStatusProcess__c : dtNull;
            Datetime Until = o.ADvendio__until_Date__c                   != null ? o.ADvendio__until_Date__c : dtNull;
            Datetime FromDate = o.ADvendio__from_Date__c                    != null  ? o.ADvendio__from_Date__c : dtNull;                                                            
    
            

            ///// NonAdserver
            if(!o.SomDig_AdServerRelevant__c || sRT == 'Paket' || sRT == 'Packet' || (dQuan < 0 && sOptiExclusion.contains('Dies ist eine Stornierungsposition einer früheren Optimierung')) || (dQuan < 0 && sOptiExclusion.contains('This is a canceled Campaign Item from a previous optimization.'))){
                o.SomDig_PositionStatus__c = 'NonAdserver';            
                continue;                
            }
            
            ///// Ad Status aktualisieren
            if(SAS < SAD && Now < Until && BD != dtNull){
                o.SomDig_PositionStatus__c = 'Ad Status aktualisieren';
                continue;
            }
            
            ///// An Adserver übermitteln        
            if(((BD > AOD || BD > UFD) &&  sSubmitStatus == 'Error') ||
                (BD == dtNull)
            ){
                o.SomDig_PositionStatus__c = 'An Adserver übermitteln';            
                continue;
            }
            
            ///// Position pausiert
            if(SAS > SAD && sADServerStatus == 'Paused' && BD != dtNull){
                o.SomDig_PositionStatus__c = 'Position pausiert';
                continue;
            }
            
            ///// Position gestoppt
            if(SAS > SAD && sADServerStatus == 'Released' && BD != dtNull){
                o.SomDig_PositionStatus__c = 'Position gestoppt';
                continue;
            }     
            
            ///// inaktiv
            if(BD != dtNull && dDeliveredImp == 0 && !bMotivGebucht &&
               (sSubmitStatus == 'Created' || sSubmitStatus == 'Updated')
            ){
                o.SomDig_PositionStatus__c = 'inaktiv';
                continue;
            }
            
            ///// Bereit
            if(BD != dtNull && dDeliveredImp == 0 && bMotivGebucht && FROMDate > Now &&
              (sSubmitStatus == 'Created' || sSubmitStatus == 'Updated')
            ){
                o.SomDig_PositionStatus__c = 'bereit';
                continue;
            }
            
            ///// Auslieferung normal
            if(BD != dtNull && FromDate <= Now && Until >= Now && o.ADvendio__PerformanceIndicator__c >= 100 &&
              (sSubmitStatus == 'Created' || sSubmitStatus == 'Updated')
              ){                
                o.SomDig_PositionStatus__c = 'Auslieferung-normal';
                continue;
            }
            
            ///// Auslieferung @risk
            if(BD != dtNull && FromDate <= Now && Until >= Now && o.ADvendio__PerformanceIndicator__c < 100 &&
               (sSubmitStatus == 'Created' || sSubmitStatus == 'Updated')                
               ){
                o.SomDig_PositionStatus__c = 'Auslieferung-@Risk';
                continue;
            }
            
            ///// Abgelaufen erfüllt
            if(BD != dtNull && Now > Until &&
              (sBillingCat == 'CPC' && dDeliveredClick >= dQuan || sBillingCat != 'CPC' && dDeliveredImp >= dQuan)){
                o.SomDig_PositionStatus__c = 'abgelaufen-erfüllt';
                continue;
            }
            
            ///// Abgelaufen unterliefert
            if(BD != dtNull && Now > Until &&
              (sBillingCat == 'CPC' && dDeliveredClick < dQuan || sBillingCat != 'CPC' && dDeliveredImp < dQuan)){
                o.SomDig_PositionStatus__c = 'abgelaufen-unterliefert';
                continue;
            }                                                       
        }        
    }
}