src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillMe__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Bill me?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__DoNotShowOnProposalPDF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not Show on Proposal PDF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__NotRelevantForTurnover__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox controls if the amount is summed up to the related account or not.</description>
        <inlineHelpText>This checkbox controls if the amount is summed up to the related account or not.</inlineHelpText>
        <label>Not Relevant For Turnover</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ADvendio__ShowOnInvoicePDF__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show on Invoice PDF</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Adv_CampaignItem_PDFCheckboxes.cls
/*
KV 02135
If "Sonderrabatt" Nachliefierung or Storno ohne Leistungsfluss set ADvendio__DoNotShowOnProposalPDF__c true
and ADvendio__ShowOnInvoicePDF__c false.
*/

public class Adv_CampaignItem_PDFCheckboxes {

    public static void setPDFCheckboxes(List<sObject> lstNewItems){
        for(sObject ci : lstNewItems){            
            ADvendio__Campaign_Item__c o = (ADvendio__Campaign_Item__c) ci;
            if(o.ADvendio__Rate_Discount_4_Name__c == 'Nachlieferung' || o.ADvendio__Rate_Discount_4_Name__c == 'Storno ohne Leistungsfluss'|| o.ADvendio__Rate_Discount_4_Name__c == 'Storno mit Leistungsfluss'){
                o.ADvendio__DoNotShowOnProposalPDF__c = true;
                o.ADvendio__ShowOnInvoicePDF__c = false;
                o.ADvendio__BillMe__c = false;
				o.ADvendio__NotRelevantForTurnover__c = true;
            }            
        }        
    }           
}