src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__BillingStatus__c</fullName>
        <label>Billing Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ADvendio__Rate_Discount_4_Name__c</fullName>
        <description>Here you are able to add an intern description to this special discount.</description>
        <inlineHelpText>Here you are able to add an intern description to this special discount.</inlineHelpText>
        <label>Special Discount (Name)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>InPage</fullName>
                </value>
                <value>
                    <fullName>InStream</fullName>
                </value>
                <value>
                    <fullName>Kompensation</fullName>
                </value>
                <value>
                    <fullName>Nachlieferung</fullName>
                </value>
                <value>
                    <fullName>Positionsrabatt Natural</fullName>
                </value>
                <value>
                    <fullName>Storno mit Leistungsfluss</fullName>
                </value>
                <value>
                    <fullName>Storno ohne Leistungsfluss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingChange__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__OptimizedValue__c</fullName>
        <description>The new opzimized value.</description>
        <inlineHelpText>The new opzimized value.</inlineHelpText>
        <label>Optimized Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ADvendio__OptimizingVersion__c</fullName>
        <label>Optimizing Version</label>
        <referenceTo>ADvendio__OptimizingVersion__c</referenceTo>
        <relationshipLabel>Optimizing Changes</relationshipLabel>
        <relationshipName>OptimizingChanges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Optimizing Change</label>
    <nameField>
        <label>Optimizing Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__OptimizingVersion__c.object
<CustomObject>
    <label>Optimizing Version</label>
    <nameField>
        <label>Optimization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Optimizing Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_OptimizingChange_Cancel.cls
/*
KV 02453.
Called when the user presses the "X" on the optimization and a cancelled Position is created.
*/
public class Adv_OptimizingChange_Cancel{
    public static void cancelPosition(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate, List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){

        // Get Optimization Version
        Id optiVersionID = (ID)lstNewItems[0].get('ADvendio__OptimizingVersion__c');
        
        // Map CampaignItemID with Map of Fieldname & Optimizing change
        Map<ID, Map<String, ADvendio__OptimizingChange__c>> mapCIOpti = Adv_OptimizingChange_Handler.getCIOptiMap((List<ADvendio__OptimizingChange__c>) lstNewItems);
                
        
        // Get Positions where the "X" was pressed
        Set<ID> setCancelledPositions = new Set<ID>();
        for(ID cID : mapCIOpti.keySet()){
             Map<String, ADvendio__OptimizingChange__c> mapFields = mapCIOpti.get(cID);  
             
             if(mapFields.containsKey('advendio__billingstatus__c'))
                 if(mapFields.get('advendio__billingstatus__c').ADvendio__OptimizedValue__c == 'canceled')
                     setCancelledPositions.add(cID);
        }        


        // For those which are cancelled create a "Storno ohne Leistungsfluss" OC    
        if(!setCancelledPositions.isEmpty()){
        
            List<ADvendio__OptimizingChange__c> listNewOC = new List<ADvendio__OptimizingChange__c>();
            Map<ID, ADvendio__Campaign_Item__c> mapCI = new Map<ID, ADvendio__Campaign_Item__c>([SELECT advendio__rate_discount_4_name__c FROM ADvendio__Campaign_Item__c WHERE ID IN :setCancelledPositions]);                

            for(ID cID : setCancelledPositions)
                listNewOC.add(Adv_OptimizingChange_Handler.createOC(cID, optiVersionID, 'advendio__rate_discount_4_name__c', String.valueOf(mapCI.get(cID).advendio__rate_discount_4_name__c), 'Storno ohne Leistungsfluss'));                     

            insert listNewOC;
        }            
    }
}