src/objects/ADvendio__Campaign_Item__c.object
<CustomObject>
    <label>Campaign Item</label>
    <nameField>
        <label>Campaign Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ADvendio__MediaCampaign__c.object
<CustomObject>
    <fields>
        <fullName>ADvendio__Stage__c</fullName>
        <description>Enter the stage in which the media campaign currently is in.</description>
        <inlineHelpText>Enter the stage in which the media campaign currently is in.</inlineHelpText>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First contact</fullName>
                </value>
                <value>
                    <fullName>Stage 25%</fullName>
                </value>
                <value>
                    <fullName>Offer on Request</fullName>
                </value>
                <value>
                    <fullName>Stage 75%</fullName>
                </value>
                <value>
                    <fullName>Stage 90%</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Offer denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Media Campaign</label>
    <nameField>
        <label>Media Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Adv_MediaCampaign_ValidateStatus_Test.cls
@isTest
public class Adv_MediaCampaign_ValidateStatus_Test{

    public static testMethod void MediaCampaignValidateStatusTest(){

        // Create Objects
        ADvendio__MediaCampaign__c objMC = cls_P7S1_TestData.createTestMediaCampaign(true);
        ADvendio__Campaign_Item__c objCI = cls_P7S1_TestData.createTestCampaignItem(true, objMC);

        // Set Mediacampaign to Closed Won
        objMC.ADvendio__Stage__c = 'Booked';
        update objMC;
    }
    
}