src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Lcm_KanStation__c</fullName>
        <label>Kanban Station</label>
        <picklist>
            <picklistValues>
                <fullName>Backlog_Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FuncSpec</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>TechSpec</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dev</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoLive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lcm_Release__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Sprint, in dem Ticket umgesetzt werden soll</description>
        <inlineHelpText>Sprint, in dem Ticket umgesetzt werden soll</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Lcm_Release__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lcm_Release__c.object
<CustomObject>
    <description>Sprint nach SCRUM-Entwicklungsmethode. Fasst Tickets zusammen, die in einem Sprint umgesetzt werden.
Dient der Termin- und Kapazitätsauslastung von Entwickungen.</description>
    <fields>
        <fullName>Lcm_EndDate__c</fullName>
        <label>Ende</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lcm_StartDate__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Lcm_Kanban_Test.cls
@isTest
public class Lcm_Kanban_Test{
        
    @testSetup
    static void setup() {
        Profile pamProfile = [SELECT ID FROM Profile WHERE Name = 'SomDig_PAM'];
        cls_P7S1_TestData.createTestUser(true, pamProfile);
    }
    
    public static testMethod void testKanban(){
        
        Lcm_Release__c objRelease = createTestRelease(true);
        
        Case objCase = cls_P7S1_TestData.createTestCase(false);
        objCase.Lcm_Release__c = objRelease.ID;
        objCase.Lcm_KanStation__c = 'Dev';
        insert objCase;
        
        objCase.OwnerId = [SELECT ID FROM User WHERE Alias = 'tester' LIMIT 1].Id;
        update objCase;
        
        PageReference pageRef = Page.Lcm_Kanban;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        
        Lcm_Kanban con = new Lcm_Kanban();
        
        // TESTS
        System.assert(con.getReleases().size() > 0 );
        System.assert(con.getStations().size() > 0 );
        System.assert(con.getTickets().size() > 0 );
        System.assert(con.getUsers().size() > 0 );
        System.assert(con.getProjects().size() > 0 );
        
        
        Test.stopTest();
    }
    
    
    // TODO: in TestData auslagern
    private static Lcm_Release__c createTestRelease(Boolean insertObject) {
        Lcm_Release__c release_TestData = new Lcm_Release__c(
            Name = 'KW29',
            Lcm_StartDate__c = Date.today(),
            Lcm_EndDate__c = Date.today()
        );
        if (insertObject) insert release_TestData;
        return release_TestData;
    }
    
}