src/objects/MT_MediaBuildingBlock__c.object
<CustomObject>
    <fields>
        <fullName>MT_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_MediaCampaign_BMV__c</fullName>
        <formula>CASE( MT_Type__c , &quot;TV&quot;,  MT_MediaCampaign_ref__r.MT_BmvTv__c , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Campaign BMV</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MT_SumBMVMonthlyPlan__c</fullName>
        <description>Cumulative Sum of BMV of monthly block plan</description>
        <label>Sum of BMV Monthly Plan</label>
        <summarizedField>MT_MediaBuildingBlockMonthlyPlan__c.MT_SumBMV__c</summarizedField>
        <summaryForeignKey>MT_MediaBuildingBlockMonthlyPlan__c.MT_MediaBuildingBlock_ref__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Media Building Block</label>
    <nameField>
        <label>Media Building Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Building Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_KPI_Controller.cls
/************************************************************************************************************
Name:       MT_KPI_Controller
======================================================
Purpose:    Controller for all MT_KPI vf pages
======================================================
History
-------
Date        AUTHOR                      DETAIL
19.01.2017  Duc Nguyen Tien             Initial architecture & development
15.02.2017  Falco Aulitzky              Updated tvBlock and istBlock to finalize the functionality
*************************************************************************************************************/
public with sharing class MT_KPI_Controller {

  private final sObject mysObject;
  private Schema.SObjectType objType;
  public ContextObjectWrapper context { get; set; }

  public MT_KPI_Controller(ApexPages.StandardController stdController) {
    this.mysObject = (sObject) stdController.getRecord();
    this.objType = this.mysObject.getSobjectType();

    if (this.objType == MT_MediaCampaign__c.SobjectType) {
      context = new MT_KPI_Global_ConsoleComp(this.mysObject);
    }
  }

  public void init(Schema.SobjectType objType) {
  }

  public abstract class ContextObjectWrapper {
    public Map<String, Object> var { get; set; }
    abstract void init();
  }

  public class MT_KPI_Global_ConsoleComp extends ContextObjectWrapper {
    public MT_MediaCampaign__c mCamp;

    public MT_KPI_Global_ConsoleComp(Sobject obj) {
      this.mCamp = (MT_MediaCampaign__c) obj;

      var = new Map<String, Object>();

      init();
    }

    public override void init() {
      load_BMV_TV_SOLL();
      calculatedProgressBar();
    }

    public void load_BMV_TV_SOLL() {
      List<MT_MediaBuildingBlock__c> blocks = new MT_MediaBuildingBlockSelector().getTVRecordsByMediaCampaignIds(new Set<Id>{
        this.mCamp.Id
      }, new Set<String>{
        'MT_MediaCampaign_BMV__c', 'MT_SumBMVMonthlyPlan__c', 'MT_Amount__c'
      });

      MT_MediaBuildingBlock__c tvBlock;

      if (blocks.isEmpty()) {
        tvBlock = new MT_MediaBuildingBlock__c();
      } else {
        tvBlock = blocks.get(0);
      }

      var.put('tvBlock', tvBlock);
    }

    public void calculatedProgressBar() {
      MT_MediaBuildingBlock__c tvBlock = (MT_MediaBuildingBlock__c) var.get('tvBlock');

      Double d = Math.min(tvBlock.MT_SumBMVMonthlyPlan__c == 0 ? 0 : tvBlock.MT_SumBMVMonthlyPlan__c / tvBlock.MT_MediaCampaign_BMV__c, 1);
      var.put('progressBarPercentage', d * 100);
    }
  }
}