src/objects/MT_MediaBuildingBlock__c.object
<CustomObject>
    <fields>
        <fullName>MT_MediaCampaign_ref__c</fullName>
        <label>Media Campaign</label>
        <referenceTo>MT_MediaCampaign__c</referenceTo>
        <relationshipLabel>Media Building Blocks</relationshipLabel>
        <relationshipName>MediaBuildingBlocks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DooH</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Media Building Block</label>
    <nameField>
        <label>Media Building Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Building Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaBuildingBlockMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume of a specific media channel used by a campaign</description>
    <fields>
        <fullName>MT_MediaBuildingBlock_ref__c</fullName>
        <label>Media Building Block</label>
        <referenceTo>MT_MediaBuildingBlock__c</referenceTo>
        <relationshipLabel>Media Building Block Monthly Plans</relationshipLabel>
        <relationshipName>MediaBuildingBlockMonthlyPlans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_PlanningDate__c</fullName>
        <label>Planning Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Building Block Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Building Block Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaFlight__c.object
<CustomObject>
    <description>Track motive distribution within a campaign campaign</description>
    <fields>
        <fullName>MT_MediaBuildingBlockMonthlyPlan_ref__c</fullName>
        <label>Media Building Block Monthly Plan</label>
        <referenceTo>MT_MediaBuildingBlockMonthlyPlan__c</referenceTo>
        <relationshipLabel>Media Flights</relationshipLabel>
        <relationshipName>MediaFlights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_Position__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The position of the flight in the list of all flights for a specific month.</description>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Flight</label>
    <nameField>
        <label>Media Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MT_MediaBuildingBlockMonthlyPlanSelector.cls
/**
* Name:     MT_MediaBuildingBlockMonthlyPlanSelector
* Purpose:  Service class for MT_MediaBuildingBlockMonthlyPlan__c object
*
* History
* -------
* DATE        AUTHOR                      DETAIL
* 17.11.2016  Duc Nguyen Tien             Initial architecture and development
* 16.03.2017  Falco Aulitzky              Added missing functions
* 12.04.2017  Falco Aulitzky              Adding JavaDoc-Styled documentation
*
*/

/* Selector class to fetch data from the database */
public with sharing class MT_MediaBuildingBlockMonthlyPlanSelector extends MT_Selector {
  public static final String objectAPIName = MT_MediaBuildingBlockMonthlyPlan__c.SobjectType.getDescribe().getName();

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaBuildingBlockMonthlyPlan ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaBuildingBlockMonthlyPlan object
  * @returns  List<SObject> a list of MediaBuildingBlockMonthlyPlan objects that are treated and stored as a generic type
  *
  */
  public List<SObject> getRecordsByIds(Set<Id> recordIds, Set<String> fields) {
    if (recordIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where Id in ' + constructInClauseString(recordIds);
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaBuildingBlock ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaBuildingBlockMonthlyPlan object
  * @returns  List<SObject> a list of MediaBuildingBlockMonthlyPlan objects that are treated and stored as a generic type ordered by PlanningDate
  *
  */
  public List<SObject> getRecordsByParentIds(Set<Id> parentIds, Set<String> fields) {
    if (parentIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_MediaBuildingBlock_ref__c in ' + constructInClauseString(parentIds) + ' order by MT_PlanningDate__c asc';
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaTransparencyCampaign ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaBuildingBlockMonthlyPlan object
  * @returns  List<SObject> a list of MediaBuildingBlockMonthlyPlan objects that are treated and stored as a generic type with type TV and a matching MediaTransparencyCampaign id ordered by PlanningDate
  *
  */
  public List<SObject> getTVRecordsByMediaCampaignIds(Set<Id> parentIds, Set<String> fields) {
    if (parentIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(fields) + ' FROM ' + objectAPIName + ' where MT_MediaBuildingBlock_ref__r.MT_Type__c = \'' + MT_Constants.getInstance().MediaBuildingBlock_Type_TV + '\' and MT_MediaBuildingBlock_ref__r.MT_MediaCampaign_ref__c in ' + constructInClauseString(parentIds) + ' order by MT_PlanningDate__c asc';
    return Database.query(query);
  }

  /*
  * Method to fetch data stored in salesforce
  *
  * @param    Set<Id>       recordIds is a set of MediaBuildingBlock ids
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaBuildingBlockMonthlyPlan object
  *           Set<String>   fields is a set of Strings that determines which fields are queried of the MediaFlights object
  * @returns  List<SObject> a list of MediaBuildingBlockMonthlyPlan objects that are treated and stored as a generic type with MediaFlight objects matching MediaBuildingBlock ids ordered by PlanningDate
  *
  */
  public List<SObject> getRecordsWithMediaFlightsByParentIds(Set<Id> parentIds, Set<String> planningFields, Set<String> flightFieds) {
    if (parentIds.isEmpty()) {
      return new List<SObject>();
    }
    String query = 'SELECT ' + constructFieldString(planningFields) + ', ( SELECT ' + constructFieldString(flightFieds) + ' FROM MediaFlights__r order by MT_Position__c asc) FROM ' + objectAPIName + ' where MT_MediaBuildingBlock_ref__c in ' + constructInClauseString(parentIds) + ' order by MT_PlanningDate__c asc';
    return Database.query(query);
  }
}