src/objects/MT_MediaBuildingBlock__c.object
<CustomObject>
    <label>Media Building Block</label>
    <nameField>
        <label>Media Building Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Building Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaBuildingBlockMonthlyPlan__c.object
<CustomObject>
    <description>Track monthly distribution of the volume of a specific media channel used by a campaign</description>
    <fields>
        <fullName>MT_MediaBuildingBlock_ref__c</fullName>
        <label>Media Building Block</label>
        <referenceTo>MT_MediaBuildingBlock__c</referenceTo>
        <relationshipLabel>Media Building Block Monthly Plans</relationshipLabel>
        <relationshipName>MediaBuildingBlockMonthlyPlans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MT_PlanningDate__c</fullName>
        <label>Planning Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Media Building Block Monthly Plan</label>
    <nameField>
        <displayFormat>MBBMPL{00000}</displayFormat>
        <label>Media Building Block Monthly Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Building Block Monthly Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MT_MediaCampaign__c.object
<CustomObject>
    <label>Media Transparency Campaign</label>
    <nameField>
        <label>Kampagnenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media Transparency Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MT_MediaBuildingBlockMonthlyPlans_Test.cls
/************************************************************************************************************
Name:  		MT_MediaBuildingBlockMonthlyPlans_Test
======================================================
Purpose: 	Test class for class MT_MediaBuildingBlockMonthlyPlans, MT_MediaBuildingBlockMonthlyPlanService and MT_MediaBuildingBlockMonthlySelector
======================================================
History
-------
Date		AUTHOR						DETAIL
06.02.2017	Duc Nguyen Tien             Initial development
16.03.2017  Falco Aulitzky				Additional Tests for Service and Selector
*************************************************************************************************************/
@isTest
private class MT_MediaBuildingBlockMonthlyPlans_Test {
  @testSetup static void setup() {
    MT_Test.init();
  }

  @isTest static void constructor() {
    MT_MediaBuildingBlockMonthlyPlans cls = new MT_MediaBuildingBlockMonthlyPlans(new List<MT_mediaBuildingBlockMonthlyPlan__c>());
  }

  @isTest static void createMonthlyPlans() {
    Test.startTest();
    Date today = Date.newInstance(Date.today().Year(), Date.today().Month(), 1);
    Date endDate = today.addMonths(14);
    List<MT_mediaBuildingBlockMonthlyPlan__c> bMonthlyPlans = MT_MediaBuildingBlockMonthlyPlans.createMonthlyPlans(new MT_MediaBuildingBlock__c(), today, endDate);

    system.assertEquals(15, bMonthlyPlans.size());
    Integer i = 0;
    while (today <= endDate) {
      system.assertEquals(today, bMonthlyPlans.get(i).MT_PlanningDate__c);

      today = today.addMonths(1);
      i++;
    }

    Test.stopTest();
  }

  @isTest static void create() {
    Test.startTest();
    MT_MediaBuildingBlockMonthlyPlan__c plan = MT_MediaBuildingBlockMonthlyPlans.create(new MT_MediaBuildingBlock__c(), Date.today());
    system.assertEquals(Date.today(), plan.MT_PlanningDate__c);
    system.assertEquals(null, plan.MT_MediaBuildingBlock_ref__c);
    Test.stopTest();
  }

  testmethod static void getRecordsByIds() {
    MT_MediaBuildingBlockMonthlyPlan__c mbbmp = [SELECT Id FROM MT_MediaBuildingBlockMonthlyPlan__c limit 1];
    System.assertNotEquals(null, mbbmp);

    Test.startTest();

    System.assert(!MT_MediaBuildingBlockMonthlyPlanService.getRecordsByIds(new Set<Id>{
      mbbmp.Id
    }).isEmpty());
    System.assert(MT_MediaBuildingBlockMonthlyPlanService.getRecordsByIds(new Set<Id>()).isEmpty());

    Test.stopTest();
  }

  testmethod static void getMediaBuildingBlockMonthlyPlansByParentIds() {
    MT_MediaBuildingBlock__c mbb = [SELECT Id FROM MT_MediaBuildingBlock__c limit 1];
    System.assertNotEquals(null, mbb);

    Test.startTest();

    System.assert(!MT_MediaBuildingBlockMonthlyPlanService.getMediaBuildingBlockMonthlyPlansByParentIds(new Set<Id>{
      mbb.Id
    }).isEmpty());
    System.assert(MT_MediaBuildingBlockMonthlyPlanService.getMediaBuildingBlockMonthlyPlansByParentIds(new Set<Id>()).isEmpty());
    System.assertEquals(mbb.Id, MT_MediaBuildingBlockMonthlyPlanService.getMediaBuildingBlockMonthlyPlansByParentIds(new Set<Id>{
      mbb.Id
    }).get(0).MT_MediaBuildingBlock_ref__c);

    Test.stopTest();
  }

  testmethod static void getTVRecordsByMediaCampaignIds() {
    MT_MediaCampaign__c mc = [SELECT Id FROM MT_MediaCampaign__c limit 1];
    System.assertNotEquals(null, mc);

    Test.startTest();

    System.assert(!MT_MediaBuildingBlockMonthlyPlanService.getTVRecordsByMediaCampaignIds(new Set<Id>{
      mc.Id
    }).isEmpty());
    System.assert(MT_MediaBuildingBlockMonthlyPlanService.getTVRecordsByMediaCampaignIds(new Set<Id>()).isEmpty());

    Test.stopTest();
  }

  testmethod static void getMediaBuildingBlockMonthlyPlansWithMediaFlightsByParentIds() {
    MT_MediaBuildingBlock__c mbb = [SELECT Id FROM MT_MediaBuildingBlock__c limit 1];
    System.assertNotEquals(null, mbb);

    Test.startTest();

    System.assert(!MT_MediaBuildingBlockMonthlyPlanService.getMediaBuildingBlockMonthlyPlansWithMediaFlightsByParentIds(new Set<Id>{
      mbb.Id
    }).isEmpty());
    System.assert(MT_MediaBuildingBlockMonthlyPlanService.getMediaBuildingBlockMonthlyPlansWithMediaFlightsByParentIds(new Set<Id>()).isEmpty());
    System.assertEquals(mbb.Id, MT_MediaBuildingBlockMonthlyPlanService.getMediaBuildingBlockMonthlyPlansWithMediaFlightsByParentIds(new Set<Id>{
      mbb.Id
    }).get(0).MT_MediaBuildingBlock_ref__c);

    Test.stopTest();
  }
}