src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ven_EffectiveYield__c</fullName>
        <label>Effective Yield</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_SOMLikelihood__c</fullName>
        <description>Hilfsfeld zur Berechnung des Equity/Cash Ratio</description>
        <formula>IF ((Probability = 0 || Ven_Likelihood__c = 0) , 0 , Ven_Likelihood__c/Probability )</formula>
        <inlineHelpText>Hilfsfeld zur Berechnung des Equity/Cash Ratio</inlineHelpText>
        <label>SOM Likelihood</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_TotalGmvCurrentYear__c</fullName>
        <label>Total GMV current Year (Full Pot)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_TotalGmvNextYear__c</fullName>
        <label>Total GMV Next Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ven_OppPipeline__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_Month__c</fullName>
        <label>Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ven_Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Pipeline</label>
    <nameField>
        <label>Opportunity Pipeline-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Pipelines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_SomLikelihood__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Ven_Apr__c</fullName>
        <label>4 Apr</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Aug__c</fullName>
        <label>8 Aug</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Dec__c</fullName>
        <label>12 Dec</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Feb__c</fullName>
        <label>2 Feb</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Jan__c</fullName>
        <label>1 Jan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Jul__c</fullName>
        <label>7 Jul</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Jun__c</fullName>
        <label>6 Jun</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Mar__c</fullName>
        <label>3 Mar</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Max__c</fullName>
        <label>Max</label>
        <precision>18</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_May__c</fullName>
        <label>5 May</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Min__c</fullName>
        <label>Min</label>
        <precision>18</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Nov__c</fullName>
        <label>11 Nov</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Oct__c</fullName>
        <label>10 Oct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_Sep__c</fullName>
        <label>9 Sep</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>SOM Likelihood</label>
</CustomObject>

src/classes/Ven_OppPipeline_CmpCtrl_Test.cls
/**
* ===================================================================
* (c) factory42 GmbH 2015, Germany, All rights reserved
* Ven_OppPipeline_CmpCtrl_Test
* @author       MS factory42 GmbH
* @email        mschmit@factory42.com
* @version      V0.1
* @date         2015/11/17
* @description
* @lastchange
* @objects
* =================================================================
*/
@isTest
public without sharing class Ven_OppPipeline_CmpCtrl_Test {

    @isTest
    private static void test_IncreaseCoverage(){
        Test.startTest();
        //******************************************************

        Ven_OppPipeline_CmpCtrl ctrl = new Ven_OppPipeline_CmpCtrl();
        ctrl.redirect();

        //Opportunity
        Opportunity opp = cls_P7S1_TestData.createTestOpportunity(true);

        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        Ven_OppPipeline_CmpCtrl ctrl2 = new Ven_OppPipeline_CmpCtrl(sc);

        //******************************************************
        Test.stopTest();
    }


    @isTest
    private static void test_insertOppPipeDetail(){

        Test.startTest();
        //******************************************************

        //General Data
        Integer year = System.now().year();
        buildSomLikelihoodCustomSetting();

        //Opportunity
        Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Ventures Default').getRecordTypeId();
        Opportunity opp = cls_P7S1_TestData.createTestOpportunity(false);
        opp.RecordTypeId = recTypeId;
        opp.Ven_EffectiveYield__c = 20;
        insert opp;

        //Check Save
        Ven_OppPipeline_CmpCtrl.saveOppPipeDetail(opp, buildOppPipeList(year));
        system.assertEquals(24, [SELECT Id FROM Ven_OppPipeline__c].size());

        Opportunity oppNew = [SELECT Id, Ven_TotalGmvCurrentYear__c, Ven_TotalGmvNextYear__c FROM Opportunity LIMIT 1][0];
        List<Ven_OppPipeline__c> oppPipesNew = [SELECT Id, Name, Ven_Amount__c, Ven_Year__c, Ven_Month__c FROM Ven_OppPipeline__c];

        system.assertEquals(12, oppNew.Ven_TotalGmvCurrentYear__c, 'total gmv current year has been set correctly');
        system.assertEquals(12, oppNew.Ven_TotalGmvNextYear__c, 'total gmv next year has been set correctly');

        //Check Update
        for(Ven_OppPipeline__c op : oppPipesNew){
            op.Ven_Amount__c    = 2;
        }

        Ven_OppPipeline_CmpCtrl.saveOppPipeDetail(opp, oppPipesNew);

        oppNew = [SELECT Id, Ven_TotalGmvCurrentYear__c, Ven_TotalGmvNextYear__c FROM Opportunity LIMIT 1][0];

        system.assertEquals(24, oppNew.Ven_TotalGmvCurrentYear__c, 'total gmv current year has been set correctly');
        system.assertEquals(24, oppNew.Ven_TotalGmvNextYear__c, 'total gmv next year has been set correctly');

        //Check Save Opportunities
        oppNew.Probability = 66;
        Ven_OppPipeline_CmpCtrl.saveOpps(new List<Opportunity>{oppNew});

        system.assertEquals(66, [SELECT Probability FROM Opportunity].Probability);

        //Check delete
        Ven_OppPipeline_CmpCtrl.deleteOppPipeDetail(oppNew.Id);
        system.assertEquals(0, [SELECT Id FROM Opportunity].size());

        //******************************************************
        Test.stopTest();
    }

    @isTest
    private static void test_LoadOppData(){

        Test.startTest();
        //******************************************************

        //General Data
        Integer year = System.now().year();
        buildSomLikelihoodCustomSetting();

        //Opportunity
        Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Ventures Default').getRecordTypeId();
        Opportunity opp = cls_P7S1_TestData.createTestOpportunity(false);
        opp.RecordTypeId = recTypeId;
        opp.Ven_EffectiveYield__c = 20;
        insert opp;

        //Teammember
        OpportunityTeamMember otm = new OpportunityTeamMember(OpportunityId = opp.Id, TeamMemberRole = 'Test', UserId = UserInfo.getUserId());

        //Create Ven_OppPipeline__c
        Ven_OppPipeline_CmpCtrl.saveOppPipeDetail(opp, buildOppPipeList(year));
        system.assertEquals(24, [SELECT Id FROM Ven_OppPipeline__c].size());

        Ven_OppPipeline_CmpCtrl.OppPipeData oppPipeData = Ven_OppPipeline_CmpCtrl.getOppPipeData();
        system.assertEquals(1, oppPipeData.summaryItems.size());

        //Get OppPipeDetail
        Ven_OppPipeline_CmpCtrl.OppPipeDetail oppPipeDetail = Ven_OppPipeline_CmpCtrl.getOppPipeDetail(opp);
        system.assertEquals(12, oppPipeDetail.currentYear.oppPipeMonths.size());

        //Get Export Data
        List<Ven_OppPipeline_CmpCtrl.ExportData> lstExData = Ven_OppPipeline_CmpCtrl.getExportData(true);
        system.assertEquals(1, lstExData.size());

        //******************************************************
        Test.stopTest();
    }


    /*****************
    *
    *****************/
    private static List<Ven_OppPipeline__c> buildOppPipeList(Integer year){

        List<Ven_OppPipeline__c> lstOppPipeline = new List<Ven_OppPipeline__c>();

        for(Integer i=1; i <= 12; i++){
            lstOppPipeline.add(new Ven_OppPipeline__c(Name = 'Test', Ven_Amount__c = 1, Ven_Year__c = year, Ven_Month__c = i));
            lstOppPipeline.add(new Ven_OppPipeline__c(Name = 'Test', Ven_Amount__c = 1, Ven_Year__c = (year+1), Ven_Month__c = i));
        }

        return lstOppPipeline;
    }

    /*****************
    *
    *****************/
    private static void buildSomLikelihoodCustomSetting(){
        Ven_SomLikelihood__c somLikelihood = new Ven_SomLikelihood__c(  Name = 'test',
                                                                        Ven_Min__c = 0,
                                                                        Ven_Max__c = 200,
                                                                        Ven_Jan__c = 1,
                                                                        Ven_Feb__c = 1,
                                                                        Ven_Mar__c = 1,
                                                                        Ven_Apr__c = 1,
                                                                        Ven_May__c = 1,
                                                                        Ven_Jun__c = 1,
                                                                        Ven_Jul__c = 1,
                                                                        Ven_Aug__c = 1,
                                                                        Ven_Sep__c = 1,
                                                                        Ven_Oct__c = 1,
                                                                        Ven_Nov__c = 1,
                                                                        Ven_Dec__c = 1);

        insert somLikelihood;
    }
}