src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Ven_EffectiveYield__c</fullName>
        <label>Effective Yield</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ven_NetPotentialCurrentYear__c</fullName>
        <label>Net Potential Current Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_NetPotentialNextYear__c</fullName>
        <label>Net Potential Next Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_TotalCashCurrentYear__c</fullName>
        <label>Total Cash Current Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_TotalCashNextYear__c</fullName>
        <label>Total Cash Next Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_TotalGmvCurrentYear__c</fullName>
        <label>Total GMV current Year (Full Pot)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_TotalGmvNextYear__c</fullName>
        <label>Total GMV Next Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ven_OppPipeline__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_Cash__c</fullName>
        <formula>Ven_Opp__r.Ven_EffectiveYield__c * Ven_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cash</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ven_Month__c</fullName>
        <label>Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ven_Opp__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Pipelines</relationshipLabel>
        <relationshipName>Opportunity_Pipelines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Pipeline</label>
    <nameField>
        <label>Opportunity Pipeline-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Pipelines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Ven_Opportunity_PipelineHandler.cls
public with sharing class Ven_Opportunity_PipelineHandler extends TriggerController{
    /**
    * @Methodname   Ven_Opportunity_PipelineHandler
    * @description  Constructor
    * @param        Trigger based values
    * @return       -
    */
    public Ven_Opportunity_PipelineHandler(Boolean isAfter, Boolean isBefore,
        Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
        List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems){
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }

    /**
    * @Methodname       runBeforeUpdate
    * @description
    * @param            -
    * @return           void
    */
    protected override void runBeforeUpdate() {
        // VVR: 05.11.2015: Unterscheidung für VEN RecordTypes
        try{
            updateTotalValues(lstNewItems);
        }
        catch(Exception e){}
    }


    /**
    * @Methodname       updateTotalValues
    * @description
    * @param            List<sObject>
    * @return           void
    */
    static void updateTotalValues(List<sObject> lstNewItems){

        Map<Id, Opportunity> oppId2Opp                  = buildOppId2Opp(lstNewItems);

        Map<Id, Decimal> oppId2TotalGmvCurrentYear      = new Map<Id, Decimal>();
        Map<Id, Decimal> oppId2TotalCashCurrentYear     = new Map<Id, Decimal>();
        Map<Id, Decimal> oppId2TotalGmvNextYear         = new Map<Id, Decimal>();
        Map<Id, Decimal> oppId2TotalCashNextYear        = new Map<Id, Decimal>();
        Map<String, Map<Integer,Decimal>> mapOppYear2Pipes = new Map<String, Map<Integer, Decimal>>();

        buildTotalMaps(oppId2Opp.keySet(), oppId2TotalGmvCurrentYear, oppId2TotalCashCurrentYear, oppId2TotalGmvNextYear, oppId2TotalCashNextYear, mapOppYear2Pipes);

        for(Id oppId : oppId2Opp.keySet()){

            Opportunity opp = oppId2Opp.get(oppId);
            
            if(oppId2TotalGmvCurrentYear.containsKey(oppId)){
            	opp.Ven_TotalGmvCurrentYear__c = oppId2TotalGmvCurrentYear.get(oppId).round(System.roundingMode.CEILING);
            }else{
            	opp.Ven_TotalGmvCurrentYear__c = 0;
            }
            
            if(oppId2TotalCashCurrentYear.containsKey(oppId)){
            	opp.Ven_TotalCashCurrentYear__c = oppId2TotalCashCurrentYear.get(oppId).round(System.roundingMode.CEILING);
            }else{
            	opp.Ven_TotalCashCurrentYear__c = 0;
            }

            if(oppId2TotalGmvNextYear.containsKey(oppId)){
            	opp.Ven_TotalGmvNextYear__c = oppId2TotalGmvNextYear.get(oppId).round(System.roundingMode.CEILING);
            }else{
            	opp.Ven_TotalGmvNextYear__c = 0;
            }
            
            if(oppId2TotalCashNextYear.containsKey(oppId)){
            	opp.Ven_TotalCashNextYear__c = oppId2TotalCashNextYear.get(oppId).round(System.roundingMode.CEILING);
            }else{
            	opp.Ven_TotalCashNextYear__c = 0;
            }

            //**** New BS 29.08.2016 *** Needed for calculation of Ven_NetPotentialCurrentYear__c
            Map<Integer, Decimal> mapMonths2Likelihood = Ven_Utility.getSomLikelihoodByEffYield(opp.Ven_EffectiveYield__c);
            Decimal somLikelihoodThisYear = calcSomLikelihood(mapMonths2Likelihood, mapOppYear2Pipes.get(oppId + '#+#' + Date.today().year()));
            Decimal somLikelihoodNextYear = calcSomLikelihood(mapMonths2Likelihood, mapOppYear2Pipes.get(oppId + '#+#' + (Date.today().year()+1)));

            opp.Ven_NetPotentialCurrentYear__c = ((opp.Ven_EffectiveYield__c/100) * (opp.Probability/100) * somLikelihoodThisYear).round(System.roundingMode.CEILING);
            opp.Ven_NetPotentialNextYear__c = ((opp.Ven_EffectiveYield__c/100)* (opp.Probability/100) * somLikelihoodNextYear).round(System.roundingMode.CEILING);

            /*** OLD BS 29.08.2016 ***
            opp.Ven_NetPotentialCurrentYear__c  = (opp.Ven_TotalGmvCurrentYear__c * (opp.Ven_EffectiveYield__c/100) * (somLikelihood/100) * (opp.Probability/100)).round(System.roundingMode.CEILING);
            opp.Ven_NetPotentialNextYear__c     = (opp.Ven_TotalGmvNextYear__c * (opp.Ven_EffectiveYield__c/100) * (somLikelihood/100) * (opp.Probability/100)).round(System.roundingMode.CEILING);
            ***/
        }
    }

    //**** New BS 29.08.2016 *** Needed for calculation of Ven_NetPotentialCurrentYear__c
    static Decimal calcSomLikelihood(Map<Integer, Decimal> mapMonths2Likelihood, Map<Integer, Decimal> mapMonths2Amounts){
        Decimal somLikelihood = 0;

        if(mapMonths2Likelihood != null && mapMonths2Amounts != null){
            for(Integer i : mapMonths2Likelihood.keySet()){
                if(mapMonths2Amounts.containsKey(i) && mapMonths2Amounts.get(i) != null){
                    somLikelihood += (mapMonths2Likelihood.get(i) / 100) * mapMonths2Amounts.get(i);
                }
            }
        }
        return somLikelihood;
    }

    static Map<Id, Opportunity> buildOppId2Opp(List<sObject> lstNewItems){
        Map<Id, Opportunity> oppId2Opp = new Map<Id, Opportunity>();

        for(sObject obj : lstNewItems){
            Opportunity opp = (Opportunity) obj;
            oppId2Opp.put(opp.Id, opp);
        }

        return oppId2Opp;
    }

    static void buildTotalMaps(Set<Id> oppIds, Map<Id, Decimal> oppId2TotalGmvCurrentYear, Map<Id, Decimal> oppId2TotalCashCurrentYear, Map<Id, Decimal> oppId2TotalGmvNextYear, Map<Id, Decimal> oppId2TotalCashNextYear,
                               Map<String, Map<Integer, Decimal>> mapOppYear2Pipes){

        Decimal thisYear = Date.today().year();
        Decimal nextYear = thisYear+1;

        for(AggregateResult ar : [  SELECT Ven_Opp__c oppId, SUM(Ven_Amount__c) totalGmv, SUM(Ven_Cash__c) totalCash
                                    FROM Ven_OppPipeline__c
                                    WHERE Ven_Opp__c IN :oppIds AND Ven_Year__c = :thisYear
                                    GROUP BY Ven_Opp__c]){

            oppId2TotalGmvCurrentYear.put((Id) ar.get('oppId'), (Decimal) ar.get('totalGmv'));
            oppId2TotalCashCurrentYear.put((Id) ar.get('oppId'), (Decimal) ar.get('totalCash'));
        }

        for(AggregateResult ar : [  SELECT Ven_Opp__c oppId, SUM(Ven_Amount__c) totalGmv, SUM(Ven_Cash__c) totalCash
                                    FROM Ven_OppPipeline__c
                                    WHERE Ven_Opp__c IN :oppIds AND Ven_Year__c = :nextYear
                                    GROUP BY Ven_Opp__c]){

            oppId2TotalGmvNextYear.put((Id) ar.get('oppId'), (Decimal) ar.get('totalGmv'));
            oppId2TotalCashNextYear.put((Id) ar.get('oppId'), (Decimal) ar.get('totalCash'));
        }

        //**** New BS 29.08.2016 *** Needed for calculation of Ven_NetPotentialCurrentYear__c
        for(Ven_OppPipeline__c op : [SELECT Ven_Opp__c, Ven_Year__c, Ven_Month__c, Ven_Amount__c, Ven_Cash__c
                                                        FROM Ven_OppPipeline__c
                                                        WHERE Ven_Opp__c IN :oppIds AND (Ven_Year__c = :thisYear OR Ven_Year__c = :nextYear)
                                                        ORDER BY Ven_Opp__c, Ven_Year__c]){

            String key = op.Ven_Opp__c + '#+#' + op.Ven_Year__c;
            if(mapOppYear2Pipes.containsKey(key)){
                Map<Integer, Decimal> mapMonths2Amounts = mapOppYear2Pipes.get(key);
                mapMonths2Amounts.put((Integer) op.Ven_Month__c, op.Ven_Amount__c);
                mapOppYear2Pipes.put(key, mapMonths2Amounts);
            }else{
                mapOppYear2Pipes.put(key, new Map<Integer, Decimal>{(Integer) op.Ven_Month__c => op.Ven_Amount__c});
            }
        }
    }
}