src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MN1__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Befüllt durch die Schnittstelle zu ProDia - betrifft alle Geschäftsarten</description>
        <inlineHelpText>Befüllt durch die Schnittstelle zu ProDia - betrifft alle Geschäftsarten</inlineHelpText>
        <label>MN1 Auftrag Gesamt</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_EmailRecipients__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>P7S1_Location__c</fullName>
        <description>Generic &quot;location&quot; where the defined email addresses are used (e.g. a class).</description>
        <inlineHelpText>Generic &quot;location&quot; where the defined email addresses are used (e.g. a class).</inlineHelpText>
        <label>Location</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Recipients__c</fullName>
        <description>Email-adresses, separated by semi-colon</description>
        <inlineHelpText>Email-adresses, separated by semi-colon</inlineHelpText>
        <label>P7S1 Recipients</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Recipients</label>
</CustomObject>

src/objects/P7S1_Rollup__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beschreibung__c</fullName>
        <label>Beschreibung</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChildCalculationField__c</fullName>
        <label>Child Calculation Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChildObject__c</fullName>
        <label>ChildObject</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_BatchFilter__c</fullName>
        <label>Batch Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_BatchResult__c</fullName>
        <label>Batch Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObject__c</fullName>
        <label>Parent Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentResultField__c</fullName>
        <label>Parent Result Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipField__c</fullName>
        <description>Field on the child object which is referencing to the parent</description>
        <label>Relationship Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Count</fullName>
                </value>
                <value>
                    <fullName>Sum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WhereCondition__c</fullName>
        <label>WHERE-Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rollup</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Rollup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rollup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/P7S1_RollUpValidator_Test.cls
@isTest
public class P7S1_RollUpValidator_Test {

    @TestSetup
    public static void setUpDate()
    {   
        Account acc = cls_P7S1_TestData.createTestAccount(true);
        Opportunity opp = cls_P7S1_TestData.createTestOpportunity(true, acc);
        OpportunityLineItem oli = cls_P7S1_TestData.createTestOpportunityLineItem(true, opp);
        insert new P7S1_EmailRecipients__c(Name = 'P7S1 RollUpValidator', P7S1_Location__c = 'P7S1_RollUpValidator_Test', P7S1_Recipients__c = 'max@example.de;john@example.com');
    }
    
    
    @isTest
    public static void testDataStructure()
    {
        Test.startTest();
        List<OpportunityLineItem> olis = [SELECT Id, OpportunityId FROM OpportunityLineItem];
        List<Opportunity> opps = [SELECT Id, AccountId FROM Opportunity];
        List<Account> accs = [SELECT Id FROM Account];
        Test.stopTest();
        system.assertEquals(opps[0].id, olis[0].opportunityId);
        system.assertEquals(accs[0].id, opps[0].accountId);
    }
    
    @isTest
    public static void testValidRecord()
    {
        P7S1_Rollup__c validRollup = createTestRollUp(true);
        
        Test.startTest();
        P7S1_RollUpValidator.performAction();
        Integer invocations = System.Limits.getEmailInvocations();
        Test.stopTest();
        system.assertEquals(0, invocations);
    }
    
    @isTest
    public static void testInvalidParentObjectRollup()
    {
        P7S1_Rollup__c validRollup = createTestRollUp(false);
        validRollup.ParentObject__c = 'Totalrice';
        insert validRollup;
        
        Test.startTest();
        P7S1_RollUpValidator.performAction();
        Integer invocations = System.Limits.getEmailInvocations();
        Test.stopTest();
        system.assertEquals(1, invocations);
    }

    @isTest
    public static void testInvalidParentResultFieldRollup()
    {
        P7S1_Rollup__c validRollup = createTestRollUp(false);
        validRollup.ParentResultField__c = 'Totalrice';
        insert validRollup;
        
        Test.startTest();
        P7S1_RollUpValidator.performAction();
        Integer invocations = System.Limits.getEmailInvocations();
        Test.stopTest();
        system.assertEquals(1, invocations);
    }

    @isTest
    public static void testInvalidChildCalculationFieldRollup()
    {
        P7S1_Rollup__c validRollup = createTestRollUp(false);
        validRollup.ChildCalculationField__c = 'Totalrice';
        insert validRollup;
        
        Test.startTest();
        P7S1_RollUpValidator.performAction();
        Integer invocations = System.Limits.getEmailInvocations();
        Test.stopTest();
        system.assertEquals(1, invocations);
    }

    @isTest
    public static void testInvalidChildObjectRollup()
    {
        P7S1_Rollup__c validRollup = createTestRollUp(false);
        validRollup.ChildObject__c  = 'Totalrice';
        insert validRollup;
        
        Test.startTest();
        P7S1_RollUpValidator.performAction();
        Integer invocations = System.Limits.getEmailInvocations();
        Test.stopTest();
        system.assertEquals(1, invocations);
    }
    
    //TODO: Auslagern
    public static P7S1_Rollup__c createTestRollUp(Boolean insertObject)
    {
        P7S1_Rollup__c validRollup = new P7S1_Rollup__c();
        validRollup.CurrencyIsoCode = 'EUR';
        validRollup.Active__c = true;
        validRollup.Beschreibung__c = '';
        validRollup.ChildCalculationField__c = 'Totalprice';
        validRollup.ChildObject__c = 'OpportunityLineItem';
        validRollup.ParentObject__c = 'Opportunity';
        validRollup.ParentResultField__c = 'MN1__c';
        validRollup.RelationshipField__c = 'OpportunityId';
        validRollup.Type__c = '';
        validRollup.WhereCondition__c = '';
        validRollup.P7S1_BatchFilter__c = '';
        validRollup.P7S1_BatchResult__c = '';
        if(insertObject) insert validRollup;
        return validRollup;
    }
}