src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>P7S1_CurrentOwnerEmail__c</fullName>
        <description>Hilfsfeld für Workflow</description>
        <formula>Owner.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hilfsfeld für Workflow</inlineHelpText>
        <label>E-Mail-Aktueller-Benutzer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_NewOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>neuer Inhaber der Opportunity, wird beim Speichern als Inhaber übernommen und geleert.</description>
        <inlineHelpText>neuer Inhaber der Opportunity, wird beim Speichern als Inhaber übernommen und geleert.</inlineHelpText>
        <label>Neuer Inhaber</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_OldOwnerEmail__c</fullName>
        <description>E-Mail des alten Inhabers. Hilfsfeld für Versand der Inhaber-Änderungs-Mail</description>
        <inlineHelpText>E-Mail des alten Inhabers. Hilfsfeld für Versand der Inhaber-Änderungs-Mail</inlineHelpText>
        <label>Alter Inhaber (E-Mail)</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/cls_P7S1_Opportunity_NewOwner.cls
public with sharing class cls_P7S1_Opportunity_NewOwner extends TriggerController {


	public cls_P7S1_Opportunity_NewOwner(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
		List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems)
	{
		super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
	}

	// before Update
	protected override void runBeforeUpdate() {
		SetNewOwner((List<Opportunity>) lstNewItems, (Map<Id, Opportunity>) mapOldItems);
	}

	private void SetNewOwner(List<Opportunity> p_oListNew, Map<Id, Opportunity> p_oMapOld) {
		for (Opportunity l_oNewOpp : p_oListNew) {

			if (l_oNewOpp.P7S1_NewOwner__c != null) {
				l_oNewOpp.Ownerid = l_oNewOpp.P7S1_NewOwner__c;
				l_oNewOpp.P7S1_NewOwner__c = null;
			}
			l_oNewOpp.P7S1_OldOwnerEmail__c = l_oNewOpp.P7S1_CurrentOwnerEmail__c;
		}
	}
}