src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SomTv_Jahr__c</fullName>
        <label>Jahr</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                    <default>true</default>
                    <label>2017</label>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/P7S1_EmailRecipients__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>P7S1_Location__c</fullName>
        <description>Generic &quot;location&quot; where the defined email addresses are used (e.g. a class).</description>
        <inlineHelpText>Generic &quot;location&quot; where the defined email addresses are used (e.g. a class).</inlineHelpText>
        <label>Location</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Recipients__c</fullName>
        <description>Email-adresses, separated by semi-colon</description>
        <inlineHelpText>Email-adresses, separated by semi-colon</inlineHelpText>
        <label>P7S1 Recipients</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Recipients</label>
</CustomObject>

src/objects/SomDig_IaNummer__c.object
<CustomObject>
    <description>Zuordnung von Innenauftragsnumer (IA) zu den ausschlaggebenden Objekten zur Erstellung der Erlösaufteilung (EA) und Hochrechnung für den Fastclose notwendig</description>
    <fields>
        <fullName>SomDig_BeschreibungCO__c</fullName>
        <description>Wie wird diese IA Nummer von Controlling benannt?</description>
        <inlineHelpText>Wie wird diese IA Nummer von Controlling benannt?</inlineHelpText>
        <label>Beschreibung CO</label>
        <length>56</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Mediagattung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Mediagattung</label>
        <referenceTo>SomDig_Mediagattung__c</referenceTo>
        <relationshipLabel>IA Nummer</relationshipLabel>
        <relationshipName>IA_Nummer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsDifferenzierung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Mediagattungs-Differenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipLabel>IA Nummer</relationshipLabel>
        <relationshipName>IA_Nummer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_MediagattungsSegment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Mediagattungs-Segment</label>
        <referenceTo>SomDig_MediagattungsSegment__c</referenceTo>
        <relationshipLabel>IA Nummer</relationshipLabel>
        <relationshipName>IA_Nummer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Werbetraergergruppierung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Werbeträger Gruppierung sind vormals als Marke bekannt und fassen mehrere Werbeträger zusammen, Grundlage für die Zuordnung von IA Nummern und Werbeträgern. 
Möglichkeit Werbeträger zu gruppieren um Marken abzubilden. 
Beispiel Werbeträger Sixx besteht aus vielen kleinen Seiten bzw. Werbeträgern, diese werden unter der Marke Sixx zusammengefasst.</description>
        <inlineHelpText>Werbeträger Gruppierung sind vormals als Marke bekannt und fassen mehrere Werbeträger zusammen,Grundlage für die Zuordnung von IA Nummern &amp; Werbeträgern. 
Möglichkeit Werbeträger zu gruppieren um Marken abzubilden.</inlineHelpText>
        <label>Werbeträgergruppierung</label>
        <referenceTo>SomDig_Werbetraegergruppierung__c</referenceTo>
        <relationshipLabel>IA Nummern</relationshipLabel>
        <relationshipName>IA_Nummern</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>IA Nummer</label>
    <nameField>
        <label>IA Nummer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Nummern</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Mediagattung__c.object
<CustomObject>
    <description>Die erste Klassifizierung/Zuordnung des Werbeträgers zu einer Mediagattung (TV/Digital/Text)</description>
    <label>Mediagattung</label>
    <nameField>
        <label>Mediagattung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsDifferenzierung__c.object
<CustomObject>
    <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
    <label>Mediagattungs-Differenzierung</label>
    <nameField>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Differenzierungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsSegment__c.object
<CustomObject>
    <description>Zwischendifferenzierung/Segmentierung einer Belegungseinheit</description>
    <label>Mediagattungs-Segment</label>
    <nameField>
        <label>Mediagattungs-Segment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Segmente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_Werbetraegergruppierung__c.object
<CustomObject>
    <description>Werbeträger Gruppierung sind vormals als Marke bekannt und fassen mehrere Werbeträger zusammen, Grundlage für die Zuordnung von IA Nummern und Werbeträgern.
Dient der Sicherstellung von Konsistenz innerhalb des Buchungstools.</description>
    <label>Werbeträgergruppierung</label>
    <nameField>
        <label>Werbeträgergruppierung-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Werbeträgergruppierungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cls_P7S1_Temp_TestData.cls
/**
 * @Description this class will be a container for createTest methods as lpong as the Original data generator class is not changable (cls_P7S1_TestData)
**/


public without sharing class cls_P7S1_Temp_TestData
{
	
	public static final String nameOfAWonStage = [SELECT Masterlabel FROM OpportunityStage WHERE isWon=true].get(0).MasterLabel;

	public static Opportunity createTestOpportunity(Boolean insertObject, Account account, RecordType recordtype)
	{
		Opportunity result = cls_P7S1_TestData.createTestOpportunity(false, account, recordtype);
		result.SomTv_Jahr__c=String.valueOf(Date.today().year());
        result.CloseDate=System.today();
        result.Amount = 1000;
        result.Name='Test Opportunity';
		return result;

	}

      public static P7S1_EmailRecipients__c createTestRecipient(Boolean insertObject, String location, String recipients)
    {
        P7S1_EmailRecipients__c result = new P7S1_EmailRecipients__c();
        result.Name = location;
        result.P7S1_Location__c = location;
        result.P7S1_Recipients__c = recipients;
        if(insertObject)
            insert result;
        return result;
    }

    public static SomDig_Werbetraegergruppierung__c createTestWerbetraegerGruppierung(Boolean insertObject)
    {
        SomDig_Werbetraegergruppierung__c result = new SomDig_Werbetraegergruppierung__c();
        if(insertObject)
            insert result;
        return result;
    }

    public static SomDig_IaNummer__c createTestIaNummer(Boolean insertObject, SomDig_Werbetraegergruppierung__c werbetraegergruppierung, SomDig_Mediagattung__c medienGattung, SomDig_MediagattungsSegment__c mediaGattungsSegment, SomDig_MediagattungsDifferenzierung__c mediaGattungsDifferenzierung)
    {
        SomDig_IaNummer__c result = new SomDig_IaNummer__c();
        result.SomDig_Werbetraergergruppierung__c = werbetraegergruppierung.id;
        result.SomDig_Mediagattung__c = medienGattung.Id;
        result.SomDig_MediagattungsSegment__c = mediaGattungsSegment.Id;
        result.SomDig_MediagattungsDifferenzierung__c = mediaGattungsDifferenzierung.Id;

        result.SomDig_BeschreibungCO__c = 'Test IA Nummer 1';

        if(insertObject)
            insert result;
        return result;
    }

    
}