src/objects/P7S1_Abonnement__c.object
<CustomObject>
    <description>Newsletter Abonnements für Portaluser und Kontakte</description>
    <fields>
        <fullName>P7S1_Newsletter__c</fullName>
        <description>Abonnement für Newsletter</description>
        <inlineHelpText>Abonnement für Newsletter</inlineHelpText>
        <label>Newsletter</label>
        <referenceTo>P7S1_Newsletter__c</referenceTo>
        <relationshipLabel>Abonnements</relationshipLabel>
        <relationshipName>Abonnements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>P7S1_PortalLogin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Abonnement durch Benutzer des Portals</description>
        <inlineHelpText>Abonnement durch Benutzer des Portals</inlineHelpText>
        <label>Portal Benutzer</label>
        <referenceTo>P7S1_PortalLogin__c</referenceTo>
        <relationshipLabel>Abonnements</relationshipLabel>
        <relationshipName>Abonnements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Abonnement</label>
    <nameField>
        <displayFormat>NL-Abo-{000000}</displayFormat>
        <label>Abonnement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abonnements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_Newsletter__c.object
<CustomObject>
    <label>Newsletter</label>
    <nameField>
        <label>Newsletter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Newsletters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_PortalLogin__c.object
<CustomObject>
    <description>Informationen zur Verwaltung von Zugängen zu Portalen wie sevenonemedia.de und adfactory.de</description>
    <fields>
        <fullName>P7S1_Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <label>Portal Login</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Portal Login</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_PortalLoginEvent__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_PortalLogin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Login</label>
        <referenceTo>P7S1_PortalLogin__c</referenceTo>
        <relationshipLabel>Portal Login Events</relationshipLabel>
        <relationshipName>Portal_Login_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Login Event</label>
    <nameField>
        <displayFormat>evt-log-{0}</displayFormat>
        <label>P7S1_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Login Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_Newsletter_NewsletterServcie.cls
/**
* Interface thats describes the methods for handling newsletter operations
* newsletter operations
*
* @author  Sebastian Listl
* @version 0.1, 2016-02-15
*/
public interface P7S1_Newsletter_NewsletterServcie {
	
	P7S1_Newsletter__c getStandardNewsletter(P7S1_PortalLogin__c portalLogin);
  	P7S1_Abonnement__c createOrGetNewsletterAbo(P7S1_PortalLogin__c portalLogin);
  	P7S1_Abonnement__c createNewNewsletterAbo(P7S1_PortalLogin__c portalLogin);
	Boolean subscribe(P7S1_Abonnement__c abo);
  	Boolean unsubscribe(P7S1_Abonnement__c abo);
  	P7S1_PortalLoginEvent__c sendNewsletterSubscribeEmail(P7S1_PortalLogin__c portalLogin);
  	
}