src/objects/P7S1_Abonnement__c.object
<CustomObject>
    <description>Newsletter Abonnements für Portaluser und Kontakte</description>
    <fields>
        <fullName>P7S1_AbgeschlossenAm__c</fullName>
        <description>Beginn des Abonnements</description>
        <inlineHelpText>Beginn des Abonnements</inlineHelpText>
        <label>Abgeschlossen am</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>P7S1_Aktiv__c</fullName>
        <description>Zeigt an, ob das Abonnement aktiv ist.</description>
        <formula>AND (  
  NOT(ISBLANK ( P7S1_AbgeschlossenAm__c )),
  P7S1_AbgeschlossenAm__c &lt;= NOW(),
  OR (
    ISBLANK ( P7S1_Kuendigungsdatum__c ),
    P7S1_Kuendigungsdatum__c &gt;= NOW(),
    AND(P7S1_Kuendigungsdatum__c &lt; NOW(), P7S1_AbgeschlossenAm__c &gt; P7S1_Kuendigungsdatum__c)
  )
)</formula>
        <inlineHelpText>Zeigt an, ob das Abonnement aktiv ist.</inlineHelpText>
        <label>Aktiv</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Kontakt der das Abonnement abgeschlossen hat</description>
        <inlineHelpText>Kontakt der das Abonnement abgeschlossen hat</inlineHelpText>
        <label>Kontakt</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Abonnements</relationshipLabel>
        <relationshipName>Abonnements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Kuendigungsdatum__c</fullName>
        <description>Ende des Abonnements</description>
        <inlineHelpText>Ende des Abonnements</inlineHelpText>
        <label>Kündigungsdatum</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>P7S1_Newsletter__c</fullName>
        <description>Abonnement für Newsletter</description>
        <inlineHelpText>Abonnement für Newsletter</inlineHelpText>
        <label>Newsletter</label>
        <referenceTo>P7S1_Newsletter__c</referenceTo>
        <relationshipLabel>Abonnements</relationshipLabel>
        <relationshipName>Abonnements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>P7S1_PortalLogin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Abonnement durch Benutzer des Portals</description>
        <inlineHelpText>Abonnement durch Benutzer des Portals</inlineHelpText>
        <label>Portal Benutzer</label>
        <referenceTo>P7S1_PortalLogin__c</referenceTo>
        <relationshipLabel>Abonnements</relationshipLabel>
        <relationshipName>Abonnements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Abonnement</label>
    <nameField>
        <displayFormat>NL-Abo-{000000}</displayFormat>
        <label>Abonnement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abonnements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_Newsletter__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_Aktiv__c</fullName>
        <description>Zeigt an, ob der Newsletter aktuell verfügbar ist</description>
        <formula>AND (
  OR (
    ISBLANK ( P7S1_Startdatum__c ) , 
    P7S1_Startdatum__c &lt;= TODAY()
  ),
  OR (
    ISBLANK ( P7S1_Enddatum__c ) , 
    P7S1_Enddatum__c &gt;= TODAY()
  )
)</formula>
        <inlineHelpText>Zeigt an, ob der Newsletter aktuell verfügbar ist</inlineHelpText>
        <label>Aktiv</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_Beschreibung__c</fullName>
        <description>Beschreibung des Newsletters  - erscheint auf der Webseire</description>
        <inlineHelpText>Beschreibung des Newsletters  - erscheint auf der Webseire</inlineHelpText>
        <label>Beschreibung</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>P7S1_Enddatum__c</fullName>
        <description>Ende der Verfügbarkeit dieses Newsletters</description>
        <inlineHelpText>Ende der Verfügbarkeit dieses Newsletters</inlineHelpText>
        <label>Enddatum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P7S1_Frequenz__c</fullName>
        <description>Frequenz des Versands</description>
        <inlineHelpText>Frequenz des Versands</inlineHelpText>
        <label>Frequenz</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Täglich</fullName>
                </value>
                <value>
                    <fullName>Wöchentlich</fullName>
                </value>
                <value>
                    <fullName>Monatlich</fullName>
                </value>
                <value>
                    <fullName>Unregelmäßig</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Kategorie__c</fullName>
        <description>Die Kategorie unter der der Newsletter auf der Webseite angeboten wird</description>
        <inlineHelpText>Die Kategorie unter der der Newsletter auf der Webseite angeboten wird</inlineHelpText>
        <label>Kategorie</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Specials</fullName>
                </value>
                <value>
                    <fullName>Newsletter</fullName>
                </value>
                <value>
                    <fullName>Sender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P7S1_Sortierung__c</fullName>
        <description>Nummerische Sortierreihenfolge pro Kategorie</description>
        <inlineHelpText>Nummerische Sortierreihenfolge pro Kategorie</inlineHelpText>
        <label>Sortierung</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P7S1_Startdatum__c</fullName>
        <description>Beginn der Verfügbarkeit des Newsletters</description>
        <inlineHelpText>Beginn der Verfügbarkeit des Newsletters</inlineHelpText>
        <label>Startdatum</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P7S1_Textfarbe__c</fullName>
        <description>Textfarbe als hex Code für Html Darstellung (Eingabe ohne #). Wenn das Feld leer ist wird der Text in schwarz dargestellt.</description>
        <inlineHelpText>Textfarbe als hex Code für Html Darstellung (Eingabe ohne #). Wenn das Feld leer ist wird der Text in schwarz dargestellt.</inlineHelpText>
        <label>Textfarbe</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Textfett__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Der Titel wird in Fettschrift dargestellt</description>
        <inlineHelpText>Der Titel wird in Fettschrift dargestellt</inlineHelpText>
        <label>Text fett</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_Version__c</fullName>
        <description>Art des Versands</description>
        <inlineHelpText>Art des Versands</inlineHelpText>
        <label>Version</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>E-Mail</fullName>
                </value>
                <value>
                    <fullName>E-Print</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Newsletter</label>
    <nameField>
        <label>Newsletter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Newsletters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_PortalLogin__c.object
<CustomObject>
    <description>Informationen zur Verwaltung von Zugängen zu Portalen wie sevenonemedia.de und adfactory.de</description>
    <fields>
        <fullName>P7S1_Beschreibung__c</fullName>
        <description>Weitere Informationen und Hinweise</description>
        <inlineHelpText>Weitere Informationen und Hinweise</inlineHelpText>
        <label>Beschreibung</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>P7S1_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Kontakt mit Zugang zum Portal</description>
        <inlineHelpText>Kontakt mit Zugang zum Portal</inlineHelpText>
        <label>Kontakt</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Logins</relationshipLabel>
        <relationshipName>Portal_Logins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_EMail__c</fullName>
        <description>Registrierte E-Mail Adresse</description>
        <inlineHelpText>Registrierte E-Mail Adresse</inlineHelpText>
        <label>E-Mail Adresse</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>P7S1_Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_PortalId__c</fullName>
        <description>Id aus dem Portal zur Identifizierung des Logins</description>
        <externalId>true</externalId>
        <inlineHelpText>Id aus dem Portal zur Identifizierung des Logins</inlineHelpText>
        <label>Portal Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Portal Login</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Portal Login</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_NLP_PortalPageController.cls
public with sharing class P7S1_NLP_PortalPageController {

    public class NLPException Extends System.Exception
    {
        
    }
    
    
    @TestVisible
    private NewsletterChangeHandler changeHandler;
    private NewsletterListHandler listHandler;
    private P7S1_PortalLogin__c portalLogin;
    @TestVisible
    private Id portalLoginId
    {
        get;
        set
        {
            if(value != portalLoginId)
            {
                portalLoginId = value;
                system.debug('portalLoginId changed to: '+portalLoginId);
                this.portalLogin = [select id, P7S1_Contact__c, P7S1_EMail__c  from P7S1_PortalLogin__c where id = :portalLoginId];
            }
        }
    }
    
    private void init(Id PortalloginId)
    {
        this.changeHandler = new NewsletterChangeHandler();
        this.portalLoginId = PortalloginId;
        List<P7S1_Newsletter__c> newsletters = getAllActiveNewsletters(this.portalLogin);
        this.listHandler =  new NewsletterlistHandler(newsletters,this);
    }
    
    @TestVisible
    private P7S1_NLP_PortalPageController(Id PortalloginId)
    {
        init(PortalloginId);
    }
    
    public P7S1_NLP_PortalPageController()
    {
        
        init(decryptId(ApexPages.currentPage().getParameters().get('pid')));
        
    }
    
    public void addToChangeHandler(P7S1_NLP_NewsletterWrapper nl)
    {
        this.changeHandler.addWrapper(nl);
    }
    
    public void removeFromChangeHandler(P7S1_NLP_NewsletterWrapper nl)
    {
        this.changeHandler.removeWrapper(nl);
    }
    
    public String getLoginEmail()
    {
        return portalLogin.P7S1_EMail__c;
    }
    
    public List<P7S1_NLP_NewsletterWrapper> getSender()
    {
        return listHandler.sender;
    }  
    
    public List<P7S1_NLP_NewsletterWrapper> getSpecials()
    {
        return listHandler.special;
    }  
    
    public List<P7S1_NLP_NewsletterWrapper> getNewsletters()
    {
        return listHandler.newsletter;
    }  
    
    public void save()
    {
        changeHandler.saveChanges(portalLogin);
        
        init(portalLoginId);
    }
    
    
    /*
     * queries all available Newsletters with abonements of the current 'User'
	 */
    public static List<P7S1_Newsletter__c> getAllActiveNewsletters(P7S1_PortalLogin__c login)
    {
        return [
            SELECT
            	Id, name, P7S1_Startdatum__c, P7S1_Enddatum__c, P7S1_Kategorie__c, P7S1_Beschreibung__c,
            	P7S1_Frequenz__c, P7S1_Version__c, P7S1_Textfett__c, P7S1_Textfarbe__c, P7S1_Aktiv__c,
            	(
                    SELECT 
                    	Id, P7S1_Contact__c, P7S1_Newsletter__c, P7S1_PortalLogin__c, P7S1_AbgeschlossenAm__c,
                    	P7S1_Kuendigungsdatum__c, P7S1_Aktiv__c
                    FROM Abonnements__r
                    WHERE P7S1_PortalLogin__c = :login.Id
                )
            FROM P7S1_Newsletter__c 
            WHERE P7S1_Aktiv__c = true
            ORDER BY P7S1_Sortierung__c
        ];
    }

    public static Boolean isNewsletterActive(P7S1_Newsletter__c newsletter)
    {
        return newsletter.P7S1_Aktiv__c;
    }
    
    public static String encryptId(Id portalLoginId)
    {
        //if id doesn't exist the errorpage will be shown automaticaly
        try
        {
            P7S1_PortalLogin__c login = [SELECT Id, P7S1_PortalId__c FROM P7S1_PortalLogin__c WHERE ID = :portalLoginId]; 
             return login.P7S1_PortalId__c;
        }
        catch(Exception exc)
        {
            throw new NLPException('Error while Encrypting');
        }     
    }
    
    public static Id decryptId(String encrPortalLoginId)
    {
        //if id doesn't exist the errorpage will be shown automaticaly
        try
        {
            P7S1_PortalLogin__c login = [SELECT Id, P7S1_PortalId__c FROM P7S1_PortalLogin__c WHERE P7S1_PortalId__c = :encrPortalLoginId];   
            return login.Id;   
        }
        catch(Exception exc)
        {
            throw new NLPException('Error while Decrypting');
        }
    }
    
    public class NewsletterlistHandler
    {
        public List<P7S1_NLP_NewsletterWrapper> sender {get; private set;}
        public List<P7S1_NLP_NewsletterWrapper> special {get; private set;}
        public List<P7S1_NLP_NewsletterWrapper> newsletter {get; private set;}
        
        public NewsletterlistHandler(List<P7S1_Newsletter__c> newsletters, P7S1_NLP_PortalPageController ctrl)
        {
            this.sender = new List<P7S1_NLP_NewsletterWrapper>();
            this.special = new List<P7S1_NLP_NewsletterWrapper>();   
            this.newsletter = new List<P7S1_NLP_NewsletterWrapper>();
            
            for(P7S1_Newsletter__c nl : newsletters)
            {
                if(!isNewsletterActive(nl)) continue;
                
                if(nl.P7S1_Kategorie__c == 'Specials') special.add(new P7S1_NLP_NewsletterWrapper(nl, ctrl));
                if(nl.P7S1_Kategorie__c == 'Newsletter') newsletter.add(new P7S1_NLP_NewsletterWrapper(nl, ctrl));
                if(nl.P7S1_Kategorie__c == 'Sender') sender.add(new P7S1_NLP_NewsletterWrapper(nl, ctrl));
            }
        }
    }
    
    private without sharing class NewsletterChangeHandler
    {
        @testVisible
        private Set<P7S1_NLP_NewsletterWrapper> changedWrappers;
        
        public NewsletterChangeHandler()
        {
            changedWrappers = new Set<P7S1_NLP_NewsletterWrapper>();
        }
        
        public void addWrapper(P7S1_NLP_NewsletterWrapper wrapper)
        {
            this.changedWrappers.add(wrapper);
        }

        public void removeWrapper(P7S1_NLP_NewsletterWrapper wrapper)
        {
            this.changedWrappers.remove(wrapper);
        }
        
        public void saveChanges(P7S1_PortalLogin__c login)
        {
            List<P7S1_Abonnement__c> abonementsToUpsert = new List<P7S1_Abonnement__c>();
			for(P7S1_NLP_NewsletterWrapper wrapper : changedWrappers)
            {
                P7S1_Abonnement__c abo = new P7S1_Abonnement__c();
                if(wrapper.abonement == NULL)
                {
                    abo.P7S1_Contact__c = login.P7S1_Contact__c;
                    abo.P7S1_PortalLogin__c = login.Id;
                    abo.P7S1_AbgeschlossenAm__c = DateTime.now();
                    abo.P7S1_Newsletter__c = wrapper.newsletter.Id;
                }
                else
                {
                    abo = wrapper.abonement;
                    if(wrapper.isChecked)
                    {
                        abo.P7S1_Kuendigungsdatum__c = NULL;
                        abo.P7S1_AbgeschlossenAm__c = DateTime.now();
                    }
                    else
                    {
                        abo.P7S1_Kuendigungsdatum__c = DateTime.now();
                    }
                }
                abonementsToUpsert.add(abo);
            }
            upsert abonementsToUpsert;
        }
        
    }
    
}