src/objects/P7S1_Comp__c.object
<CustomObject>
    <description>Firmen des P7S1-Konzerns
diesen Firmen werden Mitarbeiter zugeordnet.
inklusive externen Partnern/Lieferanten, die Mitarbeiter/User bereit stellen</description>
    <label>P7S1 Firma</label>
    <nameField>
        <label>Firmenname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P7S1 Firmen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>P7S1_Emp_Serviceweb_DefaultCompID__c</fullName>
        <description>Contains the ID of the default P7S1_Comp__c record.
Used in P7S1_Emp_Serviceweb.</description>
        <label>P7S1_Emp_Serviceweb_DefaultCompID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>P7S1_Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Lcm_Sandboxes__c</fullName>
        <description>Hier können komma-separiert Sandboxnamen/-präfixe eingetragen werden. Bei der Erstellung einer darauf matchenden Sandbox wird für diesen User automatisch die Nachbearbeitung aus Klasse Lcm_Sandbox_Setup ausgelöst.
Ticket 4349</description>
        <inlineHelpText>Hier können komma-separiert Sandboxnamen/-präfixe eingetragen werden. Bei der Erstellung einer darauf matchenden Sandbox wird für diesen User automatisch die Nachbearbeitung aus Klasse Lcm_Sandbox_Setup ausgelöst.</inlineHelpText>
        <label>Sandboxes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Projects__c</fullName>
        <description>Benutzer ist Teilnehmer von Entwicklungsprojekten (Projektteam, Tester, Fachbereich). Dient zur Steuerung von Einstellungen in Testumgebungen</description>
        <inlineHelpText>Benutzer ist Teilnehmer von Entwicklungsprojekten (Projektteam, Tester, Fachbereich). Dient zur Steuerung von Einstellungen in Testumgebungen</inlineHelpText>
        <label>Projektmitglied</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AdC_CoreTeam</fullName>
                </value>
                <value>
                    <fullName>AdC_Fachbereich</fullName>
                </value>
                <value>
                    <fullName>CRMSALES_CoreTeam</fullName>
                </value>
                <value>
                    <fullName>CRMSALES_Fachbereich</fullName>
                </value>
                <value>
                    <fullName>SalesExcellence_CoreTeam</fullName>
                </value>
                <value>
                    <fullName>SalesExcellence_Fachbereich</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Lcm_Sandbox_Setup.cls
global class Lcm_Sandbox_Setup implements SandboxPostCopy {
	global void runApexClass(SandboxContext context) {
		upadteEmailAdress(queryUserList(context));
		createDefaultCompRecordIfMissing();
	}

	global void upadteEmailAdress(List<User> listUsers){ 
		Boolean runInTestMode = false;
		System.debug('### Anzahl User: ' + listUsers.size());

		for (User usr : listUsers) {
			String oldEmail = usr.Email;
			List<String> parts = oldEmail.split('[=@]');
			parts.remove(2);
			usr.Email = String.join(parts, '@');

			System.debug('### Updating email: ' + oldEmail + ' => ' + usr.Email);
		}

		Savepoint sp = Database.setSavepoint();

		try {
			if (!runInTestMode) {
				update listUsers;
			}
		} catch (Exception e) {
			System.debug('### Error while updating email addresses: ' + e);
			Database.rollback(sp);
		}
	}

	global List<User> queryUserList(SandboxContext context){ 
		List<User> listUser = [SELECT Id, Username, Email, Lcm_Sandboxes__c
								FROM User
								WHERE IsActive = true
									AND Email LIKE '%example.com%'
									AND Lcm_Sandboxes__c != null
									AND P7S1_Projects__c INCLUDES ('AdC_CoreTeam', 'CRMSALES_CoreTeam', 'SalesExcellence_CoreTeam')
								ORDER BY Email
							];
		for(Integer i=0;i<listUser.size();i++){
			User oneUser = listUser.get(i);
			String sRegex = '(?i)^('+oneUser.Lcm_Sandboxes__c+')';
			sRegex = sRegex.replaceAll(',','|');
			sRegex = sRegex.replaceAll('\\*','\\.\\*');
			System.debug('### User: '+oneUser.Username+ ' // '+sRegex);

			Pattern onePattern = Pattern.compile(sRegex);
			Matcher oneMatcher = onePattern.matcher(context.sandboxName());
			System.debug('Result: '+oneMatcher.matches());
			if(oneMatcher.matches()){
				System.debug('Match found');
			}else{
				listUser.remove(i);
				i--;
			}
		}
		System.debug(listUser);
		return listUser;
	}

	/*
	 * Checks if there is a valid ID in P7S1_Setting__c. If not, creates a Firma(P7S1_Comp__c) record and stores the ID to mark it as default. Used for P7S1_Emp_Serviceweb.
	 */
	private void createDefaultCompRecordIfMissing() {
		// check if the P7S1_Comp__c ID in custom setting is valid.
		List<P7S1_Comp__c> comps = new List<P7S1_Comp__c>([SELECT Id FROM P7S1_Comp__c WHERE ID = :P7S1_Settings__c.getOrgDefaults().P7S1_Emp_Serviceweb_DefaultCompID__c]);
		// if so, exit.
		if(!comps.isEmpty()) return;

		// if not, create one and assign as default.
		P7S1_Comp__c objComp = cls_P7S1_TestData.createTestFirma(true);
        upsert new P7S1_Settings__c(SetupOwnerId = Userinfo.getOrganizationId(), P7S1_Emp_Serviceweb_DefaultCompID__c = objComp.Id);
	}
}