src/objects/P7S1_PortalLogin__c.object
<CustomObject>
    <description>Informationen zur Verwaltung von Zugängen zu Portalen wie sevenonemedia.de und adfactory.de</description>
    <fields>
        <fullName>P7S1_EMail__c</fullName>
        <description>Registrierte E-Mail Adresse</description>
        <inlineHelpText>Registrierte E-Mail Adresse</inlineHelpText>
        <label>E-Mail Adresse</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>P7S1_NewsletterSubscribeLink__c</fullName>
        <label>Newsletter Subscribe Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>P7S1_Portal_Status__c</fullName>
        <description>Status für das Portal</description>
        <inlineHelpText>Status für das Portal</inlineHelpText>
        <label>Portal Status</label>
        <picklist>
            <picklistValues>
                <fullName>Neu</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Aktiv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gesperrt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gelöscht</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liferay Aktiv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adfactory Aktiv</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>P7S1_Portal__c</fullName>
        <description>Auswahl des Portals für das der Zugang gilt</description>
        <inlineHelpText>Auswahl des Portals für das der Zugang gilt</inlineHelpText>
        <label>Portal</label>
        <picklist>
            <picklistValues>
                <fullName>sevenonemedia.de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sevenone-adfactory.de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sevenonemedia.ch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sevenonemedia.com</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Login</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Portal Login</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_PortalLoginEvent__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_EventMessage__c</fullName>
        <label>P7S1_EventMessage</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>P7S1_EventTimestamp__c</fullName>
        <label>P7S1_EventTimestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>P7S1_EventType__c</fullName>
        <label>P7S1_EventType</label>
        <picklist>
            <picklistValues>
                <fullName>created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>activated-salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>email-send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>activated-liferay</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>P7S1_PortalLogin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Login</label>
        <referenceTo>P7S1_PortalLogin__c</referenceTo>
        <relationshipLabel>Portal Login Events</relationshipLabel>
        <relationshipName>Portal_Login_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Successful__c</fullName>
        <defaultValue>false</defaultValue>
        <label>P7S1_Successful</label>
        <type>Checkbox</type>
    </fields>
    <label>Portal Login Event</label>
    <nameField>
        <displayFormat>evt-log-{0}</displayFormat>
        <label>P7S1_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Login Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_Newsletter_Ressource_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class P7S1_Newsletter_Ressource_Test {

    static testmethod void subscribeEmail(){

        P7S1_Liferay_TestDataGenerator.createAll();

        P7S1_PortalLogin__c portalLogin = new P7S1_PortalLogin__c (P7S1_Email__c = 'test@ambuorg.de', P7S1_Portal__c = P7S1_Liferay_Constants.PORTAL_ADFACTORY, P7S1_Portal_Status__c = P7S1_Liferay_Constants.PORTAL_STATUS_ADFACTORY_ACTIVE);
        insert portalLogin;

        RestRequest restRequest = new RestRequest();
        restRequest.addHeader( 'Content-Type' , 'application/json' );
        restRequest.httpMethod = 'POST';
        restRequest.requestBody = Blob.valueof( '{"newsletterSubscribeUrl":"https://foobar.com/subscibeUrl"}' ); // Add JSON Message as a POST
        restRequest.requestURI = 'https://p7s1--LR2SF.cs83.my.salesforce.com/services/apexrest/newsletter/'+ P7S1_Liferay_Constants.NEWSLETTER_ACTION_SUBSCRIBE_EMAIL + '/'+ portalLogin.Id;

        RestContext.request = restRequest;

        String postNewsletterResponse = P7S1_Newsletter_Ressource.postNewsletter();
        system.assert(postNewsletterResponse != null);
        system.assertEquals('success', postNewsletterResponse);

        /*** check new status is set in database ***/
        P7S1_PortalLogin__c portalLoginFromDB = [SELECT P7S1_NewsletterSubscribeLink__c FROM P7S1_PortalLogin__c Where id = :portalLogin.Id];
        system.assertEquals('https://foobar.com/subscibeUrl', portalLoginFromDB.P7S1_NewsletterSubscribeLink__c);

        /*** check if the right event objects are written ***/
        List<P7S1_PortalLoginEvent__c> portalLoginEvents =  [   SELECT Id, P7S1_EventType__c, P7S1_Successful__c, P7S1_EventTimestamp__c, P7S1_PortalLogin__c, P7S1_EventMessage__c
                                                                FROM P7S1_PortalLoginEvent__c
                                                                WHERE P7S1_PortalLogin__c = :portalLogin.Id];

        system.assert(portalLoginEvents != null);
        system.assertEquals(1, portalLoginEvents.size());

        /*** subscibed to newsletter ***/
        system.assert(portalLoginEvents.get(0) != null);
        system.assertEquals(portalLogin.Id,portalLoginEvents.get(0).P7S1_PortalLogin__c);
        system.assertEquals(portalLoginEvents.get(0).P7S1_Successful__c, true);
        system.assertEquals(portalLoginEvents.get(0).P7S1_EventType__c, P7S1_Liferay_Constants.PORTAL_EVENT_NEWSLETTER_SUBSCRIBE_CONFIRM_SEND);
        system.assert(portalLoginEvents.get(0).P7S1_EventTimestamp__c != null);
        system.assertEquals(null,portalLoginEvents.get(0).P7S1_EventMessage__c);

    }
}