src/objects/P7S1_PortalLogin__c.object
<CustomObject>
    <description>Informationen zur Verwaltung von Zugängen zu Portalen wie sevenonemedia.de und adfactory.de</description>
    <label>Portal Login</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Portal Login</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_PortalLoginEvent__c.object
<CustomObject>
    <fields>
        <fullName>P7S1_EventType__c</fullName>
        <label>P7S1_EventType</label>
        <picklist>
            <picklistValues>
                <fullName>created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>activated-salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>email-send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>activated-liferay</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>P7S1_PortalLogin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portal Login</label>
        <referenceTo>P7S1_PortalLogin__c</referenceTo>
        <relationshipLabel>Portal Login Events</relationshipLabel>
        <relationshipName>Portal_Login_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P7S1_Successful__c</fullName>
        <defaultValue>false</defaultValue>
        <label>P7S1_Successful</label>
        <type>Checkbox</type>
    </fields>
    <label>Portal Login Event</label>
    <nameField>
        <displayFormat>evt-log-{0}</displayFormat>
        <label>P7S1_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Login Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_Liferay_PortalLoginEventUtil_Test.cls
/**
* This is the Testclass for P7S1_Liferay_PortalLoginEventUtil.cls 

*
* @author  Sebastian Listl
* @version 0.1
* @since   2016-02-02
* @see P7S1_Liferay_PortalLoginEventUtil.cls
* @see P7S1_PortalLoginEvent__c
*/
@isTest
private class P7S1_Liferay_PortalLoginEventUtil_Test {
	
	static testmethod void createPortalLoginEvent(){
        
        P7S1_PortalLogin__c portalLogin = P7S1_Liferay_TestDataGenerator.createPortalLogin(true);
		system.assert(portalLogin != null);
		system.assert(portalLogin.Id != null);
		
		P7S1_PortalLoginEvent__c portalLoginEvent = P7S1_Liferay_PortalLoginEventUtil.createPortalLoginEvent( portalLogin, P7S1_Liferay_Constants.PORTAL_EVENT_STATUS_DELETED );
		system.assert(portalLoginEvent != null);
		system.assertEquals(false, portalLoginEvent.P7S1_Successful__c);
		system.assertEquals(P7S1_Liferay_Constants.PORTAL_EVENT_STATUS_DELETED, portalLoginEvent.P7S1_EventType__c);
	
	}
}