src/objects/P7S1_Abonnement__c.object
<CustomObject>
    <description>Newsletter Abonnements für Portaluser und Kontakte</description>
    <fields>
        <fullName>P7S1_Kuendigungsdatum__c</fullName>
        <description>Ende des Abonnements</description>
        <inlineHelpText>Ende des Abonnements</inlineHelpText>
        <label>Kündigungsdatum</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>P7S1_Newsletter__c</fullName>
        <description>Abonnement für Newsletter</description>
        <inlineHelpText>Abonnement für Newsletter</inlineHelpText>
        <label>Newsletter</label>
        <referenceTo>P7S1_Newsletter__c</referenceTo>
        <relationshipLabel>Abonnements</relationshipLabel>
        <relationshipName>Abonnements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>P7S1_PortalLogin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Abonnement durch Benutzer des Portals</description>
        <inlineHelpText>Abonnement durch Benutzer des Portals</inlineHelpText>
        <label>Portal Benutzer</label>
        <referenceTo>P7S1_PortalLogin__c</referenceTo>
        <relationshipLabel>Abonnements</relationshipLabel>
        <relationshipName>Abonnements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Abonnement</label>
    <nameField>
        <displayFormat>NL-Abo-{000000}</displayFormat>
        <label>Abonnement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abonnements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_Liferay_ConfigSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>P7S1_Newsletter_Unsubscribe_Success_Url__c</fullName>
        <defaultValue>&quot;http://www.sevenone-adfactory.de/newsletter/abmeldebestaetigung/&quot;</defaultValue>
        <label>Adfactory NL Unsubscribe Success Url</label>
        <type>Url</type>
    </fields>
    <label>P7S1 Liferay Config Settings</label>
</CustomObject>

src/objects/P7S1_Newsletter__c.object
<CustomObject>
    <label>Newsletter</label>
    <nameField>
        <label>Newsletter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Newsletters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_PortalLogin__c.object
<CustomObject>
    <description>Informationen zur Verwaltung von Zugängen zu Portalen wie sevenonemedia.de und adfactory.de</description>
    <fields>
        <fullName>P7S1_Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_Portal__c</fullName>
        <description>Auswahl des Portals für das der Zugang gilt</description>
        <inlineHelpText>Auswahl des Portals für das der Zugang gilt</inlineHelpText>
        <label>Portal</label>
        <picklist>
            <picklistValues>
                <fullName>sevenonemedia.de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sevenone-adfactory.de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sevenonemedia.ch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sevenonemedia.com</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Login</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Portal Login</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_Newsletter_SiteController.cls
/**
* Implementaion of the P7S1_Newsletter_SiteController inteface
*
* @author  Sebastian Listl
* @version 0.1, 2014-10-12
*/
global class P7S1_Newsletter_SiteController {
    
    public P7S1_Abonnement__c abonnement;
    public String msg {get;set;}
    public String errorCode {get;set;}
    private String abonnementId;
    private String newsletterUnsubscribeSuccessUrl = P7S1_Liferay_ConfigSettings__c.getInstance('DefaultSetting').P7S1_Newsletter_Unsubscribe_Success_Url__c;
    
    public P7S1_Newsletter_SiteController( ) {
        msg = Label.P7S1_SITE_NEWSLETTER_UNSUBSCRIBE_FAILED;
        Map<String, String> params = Apexpages.currentPage().getParameters();
        system.debug(logginglevel.INFO, 'entering P7S1_Newsletter_SiteController@P7S1_Liferay_PortalLoginController');
        abonnementId = params.containsKey('abonnementId') ? params.get('abonnementId') : '';
    }
    
    public PageReference unsubscibeNewsletter() {
        system.debug(logginglevel.INFO, 'entering unsubscibeNewsletter@P7S1_Liferay_PortalLoginController');
        PageReference pr = null;
        
        try {
            abonnement = [SELECT Id, P7S1_Kuendigungsdatum__c, P7S1_PortalLogin__c, Name FROM P7S1_Abonnement__c WHERE Id = :abonnementId];    
            abonnement.P7S1_Kuendigungsdatum__c = system.now();
            Database.UpsertResult usrAbo = Database.upsert(abonnement);
            
            P7S1_PortalLogin__c pl = [SELECT P7S1_Newsletter__c, P7S1_Portal__c FROM P7S1_PortalLogin__c WHERE Id = :abonnement.P7S1_PortalLogin__c];
            Database.UpsertResult usrPl = null;
            if (pl.P7S1_Portal__c.equals(P7S1_Liferay_Constants.PORTAL_ADFACTORY)){
	            pl.P7S1_Newsletter__c = false;
	            usrPl = Database.upsert(pl);
            }
            
            if (usrAbo.isSuccess() && usrPl != null && usrPl.isSuccess()){
                pr = new PageReference(newsletterUnsubscribeSuccessUrl);
            } else {
                msg += ' upsert result Abo: ' + usrAbo + ' upsert result Portal Login: ' + usrPl;
                ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.ERROR, msg);
                ApexPages.addMessage(errorMsg);
            }
            
       } catch(Exception e){
           msg += abonnementId;
           errorCode = e+'';
           ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.ERROR, errorCode);
           ApexPages.addMessage(errorMsg);
       } 
        
        
        return pr;
    }

}