src/objects/P7S1_Emp__c.object
<CustomObject>
    <description>Mitarbeiter des P7S1-Konzerns.
meistens auch User mit Lizenz in Salesforce
enthalten auch externe Mitarbeiter</description>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <label>Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>12Auto</fullName>
                </value>
                <value>
                    <fullName>71M</fullName>
                </value>
                <value>
                    <fullName>7Commerce</fullName>
                </value>
                <value>
                    <fullName>7coops</fullName>
                </value>
                <value>
                    <fullName>7Games</fullName>
                </value>
                <value>
                    <fullName>7Life</fullName>
                </value>
                <value>
                    <fullName>7NXT</fullName>
                </value>
                <value>
                    <fullName>7Screen</fullName>
                </value>
                <value>
                    <fullName>7Sports</fullName>
                </value>
                <value>
                    <fullName>7Travel</fullName>
                </value>
                <value>
                    <fullName>7Ventures</fullName>
                </value>
                <value>
                    <fullName>Aeria</fullName>
                </value>
                <value>
                    <fullName>App</fullName>
                </value>
                <value>
                    <fullName>CCO Sales</fullName>
                </value>
                <value>
                    <fullName>D&amp;A</fullName>
                </value>
                <value>
                    <fullName>d&amp;a Sales</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>glomex</fullName>
                </value>
                <value>
                    <fullName>Licensing</fullName>
                </value>
                <value>
                    <fullName>M&amp;A</fullName>
                </value>
                <value>
                    <fullName>Magic</fullName>
                </value>
                <value>
                    <fullName>marktguru</fullName>
                </value>
                <value>
                    <fullName>Maxdome</fullName>
                </value>
                <value>
                    <fullName>- No Unit -</fullName>
                </value>
                <value>
                    <fullName>PSD Branded Reselling</fullName>
                </value>
                <value>
                    <fullName>PSD Digital Entertainment</fullName>
                </value>
                <value>
                    <fullName>Puls4</fullName>
                </value>
                <value>
                    <fullName>Starwatch</fullName>
                </value>
                <value>
                    <fullName>Studio71</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mitarbeiter</label>
    <nameField>
        <label>Mitarbeiter</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mitarbeiter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/P7S1_Unit__c.object
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>P7S1_EmpLink__c</fullName>
        <formula>IF( ISBLANK(P7S1_Emp__c),
&apos;&apos;,
HYPERLINK(&apos;/&apos; +  P7S1_Emp__c ,  FirstName + &apos; &apos; + LastName)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mitarbeiter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Emp__c</fullName>
        <label>Mitarbeiter-Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>P7S1_Unit__c</fullName>
        <description>Enthält die Information welcher Unit der User zugeordnet ist</description>
        <inlineHelpText>Enthält die Information welcher Unit der User zugeordnet ist</inlineHelpText>
        <label>Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/P7S1_PackageUser.cls
public with sharing class P7S1_PackageUser {
    public static List<User> userlist {get; set;}
    public static string PACKAGE_NAME {get; set;}
    public static string USER_COUNT {get; set;}
    
    public P7S1_PackageUser() {
    PACKAGE_NAME = 'advendio';
    userlist = new List<User>(
    
       [SELECT Id, Name, isactive, Profile.Name, Userrole.Name, p7s1_Unit__c, lastlogindate, P7S1_EmpLink__c, P7S1_Emp__c
       FROM User 
       WHERE Id in (
           SELECT UserId 
           FROM UserPackageLicense 
           WHERE (PackageLicense.NamespacePrefix = :PACKAGE_NAME))
       order by isactive asc, lastlogindate asc
       ]);
    USER_COUNT = string.valueof(userlist.size());
   }
}