src/objects/P7S1_Newsletter__c.object
<CustomObject>
    <label>Newsletter</label>
    <nameField>
        <label>Newsletter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Newsletters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/P7S1_PortalLogin__c.object
<CustomObject>
    <description>Informationen zur Verwaltung von Zugängen zu Portalen wie sevenonemedia.de und adfactory.de</description>
    <fields>
        <fullName>P7S1_Anrede__c</fullName>
        <description>Anrede des Benutzers</description>
        <inlineHelpText>Anrede des Benutzers</inlineHelpText>
        <label>Anrede</label>
        <picklist>
            <picklistValues>
                <fullName>Herr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frau</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>P7S1_Bereich__c</fullName>
        <description>Bereich des Benutzers</description>
        <inlineHelpText>Bereich des Benutzers</inlineHelpText>
        <label>Bereich</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_EMail__c</fullName>
        <description>Registrierte E-Mail Adresse</description>
        <inlineHelpText>Registrierte E-Mail Adresse</inlineHelpText>
        <label>E-Mail Adresse</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>P7S1_Fax__c</fullName>
        <description>Faxnummer des Benutzers</description>
        <inlineHelpText>Faxnummer des Benutzers</inlineHelpText>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>P7S1_Firma__c</fullName>
        <description>Firma des Benutzers</description>
        <inlineHelpText>Firma des Benutzers</inlineHelpText>
        <label>Firma</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Funktion__c</fullName>
        <description>Funktion des Benutzers</description>
        <inlineHelpText>Funktion des Benutzers</inlineHelpText>
        <label>Funktion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Geburtstag__c</fullName>
        <label>Geburtstag</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>P7S1_Hausnummer__c</fullName>
        <description>Hausnummer des Benutzers</description>
        <inlineHelpText>Hausnummer des Benutzers</inlineHelpText>
        <label>Hausnummer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Land__c</fullName>
        <description>Land des Benutzers</description>
        <inlineHelpText>Land des Benutzers</inlineHelpText>
        <label>Land</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Mobil__c</fullName>
        <description>Mobiltelefonnummer des Benutzers</description>
        <inlineHelpText>Mobiltelefonnummer des Benutzers</inlineHelpText>
        <label>Mobil</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>P7S1_Nachname__c</fullName>
        <description>Nachname des Benutzers</description>
        <inlineHelpText>Nachname des Benutzers</inlineHelpText>
        <label>Nachname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P7S1_Ort__c</fullName>
        <description>Ort des Benutzers</description>
        <inlineHelpText>Ort des Benutzers</inlineHelpText>
        <label>Ort</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Postleitzahl__c</fullName>
        <description>Postleitzahl des Benutzers</description>
        <inlineHelpText>Postleitzahl des Benutzers</inlineHelpText>
        <label>Postleitzahl</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Strasse__c</fullName>
        <description>Strasse des Benutzers</description>
        <inlineHelpText>Strasse des Benutzers</inlineHelpText>
        <label>Strasse</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Telefon__c</fullName>
        <description>Nachname des Benutzers</description>
        <inlineHelpText>Nachname des Benutzers</inlineHelpText>
        <label>Telefon</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>P7S1_Titel__c</fullName>
        <description>Titel des Benutzers</description>
        <inlineHelpText>Titel des Benutzers</inlineHelpText>
        <label>Titel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_Unternehmensart__c</fullName>
        <description>Unternehmensart des Benutzers</description>
        <inlineHelpText>Unternehmensart des Benutzers</inlineHelpText>
        <label>Unternehmensart</label>
        <picklist>
            <picklistValues>
                <fullName>Mediaagentur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Werbeagentur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Werbungtreibender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>P7S1_Vorname__c</fullName>
        <description>Vorname des Benutzers</description>
        <inlineHelpText>Vorname des Benutzers</inlineHelpText>
        <label>Vorname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Portal Login</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Portal Login</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/P7S1_Liferay_ResourceUtil.cls
public with sharing class P7S1_Liferay_ResourceUtil {

	public static String ACTION_UPDATE = 'update';
	public static String ACTION_ACTIVATE = 'activate';
	public static String ACTION_CONFIRM = 'confirm';
	
	public static String JSON_FIELD_TITLE = 'title';
	public static String JSON_FIELD_LASTNAME = 'lastName';
	public static String JSON_FIELD_FIRSTNAME = 'firstName';
	public static String JSON_FIELD_MALE = 'male';
	public static String JSON_FIELD_EMAIL = 'email';
	public static String JSON_FIELD_COMPANYNAME =  'companyName';
	public static String JSON_FIELD_COMPANYFAX =  'companyFax';
	public static String JSON_FIELD_COMPANYPHONE =  'companyPhone';
	public static String JSON_FIELD_COMPANYSTREETADDRESS=  'companyStreetAddress';
	public static String JSON_FIELD_COMPANYSTREETNUMBER =  'companyStreetNumber';
	public static String JSON_FIELD_COMPANYZIP =  'companyZip';
	public static String JSON_FIELD_COMPANYCITY =  'companyCity';
	public static String JSON_FIELD_COMPANYCOUNTRY =  'companyCountry';
	public static String JSON_FIELD_DATEOFBIRTH =  'dateOfBirth';
	public static String JSON_FIELD_MOBILE =  'mobile';
	public static String JSON_FIELD_AREA =  'area';
	public static String JSON_FIELD_JOBTITLE =  'jobTitle';
	public static String JSON_FIELD_COMPANYTYPE =  'companyType';
	public static String JSON_FIELD_NEWSLETTER =  'newsletter';
	
	/*** FOR DELETE ***/	
	public static String JSON_FIELD_CONFIRM_DELETE_URL = 'confirmDeleteUrl';
	/*** FOR NEWSLETTER ***/
	public static String JSON_FIELD_NEWSLETTER_SUBSCRIBE_URL =  'newsletterSubscribeUrl';
	
  	public static String getIdFromURI(String requestURI){
    	return requestURI.substring(requestURI.lastIndexOf('/')+1);
  	}

  public static String getActionFromURI(String requestURI){
    String actionAndId = requestURI.substring( requestURI.lastIndexOf('/', requestURI.lastIndexOf('/') - 1  ) +1);
    return actionAndId.substring ( 0, actionAndId.lastIndexOf('/') );
  }

  public static P7S1_PortalLogin__c dynamicJsonUpdate(P7S1_PortalLogin__c portalLoginToUpdate, String jsonFieldsToUpdate ){
    JSONParser parser = JSON.createParser(jsonFieldsToUpdate);
    while (parser.nextToken() != null) {
      if (parser.getCurrentToken() == JSONToken.FIELD_NAME){
        String fieldName = parser.getText();
            system.debug('fieldName: ' + fieldName);
            parser.nextToken();
            if (fieldName == JSON_FIELD_TITLE){
              portalLoginToUpdate.P7S1_Titel__c = parser.getText();
            } else if (fieldName == JSON_FIELD_LASTNAME){
              portalLoginToUpdate.P7S1_Nachname__c = parser.getText();
            } else if (fieldName == JSON_FIELD_FIRSTNAME){
              portalLoginToUpdate.P7S1_Vorname__c = parser.getText();
            } else if (fieldName == JSON_FIELD_MALE){
              portalLoginToUpdate.P7S1_Anrede__c = ( parser.getBooleanValue() ? 'Herr' : 'Frau');
            } else if (fieldName == JSON_FIELD_EMAIL){
              portalLoginToUpdate.P7S1_EMail__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYNAME){
              portalLoginToUpdate.P7S1_Firma__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYFAX){
              portalLoginToUpdate.P7S1_Fax__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYPHONE){
              portalLoginToUpdate.P7S1_Telefon__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYSTREETADDRESS){
              portalLoginToUpdate.P7S1_Strasse__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYSTREETNUMBER){
              portalLoginToUpdate.P7S1_Hausnummer__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYZIP){
              portalLoginToUpdate.P7S1_Postleitzahl__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYCITY){
              portalLoginToUpdate.P7S1_Ort__c = parser.getText();
            } else if (fieldName == JSON_FIELD_MOBILE){
              portalLoginToUpdate.P7S1_Mobil__c = parser.getText();
            } else if (fieldName == JSON_FIELD_AREA){
              portalLoginToUpdate.P7S1_Bereich__c = parser.getText();
            } else if (fieldName == JSON_FIELD_JOBTITLE){
              portalLoginToUpdate.P7S1_Funktion__c = parser.getText();
            } else if (fieldName == JSON_FIELD_COMPANYCOUNTRY){
              portalLoginToUpdate.P7S1_Land__c = P7S1_Liferay_RegistrationFormBean.getCountryLabelForLiferayCountryId(parser.getLongValue());
            } else if (fieldName == JSON_FIELD_COMPANYTYPE){
              	portalLoginToUpdate.P7S1_Unternehmensart__c = P7S1_Liferay_RegistrationFormBean.getP7S1_UnternehmensartFromString( parser.getText() );
            } else if (fieldName == JSON_FIELD_DATEOFBIRTH ){
           		portalLoginToUpdate.P7S1_Geburtstag__c = (parser.getText() != null && parser.getText() != 'null' && parser.getText() != '') ? parser.getDateValue() : null;
            } else if (fieldName == JSON_FIELD_NEWSLETTER){
            	portalLoginToUpdate.P7S1_Newsletter__c = parser.getBooleanValue();
            } else {
				throw new LiferayRestDynamicUpdateException('not allowed to update field : ' + fieldName);
            }
      }
    }
    return portalLoginToUpdate;
  }
  
	public static String getStringValueByKey(String key, String requestBody){
 		String fieldValue = null;
 		JSONParser parser = JSON.createParser(requestBody);
    	while (parser.nextToken() != null) {
      		if (parser.getCurrentToken() == JSONToken.FIELD_NAME){
				String fieldName = parser.getText();
            	system.debug('fieldName: ' + fieldName);
            	parser.nextToken();
            	if (fieldName == key){
              		fieldValue = parser.getText();
              	}
      		}
    	}
 		return fieldValue;
	}
	public static Boolean getBooleanValueByKey(String key, String requestBody){
 		Boolean fieldValue = null;
 		JSONParser parser = JSON.createParser(requestBody);
    	while (parser.nextToken() != null) {
      		if (parser.getCurrentToken() == JSONToken.FIELD_NAME){
				String fieldName = parser.getText();
            	parser.nextToken();
            	if (fieldName == key){
	       			fieldValue = parser.getBooleanValue();
            	}
      		}
		}
		return fieldValue;
	}
	
  	public class LiferayRestDynamicUpdateException extends Exception {
	
    }
}