src/objects/P7S1_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Lcm_AutoTestExecError__c</fullName>
        <label>Automated Test Execution Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>P7S1_AutoTestQueueAsyncId__c</fullName>
        <description>Used in Apex Class &quot;P7S1_AutomatedTestingJob&quot;</description>
        <label>Automated Testing Queue AsynchId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>P7S1_Settings</label>
</CustomObject>

src/classes/Lcm_AutomatedTests_Run.cls
global class Lcm_AutomatedTests_Run implements Schedulable{
    
    global void execute(SchedulableContext SC) {
        runLocalTestsAsync();
    }    
    
    @future (callout=true)
    public static void runLocalTestsAsync(){
        system.debug('### Lcm_AutomatedTests_Run.runLocalTestsAsync - entering');
        
        Lcm_ToolingUtil toolingUtil = new Lcm_ToolingUtil();
        P7S1_Settings__c CS = P7S1_Settings__c.getOrgDefaults();
        Lcm_Tooling.Result toolingResult = toolingUtil.tooling('run-tests', null);
        
        /*** CAN REMOVED IF LAST TEST RUN CAN CALLED BY TOOLING API ***/
        if (toolingResult.success){
			system.debug('### Lcm_AutomatedTests_Run.runLocalTestsAsync sId: '  + toolingResult.message);
            CS.P7S1_AutoTestQueueAsyncId__c = extractId(toolingResult);//.message.replace('"','').substring(0,15);
            CS.Lcm_AutoTestExecError__c = null;
        } else {
            CS.P7S1_AutoTestQueueAsyncId__c = null;
            CS.Lcm_AutoTestExecError__c = toolingResult.message;
            system.debug(LOGGINGLEVEL.ERROR, '### Lcm_AutomatedTests_Run.runLocalTestsAsync toolingResult faild: '  + toolingResult.message);
        }
        upsert CS;
        system.debug('### leaving Lcm_AutomatedTests_Run.runLocalTestsAsync');
    }
    
    private static String extractId(Lcm_Tooling.Result toolingResult){
        String response = toolingResult.message;
        
        return response.replace('"','').substring(0,15);
    }
    
}