src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SomDig_DeliverPrio__c.object
<CustomObject>
    <description>Regelwerk für das Prio-Modell</description>
    <fields>
        <fullName>SomDig_Abrechungsart__c</fullName>
        <description>Hier kann angegeben werden, ob die Auslieferungsprioritäten für eine bestimmte Abrechnungsart für diesen Account im AdServer gesetzt werden sollen. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welche Abrechnungsart soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Abrechungsart</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPMo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Ad_Type__c</fullName>
        <description>Der AdType steuert die Auslieferungsprioritäten im AdServer. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver&quot;</description>
        <inlineHelpText>Hier kann der &quot;Ad Type&quot; festgelegt werden, der für diese Auslieferungspriorität im Adserver gesetzt werden soll.</inlineHelpText>
        <label>Ad Type</label>
        <picklist>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Priority</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Auswahl des Auftragstyp zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welche Auftragstyp soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Auslieferungsprioritäten</relationshipLabel>
        <relationshipName>Auslieferungsprioritaeten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Belegungseinheitstyp__c</fullName>
        <description>Auswahl des Belegungseinheitstyp zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welchen Belegungseinheitstyp soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Belegungseinheitstyp</label>
        <picklist>
            <picklistValues>
                <fullName>71m intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YouTube</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Gueltig_ab__c</fullName>
        <description>&quot;Hier wird angegeben, ab wann diese Auslieferungspriorität gültig ist.&quot; 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier bitte angegeben, ab wann diese Auslieferungspriorität gültig ist.</inlineHelpText>
        <label>Gültig ab</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Gueltig_bis__c</fullName>
        <description>&quot;Hier wird angegeben, bis wann diese Auslieferungspriorität gültig ist.&quot; 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier bitte angegeben, bis wann diese Auslieferungspriorität gültig ist.</inlineHelpText>
        <label>Gültig bis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Mediagattungsdifferenzierung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Auswahl der Mediagattungsdifferenzierung zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welche Mediagattungsdifferenzierung soll eine Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Mediagattungsdifferenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipName>Adserver_Prioritaeten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Preistyp_zur_Auslieferung__c</fullName>
        <description>Auswahl Preistyp zur Auslieferung (Delivery Rate Type) zur Steuerung der Auslieferungsprioritäten. Vgl. auch Spezifikation SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier kann der &quot;Preistyp zur Auslieferung&quot; (Delivery Rate Type) festgelegt werden, der für diese Auslieferungspriorität im Adserver gesetzt werden soll.</inlineHelpText>
        <label>Preistyp zur Auslieferung</label>
        <picklist>
            <picklistValues>
                <fullName>Evenly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frontloaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>As fast as possible</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Prio__c</fullName>
        <description>Die Prio steuert die Auslieferungsprioritäten im AdServer. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier kann die &quot;Prio&quot; festgelegt werden, die für diese Auslieferungspriorität im Adserver gesetzt werden soll.</inlineHelpText>
        <label>Prio</label>
        <picklist>
            <controllingField>SomDig_Ad_Type__c</controllingField>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <description>Auswahl des Rotationstyp zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welchen Rotationstyp soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Rotationstyp</label>
        <picklist>
            <picklistValues>
                <fullName>Brand-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Themen-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV-Brand-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Umfeld</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Werbeform_Kurzform__c</fullName>
        <description>Hier kann angegeben werden, ob die Auslieferungsprioritäten für eine bestimmte Werbeform für diesen Account im AdServer gesetzt werden sollen. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier kann angegeben werden für welche Werbeform die Auslieferungsprioritäten für diesen Werbetreibenden im Adserver festgelegt werden.</inlineHelpText>
        <label>Werbeform Kurzform</label>
        <picklist>
            <picklistValues>
                <fullName>PR1/MR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR1/MR/POR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prio3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Auslieferungspriorität</label>
    <nameField>
        <displayFormat>PRIO-{0}</displayFormat>
        <label>Priorität-Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auslieferungsprioritäten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsDifferenzierung__c.object
<CustomObject>
    <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
    <label>Mediagattungs-Differenzierung</label>
    <nameField>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Differenzierungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SomDig_DeliverPrio_Check.cls
/**
 * This trigger checks if a 'SomDig_DeliverPrio__c' is already in the database  
 */
    public with sharing class SomDig_DeliverPrio_Check extends TriggerController{  
    
        public SomDig_DeliverPrio_Check(Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
            List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems) {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }
    
    // before Insert
    protected override void runBeforeInsert() {
        checkDoubleValues((List<SomDig_DeliverPrio__c>) lstNewItems);
    }

    // before Update
    protected override void runBeforeUpdate() {
        List<SomDig_DeliverPrio__c> hasChanged = getChangedItems((List<SomDig_DeliverPrio__c>)lstNewItems, (Map<Id, SomDig_DeliverPrio__c>)mapOldItems);
        if (hasChanged.size() >0) {
            checkDoubleValues((List<SomDig_DeliverPrio__c>) hasChanged);
        } 
    }
    
    private List<SomDig_DeliverPrio__c> getChangedItems(List<SomDig_DeliverPrio__c> lstNewItems, Map<Id, SomDig_DeliverPrio__c> mapOldItems) {
        List<SomDig_DeliverPrio__c> changedItems = new List<SomDig_DeliverPrio__c>();
        
        for (SomDig_DeliverPrio__c auslieferungsprio : lstNewItems) {
            if (  mapOldItems.get(auslieferungsprio.id).SomDig_Abrechungsart__c != auslieferungsprio.SomDig_Abrechungsart__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Ad_Type__c != auslieferungsprio.SomDig_Ad_Type__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Auftragstyp__c != auslieferungsprio.SomDig_Auftragstyp__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Belegungseinheitstyp__c != auslieferungsprio.SomDig_Belegungseinheitstyp__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Gueltig_ab__c != auslieferungsprio.SomDig_Gueltig_ab__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Gueltig_bis__c != auslieferungsprio.SomDig_Gueltig_bis__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Mediagattungsdifferenzierung__c != auslieferungsprio.SomDig_Mediagattungsdifferenzierung__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Preistyp_zur_Auslieferung__c != auslieferungsprio.SomDig_Preistyp_zur_Auslieferung__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Prio__c != auslieferungsprio.SomDig_Prio__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Rotationstyp__c != auslieferungsprio.SomDig_Rotationstyp__c
               || mapOldItems.get(auslieferungsprio.id).SomDig_Werbeform_Kurzform__c != auslieferungsprio.SomDig_Werbeform_Kurzform__c
               ) {
                   changedItems.add(auslieferungsprio);
               }
        }
        return changedItems;
    }
    /**
     * Each new 'SomDig_DeliverPrio__c' gets an temporary uniqueKey as a concatenation of the following fields:
     *
     * SomDig_Abrechungsart__c, SomDig_Auftragstyp__c, SomDig_Belegungseinheitstyp__c, 
     * SomDig_Mediagattungsdifferenzierung__c,
     * SomDig_Rotationstyp__c, SomDig_Werbeform_Kurzform__c
     * 
     * If the same uniqueKey is already available we have to check if the given time periods overlaps. If 
     * yes show an error message. Otherwise the new 'SomDig_DeliverPrio__c'
     * will be inserted
     */
    private void checkDoubleValues(List<SomDig_DeliverPrio__c> newItemsList){
        List<SomDig_DeliverPrio__c> allItems = new List<SomDig_DeliverPrio__c>([SELECT Name, SomDig_Abrechungsart__c, SomDig_Auftragstyp__c, 
                                                                                                        SomDig_Belegungseinheitstyp__c, SomDig_Gueltig_ab__c, SomDig_Gueltig_bis__c, 
                                                                                                        SomDig_Mediagattungsdifferenzierung__c, 
                                                                                                        SomDig_Rotationstyp__c, SomDig_Werbeform_Kurzform__c 
                                                                                                        FROM SomDig_DeliverPrio__c]);
        
        for (SomDig_DeliverPrio__c toInsertItem : newItemsList) {
                String tmpToInsertUniqueKey = toInsertItem.SomDig_Abrechungsart__c + '|' + toInsertItem.SomDig_Auftragstyp__c + '|' + toInsertItem.SomDig_Belegungseinheitstyp__c + '|' 
                            +  + toInsertItem.SomDig_Mediagattungsdifferenzierung__c + '|'
                            + toInsertItem.SomDig_Rotationstyp__c + '|' 
                            + toInsertItem.SomDig_Werbeform_Kurzform__c;
                
                Date tmpToInsertValidFrom = toInsertItem.SomDig_Gueltig_ab__c;
                Date tmpToInsertValidUntil = toInsertItem.SomDig_Gueltig_bis__c;
        
                /** Add an error message if the from date is after the until date */
                if (tmpToInsertValidFrom > tmpToInsertValidUntil) {
                    toInsertItem.addError('Gültig ab Datum liegt vor Gültig bis Datum');
                }
            
                for (SomDig_DeliverPrio__c ap : allItems) {
                    String tmpUniqueKey = ap.SomDig_Abrechungsart__c + '|' + ap.SomDig_Auftragstyp__c + '|' + ap.SomDig_Belegungseinheitstyp__c + '|' 
                                    + ap.SomDig_Mediagattungsdifferenzierung__c + '|'
                                    + ap.SomDig_Rotationstyp__c + '|' 
                                    + ap.SomDig_Werbeform_Kurzform__c; 
                    Date tmpValidFrom = ap.SomDig_Gueltig_ab__c;
                    Date tmpValidUntil = ap.SomDig_Gueltig_bis__c;
                
                /** Just check the Auslieferungsprioritaeten where all other fields have the same values */
                if (tmpToInsertUniqueKey.equals(tmpUniqueKey)) {
                    // Such an SomDig_DeliverPrio__c is already available
                    // Now we have to check if the dates/date periods are the same.
                    boolean isSamePeriod = checkPeriods(tmpValidFrom, tmpValidUntil, tmpToInsertValidFrom, tmpToInsertValidUntil);
                    if (isSamePeriod && isInsert) {
                        toInsertItem.addError('Es gibt bereits eine Auslieferungsprioritaet, die in diesem Zeitraum liegt: ' + ap.Name);
                    }
                    if (isUpdate && isSamePeriod && (ap.Id != toInsertItem.id)) {
                        toInsertItem.addError('Es gibt bereits eine Auslieferungsprioritaet, die in diesem Zeitraum liegt: ' + ap.Name);
                    }
                }    
            }
        }
    }
        
    /**
     * Checks if a given time period is overlapping another time period
     * @param tmpValidFrom Field Gueltig_ab__c of the SomDig_DeliverPrio__c we compare to the item we want to insert.
     * @param tmpValidUntil Field Gueltig_bis__c of the SomDig_DeliverPrio__c we compare to the item we want to insert.
     * @param tmpToInsertValidFrom Field Gueltig_ab__c of the SomDig_DeliverPrio__c we want to insert
     * @param tmpToInsertValidUntil Field Gueltig_bis__c of the SomDig_DeliverPrio__c we want to insert
     * @return true if both time periods overlapp
     */    
    private boolean checkPeriods(Date tmpValidFrom, Date tmpValidUntil, Date tmpToInsertValidFrom, Date tmpToInsertValidUntil) {
        boolean hasSamePeriod = false;
        if ( !(tmpValidFrom > tmpToInsertValidUntil) && !(tmpToInsertValidFrom > tmpValidUntil) ) {
            System.debug('same period');
            hasSamePeriod = true;
        } 
        return hasSamePeriod;           
    }
}