src/objects/SomDig_Auftragstyp__c.object
<CustomObject>
    <description>Abbildung von Auftragstypen (Mandantenprozesse) der SevenOne MEdia, welcher diverse EIgentschaften steuert wir Rechnungsstellung, FC etc.</description>
    <label>Auftragstyp</label>
    <nameField>
        <label>Auftragstyp-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auftragstypen</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SomDig_DeliverPrio__c.object
<CustomObject>
    <description>Regelwerk für das Prio-Modell</description>
    <fields>
        <fullName>SomDig_Abrechungsart__c</fullName>
        <description>Hier kann angegeben werden, ob die Auslieferungsprioritäten für eine bestimmte Abrechnungsart für diesen Account im AdServer gesetzt werden sollen. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welche Abrechnungsart soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Abrechungsart</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPMo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Ad_Type__c</fullName>
        <description>Der AdType steuert die Auslieferungsprioritäten im AdServer. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver&quot;</description>
        <inlineHelpText>Hier kann der &quot;Ad Type&quot; festgelegt werden, der für diese Auslieferungspriorität im Adserver gesetzt werden soll.</inlineHelpText>
        <label>Ad Type</label>
        <picklist>
            <picklistValues>
                <fullName>Sponsorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Priority</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Auftragstyp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Auswahl des Auftragstyp zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welche Auftragstyp soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Auftragstyp</label>
        <referenceTo>SomDig_Auftragstyp__c</referenceTo>
        <relationshipLabel>Auslieferungsprioritäten</relationshipLabel>
        <relationshipName>Auslieferungsprioritaeten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Belegungseinheitstyp__c</fullName>
        <description>Auswahl des Belegungseinheitstyp zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welchen Belegungseinheitstyp soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Belegungseinheitstyp</label>
        <picklist>
            <picklistValues>
                <fullName>71m intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YouTube</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Gueltig_ab__c</fullName>
        <description>&quot;Hier wird angegeben, ab wann diese Auslieferungspriorität gültig ist.&quot; 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier bitte angegeben, ab wann diese Auslieferungspriorität gültig ist.</inlineHelpText>
        <label>Gültig ab</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Gueltig_bis__c</fullName>
        <description>&quot;Hier wird angegeben, bis wann diese Auslieferungspriorität gültig ist.&quot; 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier bitte angegeben, bis wann diese Auslieferungspriorität gültig ist.</inlineHelpText>
        <label>Gültig bis</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SomDig_Mediagattungsdifferenzierung__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Auswahl der Mediagattungsdifferenzierung zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welche Mediagattungsdifferenzierung soll eine Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Mediagattungsdifferenzierung</label>
        <referenceTo>SomDig_MediagattungsDifferenzierung__c</referenceTo>
        <relationshipName>Adserver_Prioritaeten</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SomDig_Preistyp_zur_Auslieferung__c</fullName>
        <description>Auswahl Preistyp zur Auslieferung (Delivery Rate Type) zur Steuerung der Auslieferungsprioritäten. Vgl. auch Spezifikation SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier kann der &quot;Preistyp zur Auslieferung&quot; (Delivery Rate Type) festgelegt werden, der für diese Auslieferungspriorität im Adserver gesetzt werden soll.</inlineHelpText>
        <label>Preistyp zur Auslieferung</label>
        <picklist>
            <picklistValues>
                <fullName>Evenly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frontloaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>As fast as possible</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Prio__c</fullName>
        <description>Die Prio steuert die Auslieferungsprioritäten im AdServer. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier kann die &quot;Prio&quot; festgelegt werden, die für diese Auslieferungspriorität im Adserver gesetzt werden soll.</inlineHelpText>
        <label>Prio</label>
        <picklist>
            <controllingField>SomDig_Ad_Type__c</controllingField>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_Rotationstyp__c</fullName>
        <description>Auswahl des Rotationstyp zur Steuerung der Auslieferungsprioritäten. Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Für welchen Rotationstyp soll diese Auslieferungspriorität angegeben werden?</inlineHelpText>
        <label>Rotationstyp</label>
        <picklist>
            <picklistValues>
                <fullName>Brand-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Themen-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV-Brand-Rotation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Umfeld</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SomDig_UniqueKey__c</fullName>
        <description>Zusammenfassung aller Felder einer Auslieferungspriorität um auf Duplikate zu prüfen</description>
        <label>UniqueKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SomDig_Werbeform_Kurzform__c</fullName>
        <description>Hier kann angegeben werden, ob die Auslieferungsprioritäten für eine bestimmte Werbeform für diesen Account im AdServer gesetzt werden sollen. 
Vgl. auch Konzept SOM - ADcalibur - Spezifikation - Auslieferungsprioritäten Adserver</description>
        <inlineHelpText>Hier kann angegeben werden für welche Werbeform die Auslieferungsprioritäten für diesen Werbetreibenden im Adserver festgelegt werden.</inlineHelpText>
        <label>Werbeform Kurzform</label>
        <picklist>
            <picklistValues>
                <fullName>PR1/MR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR1/MR/POR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prio3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Auslieferungspriorität</label>
    <nameField>
        <displayFormat>PRIO-{0}</displayFormat>
        <label>Priorität-Nr.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auslieferungsprioritäten</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SomDig_MediagattungsDifferenzierung__c.object
<CustomObject>
    <description>Gruppierung der einzelenen Werbeformen nach ihrer Art</description>
    <label>Mediagattungs-Differenzierung</label>
    <nameField>
        <label>Mediagattungs-Differenzierung</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mediagattungs-Differenzierungen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SomDig_DeliverPrio_Check_Test.cls
@isTest(seeAllData=false)
private class SomDig_DeliverPrio_Check_Test {

    public class Prio_DoubleChecker_Test{
        
        public SomDig_DeliverPrio__c priority;
        public SomDig_MediagattungsDifferenzierung__c mediaDiff;
        public SomDig_Auftragstyp__c auftragstyp;
        public List<SomDig_DeliverPrio__c> sameAuslieferungsprioritaeten;
        public List<SomDig_DeliverPrio__c> differentAuslieferungsprioritaeten;
        public List<SomDig_DeliverPrio__c> sameAuslieferungsprioritaetenDifferentDates;
            
        public void insertTestData() {
        
            SomDig_MediagattungsDifferenzierung__c md1 = new SomDig_MediagattungsDifferenzierung__c();
            md1.Name = 'Test MediagattungsDifferenzierung';
            insert md1;
            this.mediaDiff = md1;
            
            SomDig_Auftragstyp__c auftrag = new SomDig_Auftragstyp__c();
            auftrag.Name = 'Testauftrag';
            insert auftrag;
            this.auftragstyp = auftrag;
            
            SomDig_DeliverPrio__c p1 = new SomDig_DeliverPrio__c();
            p1.SomDig_Gueltig_ab__c = Date.today();
            p1.SomDig_Gueltig_bis__c = Date.today().addDays(1);
            p1.SomDig_Mediagattungsdifferenzierung__c = md1.Id;
            p1.SomDig_Werbeform_Kurzform__c = 'PreMid';
            p1.SomDig_Auftragstyp__c = auftrag.id;
            p1.SomDig_Abrechungsart__c = 'Festpreis';
            p1.SomDig_Rotationstyp__c = 'Umfeld';
            p1.SomDig_Belegungseinheitstyp__c = 'YouTube';
            p1.SomDig_Ad_Type__c = 'Sponsorship';
            p1.SomDig_Prio__c ='3';
            p1.SomDig_Preistyp_zur_Auslieferung__c = 'Evenly';
            this.priority = p1;
            
            SomDig_DeliverPrio__c p2 = new SomDig_DeliverPrio__c();
            p2.SomDig_Gueltig_ab__c = Date.today();
            p2.SomDig_Gueltig_bis__c = Date.today().addDays(1);
            p2.SomDig_Mediagattungsdifferenzierung__c = md1.Id;
            p2.SomDig_Werbeform_Kurzform__c = 'PreMid';
            p2.SomDig_Auftragstyp__c = auftrag.id;
            p2.SomDig_Abrechungsart__c = 'Festpreis';
            p2.SomDig_Rotationstyp__c = 'Umfeld';
            p2.SomDig_Belegungseinheitstyp__c = 'YouTube';
            p2.SomDig_Ad_Type__c = 'Sponsorship';
            p2.SomDig_Prio__c ='3';
            p2.SomDig_Preistyp_zur_Auslieferung__c = 'Evenly';

            
            sameAuslieferungsprioritaeten = new List<SomDig_DeliverPrio__c>();
            sameAuslieferungsprioritaeten.add(p1);
            sameAuslieferungsprioritaeten.add(p2);
            
            
            SomDig_DeliverPrio__c p3 = new SomDig_DeliverPrio__c();
            p3.SomDig_Gueltig_ab__c = Date.today();
            p3.SomDig_Gueltig_bis__c = Date.today().addDays(1);
            p3.SomDig_Mediagattungsdifferenzierung__c = md1.Id;
            p3.SomDig_Werbeform_Kurzform__c = 'PreMid';
            p3.SomDig_Auftragstyp__c = auftrag.id;
            p3.SomDig_Abrechungsart__c = 'Festpreis';
            p3.SomDig_Rotationstyp__c = 'Umfeld';
            p3.SomDig_Belegungseinheitstyp__c = 'YouTube';
            p3.SomDig_Ad_Type__c = 'Sponsorship';
            p3.SomDig_Prio__c ='3';
            p3.SomDig_Preistyp_zur_Auslieferung__c = 'Evenly';

            //this.priority = p1;
            
            SomDig_DeliverPrio__c p4 = new SomDig_DeliverPrio__c();
            p4.SomDig_Gueltig_ab__c = Date.today();
            p4.SomDig_Gueltig_bis__c = Date.today().addDays(1);
            p4.SomDig_Mediagattungsdifferenzierung__c = md1.Id;
            p4.SomDig_Werbeform_Kurzform__c = 'PreMid';
            p4.SomDig_Auftragstyp__c = auftrag.id;
            p4.SomDig_Abrechungsart__c = 'Festpreis';
            p4.SomDig_Rotationstyp__c = 'Umfeld';
            p4.SomDig_Belegungseinheitstyp__c = 'YouTube';
            p4.SomDig_Ad_Type__c = 'Standard'; //This value differs to p3
            p4.SomDig_Prio__c ='3';
            p4.SomDig_Preistyp_zur_Auslieferung__c = 'Evenly';
            
            differentAuslieferungsprioritaeten = new List<SomDig_DeliverPrio__c>();
            differentAuslieferungsprioritaeten.add(p3);
            differentAuslieferungsprioritaeten.add(p4);
            
            
            SomDig_DeliverPrio__c p5 = new SomDig_DeliverPrio__c();
            p5.SomDig_Gueltig_ab__c = Date.today().addDays(2);
            p5.SomDig_Gueltig_bis__c = Date.today().addMonths(6);
            p5.SomDig_Mediagattungsdifferenzierung__c = md1.Id;
            p5.SomDig_Werbeform_Kurzform__c = 'PreMid';
            p5.SomDig_Auftragstyp__c = auftrag.id;
            p5.SomDig_Abrechungsart__c = 'Festpreis';
            p5.SomDig_Rotationstyp__c = 'Umfeld';
            p5.SomDig_Belegungseinheitstyp__c = 'YouTube';
            p5.SomDig_Ad_Type__c = 'Sponsorship';
            p5.SomDig_Prio__c ='3';
            p5.SomDig_Preistyp_zur_Auslieferung__c = 'Evenly';
            
            SomDig_DeliverPrio__c p6 = new SomDig_DeliverPrio__c();
            p6.SomDig_Gueltig_ab__c = Date.today().addMonths(6).addDays(1);
            p6.SomDig_Gueltig_bis__c = Date.today().addMonths(6).addDays(30);
            p6.SomDig_Mediagattungsdifferenzierung__c = md1.Id;
            p6.SomDig_Werbeform_Kurzform__c = 'PreMid';
            p6.SomDig_Auftragstyp__c = auftrag.id;
            p6.SomDig_Abrechungsart__c = 'Festpreis';
            p6.SomDig_Rotationstyp__c = 'Umfeld';
            p6.SomDig_Belegungseinheitstyp__c = 'YouTube';
            p6.SomDig_Ad_Type__c = 'Sponsorship'; 
            p6.SomDig_Prio__c ='3';
            p6.SomDig_Preistyp_zur_Auslieferung__c = 'Evenly';
            
            sameAuslieferungsprioritaetenDifferentDates = new List<SomDig_DeliverPrio__c>();
            sameAuslieferungsprioritaetenDifferentDates.add(p5);
            sameAuslieferungsprioritaetenDifferentDates.add(p6);
        }
    }
    
    @isTest
    static void testDoubleEntry() {
        Prio_DoubleChecker_Test testClass = new Prio_DoubleChecker_Test();
        testClass.insertTestData();
        //insert testClass.sameAuslieferungsprioritaeten;
        Test.startTest();
        
        /*
        SomDig_DeliverPrio__c ap1 = [ Select SomDig_UniqueKey__c from SomDig_DeliverPrio__c Where id =: testClass.priority.Id ];
        String valueOfUniqueKey = testClass.priority.SomDig_Abrechungsart__c + '|' + testClass.priority.SomDig_Ad_Type__c + '|' + testClass.priority.SomDig_Auftragstyp__c + '|' + testClass.priority.SomDig_Belegungseinheitstyp__c + '|' 
                            + testClass.priority.SomDig_Gueltig_ab__c + '|'+ testClass.priority.SomDig_Gueltig_bis__c + '|'+ testClass.priority.SomDig_Mediagattungsdifferenzierung__c + '|'
                            + testClass.priority.SomDig_Preistyp_zur_Auslieferung__c + '|'+ testClass.priority.SomDig_Prio__c + '|' + testClass.priority.SomDig_Rotationstyp__c + '|' 
                            + testClass.priority.SomDig_Werbeform_Kurzform__c;
        System.assertEquals(ap1.SomDig_UniqueKey__c, valueOfUniqueKey);
        */
        insert testClass.differentAuslieferungsprioritaeten;
        
        insert testClass.sameAuslieferungsprioritaetenDifferentDates;
        Test.stopTest();
    }
    
}