src/objects/Ven_Contract_Terms__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Abweichender_Term__c</fullName>
        <description>Hier wird der abweichende Term von Vertriebsmitarbeiter eingetragen.</description>
        <inlineHelpText>Bitte den abweichenden Term hier eintragen.</inlineHelpText>
        <label>Abweichender Term</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ven_G_ltig__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Diese Checkbox gibt an ob ein Term im Standard gültig ist oder nicht.</description>
        <inlineHelpText>Der Term ist gültig im Standart wenn die Checkbox gesetzt ist.</inlineHelpText>
        <label>Gültig</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Kommentar_warum_nicht_g_ltig__c</fullName>
        <description>Begründung warum ein Term in Standard nicht gültig ist.</description>
        <inlineHelpText>Hier bitte die Begründung angeben, warum ein Term im Standard nicht gültig ist.</inlineHelpText>
        <label>Kommentar warum nicht gültig</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ven_Standard_Term_kurz__c</fullName>
        <description>Hier wir der nur ein Auszug vom Term angezeigt.</description>
        <inlineHelpText>Hier wir der nur ein Auszug vom Term angezeigt.</inlineHelpText>
        <label>Standard Term (kurz)</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Es werden nur Aktive Standart Terms angezeigt!</errorMessage>
            <filterItems>
                <field>Ven_Standart_Terms__c.Ven_Aktiv__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ven_Standart_Terms__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Vertrag_SevenVentures__c</fullName>
        <description>Hier wird die Verbindung eines Contract Terms zum Vertrag eingetragen.</description>
        <inlineHelpText>Hier wird die Verbindung eines Contract Terms zum Vertrag eingetragen.</inlineHelpText>
        <label>Vertrag (SevenVentures)</label>
        <referenceTo>Ven_Vertrag_SevenVentures__c</referenceTo>
        <relationshipLabel>Contract Terms</relationshipLabel>
        <relationshipName>Contract_Terms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Terms</label>
    <nameField>
        <displayFormat>VenCT-{0000000}</displayFormat>
        <label>Contract Term-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Standart_Terms__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Abschnitt__c</fullName>
        <description>Gibt an in welchen Abschnitt der Term auf dem Vertrag gruppiert werden soll.</description>
        <inlineHelpText>Gibt an in welchen Abschnitt der Term auf dem Vertrag gruppiert werden soll.</inlineHelpText>
        <label>Abschnitt</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medialeistung</fullName>
                </value>
                <value>
                    <fullName>Abrechnung und Reporting</fullName>
                </value>
                <value>
                    <fullName>Kündigungsmöglichkeiten von 7V</fullName>
                </value>
                <value>
                    <fullName>Rechtsfolgen einer Kündigung durch SevenVentures</fullName>
                </value>
                <value>
                    <fullName>Beteiligungsvereinbarung (sofern Verträge nicht zeitgleich abgeschlossen werden)</fullName>
                </value>
                <value>
                    <fullName>Regelungen für Nachlaufphase</fullName>
                </value>
                <value>
                    <fullName>Individuelle Terms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ven_Standard_Term_Lang__c</fullName>
        <description>Hier wird der gesamte Text des Standart Term angezeigt.</description>
        <inlineHelpText>Hier wird der gesamte Text des Standart Term angezeigt.</inlineHelpText>
        <label>Standard Term (Lang)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Standard Term</label>
    <nameField>
        <label>Standart Terms-Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ven_Vertrag_SevenVentures__c.object
<CustomObject>
    <description>Vertragsobjekt für SevenVentures Verträge</description>
    <label>Vertrag (Sevenventures)</label>
    <nameField>
        <displayFormat>VenV-{00000000}</displayFormat>
        <label>Vertrag (SevenVentures)-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verträge (Sevenventures)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContractTerms.cls
/**
 * @author: ADvendio.com (helge.kosuch@advendio.com)
 * 
 * An instance of ContractTerms represents the ContractTerms which are used in one of the Contracts passed to the contructor. 
 * Each ContractTerm has a lookup pointing to a StandardTerm object.
 */

public with sharing class ContractTerms {
		
    /** AbschnittsSection represents a section on the VF page, with a title and a list of terms
        * Should be a subclass of Terms, but that is not allowed.
        * These will be displayed in a repeat on the VF page */
    public class AbschnittsSection {
        public String title {get; set;}
        
        /** If the following is false, the stardard term will not be displayed at all if it is not valid. */
        public Boolean displayStandardTerms {get; private set;}
        
        /** These will be displayed in a repeat on the VF page */
        public List<Ven_Contract_Terms__c> terms {get; set;}
    }
    
    /** Map aller AbschnittTerms des aktuellen Vertrags nach Abschnitt. */
	Map<String,AbschnittsSection> abschnittsSectionsByAbschnitt = new Map<String,AbschnittsSection>(); 
	
	/** This is list is needed for the repeat on the VF page */
	public List<AbschnittsSection> abschnittsSections {get; private set;}
	
	/** Test this with: 
	InvestmentSummaryController.Terms termsInstance = new InvestmentSummaryController.Terms(
					[SELECT id FROM Ven_Vertrag_SevenVentures__c WHERE id=: InvestmentSummaryController.testClassInstance.vertragsId]
	); 
	*/
	
	static final String INDIVIDUELLE_TERMS_TITLE_STR = 'Individuelle Terms';
	
	public ContractTerms(List<Ven_Vertrag_SevenVentures__c> vertraege) {  //constructor
		List<Ven_Contract_Terms__c> contractTerms = [SELECT id
			, Ven_Standard_Term_kurz__r.Ven_Abschnitt__c
			, Ven_Standard_Term_kurz__r.Ven_Standard_Term_Lang__c
			, Ven_G_ltig__c                          
			, Ven_Kommentar_warum_nicht_g_ltig__c      
            , Ven_Abweichender_Term__c                                         
			FROM Ven_Contract_Terms__c WHERE Ven_Vertrag_SevenVentures__c IN :vertraege
		];  
		
		System.debug('contractTerms=='+contractTerms);

		// populate abschnittsSectionsByAbschnitt map
		for (Ven_Contract_Terms__c term : contractTerms) {
            addTerm(abschnittsSectionsByAbschnitt,term);
		}
		
		{ // Make a list of the AbschnittsSections to display them on the page with the section "Individuelle Terms" at the end.
			abschnittsSections = new List<AbschnittsSection>();
			for (AbschnittsSection currentAbschnittsSection : abschnittsSectionsByAbschnitt.values()) {
				if (currentAbschnittsSection.title.equalsIgnoreCase(INDIVIDUELLE_TERMS_TITLE_STR)) {
					// don't add, will be added at the end
				} else {
					abschnittsSections.add(currentAbschnittsSection);
				}
			}
			
			abschnittsSections.add(abschnittsSectionsByAbschnitt.get(INDIVIDUELLE_TERMS_TITLE_STR));
		}
		
	} // end constructor
    
    static private void addTerm(Map<String,AbschnittsSection> abschnittsSectionsByAbschnitt, Ven_Contract_Terms__c term) {
        final String abschittsTitle = term.Ven_Standard_Term_kurz__r.Ven_Abschnitt__c;
        AbschnittsSection currentAbschnittsSection = abschnittsSectionsByAbschnitt.get(abschittsTitle);
        if ( currentAbschnittsSection == null) {
            // No map entry for this Abschnitt yet. Create one:
            currentAbschnittsSection = new AbschnittsSection();
            currentAbschnittsSection.title = abschittsTitle;
            currentAbschnittsSection.terms = new List<Ven_Contract_Terms__c>();
            
            /** Don't display standard terms in the section "Individuelle Terms": */
            currentAbschnittsSection.displayStandardTerms = ! (abschittsTitle!=null && abschittsTitle.equalsIgnoreCase(INDIVIDUELLE_TERMS_TITLE_STR));
            
            abschnittsSectionsByAbschnitt.put(abschittsTitle, currentAbschnittsSection);

        }
        currentAbschnittsSection.terms.add(term); 
    }
}