src/objects/Ven_Round__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Aktiv__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gibt an ob eine Runde aktiv ist oder nicht! Wird automatisch gesetzt.</description>
        <inlineHelpText>Gibt an ob eine Runde aktiv ist oder nicht! Wird automatisch gesetzt.</inlineHelpText>
        <label>Aktiv</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_G_ltig_ab__c</fullName>
        <description>Hier wird die Gültigkeit des Cap Tables angegeben.</description>
        <inlineHelpText>Bitte das Datum angeben ab wann der Cap Table gültig ist.</inlineHelpText>
        <label>Gültig ab</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ven_Round_Number__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Hier wird die Beteiligungsrunde erfasst.</inlineHelpText>
        <label>Round Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Round</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Round-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ven_Share__c.object
<CustomObject>
    <fields>
        <fullName>Ven_Aktiv__c</fullName>
        <formula>Ven_Round__r.Ven_Aktiv__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aktiv</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ven_Round_Number__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt. Die Formel kopiert den Wert aus dem gleichnamigen Feld aus dem Objekt Round.</description>
        <formula>Ven_Round__r.Ven_Round_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hier wird die Beteiligungsrunde erfasst per Formel.</inlineHelpText>
        <label>Round Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ven_Round__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <inlineHelpText>Die Round zu der dieser Share gehört.</inlineHelpText>
        <label>Round</label>
        <referenceTo>Ven_Round__c</referenceTo>
        <relationshipLabel>Shares</relationshipLabel>
        <relationshipName>Ven_Shares</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ven_Share__c</fullName>
        <description>Das Feld gehört zum Seven Ventures Objekt &quot;Cap Table&quot;, was die Beteiligung von Seven Ventures oder auch anderen Shareholder anzeigt.</description>
        <formula>Ven_Shares__c / Ven_Round__r.Ven_all_Shares__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hier werden automatisch die % der Beteiligungen errechnet.</inlineHelpText>
        <label>Share %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Share</label>
    <nameField>
        <displayFormat>CT-{0000000}</displayFormat>
        <label>Share-Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CapTableTests.cls
@isTest
public without sharing class CapTableTests {

	@isTest
	static void test1CoverageOnly() {
		Account sevenVenturesAcc = ClsHelper.newTestAccount(System.UserInfo.getUserId(), 'sevenVenturesAcc');
		sevenVenturesAcc.AccountNumber = '1';
		insert sevenVenturesAcc;

		Account acc = ClsHelper.newTestAccount(System.UserInfo.getUserId(), 'Test account 1');
		insert acc;

		CapTableEditorController controller = new CapTableEditorController(new ApexPages.StandardController(acc));

		controller.getC();
		controller.newestRoundWrapperInstance.getNewestRoundShares();

	}


	@isTest
	static void test1() {
		Account sevenVenturesAcc = ClsHelper.newTestAccount(System.UserInfo.getUserId(), 'sevenVenturesAcc');
		sevenVenturesAcc.AccountNumber = '1';
		insert sevenVenturesAcc;

		Account acc = ClsHelper.newTestAccount(System.UserInfo.getUserId(), 'Test account 1');
		insert acc;

		{
			Savepoint savepoint1 = Database.setSavepoint();

			// Having no rounds at all could fail. Let's test it:
			CapTableEditorController controllerEmpty = new CapTableEditorController(new ApexPages.StandardController(acc));
			controllerEmpty.createFirstRound();
			controllerEmpty.newestRoundWrapperInstance.getNewestRound().Ven_G_ltig_ab__c = Date.today();
			controllerEmpty.saveRoundButton();

			Database.rollback(savepoint1);
		}

		Ven_Share__c share = ClsHelper.insertRounds1And2AndShares(acc.Id);

		{  // The following test this: If the user presses "Neue Runde" the shares of the old round should be copied to the new one.
			// This test test fails in rev7484 if you insert it there.

			Savepoint savepoint1 = Database.setSavepoint();

			CapTableEditorController controller = new CapTableEditorController(new ApexPages.StandardController(acc));

			controller.getOldRoundsExistFlag(); // just for coverage

			controller.newRound();

			System.assertNotEquals(0,controller.newestRoundWrapperInstance.newestRoundShares.size(),'Fail: Shares have not been copied to new round!');

			Database.rollback(savepoint1);
		}

		{  // The following test this: If the user presses "Runde löschen" the next lower should be marked as active.
			// This test test fails in rev7484 if you insert it there.

			Savepoint savepoint1 = Database.setSavepoint();

			CapTableEditorController controller = new CapTableEditorController(new ApexPages.StandardController(acc));

			{
				Ven_Round__c currentRound = controller.getRecordsOfCurrentSetControllerPage()[0];

				System.assertEquals(2.0,currentRound.Ven_Round_Number__c, 'Wrong round number.');
				System.assert(currentRound.Ven_Aktiv__c, 'Ven_Aktiv__c should be true, but is not!');
			}

			controller.deleteRoundButton();

			{
				Ven_Round__c currentRound = controller.getRecordsOfCurrentSetControllerPage()[0];
				System.assertEquals(1.0,currentRound.Ven_Round_Number__c, 'Wrong round number.');
				System.assert(currentRound.Ven_Aktiv__c, 'Ven_Aktiv__c should be true, but is not!');
			}

			System.assertNotEquals(0,controller.newestRoundWrapperInstance.newestRoundShares.size()
				,'Fail: Shares have not been copied to new round!'
			);

			Database.rollback(savepoint1);
		}

		CapTableEditorController controller = new CapTableEditorController(new ApexPages.StandardController(acc));


		Apexpages.currentPage().getParameters().put('shareToBeDeletedId',share.id);
		controller.deleteShare();

		controller.newShare();
		controller.newRound();
		controller.saveRoundButton();

		controller.cancel();
		controller.editFlag = true;
		controller.cancel();

		controller.edit();
	}

}